### ISSUE TITLE
提个关于记住布局的建议

### ISSUE THREAD

**Issue by hpfs0** [sourcegit-scm/sourcegit#1]
提下建议，可否增加记住布局的功能。
每次重新打开时候窗口大小还有布局的左右分割大小都会恢复到初始化到默认状态，使用起来每次都要手动再次调节比较麻烦，不知道可否增加记住最后关闭软件时的窗口大小以及布局情况。

**Comment by sourcegit-scm** [comment]
窗口大小是记录的，左右分隔大小未记录

**Comment by hpfs0** [comment]
我这边每次打开后窗口大小都会自动还原，关闭的时候是最大化的。

**Comment by sourcegit-scm** [comment]
最大化与最小化状态是未记录的，只记录了正常状态下的窗口大小

**Comment by hpfs0** [comment]
好的，如果大佬有空的话，可以把记住布局的功能加上吗？
