### ISSUE TITLE
Any plan to port other framework and make it cross-platform?

### ISSUE THREAD

**Issue by alluLinger** [sourcegit-scm/sourcegit#10]
like Avalonia a cross-platform XAML framework https://github.com/AvaloniaUI/Avalonia

**Comment by sourcegit-scm** [comment]
I haven't using the Avalonia framework before, and I'm not sure if the solution is optimized for large lists (20,000+ entries) and tree views (WPF has a corresponding virtualization solution). And whether custom drawing (used to visualize commit branch graphs) is supported.
