### ISSUE TITLE
HotKeys for macOS

### ISSUE THREAD

**Issue by successgo** [sourcegit-scm/sourcegit#103]
Hi, thank you for the fantastic software.

macOS is mainly using `Command` other than `Control` like `Command + T` to open new page. Can we keep this convention?

**Comment by love-linger** [comment]
I'm using hackintosh to compile and distribute this app for macOS and I do NOT have an apple keyboard to test with hotkeys. I can't guarantee that the current changes are consistent with macOS user habits. 

Looking forward to your feedback.

**Comment by successgo** [comment]
Cool, I'll check that later.

**Comment by successgo** [comment]
Confirmed: `CMD+W` and `CMD+T` worked very well. I thought others should be too because I don't use them.

Thank you @love-linger

**Comment by love-linger** [comment]
The `HotKeys` from main menu shows all the hotkeys used by this app.
![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/64c56edb-17a0-483d-8cf2-dfd76f758675)

Could you help me to test these hotkeys?

**Comment by successgo** [comment]
Tested and all working fine.

But reguarding `F5`, while reloading done, the focus is updated to the middle of the commit history other that the top and I have to scroll to the top, did that design so?

For text editor searching:
On Chrome and Rider, `Enter` is for next match, and `Shift + Enter` is for the previous match.

**Comment by love-linger** [comment]
1. After reloading repository, the selected commit keeps to the last selected one. See PR #104
2. It's the built-in hotkeys in AvaloniaEdit control.
3. I'll consider to add these keys. 
4. The TreeView/ListView/DataGrid has these built-in hotkeys.

**Comment by love-linger** [comment]
I have just confirmed that use `Enter` for next match and `Shift+Enter` for previous match is also worked on Windows

**Comment by successgo** [comment]
1. Sorry, You are right. This is great to keep the last selected commit.

**Comment by successgo** [comment]
> I have just confirmed that use `Enter` for next match and `Shift+Enter` for previous match is also worked on Windows

Yes, and I just confirmed it's also working fine for macOS.

**Comment by successgo** [comment]
While digging more on searching:

1. Search Files on CHANGES tab does not support shortcut, like `Ctrl + F` on windows and `Command + F` on macOS.
1. Search commits and search text, both are using `Ctrl + F` to invoke, but cancel searching is using different approach, it will be better to keep consistence, `ESC` to cancel would acceptable.

**Comment by love-linger** [comment]
https://github.com/sourcegit-scm/sourcegit/actions/runs/8963157118

* add `Shift+Ctrl+Tab` (`⌘+⌥+←` on macOS) to go to previous page
* use `ESC` to cancel commit searching

**Comment by successgo** [comment]
Hi @love-linger 
As for switching pages `Ctrl+Tab` and `Shift+Ctrl+Tab` does not work in v8.11.

**Comment by love-linger** [comment]
> Hi @love-linger As for switching pages `Ctrl+Tab` and `Shift+Ctrl+Tab` does not work in v8.11.

Which OS do you use? On macOS, the hotkey to switch pages is `⌘+⌥+←` and `⌘+⌥+→`

**Comment by successgo** [comment]
It's macOS. I thought you added `Ctrl+Tab` and `Shift+Ctrl+Tab`.
