### ISSUE TITLE
add support for 'double click' to stage / unstage changes

### ISSUE THREAD

**Issue by successgo** [sourcegit-scm/sourcegit#108]

**Comment by love-linger** [comment]
If you displays the changes in file tree mode, the `double click` has been used to fold/unfold selected node.

![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/f6eb97d5-6124-4e04-abd8-42b18c8ea84a)

**Comment by love-linger** [comment]
Therefore, in order to unify operations on different display modes, `Space` is used as the hotkey for Stage/Unstage behaviour.
