### ISSUE TITLE
split the commit message box to subject and body

### ISSUE THREAD

**Issue by successgo** [sourcegit-scm/sourcegit#109]

**Comment by love-linger** [comment]
It's an interesting story. In very earlier versions of the software (not published on github, but on gitee), the Subject was displayed separately from the Body.

![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/02a256bb-cbf1-4938-be21-703df1a5e8db)

At that time, some users suggested that it was inconvenient to copy the entire commit description. Therefore, the Subject and Body are merged into one entry.

**Comment by successgo** [comment]
Oh that's interesting.

We may need to add an option to solve this.

> GUI can always do better than cli.

**Comment by love-linger** [comment]
After I asked some of my friends who use this software, I decided to keep it the way it is now.

* Some people need to copy the generated content from another website (a team cooperation system) as the commit message
* Currently, the way the commit message is entered and presented does not result in any missing information or additional actions
