### ISSUE TITLE
合并分支时会缺失某些文件提交信息

### ISSUE THREAD

**Issue by hpfs0** [sourcegit-scm/sourcegit#11]
如下图所示，在合并分支时候会出现丢失提交的部分文件信息。
![image](https://s2.loli.net/2022/11/22/WGr2QpCY6IR94es.png)
![image](https://s2.loli.net/2022/11/22/AGY6MuHOPB1yj7L.png)

**Comment by sourcegit-scm** [comment]
这是由于merge提交有两个父提交，sourcegit目前采用与第一个parent做变更对比的base，你可以尝试使用ctrl键，选中另一个提交与该merge节点，查看一下是否显示了你期望的文件变更列表

**Comment by hpfs0** [comment]
按照上面操作可以了，显示逻辑好像和sourcetree不太一样，有点不太习惯。

**Comment by sourcegit-scm** [comment]
嗯，关于这个的处理方式各个软件是不同的，对于一些用户是会出现一些困扰
