### ISSUE TITLE
[SUGGESTION]推送失败的时候关闭PUSH窗口

### ISSUE THREAD

**Issue by owllyi** [sourcegit-scm/sourcegit#119]
1、希望推送失败的时候关闭推送弹出的窗口。
2、右侧会有一个小的错误窗口，能否加大窗口，更方便的查看错误信息呢（能拷贝错误信息更好）。
3、如果可行的话，错误窗口放在中间偏上，替代了PUSH弹出窗口可能会更符合直觉。

越来越完善好用了，加油！

**Comment by love-linger** [comment]
1. 不关闭窗口是基于这样一个考虑：如果当前错误是操作的选项/或输入项错误引起的，用户可以直接修改，接着操作。
2. 错误提示一些情况下确实大小过于小，后面有时间优化。错误是可以拷贝的，这里特意用了ReadOnly的TextBox输入框方便拷贝操作
3. 放在右边是因为，错误信息有时不止一条，或是由于用户未及时关闭，这样它会从右上到右下堆叠。移到中间，一是会挡住主要操作区域，二是不好处理多条错误消息（比如自己操作出现一条，开启后台自动Fetch后，可能同时出现错误）

**Comment by owllyi** [comment]
多谢回复，我遇到的大对数情况都是远程有内容造成的。所以每次都要关闭错误，关闭推送窗口，再去推送。感觉很繁琐。

**Comment by love-linger** [comment]
> 多谢回复，我遇到的大多数情况都是远程有内容造成的。所以每次都要关闭错误，关闭推送窗口，再去推送。感觉很繁琐。

如果遇到的错误是`fetch first`类的，我的操作是：关闭错误，直接点击fetch按钮（注意不是先关闭push面板），这样程序会自动将push面板替换为fetch面板。在当前面板不是进行中状态时，是可以被其他面板直接替换的，同时面板后面的空白区域点击也可以关闭当前面板

![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/25f1c3a9-aa19-49a2-bde0-39d39edf18c8)

**Comment by owllyi** [comment]
好的，我的习惯是遇到推送问题了会pull并选择rebase，然后再push。理论上我可以不管上面的界面，直接左侧操作对吧。

**Comment by love-linger** [comment]
> 好的，我的习惯是遇到推送问题了会pull并选择rebase，然后再push。理论上我可以不管上面的界面，直接左侧操作对吧。

基本上是的，我很少去点那个Cancel按钮，要不然就是按一下ESC，要不然就是鼠标随便点个位置

**Comment by owllyi** [comment]
ok，那先关闭吧。
