### ISSUE TITLE
rpm fedora 38 and 40 install package file conflict

### ISSUE THREAD

**Issue by habegit** [sourcegit-scm/sourcegit#128]
DNF INSTALL OUTPUT:
Error: Transaction test error:
  file /usr/bin from install of sourcegit-8.12-1.x86_64 conflicts with file from package filesystem-3.18-8.fc40.x86_64

OS:
cat /etc/fedora-release 
Fedora release 40 (Forty)

REPRODUCE:
sudo dnf install https://github.com/sourcegit-scm/sourcegit/releases/download/v8.12/sourcegit-8.12-1.x86_64.rpm

same error happened already on fc38.

**Comment by habegit** [comment]
seems .spec sets /usr/bin to 755 whilst it should be 555

stat -c '%a %n' /usr/bin/
555 /usr/bin/

stat -c '%a %n' /usr/bin/bash
755 /usr/bin/bash

build/resources/rpm/SPECS/build.spec
line 23
chmod 755 -R $RPM_BUILD_ROOT

seems to be the cause

**Comment by love-linger** [comment]
Thank you very much.

**Comment by habegit** [comment]
fix:
diff --git a/build/resources/rpm/SPECS/build.spec b/build/resources/rpm/SPECS/build.spec
index 2e6875a..064af1b 100644
--- a/build/resources/rpm/SPECS/build.spec
+++ b/build/resources/rpm/SPECS/build.spec
@@ -24,8 +24,8 @@ chmod 755 -R $RPM_BUILD_ROOT
 
 %files
 /opt
-/usr/bin
+%attr(555,root,root)/usr/bin
 /usr/share
 
 %changelog
-# skip
\ No newline at end of file
+# skip

**Comment by habegit** [comment]
Thx 4 fast fixing!
