### ISSUE TITLE
远程仓库ssh地址用户名不是git时会报错

### ISSUE THREAD

**Issue by Izumiko** [sourcegit-scm/sourcegit#13]
![图片](https://github.com/sourcegit-scm/sourcegit/assets/5195868/b7389c63-492a-4e36-b908-6ccefe539d62)
我用自建的Gitea时，如果服务器那边的用户名使用了gitea会报如上的错误。在命令行中可以正常添加并pull/push。

**Comment by love-linger** [comment]
SSH访问吗？如果是SSH访问，尝试将地址改为 ssh://user@……这种格式看一下 fetch 还会不报错呢

**Comment by Izumiko** [comment]
@love-linger 
![图片](https://github.com/sourcegit-scm/sourcegit/assets/5195868/ad299ed8-e061-4b12-ba9c-da85e5472fd7)
同样无法添加

**Comment by Izumiko** [comment]
找了一下，问题应该是出在这个文件：[GitURL.cs](https://github.com/sourcegit-scm/sourcegit/blob/master/src/Views/Validations/GitURL.cs)

**Comment by love-linger** [comment]
嗯，这个只是控制上面那个输入合法性检测的，后面我将SSH添加上去

**Comment by love-linger** [comment]
SSH协议clone库，一般不需要指定用户名，会根据key自动判断，你将 地址换成 git@xxxx 试一下

**Comment by Izumiko** [comment]
改成`git@xxxx`，并指定了我在Gitea中设置的key之后，还是会报“Permission denied”。

另外，key中不包含用户名信息吧？按我的理解，`git@xxxx`指的是服务端的git服务是以git用户来运行的，所以@前填的是git。而用包管理器安装的gitea，它默认是以gitea用户来运行，所以git的地址填`git@xxxx`的话，服务端那边不存在git用户，肯定连不上。不知道这样理解对不对

**Comment by sourcegit-scm** [comment]
![image](https://github.com/sourcegit-scm/sourcegit/assets/85621660/5c9e0993-08ed-4069-b5b6-bd9e9d132521)

https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols

与服务端是以什么用户来启动的没有关系，git 只是个默认的潜规则，key 中包含了邮箱信息，用户名填写 git 时，服务会自动判断

**Comment by Izumiko** [comment]
是呀，ssh协议中，省略用户名的话，是用客户端这边当前登录的用户名来作为连接时的用户名(**the user you're currently logged in as**)。比如我本机登录的用户叫做izumiko，那连接服务器时用户名就会用izumiko，和key无关。

**Comment by Izumiko** [comment]
![图片](https://github.com/sourcegit-scm/sourcegit/assets/5195868/359162f8-bd28-4460-bdc8-cf902fcb6b8e)
gitea的网页中，给出的地址是这个，用这个地址在git的命令行或者TortoiseGit中都可以正常使用

**Comment by sourcegit-scm** [comment]
> 是呀，ssh协议中，省略用户名的话，是用客户端这边当前登录的用户名来作为连接时的用户名(**the user you're currently logged in as**)。比如我本机登录的用户叫做izumiko，那连接服务器时用户名就会用izumiko，和key无关。

这个之前真没发现。我这里远程SSH连接也是直接使用的SSH key，登录上去的就是与我设置密钥时的帐号一致的。

> ![图片](https://user-images.githubusercontent.com/5195868/239889844-359162f8-bd28-4460-bdc8-cf902fcb6b8e.png)
> gitea的网页中，给出的地址是这个，用这个地址在git的命令行或者TortoiseGit中都可以正常使用

这个已经加上去了，需要自己编译一下

**Comment by Izumiko** [comment]
我本地没.net framework sdk，还是等下个版本发布吧。现在在命令行中添加完gitea的地址，在sourcegit中也能pull和push
