### ISSUE TITLE
ssh密钥.

### ISSUE THREAD

**Issue by zhepamagod** [sourcegit-scm/sourcegit#136]
非常喜欢这个软件.简单便捷.今天第一次使用,但有一些小问题
1. 没找到设置ssh密钥的地方,就是类似sourcetree这种:
![image](https://github.com/sourcegit-scm/sourcegit/assets/169280828/acedad35-0080-4cf7-96ad-7abf6003584e)

2. 在light模式..顶部的按钮tooltip有点小问题..

**Comment by love-linger** [comment]
感谢您使用SourceGit。

1. 该软件的SSH配置是针对每个remote的（即可为每个remote分别指定不同的SSH密钥）。当远程仓库地址被检测为SSH协议时，会出现输入密钥地址的输入框，如图所示：
![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/5455da5e-0eae-41c1-9f51-75b5af593f85)
2. AvaloniaUI的Tooltip确实存在一些问题，比如在多个屏幕下，有时会显示不全。目前还未找到具体的解决办法。

**Comment by zhepamagod** [comment]
我测试了下..
输入github的远程ssh地址确实可以,会显示sshprivatekey的选择框
国内的gitee是可以使用的,
但是国内腾讯的coding和阿里的codeup,都会提示: bad remote url format!!!   
![image](https://github.com/sourcegit-scm/sourcegit/assets/169280828/b62350da-0bc2-40bb-aa96-001011d4ac9a)
不知道其中有什么区别.

**Comment by love-linger** [comment]
1. 能否分别给个coding或阿里公共仓库中，软件不能识别的地址，我看一下是否需要扩展一下正则表达式检测
2. 对本质都是AvaloniaUI Tooltip显示不全的问题。我上面只是举了个例子

**Comment by love-linger** [comment]
哦，不用了，我知道问题在哪里了

```csharp
[GeneratedRegex(@"^[\w\-]+@[\w\.\-]+(\:[0-9]+)?:[\w\-]+/[\w\-\.]+\.git$")]
private static partial Regex REG_SSH1();

[GeneratedRegex(@"^ssh://([\w\-]+@)?[\w\.\-]+(\:[0-9]+)?/[\w\-]+/[\w\-\.]+\.git$")]
private static partial Regex REG_SSH2();
```

只支持`XXX@HOST:PORT/USER_OR_GROUP/REPO.git`或`ssh://XXX@HOST:PORT/USER_OR_GROUP/REPO.git`这种两级（USER_OR_GROUP后面直接跟REPO）的URL

这是个功能缺陷，我马上改一下

**Comment by zhepamagod** [comment]
coding:
https://godgodgame.coding.net/public/tools/ygfw/git/files
git@e.coding.net:godgodgame/tools/ygfw.git

阿里的codeup不能公开,地址大概是这样的.
git@codeup.aliyun.com:godgodgame/c-sharp-playground.git

这是gitee和github
git@gitee.com:godgodgame_admin/ggg-blog.git
git@github.com:sourcegit-scm/sourcegit.git


如果是正则的问题..感觉唯一的区别可能就是域名了...
前两个的域名都是二级域名.

**Comment by zhepamagod** [comment]
好了这个问题就关闭吧...我认为你的判断是正确的.!!!

**Comment by love-linger** [comment]
等我提交修改后，再关闭

**Comment by love-linger** [comment]
修改已入，您可下载 https://github.com/sourcegit-scm/sourcegit/actions/runs/9170013371/artifacts/1521802193 测试

**Comment by zhepamagod** [comment]
![image](https://github.com/sourcegit-scm/sourcegit/assets/169280828/e070f154-f099-463c-8ad1-c81b5f9e16a3)
Nice! 已经可以正常使用了!
