### ISSUE TITLE
Allow to delete multiple branches at the same time

### ISSUE THREAD

**Issue by Zuppremo** [sourcegit-scm/sourcegit#137]
Hi, I'm currently in my work project and doing some cleanup to the repo, I saw I can't select multiple branches to delete, and I thought that it would be nice if holding SHIFT + Left Click, allows me to select multiple branches and then right click delete branches (Or a shortcut like del), and a dialog box showing which branches are going to be deleted 

![imagen](https://github.com/sourcegit-scm/sourcegit/assets/48632338/4ad5cd05-bfdd-492d-82c6-40cdc819e877)

An example what I say 

![Untitled-2](https://github.com/sourcegit-scm/sourcegit/assets/48632338/7045b597-6c61-4199-811f-3eff6ee47897)

**Comment by love-linger** [comment]
You can try this build from https://github.com/sourcegit-scm/sourcegit/actions/runs/9232508906 to test this feature
