### ISSUE TITLE
feature request: better commit creation

### ISSUE THREAD

**Issue by Jayllyz** [sourcegit-scm/sourcegit#138]
Hi, I have a few ideas for this tool: 

I seem to be missing the commit description when creating a new commit, or is it a parameter I'm missing?

A way to save a commit template or a shortcut to write a [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) would be nice.

There's also the possibility of adding a co-author when creating a commit.

**Comment by love-linger** [comment]
> I seem to be missing the commit description when creating a new commit, or is it a parameter I'm missing?

Only `commit message subject` but not `commit message body` is displayed in the commit list. You can select the commit to see the full commit message in the details page below.

> A way to save a commit template or a shortcut to write a [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) would be nice.

> 
> There's also the possibility of adding a co-author when creating a commit.

I'm sorry, these features, while they sound great, won't be added in the near future.
