### ISSUE TITLE
非法远程仓库地址

### ISSUE THREAD

**Issue by Karlvision** [sourcegit-scm/sourcegit#14]
ver6.6版本中克隆远程仓库地址，发现远程仓库地址错误
升级到ver6.7版本中仍然错误，发现如果地址定义含有  ·   就会错误
当我切回ver5.8版本后，没有发现此错误。不确定是不是我的规范问题！

![image](https://github.com/sourcegit-scm/sourcegit/assets/50682981/3dc1f2d8-68c5-4ae0-a994-bbf18f966241)

**Comment by Karlvision** [comment]
private static readonly Regex[] VALID_FORMATS = new Regex[] {
            new Regex(@"^http[s]?://([\w\-]+@)?[\w\.\-]+(\:[0-9]+)?/[\w\-]+/[\w\-\.]+\.git$"),
            new Regex(@"^[\w\-]+@[\w\.\-]+(\:[0-9]+)?:[\w\-]+/[\w\-\.]+\.git$"),
            new Regex(@"^ssh://([\w\-]+@)?[\w\.\-]+(\:[0-9]+)?/[\w\-]+/[\w\-\.]+\.git$"),
        };

**Comment by love-linger** [comment]
非常抱歉，最近有点忙，现在才看到。如果能在各主要git托管平台创建名称带`.`的仓库，说明这是合理的。你可以提交pr或是由我直接修改。

**Comment by love-linger** [comment]
我这里直接改了
