### ISSUE TITLE
[BUG] 在 fast-forward 的时候再点击右键，等 fast-forward 同步完后会出现右键菜单的残影

### ISSUE THREAD

**Issue by findxyz** [sourcegit-scm/sourcegit#140]
![Snipaste_2024-05-22_21-18-39](https://github.com/sourcegit-scm/sourcegit/assets/1762895/cb7669d1-4e54-4508-81b1-3db893c1b80e)

**Comment by love-linger** [comment]
这可能是AvaloniaUI的bug，但我这里无法重现这一BUG

**Comment by gadfly3173** [comment]
在Deepin 20.9上也复现了，准确的说是要在fast-forward的[确定]键点击后快速右键分支就可以触发。reset操作也可以触发这个问题。看起来像是因为本地分支被刷新后，分支的选中状态消失或者原本的右键菜单触发节点消失导致的问题

**Comment by love-linger** [comment]
> 在Deepin 20.9上也复现了，准确的说是要在fast-forward的[确定]键点击后快速右键分支就可以触发。reset操作也可以触发这个问题。看起来像是因为本地分支被刷新后，分支的选中状态消失或者原本的右键菜单触发节点消失导致的问题

是的，我也在Windows及macOS平台重现了。根据你的描述，我直接以下面方式重现了：

1. 打开任意右键菜单
2. 按F5刷新整个仓库

**Comment by love-linger** [comment]
修复已提交，可下载 https://github.com/sourcegit-scm/sourcegit/actions/runs/9208856798 测试

**Comment by findxyz** [comment]
经过测试，在 fast-forward  时，无法再点出右键了，fast-forward 完成后正常点击出右键
