### ISSUE TITLE
[FEATURE] Allow to checkout to any commit in the tree.

### ISSUE THREAD

**Issue by filipeRmlh** [sourcegit-scm/sourcegit#144]
Sometimes is needed to test parts of the applications that is not necessary up to date with any branch or tag. I didn't notice any way to do that with the current state of the application.

**Comment by filipeRmlh** [comment]
Yes, I could do that. But that wasn't what I meant. I'm talking about checking out the commit itself. Sometimes it happens to be necessary.

**Comment by love-linger** [comment]
I do NOT understand. Did you talk about `cherry-pick` commit?

<img width="989" alt="截屏2024-05-25 19 46 30" src="https://github.com/sourcegit-scm/sourcegit/assets/4075673/d718baf3-640c-4ed0-8cf7-f5d33b3eb878">

Or you can provide the Git commands to do that job.

**Comment by gadfly3173** [comment]
> I do NOT understand. Did you talk about `cherry-pick` or `archive` command?


I think [filipeRmlh](https://github.com/filipeRmlh) means `git checkout <SHA1>`, which would not create a new branch.

> git checkout <SHA1>: Switches to a specific commit, creating a detached HEAD state.
> git reset: Moves the current branch's HEAD to a different commit, with options to affect the index and working directory.
> git checkout -b <branch name> <SHA1>: Creates a new branch starting from a specific commit, allowing you to safely work from that point in history.

**Comment by filipeRmlh** [comment]
I just made a Pull request about it... but I think it needs review. rs

**Comment by love-linger** [comment]
I've merged PR #147.
