### ISSUE TITLE
[FEATURE] Option to choose if I want to view an file in the "changes" section entirely or partially

### ISSUE THREAD

**Issue by filipeRmlh** [sourcegit-scm/sourcegit#145]
Righ now I can only view some lines around the change itself. It would be nice if I could choose how many lines around it I can visualize, or, at least, a simple button to change if I want to see the entire file or just parts of it.

**Comment by love-linger** [comment]
I've added two buttons to increase/decrease the number of visible lines in text diff view. For better comparison requirements, I recommand you to configure an external merge tool in Preference panel.
