### ISSUE TITLE
非法远程仓库地址

### ISSUE THREAD

**Issue by luckykeeper** [sourcegit-scm/sourcegit#15]
Release 6.9
git 仓库：自建 gitlab
问题：使用群组和子组组织项目时，路径会出现多个“/”，无法通过校验
e.g. http://test.com:8080/group/project/test.git 不可以 ； 而 http://test.com:8080/group/test.git 可以

![image](https://github.com/sourcegit-scm/sourcegit/assets/34579433/634f58a3-fee9-45ab-8e1e-f93580fa7940)

预期行为：能够正确识别并 clone

**Comment by luckykeeper** [comment]
感谢回复，是这里的正则表达式，回头我装个环境改一下，顺带问一下，请问您那边有计划改一下表达式匹配一下这种情况吗

https://github.com/sourcegit-scm/sourcegit/blob/8fa3a558a074a265d3ad9ccab129d79adc0148cf/src/Views/Validations/GitURL.cs#L7C1-L12C11

```csharp
    public class GitURL : ValidationRule {
        private static readonly Regex[] VALID_FORMATS = new Regex[] {
            new Regex(@"^http[s]?://([\w\-]+@)?[\w\.\-]+(\:[0-9]+)?/[\w\-]+/[\w\-\.]+\.git$"),
            new Regex(@"^[\w\-]+@[\w\.\-]+(\:[0-9]+)?:[\w\-]+/[\w\-\.]+\.git$"),
            new Regex(@"^ssh://([\w\-]+@)?[\w\.\-]+(\:[0-9]+)?/[\w\-]+/[\w\-\.]+\.git$"),
        };

```

**Comment by Cyborge1** [comment]
参照原有格式添加
`new Regex(@"^http[s]?://([\w\-]+@)?[\w\.\-]+(\:[0-9]+)?/[\w\-]+/[\w\-]+/[\w\-\.]+\.git$")`
可以满足你所列的路径，如果路径变化得再调整。

**Comment by luckykeeper** [comment]
好的，了解，感谢回复，我这边没有别的什么问题了，那我关闭 issues 了哈？
