### ISSUE TITLE
Better support for signed commits

### ISSUE THREAD

**Issue by hieucckha** [sourcegit-scm/sourcegit#154]
Hi,

When using the app, on the histories change, the message for that sign commit begins with "gpgsign..." as shown in the screenshot below. I wanted suggest we remove the "gpgsign" part and display the actual message. The "gpgsign" part can be moved to a label to indicate that the commit is signed.

![image](https://github.com/sourcegit-scm/sourcegit/assets/43875836/2adbda20-b0d0-4f87-b6d3-de44b651471f)

Thanks, very love this app.

**Comment by love-linger** [comment]
You can try this build from https://github.com/sourcegit-scm/sourcegit/actions/runs/9298593743
