### ISSUE TITLE
The changelist display and click behavior looks weird

### ISSUE THREAD

**Issue by gadfly3173** [sourcegit-scm/sourcegit#157]
In grid mode, the path on the right may be offset, click it will scroll to right, but not always the end.

https://github.com/sourcegit-scm/sourcegit/assets/28685179/d3af2548-89e4-43e4-9feb-2c402089107f

**Comment by gadfly3173** [comment]
`SourceGit.Views.ChangeCollectionView.IsWorkingCopy` property's name seems not match with `src/Views/ChangeCollectionView.axaml`'s Binding

**Comment by love-linger** [comment]
it's my mistake. i will fix it later

**Comment by gadfly3173** [comment]
https://github.com/sourcegit-scm/sourcegit/assets/28685179/f272038a-969a-44b1-85a7-30bb74273b4c

Switch the mode of the change list sometimes not correct with commit [f1ff969](https://github.com/sourcegit-scm/sourcegit/commit/f1ff969090dc376f90837139b5280af04c1166ec)

**Comment by gadfly3173** [comment]
LGTM
