### ISSUE TITLE
 GitFlow Start reliase show error

### ISSUE THREAD

**Issue by Shagrat2** [sourcegit-scm/sourcegit#168]
Ver: 8.15
OS: MacOs 14.5 M2

GitFlow Start reliase show error:

git: 'flow' is not a git command. See 'git --help'.
The most similar commands are
	reflog
	show
	
brew: git-flow 0.4.1_1 is already installed

**Comment by love-linger** [comment]
This is because macOS limits the PATH environment variable that GUI applications can access. You can do as following steps to resolve the problem.

1. Get the location where your git-flow installed. 
```shell
$ which git-flow
/opt/homebrew/bin/git-flow
```
2. Set the `PATH` environment for GUI application.
```shell
$ sudo launchctl setenv PATH $PATH:/opt/homebrew/bin
```

**Comment by love-linger** [comment]
Did you restart the SourceGit after running `launchctl setenv` command?

Try to run:
```shell
$ launchctl getenv PATH
```

Check if the `PATH` environment have been set properly

**Comment by love-linger** [comment]
Oh, I'm sorry. I know what's wrong. You need run `killall Dock` after `launchctl` command, and then restart the SourceGit.

**Comment by Shagrat2** [comment]
Yes. Restart user session

```
% launchctl getenv PATH
/opt/homebrew/opt/openjdk@17/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/X11/bin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/Applications/Little Snitch.app/Contents/Components:/usr/local/go/bin:/Users/ivan/workspace/golang/bin:/opt/homebrew/bin

```

**Comment by love-linger** [comment]
> Yes. Restart user session
> 
> ```
> % launchctl getenv PATH
> /opt/homebrew/opt/openjdk@17/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/X11/bin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/Applications/Little Snitch.app/Contents/Components:/usr/local/go/bin:/Users/ivan/workspace/golang/bin:/opt/homebrew/bin
> ```

Still not work after `killall Dock` ?

**Comment by Shagrat2** [comment]
killall Dock - Does not give a result
Restart computer - Does not give a result

**Comment by love-linger** [comment]
I'm using macOS 14.5 M3. I have no problem after running `launchctl setenv`...

You can try to add `LSEnvironment` key to the `Info.plist` of this app. Remember replace the value of `PATH` with yours.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleIconFile</key>
    <string>App.icns</string>
    <key>CFBundleIdentifier</key>
    <string>com.sourcegit-scm.sourcegit</string>
    <key>CFBundleName</key>
    <string>SourceGit</string>
    <key>CFBundleVersion</key>
    <string>SOURCE_GIT_VERSION.0</string>
    <key>LSMinimumSystemVersion</key>
    <string>10.12</string>
    <key>LSEnvironment</key>
    <dict>
        <key>PATH</key>
        <string>/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin</string>
    </dict>
    <key>CFBundleExecutable</key>
    <string>SourceGit</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleShortVersionString</key>
    <string>SOURCE_GIT_VERSION</string>
    <key>NSHighResolutionCapable</key>
    <true/>
</dict>
</plist>

```

**Comment by love-linger** [comment]
I've add `/opt/homebrew/bin` and `/opt/homebrew/sbin` into the plist. You can try the latest release.

**Comment by Shagrat2** [comment]
Worked

**Comment by Shagrat2** [comment]
Hello. New version broken this issue

**Comment by love-linger** [comment]
You can run `echo $PATH > ~/Library/Application\ Support/SourceGit/PATH` to generate a custom PATH env file to introduce `PATH` env to SourceGit.

**Comment by Shagrat2** [comment]
> You can run `echo $PATH > ~/Library/Application\ Support/SourceGit/PATH` to generate a custom PATH env file to introduce `PATH` env to SourceGit.

It works
