### ISSUE TITLE
A way to stage/unstage/reset a chunk of file

### ISSUE THREAD

**Issue by kekekeks** [sourcegit-scm/sourcegit#17]
i. e. this is how it works with GitExtensions:

https://github.com/sourcegit-scm/sourcegit/assets/1067584/0f202823-4a46-4ddc-abbc-3e58c0d8a689

With command-line tools it can be done interactively via `git add --patch <file>`.

**Comment by love-linger** [comment]
Very nice suggestion. I'm going to take a closer look at the GitExtension implementation and try to add that functionality.

**Comment by love-linger** [comment]
I submitted a simple implemetation for this feature to branch 'master'. I don't know if it meets your needs.

**Comment by kekekeks** [comment]
Would be really nice to not reset the scroll after recomputing the diff. Also, discard from staged is quite useful too.

**Comment by love-linger** [comment]
2b97d7c5999360006b7835162d100b07bd3a610b Keep the scroll offset after recomputing the diff
096fd6cb2270c26e8e04eaad97c9176ce9d65921 Supports discard changes from staged directly

These two commits has been pushed into branch 'master'.
