### ISSUE TITLE
[FEATURE] - UI graph of commits like the dead gmaster

### ISSUE THREAD

**Issue by albgen** [sourcegit-scm/sourcegit#171]
Hi,

is it possible to add a graph like the following.  Seems so much more clean.
![image](https://github.com/sourcegit-scm/sourcegit/assets/7231968/0bc7efd5-ab4d-40bd-83f3-b1c3a2147d3e)
![image](https://github.com/sourcegit-scm/sourcegit/assets/7231968/41fba1ad-f085-4d70-9876-a1c1f2a14a63)

**Comment by albgen** [comment]
not possible :( ?

**Comment by love-linger** [comment]
Yes, at least not planned in the near future
