### ISSUE TITLE
macOS sourcegit_8.15.osx-arm64.zip "app is damaged" 

### ISSUE THREAD

**Issue by jokax3m** [sourcegit-scm/sourcegit#173]
Hi,
after running sourcegit.app from sourcegit_8.15.osx-arm64.zip on macbook pro M1, the system reports: "The "SourceGit.app" application is corrupted and cannot be opened. You should move the item to the trash." . I tried downloading it on different networks and different browsers. The output is identical. The macOS version for Intel will run correctly in intel emulation.

Thank you.

Jozef.

**Comment by jokax3m** [comment]
Hi, I need for arm version run sudo xattr -cr /Applications/SourceGit.app, after that is app working. Thank you and sorry for issue.

**Comment by jokax3m** [comment]
it was a problem between the keyboard and the chair

**Comment by FardinHaque70** [comment]
@jokax3m Hey thanks a lot for providing the fix! Was facing the same issue on my mac as well.

**Comment by kashifsoofi** [comment]
@jokax3m thanks for the fix, was facing the same issue
