### ISSUE TITLE
Compare Branches

### ISSUE THREAD

**Issue by aklcraigc** [sourcegit-scm/sourcegit#174]
Hi, Love the project.
Is comparing branches on the road-map?
Thanks.

**Comment by love-linger** [comment]
Several revision comparisons are now supported:

* You can use `Ctrl` to select two different revisions to compare with in histories page.
* You can select a commit which is not the HEAD of current local branch in histories page, and using context menu to compare it with current local branch HEAD or worktree.
* You can select a branch to compare with current local branch HEAD or worktree by context menu. If there's no different between the selected branch and local branch HEAD or worktree, the context menu item will hide.

The branch comparison will be added in the next version

**Comment by love-linger** [comment]
You can try this build from https://github.com/sourcegit-scm/sourcegit/actions/runs/9461413286 with `Branch Comparison` feature.

![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/b26aa2ea-7e85-48fb-a5d5-7e61ba3814db)
