### ISSUE TITLE
Hope privode Keyboard Shortcuts for Actions，e.g. Commit ( Ctrl + Enter )

### ISSUE THREAD

**Issue by ccyr119** [sourcegit-scm/sourcegit#176]
Hope privode Keyboard Shortcuts for Actions，e.g. Commit ( Ctrl + Enter )
![image](https://github.com/sourcegit-scm/sourcegit/assets/1924486/84d64df6-4851-481e-b20e-8b7138d0bef0)

**Comment by love-linger** [comment]
Two hotkeys have been added:

![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/e7f0486e-6e44-4451-8fb7-5675f09d31db)

**Comment by love-linger** [comment]
For some reasons, the others are not in the plan.

* It is difficult to find a suitable key combination that does not conflict with the existing shortcut keys of each platform (Windows/macOS/Linux)
* Most of these features require the user to determine some parameters to run, while the entry of these features in UI is easy to find and interact with.
