### ISSUE TITLE
[FEATURE] Rename tab

### ISSUE THREAD

**Issue by lgranie** [sourcegit-scm/sourcegit#178]
Currently a tab got the name of the local repository's directory.
Could be nice to be able to rename it.

**Comment by love-linger** [comment]
You can select the repo you want rename, and open context menu by right-click, then you'll see the entry to edit it

**Comment by lgranie** [comment]
Without the "repo view" opened, it was not obvious
Thx

**Comment by love-linger** [comment]
> Without the "repo view" opened, it was not obvious Thx

You need not open a repo. You can do this in the Welcome page.
