### ISSUE TITLE
[FEATURE] Group tabs

### ISSUE THREAD

**Issue by lgranie** [sourcegit-scm/sourcegit#179]
I've got like 30 different git repositories : could be nice to be able to join some of them in a group/workspace.

**Comment by love-linger** [comment]
Try to right click on the blank area of the tree, then you'll find the entry to creat group. After that, you can drag repo nodes into it.

**Comment by lgranie** [comment]
- Right click on group => open all
- Add submodule to a group ( to open a repo and all the modules )

**Comment by love-linger** [comment]
I've add a context menu item to open all repositories in selected node. You can try it from this build https://github.com/sourcegit-scm/sourcegit/actions/runs/9558317794

I'll keep the way to open submodules in a repository.
