### ISSUE TITLE
[FEATURE] Get merge/diff tool config from git

### ISSUE THREAD

**Issue by lgranie** [sourcegit-scm/sourcegit#181]
Could be nice to init the merge/diff tool config from gitconfig.
For exemple : 
[merge]
  tool = p4merge
  conflictStyle = diff3
[mergetool "p4merge"]
  cmd = p4merge.exe -dw -tw 4 -le win "$BASE" "$LOCAL" "$REMOTE" "$MERGED"
[diff]
  tool = p4merge
  colorMoved = default
[difftool "p4merge"]
  cmd = p4merge.exe -dw -tw 4 -le win "$BASE" "$LOCAL" "$REMOTE" "$MERGED"

**Comment by love-linger** [comment]
I've pushed a commit that changes the `Custom` mode to `Use Git Settings`, which means you need not config difftool/mergetool commands in this app.

![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/f01ea8bc-5a22-4396-b88d-110888125b28)

**Comment by love-linger** [comment]
You can try it from https://github.com/sourcegit-scm/sourcegit/actions/runs/9558840357

**Comment by lgranie** [comment]
Hi,
I have got a "[$home]\AppData\Local\Temp/git-blob-b58684/[myfile]" is invalid
The file does not exist

**Comment by lgranie** [comment]
And "Custom" disappeared

**Comment by love-linger** [comment]
> And "Custom" disappeared

Yes, as I said, `Custom` has been replaced with `Use Git Settings`. It means there are only two ways to use external difftool/mergetool:

* Use tools supported by this app. In this way, you need only provide the path to the executable file.
* Use git settings. In this way, this app will open the external difftool/mergetool by command `git difftool -g --no-prompt ${DIFF_OPTIONS_FROM_CHANGE}` or `git mergetool ${CHANED_FILE}`

**Comment by love-linger** [comment]
I've test the `p4merge`, and can not re-produce the issue your video shows.

https://github.com/sourcegit-scm/sourcegit/assets/4075673/496e433f-39b9-429b-b35d-a86620cc6fa6

**Comment by love-linger** [comment]
I've add the `P4Merge` to the build-in external merge/diff tool. You can try from this build https://github.com/sourcegit-scm/sourcegit/actions/runs/9607351924
