### ISSUE TITLE
File picker could not open on Deepin with commit 67c771d

### ISSUE THREAD

**Issue by gadfly3173** [sourcegit-scm/sourcegit#183]
It seems that Avalonia does not support deepin-file-manager or need some other configuration. 
![image](https://github.com/sourcegit-scm/sourcegit/assets/28685179/f526313f-d730-4869-bfb8-e41a1d0d9232)
The file picker with `builder.UseManagedSystemDialogs();`

**Comment by love-linger** [comment]
According to https://github.com/AvaloniaUI/Avalonia/issues/9383#issuecomment-1378350456, AvaloniaUI will use native picker when turn off `UseDBusFilePicker`, which seems to be even less stable.

![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/04dd843e-9116-4144-8e3c-486fbbe27b3c)

I would like to revert commit 67c771d7d99a54845131816d753ad9ddccec608d.
