### ISSUE TITLE
[FEATURE] - Filtered branches

### ISSUE THREAD

**Issue by lgranie** [sourcegit-scm/sourcegit#184]
Hi,

Thx for sourcegit, I love it \o/

Will it be nice to be able to :
- know / list / group all filtered branches ( maybe an entry like "LOCAL BRANCHES" or "REMOTES" )
- clear all the filters with one click

**Comment by love-linger** [comment]
I've a simple implementation for this feature, which is similar to another well-known software - Fork.

![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/e54eea84-53aa-463f-8150-74750e93f481)

You can try it from this build https://github.com/sourcegit-scm/sourcegit/actions/runs/9563415658
