### ISSUE TITLE
URL with ~ character results in incorrect format error during git clone

### ISSUE THREAD

**Issue by doom4ster** [sourcegit-scm/sourcegit#186]
Description:
When attempting to clone a repository using the git clone <url> command, if the URL contains the ~ character, an error is returned indicating that the URL format is incorrect.

Steps to Reproduce:
Use the git clone command with a URL that includes the ~ character.
Observe the error message indicating an incorrect URL format.
Expected Behavior:
The repository should be cloned successfully without any format errors, even if the URL contains the ~ character.

Actual Behavior:
An error is returned stating that the URL format is incorrect.

Additional Information:
Git version: 2.45.1
Operating System: WIN11 23H2

Screenshots:
<img width="331" alt="截圖 2024-06-19 10 23 28" src="https://github.com/sourcegit-scm/sourcegit/assets/3806072/61d6e9af-e872-4880-8595-42d9d71122ce">
<img width="325" alt="截圖 2024-06-19 10 19 55" src="https://github.com/sourcegit-scm/sourcegit/assets/3806072/353710dc-8aea-49b7-b1c2-acec0be39ffa">

**Comment by love-linger** [comment]
I've pushed a commit to fix this issue. You can try this build from https://github.com/sourcegit-scm/sourcegit/actions/runs/9575271828
