### ISSUE TITLE
Improvement request: CTRL+1 and CTRL+2 shortcuts

### ISSUE THREAD

**Issue by gigi81** [sourcegit-scm/sourcegit#19]
In other git clients, these shortcuts are common:
- CTRL+1 takes you to "changes"
- CTRL+2 takes you to "histories"

Would be nice to have. thanks

**Comment by love-linger** [comment]
Good suggestion. Perhaps a page that introduce all the hotkeys used in this app is needed also.

**Comment by gigi81** [comment]
Having these shortcuts would be already great. Having a page somewhere with the list of shortcuts would be even better! Thanks for the work on this!
