### ISSUE TITLE
[FEATURE] Grouping Changes

### ISSUE THREAD

**Issue by lzcjames** [sourcegit-scm/sourcegit#195]
Hello,

Is it possible to group changes in the changes area? 

Similar to the changelist feature in IntelliJ IDEA.

谢谢!

**Comment by love-linger** [comment]
不太明白你所指的分组具体指的是什么。是文件目录树视图吗？或是截图说明一下呢？期待你的回复

**Comment by lzcjames** [comment]
感谢你的快速回复。

如果能在Changes的版块里能创建分组，就像Intellij中的创建changelist那样:
![image](https://github.com/sourcegit-scm/sourcegit/assets/41846652/6dae897e-4d59-4123-a42c-c16b8126132f)
在图中，默认的分组名为Default Changelist, 然后我们也可以自己创建新分组比如图中的My new feature来对已更改的文件进行分组。

我这样的解释是否清楚些?

**Comment by love-linger** [comment]
很有意思的feature。这个分组是如何建立的呢？（不好意思，我对IDEA不熟悉）需要用户填写正则表达式吗，还是完整路径列表？

**Comment by lzcjames** [comment]
我觉得这个分组应该不需要正则表达式或者完整路径列表，它在Intellij中应该就是一个虚拟的分组。

以下是我在Intellij中个人项目的一个演示:
![Demo-2](https://github.com/sourcegit-scm/sourcegit/assets/41846652/1afef632-c4fa-4277-b37f-7dd8b9019901)

在Local changes 的版块里，默认分组 "changes" (之前叫Default Changelist) 包含了两个被更改的文件，然后我新建一个分组名为 "change for beer"，并把这两个文件拖动到新分组里。

如果这个功能能被实现，那会很棒。

**Comment by love-linger** [comment]
感谢您的耐心回复。我基本上了解了该功能具体的应用场景。

如果照搬IDEA的方案，要改动的东西太多了，目前支持的三种显示方式（列表，文件名+路径列表，文件目录树）都需要修改，包括但不限于：

* 计算选中changes
* 仓库因外部编辑或其他原因，changes列表变更，自动选中之前的文件
* discard操作会根据是否所有的changes被选中，而采用 reset 还是 一个个选中文件 checkout -f

换个思路，如果保持当前显示方式，加入类似macOS的颜色标签功能（可过滤），实现应该比较简单，但会增加记忆难度。

后面我再想想是否需要加入这个feature和如果实现它吧。

**Comment by heartacker** [comment]
借题问一下:
这个分组啥意思，如何使用呢，一直搞不懂。
![image](https://github.com/user-attachments/assets/baafd583-f0d1-417b-9073-ccc7ebd1ad13)

**Comment by love-linger** [comment]
![image](https://github.com/user-attachments/assets/5e908e9a-5abb-4b9b-a4d5-e5072e3cbe3b)

像这样，将你的仓库分一下类/组，方便管理

**Comment by heartacker** [comment]
但是不知道如何添加仓库到这个分组？新建分组之后，如何将仓库添加到这个分组合。
我以为是类似浏览器的分组
![image](https://github.com/user-attachments/assets/d18f49c6-c0ba-4c43-89ad-1a669faedb4f)
（挺需要这个功能的）比如，同一个仓库，不同的项目分支，但是显示都是一个名字，暂时只能标记颜色区分。
![image](https://github.com/user-attachments/assets/f8778f07-08f5-41f9-b066-0d5cf951a7a8)

**Comment by love-linger** [comment]
* 可以直接将仓库拖拽到那个组下
* 标签页的名字是可以自定义的，右键树中的仓库，选择编辑，可以给仓库指定一个友好的名字，比如我上面的截图中，sourcegit-scm.github.io仓库，我给了个简短的名字 SourceGit.Pages

**Comment by heartacker** [comment]
好的，明白了。谢谢了
不过
针对第一点：建议可以添加明显一下的入口，比如添加仓库，或者在仓库里面可以选中所在分组之类的。
针对第二点：除了这个之外，是否可以添加 谷歌浏览器类似的分组。 然后如果仓库已经属于分组，打开的之后可以自动显示分组。

**Comment by love-linger** [comment]
设计颜色的目的参考了macOS的设计，本意就是快速识别同类型/组的库

**Comment by love-linger** [comment]
非常抱歉，现在工作区变更列表更加复杂了（需要支持amend模式等），综合考虑，不计划支持该特性。

**Comment by lzcjames** [comment]
> 非常抱歉，现在工作区变更列表更加复杂了（需要支持amend模式等），综合考虑，不计划支持该特性。

没事，谢谢你的反馈!
