### ISSUE TITLE
用户体验问题：1.树形分支会在提交代码、下拉代码等操作自动关闭树形结构； 2.拉取远程分支要手动输入本地分支名

### ISSUE THREAD

**Issue by heyXiaoT** [sourcegit-scm/sourcegit#20]
1. 如图，当我在当前分支下拉代码、提交代码后，分支文件夹会自动收起来，体验较差
![image](https://github.com/sourcegit-scm/sourcegit/assets/30957584/83555e4b-d852-4717-b2ee-0a961948895d)

变成如下图所示
![image](https://github.com/sourcegit-scm/sourcegit/assets/30957584/92cc6098-b3e8-41a6-87f6-50da3328a15d)

2. 拉取远程分支需要手动输入本地分支名，建议默认复制远程分支名给本地分支
![image](https://github.com/sourcegit-scm/sourcegit/assets/30957584/7a8577d3-e946-4ec7-b81d-f9a6a61ee296)

**Comment by love-linger** [comment]
问题1，已确认为BUG，本来设计是在重建分支树时会记录Expanded状态的，见`SourceGit.ViewModels.Repository.RefreshBranches`。后面会提交修复。
问题2，已在最近提交 2ec46c9da0ecdf6620aa08397fd9566da47bf3f4 中实现。***注：该提交未入Release 8.2，可在Action中下载基于最新提交的编译结果***

**Comment by love-linger** [comment]
你可以尝试 https://github.com/sourcegit-scm/sourcegit/actions/runs/8214723561#artifacts ，是否满足需求

**Comment by love-linger** [comment]
另外，对于之前版本创建的分支（基于某一remote branch），并未自动设置upstream，可按以下方式手动设置
![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/22e166e7-211e-476d-a464-05948143888b)
> 注，8.3 创建的分支（基于某一remote branch）已自动设置upstream，无需此操作

**Comment by love-linger** [comment]
因为该问题一周时间内没有反馈，所以这里我先关闭，有问题再打开
