### ISSUE TITLE
[FEATURE] Warn when commit subject line goes beyond a certain number of characters

### ISSUE THREAD

**Issue by WrichikBasu** [sourcegit-scm/sourcegit#201]
It is customary to limit the commit subject line to 50 characters. The subject line should be a synopsis; the details should go into the commit body. GitHub, for instance, trims the subject line to 50 characters, and shows the characters beyond that in the body of the commit.

JetBrains IDEs like IntelliJ IDEA, Android Studio and PyCharm have an option to show a warning if the commit subject line goes beyond a certain number of characters. It's switched off by default, but can be enabled independently in each project.

It would be extremely helpful if such a warning can be shown in this application too! I checked the Preferences window, but couldn't find any setting for that, so I assume this has not been implemented yet. If I am wrong, and this feature already exists, please let me know where to find it.

I have been using this application for the last few days, and find it extremely helpful. Especially because it can GPG-sign the commits, which no other git GUI application does currently (I have been through a lot of them, and every one lacks this feature.) Will be immensely helpful if this warning feature is implemented.

In case it matters, I am on Ubuntu 22.04.

**Comment by love-linger** [comment]
It's a new feature that is not supported by this app currently. I'll consider to add this feature later.

**Comment by love-linger** [comment]
I've pushed a simple implementation of this feature. Since the git traits all text before an empty line as `subject`, the subject length is not only include the first line. For example:
```
feature: xxxx
* a
* b

message
```
The subject of full commit message above is `feature: xxxx * a * b`. You can test this by `git log --pretty=format:"%s"`. 
> `%s` in `--pretty=format` means to output commit's subject only.

In this implementation, there is a horizontal line to indicate where the subject ends. For example:

<img width="755" alt="image" src="https://github.com/sourcegit-scm/sourcegit/assets/4075673/828377ea-ab3f-44a6-ba59-0c831dcbd01a">

<img width="755" alt="image" src="https://github.com/sourcegit-scm/sourcegit/assets/4075673/64395fa9-7a3f-478e-9a49-f54358c50be2">

You can test it from this build 
https://github.com/sourcegit-scm/sourcegit/actions/runs/9631824264

**Comment by WrichikBasu** [comment]
The horizontal line looks nice! Yes, git treats everything before the first blank line as subject, but GitHub treats anything after the first `\n` as body. Though I believe it's fine to stick to the current implementation; in general, it is not expected to use newlines in the subject. Tested it from the artifact and it worked fine.

One small improvement would be nice: I don't see any option to vertically decrease/increase the size of the commit message box. It would be helpful if one can decrease the vertical length of the `Select File to View Changes` box and thereby increase the vertical size of the commit message box.

**Comment by 40detectives** [comment]
I really enjoy this hint in the UI, but the hardcoded 50 characters is a bit too strict. It would be nice to be able to adjust the limit to a custom length (for each repository, for example), or at the very least to have a few sensitive options to chose from (72, 50, ...).

For example, if you are following a convention like [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/), the amount of characters remaining for the subject of the commit message is scarce. So if you are writing a commit message with a type and scope, e.g.:
```
refactor(testing): <actual subject>
```
In that case that would be already 18 characters long before the subject. 

Other software (like gitkraken) uses a limit of 72 characters for the subject. If I understand it correctly, the 72 limit comes from assuming 80 character width terminals, and giving some space for common indentation while pretty printing it to the console.

**Comment by love-linger** [comment]
You can change it from the Preferences dialog

**Comment by 40detectives** [comment]
@love-linger thanks! My bad, I somehow skipped that setting when I was searching for it.
