### ISSUE TITLE
[FEATURE] Add resizable columns and resizable vertical areas

### ISSUE THREAD

**Issue by ozmium** [sourcegit-scm/sourcegit#203]
### Summary 

SourceGit is great, but many parts of the User Interface (UI) cannot be resized or customized to the user's preferred width or height. This causes large usability problems, because text is truncated, even if it's a small amount of text, and it's not possible to see all the words or sentences.

![SourceGit_bugs_resizable_columns_and_vertical_areas_are_needed](https://github.com/sourcegit-scm/sourcegit/assets/6191136/4fa7db45-377b-4334-a58b-60d1b6795a0a)

### Steps to reproduce the bugs

1. Launch SourceGit and load a typical Git repository, for example, see the screenshot.
2. In the list of Git commits, try to view the full name and email address of a committer. Try to resize the column to be bigger or smaller.
3. In the list of Git commits, try to view the full SHA Git ID of each commit. I want to see more than 10 characters. Try to resize the column to be bigger or smaller.
4. In the MESSAGE area that shows the Git commit message, try to display 10 lines of the Git commit message, by resizing it.
5. In the list of file changes of a Git commit, at the bottom, try to show more than 10 files in the list, by resizing it.

### Expected Result

* I should be able to resize all the columns mentioned above. (Also shown in the screenshot)

### Actual Result

* In the list of Git commits, the full name and email address cannot be seen, because the column is too small and it cannot be resized. It can only show about 6-10 characters maximum.
* In the list of Git commits, the full SHA Git ID cannot be seen, because the column is too small and it cannot be resized.
* In the MESSAGE area that shows the Git commit message, it will only show 2 lines, and it cannot be resized bigger or smaller. It's also impossible to select text across multiple lines.
* In the list of file changes of a Git commit, I can only see about 2-3 lines, even when the window is full screen. The file list cannot be resized.

### Impact

* Usability problems - truncated text, cannot see the full words.
* Non-customizable UI.
* The UI does not adapt to different screen sizes or different window sizes.
* Space is wasted in some places.

**Comment by love-linger** [comment]
![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/d25439f5-9274-45fc-b6de-3a7191aaf575)

The information page shows the details of selected commit. The solution shows in your picture above is more likely to result in incomplete information presentation, especially if you're using a horizontal layout:

![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/ef893a5d-ec42-429a-80d3-c1ff9b57e07d)

**Comment by love-linger** [comment]
The commit SHA in list is not displayed incomplete, but displayed in abbreviated way. This is a common way to display commits in list. For example, this is the histories of a branch on Github:

![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/e3b28d4f-5a93-4744-95ca-2781b4035fbe)

**Comment by ozmium** [comment]
> ![image](https://private-user-images.githubusercontent.com/4075673/342177595-d25439f5-9274-45fc-b6de-3a7191aaf575.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMjUyMjUsIm5iZiI6MTcxOTIyNDkyNSwicGF0aCI6Ii80MDc1NjczLzM0MjE3NzU5NS1kMjU0MzlmNS05Mjc0LTQ1ZmMtYjZkZS0zYTcxOTFhYWY1NzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjRUMTAyODQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmQ2ZTI0YWY3NzJjM2NiYzBjYmZiZmE4ZTc0YzMzYzhkZTc4NzA5YjczNjNjNjc2Njg1NzJjMzg3NGIwODAyOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vGJRapywLqIDDjawkG96w7sWPbqVsevKK6835hNuKT4)
> 
> The information page shows the details of selected commit. The solution shows in your picture above is more likely to result in incomplete information presentation, especially if you're using a horizontal layout:
> 
> ![image](https://private-user-images.githubusercontent.com/4075673/342178239-ef893a5d-ec42-429a-80d3-c1ff9b57e07d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMjUyMjUsIm5iZiI6MTcxOTIyNDkyNSwicGF0aCI6Ii80MDc1NjczLzM0MjE3ODIzOS1lZjg5M2E1ZC1lYzQyLTQyOWEtODBkMy1jMWZmOWI1N2UwN2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjRUMTAyODQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWUxYTNiMTY0ZmJhY2YxM2U5Mzc4ZWNlYTY5YjcwMGQ0NDUwY2E5NTdkMGE5N2Q4YzRmYTc2MmY1ZDU1NDAwZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZqNnZkdNWIJbh9MtFRYImddX5U14koaEQftJQfEjTCg)

Thanks for responding.

There will always be incomplete information displayed for any layout used, whether it's the horizontal layout or the vertical layout. In the example screenshot above in the Git history list on the left, it shows very heavily truncated Git messages, where only 24 characters are displayed. That's not enough for most people.

The important thing is that every user has different preferences for how they want this data to be displayed. Sometimes a user wants to see the long Git messages. Other times, they want to see the full name + email address of the committer.

That's why all of these things should be resizable, so that the user can choose which columns they want to see more or less of, at any time.

Everything needs to be resizable so that the user can change the display of data at any time.

The sidebar on the left is resizable (the place that shows "WORKSPACE" , "LOCAL BRANCHES" and so on). Please add the resize ability to all the other places.

**Comment by ozmium** [comment]
Thanks for adding these new features 👍. I tested them on SourceGit version 8.20 (from 8 July 2024) and they work great! Well done. 😎
