### ISSUE TITLE
[Feature Request] Support multi worktrees

### ISSUE THREAD

**Issue by prime167** [sourcegit-scm/sourcegit#205]
> Manage multiple working trees attached to the same repository.
> 
> A git repository can support multiple working trees, allowing you to check out more than one branch at a time. 

sourcegit can now open a worktree without any issue. I suggest add Create，Remove and prune worktrees functions
worktree 对于多分支开发非常有用，避免频繁切换分支的麻烦。
建议增加 管理 worktee 的功能，包括从本地分支创建一个worktree，删除 worktree，清除无 效worktree

谢谢!

**Comment by love-linger** [comment]
我提交了一版这一功能的实现。你可下载 https://github.com/sourcegit-scm/sourcegit/actions/runs/9694914222 体验该功能

**Comment by prime167** [comment]
辛苦！
我试了一下新建worktree，分支不存在是可以的，已存在的分支不行，提示已存在。
以下是GitExtensions的新建worktree的截图。供参考
![图片](https://github.com/sourcegit-scm/sourcegit/assets/3722845/2f8ad341-d643-4025-bf8e-1692d86e5e13)

**Comment by love-linger** [comment]
提交了一版新的修改，你可下载 https://github.com/sourcegit-scm/sourcegit/actions/runs/9706084089 测试

**Comment by prime167** [comment]
![3](https://github.com/sourcegit-scm/sourcegit/assets/3722845/658135bf-d882-4c30-843e-e9354d57ed88)

还是不行。输入分支名后，不点确定就提示分支存在了。
还是希望把界面再改一改，能够选择已有分支或者新建分支，路径根据主分支路径自动生成

**Comment by love-linger** [comment]
又又又又提交了一版……

参考你给出的截图，分两种模式：一是使用现有分支
![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/d7a779ea-73e5-406a-86a9-2002ef30f864)
一是创建新分支
![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/e861cfbe-f736-44e6-ac6d-3af3dce16eca)

你可下载 https://github.com/sourcegit-scm/sourcegit/actions/runs/9707282033 测试该功能

**Comment by prime167** [comment]
谢谢，动作好快！这一版距离我的预想很近了。

#### 我觉得是先选择或创建分支再选路径，路径名根据分支名走。
相比存储路径，大多数人更关心的是分支名。分支可能是公开的、已经创建的，但目录肯定是只有自己知道、关心（其实也没有那么关心，按照统一的规则生成即可，比如下面的用 _ 连接）

#### Location 最好可以预填充，当然用户可以选择其他目录
如上面所说，比如我的主目录是d:\test 
 * 如果我的分支名是Develop，那么这个分支的目录就是D:\test_Develop
 * 我的主目录是d:\test, 如果我的分支名是Feat/A，那么这个分支的目录就是D:\test_Feat_A

**Comment by love-linger** [comment]
> 我觉得是先选择或创建分支再选路径，路径名根据分支名走

在这个软件中，不会这样设计。因为`git worktree add`命令中只有`path`是必填项。本地分支名反而是选填参数，缺省时使用路径文件夹名。且如果手动指定本地分支名时，可选两种方式：

* `-b <branch_name>` 会保证本地没有该名称的分支存在，也是这个软件修改之前使用参数
* `-B <branch_name>` 忽略上述检测，这是修改之后的

该软件会尽量使图形操作与原始命令操作一致

**Comment by love-linger** [comment]
我现在正在考虑在选择`Create New Branch`后，会重新使用`-b <branch_name>`来保证本地没有该名称的分支存在。这样与使用本地已存在分支做出区别。同时也会体现`-b`与`-B`的差异。

**Comment by prime167** [comment]
> 在这个软件中，不会这样设计。因为git worktree add命令中只有path是必填项。本地分支名反而是选填参数，缺省时使用路径文件夹名

好的，我的思路更多是从图形界面出发的，也受了其他软件先入为主的影响。

**Comment by love-linger** [comment]
其实可以在路径中直接填写相对路径，比如：想新建一个名为test的分支并以worktree方式checkout到新的目录。那路径就可以直接填写`../test`并启用`Create New Branch`（后面该方式会改为默认选中方式），不需要填写分支名。

**Comment by prime167** [comment]
没问题，这样自由度更大一些，也更符合原始命令

我测试了上面的最新版，我比较喜欢的一个功能是如果一个分支已经签出到了一个 worktree，双击会自动在新的标签打开这个分支，否则在当前标签切换分支。Fork 和 GitExtensions 都会报错

在打开新标签后能否自动选中这个分支的最新提交？
