### ISSUE TITLE
[FR] lfs操作，支持选定 remote

### ISSUE THREAD

**Issue by heartacker** [sourcegit-scm/sourcegit#209]
![image](https://github.com/sourcegit-scm/sourcegit/assets/1876302/bcb4292d-b01e-4758-93ea-993d6cc46cc8)

请求支持选定操作那个remote

lfs 在多remote 的管理一直是很头疼的，希望此软件可以解决这个问题

**Comment by love-linger** [comment]
真心不建议多个LFS server存在，Cherry-Pick/Merge等操作都会有问题，建议多个remote下，始终使用其中一个LFS server。比如在项目中新建`.lfsconfig`文件，添加如下配置：
```
[lfs]
    url = https://example.com/lfs/objects
```

**Comment by love-linger** [comment]
当然这个功能是可以添加的

**Comment by heartacker** [comment]
比如， 代码仓库 同时使用 gitlab 和github，并都开启了 lfs，
默认使用gitlab 开发，大家都往gitlab 里面提交。
后面代码从gitlab pull 下来以后，就无法 push 到github，很多时候，是英文 lfs 问题。

当然，一般都是使用一个 平台做开发，另外一个主要做代码备份，但是这个确实是很常见的问题啊，没法避免。

所以希望，此功能。

**Comment by heartacker** [comment]
> 当然这个功能是可以添加的

感谢，刚需，谢谢啊

**Comment by love-linger** [comment]
提交了相关的功能扩展

* 对原有的GIT LFS Fetch/Pull/Locks/Lock/Unlock等操作，增加指定remote的功能
* 增加了Push菜单，用于向指定的remote推送本地LFS对象
* 当只有一个remote时，各操作会自动选择remote。比如：Fetch操作不再需要手动选择一次remote，会自动选择并运行。

下载地址：https://github.com/sourcegit-scm/sourcegit/actions/runs/9673264293
