### ISSUE TITLE
open last repositories

### ISSUE THREAD

**Issue by ghiboz** [sourcegit-scm/sourcegit#210]
should be possible open the last repositories *(better is to have a parameter in the config to mantain this thing)*

**Comment by love-linger** [comment]
You can enable the `Restore windows` option in `Preference` window.

![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/647e8547-2222-440d-8cb6-7f5276313422)

**Comment by ghiboz** [comment]
wow! thank you! I missed this setting, sorry!
