### ISSUE TITLE
设置的是vscode ，但是实际上却是 vscode insider

### ISSUE THREAD

**Issue by heartacker** [sourcegit-scm/sourcegit#212]
![image](https://github.com/sourcegit-scm/sourcegit/assets/1876302/d8897db1-35bb-411c-8f04-8b2f775f36c7)

**Comment by love-linger** [comment]
这是两个功能，对比工具是点击DiffView中使用外部对比工具查看时调用的。
![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/6ce98f07-44c3-4f82-b275-f913b2bd33d9)

而主工具栏的使用外部编辑器打开，一般不需要配置，它会自检测是否已安装相关应用，这里是个列表，比如：
![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/8bf62a51-99e6-4d85-9c51-83f9e4c08fc1)

对于VSCode，它检测的是相应的注册表项是否存在。
