### ISSUE TITLE
[Feature] Switch bouton on unstaged / Staged block

### ISSUE THREAD

**Issue by Kvnsm** [sourcegit-scm/sourcegit#214]
Would it be possible to have a switch button to display the "file name / full file path" for the "staged / unstaged" block?
Thank's a lot

**Comment by love-linger** [comment]
You can change the display mode by this button:
![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/191741e6-f321-4178-97c7-4df842c783d6)

**Comment by Kvnsm** [comment]
Oooh really ! Appreciate it ! Sorry for the disturb ^^
