### ISSUE TITLE
[Feature] Filtrer for tags

### ISSUE THREAD

**Issue by Kvnsm** [sourcegit-scm/sourcegit#215]
Wouldn't it be nice to have a tag filter if possible?

![image](https://github.com/sourcegit-scm/sourcegit/assets/17532533/e8f1384a-734e-410a-becf-8fc581d4c3fe)

**Comment by love-linger** [comment]
To try this feature, please download the latest build from https://github.com/sourcegit-scm/sourcegit/actions/runs/9697741836
