### ISSUE TITLE
[FEATURE] Ability to change branch yellow color

### ISSUE THREAD

**Issue by MelonHell** [sourcegit-scm/sourcegit#225]
I tried changing all the color options, but it doesn't change
![image](https://github.com/sourcegit-scm/sourcegit/assets/53826469/2b68fd5c-1f06-4ac5-b9cf-a5a6b339dea8)

**Comment by love-linger** [comment]
Four colors added.

| KEY | DESC |
| --- | --- |
| Color.DecoratorIconBG | Background color for commit ref icon |
| Color.DecoratorIcon | Foreground color for commit ref icon |
| Color.DecoratorBranch | Background color for commit branch ref name |
| Color.DecoratorTag | Background color for commit tag ref name |

**Comment by love-linger** [comment]
| KEY | DESC |
| --- | --- |
| Color.DecoratorFG | Foreground color for commit ref name |
