### ISSUE TITLE
No place to post your themes :D

### ISSUE THREAD

**Issue by MelonHell** [sourcegit-scm/sourcegit#227]
I would like to see some place where people could share themes and other things

"JetBrains Dark" theme 
https://gist.github.com/MelonHell/a8c00cd0d6d8df4ebcbe3b92edd37de6

**Comment by love-linger** [comment]
I've created a new repo [sourcegit-theme](https://github.com/sourcegit-scm/sourcegit-theme) and add your themes into it. Thanks very much.

**Comment by love-linger** [comment]
@MelonHell I've changed the theme configuration file format. You can see it from https://github.com/sourcegit-scm/sourcegit-theme/tree/develop
