### ISSUE TITLE
commit time doesn't take the right timezone

### ISSUE THREAD

**Issue by ghiboz** [sourcegit-scm/sourcegit#229]
I'm using with my custom server (i'm on CEST as timezone) and this is a gk list:
![image](https://github.com/sourcegit-scm/sourcegit/assets/446533/50c8906b-c0bd-4fb3-98c3-5484a2fe5675)

and this is a sourcegit list:
![image](https://github.com/sourcegit-scm/sourcegit/assets/446533/cf9e4958-8bbe-47e9-981b-3ddff80b938a)

**Comment by love-linger** [comment]
Commit datetime gets from `git log --pretty=format:"%ct"`, which outputs the Unix timestap of commit time, and converts to the local time zone of your PC by this code:

```cs
 public string CommitterTimeStr => _utcStart.AddSeconds(CommitterTime).ToString("yyyy/MM/dd HH:mm:ss");
 public string CommitterTimeShortStr => _utcStart.AddSeconds(CommitterTime).ToString("yyyy/MM/dd");

 private static readonly DateTime _utcStart = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc).ToLocalTime();
```

I don't know if the algorithm is wrong.

**Comment by gadfly3173** [comment]
> I don't know if the algorithm is wrong.

It may be because your _utcStart is converted to local time when it is initialized, instead of converting the calculated target time to local time. Daylight saving time changes will not be reflected in the UTC timestamp 0.

**Comment by love-linger** [comment]
> > I don't know if the algorithm is wrong.
> 
> It may be because your `_utcStart` is converted to local time when it is initialized, instead of converting the calculated target time to local time. Daylight saving time changes will not be reflected in the UTC timestamp 0.

Should I change the code to:
```cs
DateTime.UnixEpoch.AddSeconds(CommitterTime).ToLocalTime().ToString(...)
```

**Comment by gadfly3173** [comment]
> ```cs
> DateTime.UnixEpoch.AddSeconds(CommitterTime).ToLocalTime().ToString(...)
> ```

I am not familiar with time handling in C#, but it looks similar to what I usually do in Java (as shown below)
```java
new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date())
```

**Comment by love-linger** [comment]
> > ```cs
> > DateTime.UnixEpoch.AddSeconds(CommitterTime).ToLocalTime().ToString(...)
> > ```
> 
> I am not familiar with time handling in C#, but it looks similar to what I usually do in Java (as shown below)
> 
> ```java
> new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date(timestamp))
> ```

Thanks for reply. I'll try to fix it by this way.

**Comment by ghiboz** [comment]
thanks! checked and works fine here now! 👏🏻
