### ISSUE TITLE
Pull settings not stored

### ISSUE THREAD

**Issue by ghiboz** [sourcegit-scm/sourcegit#231]
![image](https://github.com/sourcegit-scm/sourcegit/assets/446533/368d1644-1a6a-42a7-a756-e4fe94072bfe)

I use `stash and reapply` but each time I have to check this.. should be possible to store them?
thanks

**Comment by love-linger** [comment]
Duplicated #185

**Comment by love-linger** [comment]
Since this feature has been mentioned many times, I decided to save the last selection of some common operations. I should emphasize that users need to pay extra attention to whether they use the results of the last selection.
