### ISSUE TITLE
Low/inconsistent default themes contrast

### ISSUE THREAD

**Issue by Shimoon** [sourcegit-scm/sourcegit#232]
Some contrasts in the default themes make hard to see whats going on.

### History tabs
Is is a bit hard to understand which tab is selected if not for the underline.
![sourcegit_dark_tabs](https://github.com/sourcegit-scm/sourcegit/assets/17713307/7dec07ce-11d6-4322-8a59-f04a3c896341)
While the light theme makes it pretty obvious though :
![sourcegit_light_tabs](https://github.com/sourcegit-scm/sourcegit/assets/17713307/2da4a32a-e951-4046-bab6-a34868d3d165)

### Changes tab (right side buttons)
Here, `syntax highlighting` and `side-by-side diff` are both enabled while `line word wrap` and `show hidden symbols` are disabled.
![sourcegit_dark_buttons](https://github.com/sourcegit-scm/sourcegit/assets/17713307/098238e0-3cb0-4cc9-82a4-9ceed98aec81)
If we keep the `increase/decrease context lines` buttons logic (dark theme), lighted should be active while dimmed should be inactive.
The issue here gets even worse using the light theme, the contrast remain basically the same activated or not :
![sourcegit_light_buttons](https://github.com/sourcegit-scm/sourcegit/assets/17713307/6e17884f-6f62-4738-b22f-8506ad9e9476)

### Dashboard / Search
Either with the dark theme or light one, the active button is dimmed which makes it visually inactive for the user :
![sourcegit_dark_dashboard-search](https://github.com/sourcegit-scm/sourcegit/assets/17713307/7576a829-515c-47e4-8bff-389c156e79db)
![sourcegit_light_dashboard-search](https://github.com/sourcegit-scm/sourcegit/assets/17713307/41bb099d-4770-4574-92e0-8d43236ca2b4)

It may be good to have some sort of consistent guideline for both default themes that implies that selected/actif items should be the more visibles ones to avoid any confusion.

_Previous Source Git versions had blue tint for actives items that was actually pretty nice to understand quickly what was enabled or not._

**Comment by love-linger** [comment]
The accent color is depends on your system. For example, on Windows, you can change accent color from
![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/f705bd21-0abe-42d4-8e0b-17314ed0d9e6)

**Comment by love-linger** [comment]
https://github.com/sourcegit-scm/sourcegit/assets/4075673/783c561a-7724-4b6e-9a58-ee1382c49784

**Comment by Shimoon** [comment]
Oh that makes sense now, mine is set to dark grey !
While this is pretty nice, wouldn't it be preferable to have a toggle option for that ?
And a fallback color if disabled - or the ability to set a custom one if we want to go crazy :) ?

**Comment by love-linger** [comment]
you can use custom themes from https://github.com/sourcegit-scm/sourcegit-theme/tree/develop

**Comment by love-linger** [comment]
a new key `SystemAccentColor` was added to customize the accent color.
