### ISSUE TITLE
Wrong highlight for some tooltip popups

### ISSUE THREAD

**Issue by Shimoon** [sourcegit-scm/sourcegit#233]
Using the light theme, some tooltip popups are dark both for background and foreground :
![sourcegit_light_popup](https://github.com/sourcegit-scm/sourcegit/assets/17713307/c65b5d36-696b-48cf-a676-254315d1013c)
_Here with the `open in file browser` button._

The issue is not present for all the items though :
![sourcegit_light_popup2](https://github.com/sourcegit-scm/sourcegit/assets/17713307/b6ea6200-7fba-4541-97f5-3066f2d60559)

**Comment by love-linger** [comment]
Did you restart app after change theme? It's an avalonia's bug, after changing theme, tooltip did not updated.

**Comment by love-linger** [comment]
I find a way to resolve this issue.
