### ISSUE TITLE
discard single line doesn't work as expected

### ISSUE THREAD

**Issue by ghiboz** [sourcegit-scm/sourcegit#235]
hello again: I have this situation:

![image](https://github.com/sourcegit-scm/sourcegit/assets/446533/ab265a92-98d1-47a1-9815-ee84e712da9d)
and under these lines are many changes: I want discard the first change and commit all the other changes: with other git client I'm used to discard the line I don't need and commit the entire file: but if I discard this line, this happens:

![image](https://github.com/sourcegit-scm/sourcegit/assets/446533/3da4e0a9-1a33-4b99-bf8a-26bc450c7a06)

and my file have the line cancelled, not restored with the old situation:

```cpp
#include <queue>
#include <regex>

```

**Comment by love-linger** [comment]
Yes, in side-by-side view, you need discard changes in both side. In your description above, you only discard the new line added and leave the remove action.

**Comment by ghiboz** [comment]
ah ok! and I suppose also for stage in selected works like this: I have to do in both side
