### ISSUE TITLE
[Feature] Start ssh agent automatically

### ISSUE THREAD

**Issue by Noisyfox** [sourcegit-scm/sourcegit#239]
Currently I have to start ssh agent and add my password-protected ssh key manually, otherwise I will get issue like
![image](https://github.com/sourcegit-scm/sourcegit/assets/1537155/5887f087-e915-47b3-ad71-4e1a095ce498)

I'm using Windows and I tried both openssh and putty based ssh and they all have the same issue.

Any plan to start the agent automatically when app starts/prior to any git command, like what SourceTree does?

**Comment by love-linger** [comment]
Here's my solution for this issue. Install offical git with `Use external OpenSSH` turn on. This will use Window's built-in OpenSSH client.
![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/028cb5c0-0cab-4601-b81e-c9996b5f7219)
After that, go to Services and start the built-in `OpenSSH Authentication Agent` and switch the `Startup type` to `Automatic`.
![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/fe5d0ed8-1678-4cc9-bd8d-4fdd4e4e9859)

**Comment by AleksandrLiakhavetsEPAM** [comment]
And what is the next action?

**Comment by love-linger** [comment]
> And what is the next action? It is just stuck in this state ![image](https://private-user-images.githubusercontent.com/97155822/346205808-6639ed9c-7937-4979-96a6-c47a90e0450e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyMjQwOTEsIm5iZiI6MTcyMDIyMzc5MSwicGF0aCI6Ii85NzE1NTgyMi8zNDYyMDU4MDgtNjYzOWVkOWMtNzkzNy00OTc5LTk2YTYtYzQ3YTkwZTA0NTBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDIzNTYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhMjA0ZTUyMWVmN2RkNTQzY2NkYTdiOTA0MjA5YmRjNmU3MjMxYzAzMmE1ZjA5MDZmOTY3ZjZlZjIxNGQzNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WjdLO_eAlhNmpy2lRFE8tTrEDl5pQDvjctrOaR5PLeI) Thanks!

you can manually run one of these fetch command:

* `git fetch --all` for HTTPS access
* `git -c core.sshCommand "ssh -i YOUR_PRIVATEKEY_FILE" fetch --all` for SSH access

to see why it stuck there

**Comment by AleksandrLiakhavetsEPAM** [comment]
Did it - it sucks in a step when i need to enter passphrase for rsa key. Just nothing happening. For example visual studio shows 
![image](https://github.com/sourcegit-scm/sourcegit/assets/97155822/4ca52d9d-f8c8-4f1a-99e1-c92fedca0251)

**Comment by love-linger** [comment]
> Did it - it's stuck in a step when i need to enter passphrase for rsa key. Just nothing happening. For example visual studio shows ![image](https://private-user-images.githubusercontent.com/97155822/346537372-4ca52d9d-f8c8-4f1a-99e1-c92fedca0251.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0Mzc1NzAsIm5iZiI6MTcyMDQzNzI3MCwicGF0aCI6Ii85NzE1NTgyMi8zNDY1MzczNzItNGNhNTJkOWQtZjhjOC00ZjFhLTk5ZTEtYzkyZmVkY2EwMjUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDExMTQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0MmNhZTZkNTY2ZDRlYmRhYTM4OWVmYTFiZWE5YmE4NWU1MTgzYTUzMTc0NzUyMTMwYmQ3NTkyMjcwNDE5ODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UbvxLf5Fj_t50NR8bF2PVlWcaizonn4X5jbcRCsAIxQ)

Thank you very much. I'm using a private key without passphrase, and did not notice that. I'll try to fix it.

**Comment by love-linger** [comment]
Add support for `SSH_ASKPASS`

![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/27fe62c2-9165-4844-b475-d2d762e940a1)

You can test it from this build: https://github.com/sourcegit-scm/sourcegit/actions/runs/9841154876

**Comment by Noisyfox** [comment]
![image](https://github.com/sourcegit-scm/sourcegit/assets/1537155/e0f9611a-c886-47c9-bc67-f4675be64011)
I'm getting this error when running the latest developer branch.

**Comment by love-linger** [comment]
> ![image](https://private-user-images.githubusercontent.com/1537155/347236057-e0f9611a-c886-47c9-bc67-f4675be64011.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1Nzg1MjUsIm5iZiI6MTcyMDU3ODIyNSwicGF0aCI6Ii8xNTM3MTU1LzM0NzIzNjA1Ny1lMGY5NjExYS1jODg2LTQ3YzktYmM2Ny1mNDY3NWJlNjQwMTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTBUMDIyMzQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzE5MTkwMDRiZjNlMGVmYjBjMWMzMmFlZGRhNGY5ZGQ0M2U2YjUyNmQ1ZDEwNWY2MjBjN2FiZjFiZTYyZmUwYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LdSQQ9LHQgiQZelOckbOuxmjIkcctW4PmAzOVfQDzlE) I'm getting this error when running the latest developer branch.


This seems a little strange. From the point of view of the path, you are using this app on Windows platform, but why it uses `exec` to create the child process?

BTW, I'm trying to fix this issue on Linux/macOS platform

**Comment by love-linger** [comment]
I've fixed this issue. You can try it on the latest `develop` branch

**Comment by Noisyfox** [comment]
Cool that does solve the problem.

**Comment by AleksandrLiakhavetsEPAM** [comment]
Thank you - it works super good!
