### ISSUE TITLE
[FEATURE] Hope add a feature that remember last pull settings.

### ISSUE THREAD

**Issue by htw128** [sourcegit-scm/sourcegit#240]
希望针对未提交更改的操作可以增加一个针对每个repo不同的记忆。比如在这个repo我上次选的是丢弃更改，下次再pull这个repo的时候默认选丢弃更改。
如果可以在设置页面toggle这个行为就更好了。

感谢

**Comment by htw128** [comment]
Duplicate #185

**Comment by love-linger** [comment]
最新的develop分支已支持，可从action页下载最新编译
