### ISSUE TITLE
[Feature] Auto Stage option

### ISSUE THREAD

**Issue by caioraphael1** [sourcegit-scm/sourcegit#244]
I have a suggestion:

I'm quite used to the githubdesktop workflow (or alikes), and I'd like to not have to click 'stage all' every time I want to commit something. So, I'd like to propose the option to 'Auto Stage' all changes made before committing.

Thanks, I'm loving the app!

**Comment by love-linger** [comment]
An checkbox named `Auto-Stage` has been added into the `Changes` view. It will enable `-a, --all` option in `git commit` commmand. 

The last state of this checkbox will be saved into repositories setting. Remember to turn it off if you do NOT want this feature!!!

Note: Enable this option will tell the command to automatically stage files that have been modified and deleted, but new files you have not told Git about are not affected.

![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/f3108d5b-1957-4510-8fe2-4fab744fcfcc)

you can try it from this build https://github.com/sourcegit-scm/sourcegit/actions/runs/9823943892

**Comment by caioraphael1** [comment]
oh wow, that was fast! Thanks a lot!

Is there a reason for not considering newly added files? 

I was thinking it would be a bit more intuitive if the option physically moved the items from the Unstaged tab to the Staged tab, before committing, so it would be clear what is being affected or not. It would be just like clicking the 'Stage All' button automatically, as soon as you click in the Changes tab, or something in those terms, to guarantee that all changes are staged.

Also, I liked the button placement, but maybe here is also an option:
![image](https://github.com/sourcegit-scm/sourcegit/assets/58512144/8b98d0c0-9102-4dfe-ad46-8c95833363c9)

Thanks for the quick response!

**Comment by love-linger** [comment]
> Is there a reason for not considering newly added files?

It's what the `-a, --all` argument does. According to the document of `git-commit`:

![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/6b0bc427-235e-43da-a4e3-47badfdf8917)
