### ISSUE TITLE
MacOS 13.6.7打不开

### ISSUE THREAD

**Issue by Pro34** [sourcegit-scm/sourcegit#245]
修改App.plist里面的LSMinimumSystemVersion从10.12到10.6行吗？
![s2024-07-07_12 09 37](https://github.com/sourcegit-scm/sourcegit/assets/72383681/f2fdfd47-1b5c-4853-a94d-448890b0ed7d)

**Comment by love-linger** [comment]
可能你需要自己编译了，执行build.os.command

**Comment by Pro34** [comment]
> 可能你需要自己编译了，执行build.os.command

好的👌🏻
