### ISSUE TITLE
`linux-x64.tar.gz` asset discontinued from the v8.20?

### ISSUE THREAD

**Issue by WrichikBasu** [sourcegit-scm/sourcegit#246]
This would have been better as a Discussion rather than an issue. But Discussions are not enabled in this repo, so no option.

Till v8.19, there used to be a `linux-x64.tar.gz` asset with the release. I can see that `.AppImage` has been added in v8.20. But has `linux-x64.tar,gz` been discontinued from this release onwards, in favour of an AppImage?

**Comment by love-linger** [comment]
The `tar.gz` package was used for the Linux distributions that do not support rpm/deb packages. As you can see, the AppImage package was added after 8.20, so tar.gz has been replaced by it.

**Comment by WrichikBasu** [comment]
Makes sense. Thanks for the prompt reply.
