### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by Mike710Shine** [sourcegit-scm/sourcegit#248]
Improvement

It would be nice if in the "UnSTAGED" and "STAGED" area not only the individual files were displayed, but it would be structured like the folder structure itself, especially if there are many changes or it is very deeply branched, this should be much more helpful.
Like this way.
![grafik](https://github.com/sourcegit-scm/sourcegit/assets/19763591/27fcf1c1-56ae-4957-a0c1-fa7272689f7d)

**Comment by love-linger** [comment]
You can swith the display mode by this button:
![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/20174b12-8f79-47fd-b625-5f2e7142f7c6)

And select `Show as Filesystem Tree` item
![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/80732ef5-0a49-4c4f-af91-5b4e664050d1)

**Comment by Mike710Shine** [comment]
Ohh cool thanks for the hint I had not seen that you can change that there. Super exactly what I wanted
