### ISSUE TITLE
Code formatting

### ISSUE THREAD

**Issue by gigi81** [sourcegit-scm/sourcegit#25]
I noticed that the project follows more of a java code styling than a c# one.
I was wondering what would you think in aligning the syntax style more to the c# standard.
Obvioulsy, this is simply an exercise in style and would not bring any particular advantage and I will understand if you will just close this issue, however I think it will make it easier for c# developers to contribute.

This can be achieved by running 2 commands from the command line, on the root of the project, run:
```
dotnet new editorconfig
dotnet format
```

Let me know what you think.

**Comment by love-linger** [comment]
I don't have a particular preference for which code style to use. I would prefer more people to get involved in improving this software. As a result, I'm very much in favor of changing the project's code style to the way C# developers prefer.
