### ISSUE TITLE
Pull-request

### ISSUE THREAD

**Issue by datnm8x** [sourcegit-scm/sourcegit#250]
Dear team,

I want to add the new feature to show merge requests from remote, and changes of them.

Thanks!

**Comment by love-linger** [comment]
This feature is a bit difficult to implement. The interface associated with `merge requests` or `pull requests` depends on the hosting service. Although **Github** provides the command line tool `gh`, **GitLab** also provides `glab`, to operate PRs, but these are only specific official services, not for self-hosted git servers.

At this time, it will not be included in the development plan.
