### ISSUE TITLE
Check performance on windows for repos in WSL

### ISSUE THREAD

**Issue by PhilippDehner** [sourcegit-scm/sourcegit#251]
I'm using SourceGit for git repos which are located in WSL (Host: Windows 10, WSL: Ubuntu)

The GUI reacts ~10x slower than using repos directly on Windows. I use the repo via the following path: `\\wsl.localhost\Ubuntu\home\xxx `

Example: updating the Changes is really slow. When I click F5, there is sometimes no response if the refresh is finished or not

**Comment by PhilippDehner** [comment]
Not necessary anymore, I just installed SourceGit in WSL.

**Comment by zd-dalibor** [comment]
@PhilippDehner 
I installed the SourceGit in WSL, but when I run it I got strange transparent box around the app window. Do you have the same issue?

<img width="319" alt="Image" src="https://github.com/user-attachments/assets/51922aa4-4340-4832-a8b3-c14803c3037f" />

**Comment by love-linger** [comment]
![Image](https://github.com/user-attachments/assets/099688ee-eae5-456f-a17d-2b252564d42b)

**Comment by kakavips2edu** [comment]
Hi @love-linger, I think the way installing in wsl isn't good way. For my machine, when opening sourcegit in wsl, It's very lagging and slow.
I want to recommend that sourcegit should support to access & actions git in WSL repositories from sourcegit windows app (example: wslgit tool). It's better for using both windows & wsl repositories in one sourcegit window app.
I love to use sourcegit for all time. Thanks for the project <3
