### ISSUE TITLE
[FEATURE] Make the search feature for Git commits search through the Git descriptions (not just titles)

### ISSUE THREAD

**Issue by ozmium** [sourcegit-scm/sourcegit#256]
### Summary

SourceGit is great 👍, but the search feature is very limited. When the user tries to search through historical Git commits, it only works to search through the **titles** of the Git commits. **It does not search through the text of the whole body and descriptions**.

### Steps to reproduce the bug

![SourceGit_search_bar_theme_light](https://github.com/user-attachments/assets/00e0ccb9-69c9-4cc5-ac37-9c0be5f89406)

1. Launch SourceGit and load a typical Git repository, for example, see the screenshot above that uses the actual [SourceGit repository](https://github.com/sourcegit-scm/sourcegit) on GitHub.
2. On the left sidebar, click the search icon 🔍 to start searching through commits.
3. Type **`"ignore WordWrap"`** into the search field (without quotes). This text was written in this Git commit on 3 July 2024 as a description: https://github.com/sourcegit-scm/sourcegit/commit/d822afc4ec321dddd717509ea6bb76b7ed102462
4. Press the Enter button to start the search

### Expected Result

* The app should display the search result that contains the description - from this commit: https://github.com/sourcegit-scm/sourcegit/commit/d822afc4ec321dddd717509ea6bb76b7ed102462

![Search result that should be found in Git commits](https://github.com/user-attachments/assets/21dec8de-dd20-446a-b6ea-7c4facccd1f3)

### Actual Result

* No results are displayed, even though the commit exists in the history.
* The app only allows to search on the Git titles.

![Screenshot of no search results](https://github.com/user-attachments/assets/18b47332-222b-413b-9c49-8e4135c71379)

### Impact

* Usability problems - Searching on Git titles only is not enough.
* Confusion for the user - Zero search results are showed for valid searches

### Premium feature

* If possible, the search feature should also allow searches where **the words are in any order**. For example, a search for **`"wordwrap ignore"`** or **`"ignore wordwrap"`** should find this commit: https://github.com/sourcegit-scm/sourcegit/commit/d822afc4ec321dddd717509ea6bb76b7ed102462

* Another example: A search for **`"push tags without"`** should return this commit, where the words are reordered across multiple lines: https://github.com/sourcegit-scm/sourcegit/commit/f4f4a26a642c6b77cc84046c7b75f5f2162dfe28

![Search result that should be found with reordered words](https://github.com/user-attachments/assets/511d61f9-18d8-49ad-9ba2-432abdefe7ff)

However, I'm aware that this would be a difficult feature to implement, so perhaps make it optional. Or do it later, in the future. In any case, here are some tutorials that may provide help for how to do it:

* https://stackoverflow.com/questions/74366364/how-to-search-for-string-in-any-order
* https://stackoverflow.com/questions/65599538/match-a-list-of-possible-words-in-a-string-in-any-order
* https://stackoverflow.com/questions/1177081/multiple-words-in-any-order-using-regex
* https://superuser.com/questions/310224/how-do-i-search-for-multiple-strings-in-any-order-across-multiple-lines
* https://forum.freecodecamp.org/t/regex-to-match-string-containing-two-words-in-any-order/333791
* https://www.google.com/search?q=search+for+strings+in+any+order (general web search)

**Comment by love-linger** [comment]
I have redesigned the commit searching feature. A way to search the entire commit message have been added. 

> * If possible, the search feature should also allow searches where the words are in any order. For example, a search for "wordwrap ignore" or "ignore wordwrap" should find this commit: d822afc4ec321dddd717509ea6bb76b7ed102462

This feature is not currently implemented. There are two reasons:

* To speed up the opening of the repository, only the `SUBJECT` of commit is readed. The entire commit message is only read when required, such as when selecting a commit to view details. This is also why the old implementation does not supports to search the entire commit message.
* The following GIT command is currently used to search for commit full message. `git log --grep="{SEARCH_CONTENT}"`, instead of reading all commits and detecting whether the commit information contains the search content in a custom function.

**Comment by ozmium** [comment]
Hello 👋. Thanks for fixing this bug so quickly!

I believe it is possible to use a git search with the words reordered, and I think it's possible to do it inside SourceGit. I have created some sample code for you, which you can run in a web browser:

### Sample code

* C# (C Sharp) code sample with unit tests: https://www.jdoodle.com/ia/18Ug
* Java code sample with unit tests: https://www.jdoodle.com/ia/18UN (the original code)

Run the sample code in the browser and look at the output (press the "Execute" button). It will generate the correct Git search commands to handle multiple words in any order. It also handles all of the edge cases properly. It limits the search to a maximum of 6 words, to ensure that the search is fast. You can verify the output by running the commands in a Terminal. You will see that they will search the Git history properly and very efficiently.

### How it works

1. The function `GenerateGitLogSearchCommand()` splits the user's search query into separate words. For example `"word1 word2"` is split into an array of `"word1"`, `"word2"`.
2. Then it creates the correct search command, for example: `git log -i --grep "word1" --grep "word2" --all-match`
3. This command uses git's built-in search method to search for multiple words in any order. It runs very quickly, even for a large repo.

![Terminal window screenshot - run the git log command with multiple words - 2024-07-14 15.14](https://github.com/user-attachments/assets/4dfab492-5ce0-4b89-9586-00ebc2bef5aa)


Guidance and tutorials:

* https://www.baeldung.com/ops/git-commit-search-string
* https://stackoverflow.com/questions/52065604/how-do-you-search-for-multiple-words-in-commit-messages

I've also attached the sample code here to this comment, in case you cannot access the jdoodle website.

### How to integrate the sample code into your project

I grant permission to use and modify the sample code in your project. You can integrate it into your code, something like this:

For the file: `src/ViewModels/Repository.cs` -> `StartSearchCommits()`

Copy the function `GenerateGitLogSearchCommand()` into this file (from the sample code).

Then replace:

```cs
case 2:
    visible = new Commands.QueryCommits(FullPath, $"-1000 --grep=\"{_searchCommitFilter}\"", false).Result();
    break;
```

with:

```cs
case 2:
    string searchCommitCommand = GenerateGitLogSearchCommand(_searchCommitFilter);
    visible = new Commands.QueryCommits(FullPath, searchCommitCommand, false).Result();
    break;
```

I am not 100% sure if that will work, it's just an estimate.
