### ISSUE TITLE
[Bug] The Unstaged and Stage resets its scroll

### ISSUE THREAD

**Issue by caioraphael1** [sourcegit-scm/sourcegit#257]
- I scroll down in the Unstage or Stage tab.
- It resets its scroll after 0.5~2 seconds.

That's it. Quite annoying. I can't see what has changed in a file if I have to scroll down to see the file.

This happens whatever the view I'm using: Path List, File and Dir List, Filesystem Tree.

I'm using v8.20.

**Comment by love-linger** [comment]
The unstage/stage changes view will rebuild after working copy files changing detected.

**Comment by caioraphael1** [comment]
> The unstage/stage changes view will rebuild after working copy files changing detected.

That might be it. I can't test it anymore, as I just committed my changes, but that was likely the cause...
