### ISSUE TITLE
Questions about Merge tag submission

### ISSUE THREAD

**Issue by gadfly3173** [sourcegit-scm/sourcegit#258]
The `Merge tag '[tagName]' into develop` commit of this repository will have an extra useless SSH SIGNATURE section starting from v8.18. I tried running `git merge v8.21 --no-ff` in the terminal and found that it would enter the interactive interface and the prompt was as follows. This part of the content would not appear after submission.

```bash
# -----BEGIN SSH SIGNATURE-----
# sth......
# -----END SSH SIGNATURE-----
# sth......
# Please enter a commit message to explain why this merge is necessary,
# especially if it merges an updated upstream into a topic branch. 
#
# Lines starting with '#' will be ignored, and an empty message aborts
# the commit.
```

Maybe there is some configuration error in your merge process?

**Comment by love-linger** [comment]
I haven't noticed the problem yet. Maybe I'm using `git flow release start/finish` to merge the develop and master branches automatically.

**Comment by love-linger** [comment]
Before I configure the `gpg.ssh.allowedSignersFile`, finishing a release branch will append the following content
```
# -----BEGIN SSH SIGNATURE-----
# ....
# -----END SSH SIGNATURE-----
# gpg verification failed.
```
After configured, it will be
```
# -----BEGIN SSH SIGNATURE-----
# ....
# -----END SSH SIGNATURE-----
# Good "git" signature for [EMAIL] with ED25519 key [KEY]
```

I'll try to remove this from message

**Comment by love-linger** [comment]
When I using `Fork` to do the same job, that finishing a `git-flow release branch` with gpg signing enabled, it also appends the commit message……

![image](https://github.com/user-attachments/assets/df5e606c-9f95-4a9d-85b1-cf1ff69269ee)

Looks like it's a issue in `git-flow`
