### ISSUE TITLE
[FEATURE REQUEST] Add how much time it is from the current time for Commit Time

### ISSUE THREAD

**Issue by idepin** [sourcegit-scm/sourcegit#259]
I hope there is a feature to change the commit time for each commit like the image below 
![image](https://github.com/user-attachments/assets/7f14f9f0-a098-4a23-a9e2-9d2de51ead92)

**Comment by love-linger** [comment]
I've add a tooltip for commit time that shows how much time it is from now. But the tooltip is not updated per second, instead, it will recreate after its owner row recreated or row's DataContext changed. For example, you can scroll it out of bound, the scroll it back to view to force update it.

![image](https://github.com/user-attachments/assets/f2fd550f-01c9-4857-b26d-1a43513276e8)

You can test this feature from https://github.com/sourcegit-scm/sourcegit/actions/runs/9936556679

**Comment by love-linger** [comment]
now you can switch the commit time display mode to time period it's passed from now by this toggle button
![image](https://github.com/user-attachments/assets/24c19cb8-5a53-4f56-b50d-2cd2de28ddbc)

**Comment by idepin** [comment]
That's cool!, i'll test the feature
