### ISSUE TITLE
[FEATURE REQUEST] Add gitleaks functionality

### ISSUE THREAD

**Issue by WarFiN123** [sourcegit-scm/sourcegit#260]
Add gitleaks functionality to check for any leaks in source code before release

**Comment by love-linger** [comment]
I suggest you use gitleaks in git `pre-commit` hooks. This allows `gitleaks` to work even without any GUI client.

**Comment by WarFiN123** [comment]
> I suggest you use gitleaks in git `pre-commit` hooks. This allows `gitleaks` to work even without any GUI client.

Yea but it would be good if it was straight away implemented in sourcegit aswell when we check out commits

**Comment by love-linger** [comment]
Sorry, I will not add built-in supports for `gitleaks` because it supposes to work without (or with) any GUI clients.
