### ISSUE TITLE
[FEATURE REQUEST]  When selected commit changed, auto select first changed file in Changes tab

### ISSUE THREAD

**Issue by prime167** [sourcegit-scm/sourcegit#261]
When selected commit changed, auto select first changed file in Changes tab

![3](https://github.com/user-attachments/assets/4f4117f8-c09d-4b9f-929b-d0941639eb4d)

Version 8.21

**Comment by heartacker** [comment]
https://github.com/sourcegit-scm/sourcegit/issues/63

**Comment by love-linger** [comment]
Currently there's no plan to add features like:

* auto select the current branch in local branch tree
* auto select HEAD in histories view
* auto select the first changes in commit details panel with CHANGES tab actived
* auto select the first file in commit details panel with FILES tab actived
* ....
