### ISSUE TITLE
[FEATURE REQUEST] When a worktree is opened, auto locate the HEAD

### ISSUE THREAD

**Issue by prime167** [sourcegit-scm/sourcegit#262]
我在 #205 提到过

> 我比较喜欢的一个功能是如果一个分支已经签出到了一个 worktree，双击会自动在新的标签打开这个分支

打开新标签后能不能自动定位到该分支最新的提交？或者仅仅显示该分支的提交？

**Comment by love-linger** [comment]
1. 您可在本地分支列表中选择当前分支或使用下方所示的按钮快速定位当前的HEAD
![image](https://github.com/user-attachments/assets/bfd4ed0a-c0ce-4b6a-b9a7-b7221963d24c)
2. 您可在`worktree`创建完成后，点击分支右侧的过滤开关，启用提交列表过滤，如图：
![image](https://github.com/user-attachments/assets/657b0edd-fc74-4c14-8322-e953c8d2bd9a)
该过滤行为会被保存，即下次打开依然有效。
---
* 每次打开新仓库默认选中`HEAD`查看提交详情是过度猜测用户行为的设计。比如：相比查看当前HEAD的需求，默认选中工作变更页面可能比默认选中提交列表页面适应的人群更广（这是因为对于大部分个人项目，【查看自己刚刚提交了什么】这一行为相比【提交/丢弃本地变更】这些操作频率更低）
* 仅显示`worktree`分支的提交也是过度猜测用户行为的设计。既然应用到了`worktree`，那么必然存在多分支，这时分支合并，`cherry-pick`等行为也是可能发生的。如需要过滤显示提交记录，只需要操作一次即可。

**Comment by prime167** [comment]
谢谢，之前没注意到这个两个功能。你说的非常合理。

还有个问题是双击某个 有单独worktree的分支，在新的标签打开worktree后，左侧的分支树是否需要自动展开到当前分支

**Comment by love-linger** [comment]
> 谢谢，之前没注意到这个两个功能。你说的非常合理。
> 
> 还有个问题是双击某个 有单独worktree的分支，在新的标签打开worktree后，左侧的分支树是否需要自动展开到当前分支

按理说，现在的版本就是呀，对于`Local Branch`中当前的分支，其节点是默认展开的

**Comment by prime167** [comment]
现在 在新的标签打开worktree后，分支树是合着的

**Comment by love-linger** [comment]
https://github.com/user-attachments/assets/05219ed6-6eea-407f-88b8-1267e3e4960e

**Comment by prime167** [comment]
我的分支名是多级的。
三级的分支创建的worktree是可以的 Feat/Jack/aaa
四级的不行     Feat/Rose/aaa/aaa_1

![3](https://github.com/user-attachments/assets/a6887eda-ef60-4aef-a814-433daa03c4ba)

**Comment by love-linger** [comment]
这个BUG和几层没关系，是因为同级的不是Current，而关闭了node的展开，已修复，可下载 https://github.com/sourcegit-scm/sourcegit/actions/runs/9952245991

**Comment by prime167** [comment]
LGTM
