### ISSUE TITLE
improve stage/discard hunk

### ISSUE THREAD

**Issue by ghiboz** [sourcegit-scm/sourcegit#265]
should be good do something like gk:
set a block distance and let with one click to stage/discard

![image](https://github.com/user-attachments/assets/e1cd4ad5-9c87-4ceb-9d39-379cfa9fbc04)

now you need to do in both sides and is not so useful

**Comment by KorolevSoftware** [comment]
Like this)
![image](https://github.com/user-attachments/assets/71d4eea3-8461-4d75-b854-4eb465f65797)

**Comment by ghiboz** [comment]
right: using the other view is 50% job done: adding buttons complete the job

**Comment by love-linger** [comment]
![image](https://github.com/user-attachments/assets/2f538371-5de1-4f94-b669-b61c1fa9ef91)

* side-by-side diff also supports this feature
* stage/unstage/discard changes in selected lines still work, if you just want to stage/unstage/discard changes that parts of a hunk you can do it this way.

You can try the latest build from https://github.com/sourcegit-scm/sourcegit/actions/runs/9971223579

**Comment by patzm** [comment]
This is a very useful feature in GitKraken and other tools indeed. However, being able to stage / unstage individual lines was _super_ useful before! That seems to be gone now 😢. Am I overlooking something?
If unrelated changes happened one close-by lines, they are now (force?)-grouped into a staging group proposal. It would be great to be able to stage lines individually (select, right-click, stage) to separate unrelated changes in separate commits.

**Comment by love-linger** [comment]
> This is a very useful feature in GitKraken and other tools indeed. However, being able to stage / unstage individual lines was _super_ useful before! That seems to be gone now 😢. Am I overlooking something? If unrelated changes happened one close-by lines, they are now (force?)-grouped into a staging group proposal. It would be great to be able to stage lines individually (select, right-click, stage) to separate unrelated changes in separate commits.

You can still stage/unstage individual lines by select lines manually as before. For example:

* Without selected lines, this app detect chunk automatically
  ![image](https://github.com/user-attachments/assets/3418d01c-0aa1-452d-94a5-fb20a1fa8559)
* With selected lines, this app just using the lines you selected
  ![image](https://github.com/user-attachments/assets/4ebdeabe-1e41-4d0d-9e6a-ec24e20ed81d)

**Comment by love-linger** [comment]
One more thing, if you stage/unstage changes by selecting lines manually in side-by-side diff view, remember it only takes the lines you have selected. You may need do it in both sides manually.

**Comment by patzm** [comment]
ok cool. May I then suggest changing "Stage" and "Discard" to "Stage lines" and "Discard lines", respectively, when lines are selected? I was assuming that my selecting lines wouldn't influence the logic.

**Comment by love-linger** [comment]
> ok cool. May I then suggest changing "Stage" and "Discard" to "Stage lines" and "Discard lines", respectively, when lines are selected? I was assuming that my selecting lines wouldn't influence the logic.

I've pushed a commit to extends the background hightlight area of selected/detected chunk to line number area.

![image](https://github.com/user-attachments/assets/104e6ebd-463b-4015-9da2-32c53115a510)
