### ISSUE TITLE
[SUGGUEST] Use a lower version of Debian to release the Linux package

### ISSUE THREAD

**Issue by gadfly3173** [sourcegit-scm/sourcegit#267]
I recommend using Debian 11/Ubuntu 20.04 to release Linux packages. The currently released Linux packages require `libc6` >= 2.34, while the `libc6` version of Debian 11 (LTS until 2026.8) Ubuntu 20.04 (LTS until 2025.4) does not exceed 2.31. In fact, this application can even be packaged normally in the Debian 10 environment. Currently I use https://gitee.com/spark-store-project/additional-base-lib to run this application on Deepin 20.9. If the application can be packaged on a lower version of Linux, it will be helpful for more people to use it.

The CI on the develop branch can be easily modified to do this, but the release version seems to be manually packaged and cannot enjoy the system image provided by Github Actions.

**Comment by love-linger** [comment]
By the way, does `*.AppImage` package work on your Deepin 20.9?
