### ISSUE TITLE
[BUG] Git commit searching problems: It's case-sensitive and it misses many results

### ISSUE THREAD

**Issue by ozmium** [sourcegit-scm/sourcegit#268]
[BUG] Git commit searching problems: It's case-sensitive and it misses many results

Great work for making the search improvements in Issue #256 👍. Well done 😎.

I tested the search feature in the latest version 8.21. However, most of the time, searching is not working for me. There are 3 big problems:

---------

### 1. The search is case-sensitive

**Steps to reproduce the bug**

1. Launch SourceGit 8.21 and load a typical Git repository, for example, see the screenshot below that uses the actual [SourceGit repository](https://github.com/sourcegit-scm/sourcegit) on GitHub.
2. On the left sidebar, click the search icon 🔍 to start searching through commits. Select the search type as `"Search by Message"`.
3. Type **`"8.20 Release version"`** into the search field (without quotes, and **use the exact spelling**).
4. Observe that it finds 1 search result

![Screenshot from 2024-07-15 15-23-12](https://github.com/user-attachments/assets/5849703e-75da-419a-b3ab-c359652279a7)

5. Now repeat the search with with **lowercase letters**: Type **`"8.20 release version"`** (without quotes, and **use the exact spelling**).
6. Observe the search results

**Expected result**

It should find the same search result: https://github.com/sourcegit-scm/sourcegit/commit/212c9e0f9e4cfe4b1559f6874a742268f06d36cf

**Actual result**

It shows zero results.

![Screenshot from 2024-07-15 15-25-03](https://github.com/user-attachments/assets/95b83be9-d75b-4714-8b99-e2f5fa61813a)

**Impact**

* This is a major problem because people will usually search using lowercase letters only.
* Therefore, most of the time, it will show zero results.
* Users will be confused as to why it does not find any search results.
* Users will not know how to search for things, because they cannot remember whether something was spelled with a capital letter or not. And they won't know which letters should be capitalized or not.

**Possible solution**

I believe you need to add the `"-i"` flag to the `git log` search command, so that it becomes `git log -i` to make it **case-insensitive**, like this:

https://github.com/sourcegit-scm/sourcegit/blob/791b5bd6f86979e6a56f856b2887996b76bd109e/src/Commands/QueryCommits.cs#L13

https://github.com/sourcegit-scm/sourcegit/blob/791b5bd6f86979e6a56f856b2887996b76bd109e/src/Commands/QueryCommits.cs#L30

Old:

```cs
Line 13:
Args = "log --date-order --no-show-signature --decorate=full --pretty=format:%H%n%P%n%D%n%aN±%aE%n%at%n%cN±%cE%n%ct%n%s " + limits;

Line 30:
Args = $"log -{maxCount} --date-order --no-show-signature --decorate=full --pretty=format:%H%n%P%n%D%n%aN±%aE%n%at%n%cN±%cE%n%ct%n%s " + argsBuilder.ToString();
```

New:

```cs
Line 13:
Args = "log -i --date-order --no-show-signature --decorate=full --pretty=format:%H%n%P%n%D%n%aN±%aE%n%at%n%cN±%cE%n%ct%n%s " + limits;

Line 30:
Args = $"log -i -{maxCount} --date-order --no-show-signature --decorate=full --pretty=format:%H%n%P%n%D%n%aN±%aE%n%at%n%cN±%cE%n%ct%n%s " + argsBuilder.ToString();
```
----------

### 2. SourceGit only searches up to the sync point of the local branch, and it misses many results

**Steps to reproduce the bug**

1. Launch SourceGit and load a typical Git repository, for example, see the screenshot below that uses the actual [SourceGit repository](https://github.com/sourcegit-scm/sourcegit) on GitHub.
2. Sync to the most recent master branch (but only with git fetch - do not update your local branch yet)
3. If necessary, make your local master branch be **behind** the remote master branch: Click on an older commit, for example from "2024/07/08" -- title `"Merge branch 'release/v8.20'"` -> Right-click -> Reset master to here -> `Reset Hard`

![Screenshot from 2024-07-16 11-03-17](https://github.com/user-attachments/assets/5cb21789-997b-45c4-9c87-975fe8402a6e)

![Screenshot from 2024-07-16 11-04-32](https://github.com/user-attachments/assets/29922e1e-6e3a-4ff9-ab69-522237246f6e)

4. Notice that the newer commits on this branch are shown in light gray.
2. On the left sidebar, click the search icon 🔍 to start searching through commits. Select the search type as `"Search by Message"`.
3. Type **`"json serialization"`** into the search field (without quotes, and use the exact spelling).
4. Observe the search results

**Expected result**

It should find the search result which is in the newest git history, even if the branch is behind the remote, in the local sync point.

**Actual result**

It shows zero results. It does not search through the whole history of the newer commits that have already been fetched into the local branches.

![Screenshot from 2024-07-15 15-26-28](https://github.com/user-attachments/assets/fe8fe6c1-d17b-4951-9340-ebd90c96d3f2)

**Imapct**

* This is another problem, because there are missing search results of the newer commits on the local branches.
* The user is confused, because SourceGit is not searching through the whole history that is downloaded.
* Remote branches are updated very often, so SourceGit will show always incomplete search results.

----------

### 3. SourceGit shows gray text for newer commits on the branch

**Steps to reproduce the bug**

* See item 2 above, where a local branch has fetched new changes from the remote branch, but the branch pointer is behind the latest remote branch.

![Screenshot from 2024-07-17 15-25-03 copy](https://github.com/user-attachments/assets/31402d04-ad05-475f-91e0-79358ce0db4a)

**Expected result**

* Newer commits should be displayed in black letters, like the older commits. The colors should not change.
* Or there should be a preference setting to not show gray text. Or an option to customize this color.

**Actual result**

* Newer commits are displayed in light gray letters.
* It's difficult to read these gray words against a white background.
* The gray color cannot be customized.

**Impact**

* It's difficult to read the text of light gray against a white background, because the contrast is too low.
* Users are confused about why the text colors are diffferent.

**Comment by love-linger** [comment]
commit d09866e2c3abf2499d6bfa3aee92cb25ccc941de solves the first two problems

> 3. SourceGit shows gray text for newer commits on the branch

The commit rows that have a lower opacity does not means `newer commits`, it means this commit is not belongs (not merged to) current branch. Just like another well-known git client `Fork`:
![image](https://github.com/user-attachments/assets/125245f2-3dd4-47f9-a1ba-e41caaf5577d)

**Comment by ozmium** [comment]
> The commit rows that have a lower opacity does not means newer commits, it means this commit is not belongs (not merged to) current branch. Just like another well-known git client Fork.

Thank you for explaining 👍. Is it possible to make this color/opacity customizable in the theme settings JSON file? The gray is too light for me, so it is difficult to read the text. Or perhaps have a setting to not use different colors? Some people may not like the different colors. Thanks in advance 😎.

**Comment by love-linger** [comment]
a new key `OpacityForNotMergedCommits` has been added to the theme override JSON schema.

```json
"OpacityForNotMergedCommits": {
    "type": "number",
    "minimum": 0.1,
    "maximum": 1,
    "description": "Opacity for commits that not belongs (haven't been merged) to current branch in histories view"
}
```
