### ISSUE TITLE
differentiate commits not belong to commits to pull

### ISSUE THREAD

**Issue by ghiboz** [sourcegit-scm/sourcegit#270]
this https://github.com/sourcegit-scm/sourcegit/commit/14469b13990d9c6d93b447b4b967bd894167ba49 made me a suggestion: should be good differentiate colors about the commits that not belong to the branch (and now is a great thing), but should be good have a difference about the commits that need to be pulled

**Comment by love-linger** [comment]
I've pushed a commit that implements this feature in the way that another well-known git GUI client `Fork` does.

![image](https://github.com/user-attachments/assets/5674ea44-3b40-4106-9300-4b33d13b1871)
