### ISSUE TITLE
ssh-askpass not working anymore, even internal ask pass

### ISSUE THREAD

**Issue by popolony2k** [sourcegit-scm/sourcegit#272]
Hi. I'm using this excellent git client since 8.20 (both Linux and Windows) and on Linux, since 8.21 the ask-pass feature is not working properly anymore.
Since 8.20 version, instead opening the ssh-askpass dialog, SourceGit open a new instance of SourceGit and the previous SourceGit Window   show the message below:

Received disconnect from xxxx.xx.xxx.xxx port xxxxx:2: Too many authentication failures
Disconnected from xxxx.xx.xxx.xxx port xxxxx
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

If you need more details, please let me know.

PopolonY2k

**Comment by love-linger** [comment]
Could you please run `git fetch` command manually and copy the output message from terminal?

**Comment by love-linger** [comment]
I've pushed a commit 1e0a2ab5f733572fed9743127b23ac292751e3b8 that add `-o StrictHostKeyChecking=accept-new` option to `GIT_SSH_COMMAND`, which will automatically accept new connections. You can try this build https://github.com/sourcegit-scm/sourcegit/actions/runs/10034206003

**Comment by popolony2k** [comment]
> https://github.com/sourcegit-scm/sourcegit/actions/runs/10034206003

Hi friend...I tried now a git fetch at command line and it only request the password and nothing more (because there's no any data to fetch).

**Comment by popolony2k** [comment]
> I've pushed a commit [1e0a2ab](https://github.com/sourcegit-scm/sourcegit/commit/1e0a2ab5f733572fed9743127b23ac292751e3b8) that add `-o StrictHostKeyChecking=accept-new` option to `GIT_SSH_COMMAND`, which will automatically accept new connections. You can try this build https://github.com/sourcegit-scm/sourcegit/actions/runs/10034206003

I tried this build but I'm facing the same problem

**Comment by love-linger** [comment]
> Hi friend...I tried now a git fetch at command line and it only request the password and nothing more (because there's no any data to fetch).

Is there any output message like `Enter passphrase`?

**Comment by popolony2k** [comment]
> > Hi friend...I tried now a git fetch at command line and it only request the password and nothing more (because there's no any data to fetch).
> 
> Is there any output message like `Enter passphrase`?

No...absolutely nothing. I dowloaded latest sourcegit from repository and started debugging. If I discover something I'll post here

**Comment by love-linger** [comment]
> No...absolutely nothing. I dowloaded latest sourcegit from repository and started debugging. If I discover something I'll post here

Thank you very much. I can NOT reproduce this issue on my Windows/macOS/Linux

**Comment by love-linger** [comment]
By the way, you can remove this condition to see the message your ssh client calling SSH_ASKPASS with:

```diff
 private bool TryLaunchedAsAskpass(IClassicDesktopStyleApplicationLifetime desktop)
 {
     var args = desktop.Args;
-     if (args == null || args.Length != 1 || !args[0].StartsWith("Enter passphrase", StringComparison.Ordinal))
+     if (args == null || args.Length != 1)
        return false;

     desktop.MainWindow = new Views.Askpass(args[0]);
     return true;
 }
```

**Comment by popolony2k** [comment]
> By the way, you can remove this condition to see the message your ssh client calling SSH_ASKPASS with:
> 
> ```diff
>  // File: App.axaml.cs
>  private bool TryLaunchedAsAskpass(IClassicDesktopStyleApplicationLifetime desktop)
>  {
>       var args = desktop.Args;
> -     if (args == null || args.Length != 1 || !args[0].StartsWith("Enter passphrase", StringComparison.Ordinal))
> +     if (args == null || args.Length != 1)
>         return false;
> 
>      desktop.MainWindow = new Views.Askpass(args[0]);
>      return true;
>  }
> ```

Yes....perfect....your suggestion fix the problem and now is showing SourceGit AskPass dialog correctly and all git operations (Fetch, Push, Pull) works again.

I think you have a bugfix for the next build :)

Thanks

**Comment by love-linger** [comment]
> Yes....perfect....your suggestion fix the problem and now is showing SourceGit AskPass dialog correctly and all git operations (Fetch, Push, Pull) works again.

So, what's the arguments your SSH client passed to SSH_ASKPASS to launch this app as ask-pass client? It is displayed as title of input box like:
![image](https://github.com/user-attachments/assets/ea87f4cc-4a3c-4314-a5a1-b4ac00eb3d1a)

**Comment by popolony2k** [comment]
> 
> So, what's the arguments your SSH client passed to SSH_ASKPASS to launch this app as ask-pass client? It is displayed as title of input box like: ![image](https://private-user-images.githubusercontent.com/4075673/351183611-ea87f4cc-4a3c-4314-a5a1-b4ac00eb3d1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MDg1NTYsIm5iZiI6MTcyMTcwODI1NiwicGF0aCI6Ii80MDc1NjczLzM1MTE4MzYxMS1lYTg3ZjRjYy00YTNjLTQzMTQtYTVhMS1iNGFjMDBlYjNkMWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjNUMDQxNzM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTc1NzIzNTdlMzk2ZGU3OGFlYTg2NmU4ZGUyYzBkY2ViODM2ZjFmNzQ1NmE0ZWE0ZDNmNmI5ZGQ1YjIxODY4NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zW92LV6moP3Kpxz9WF3_-fH3F2QSbi9fGFcHHOWuPLo)

Apparently it is not passing any parameter:

![image](https://github.com/user-attachments/assets/0fd44cdb-c11e-49c6-9850-7de3b3ac5b13)

**Comment by popolony2k** [comment]
It is asking by password because my personal git is using Linux authentication only.

**Comment by love-linger** [comment]
> It is asking by password because my personal git is using Linux authentication only.

It seems that checking the argument with 'Enter passphrase' is not applicable in all cases.

**Comment by love-linger** [comment]
But this app supports to open repository at commandline like:

```shell
sourcegit SOME_REPO
```

I need to find a way to distinguish between `Open Repository` and `Launch as Askpass Client`

**Comment by popolony2k** [comment]
> But this app supports to open repository at commandline like:
> 
> ```shell
> sourcegit SOME_REPO
> ```
> 
> I need to find a way to distinguish between `Open Repository` and `Launch as Askpass Client`

Why not call your software with an extra parameter when it has been called as ask-pass, like a SourceGit --ask-pass command line parameter ??

Regards

**Comment by popolony2k** [comment]
When calling SourceGit --ask-pass you will be able to know exactly your software has been called to display the ass-pass dialog.

:)

**Comment by love-linger** [comment]
Env SSH_ASKPASS can not have extra arguments. It is passed to `execv` function directly by SSH client.

**Comment by love-linger** [comment]
see issue #239

**Comment by love-linger** [comment]
Would you like to test this code for me?

```diff
// App.axaml.cs
+[GeneratedRegex(@"^([A-Za-z0-9_-]+(\.\w+)*@(\w+\.)+\w{2,5})'s password$")]
+private static partial Regex REG_ASKPASSWORD();
 
 private bool TryLaunchedAsAskpass(IClassicDesktopStyleApplicationLifetime desktop)
 {
     var args = desktop.Args;
     if (args == null || args.Length != 1)
         return false;

+    var arg = args[0];
+    if (!arg.StartsWith("Enter passphrase", StringComparison.Ordinal) && !REG_ASKPASSWORD().IsMatch(arg))
+        return false;

-    desktop.MainWindow = new Views.Askpass(args[0]);
+    desktop.MainWindow = new Views.Askpass(arg);
     return true;
 }
```

**Comment by love-linger** [comment]
Never mind. I've pushed a commit e0319e3f9b36d8bd2116fe1d5ceb5e2a8cddc8e7 to fix this issue.

Here is the change:
```diff
        private bool TryLaunchedAsAskpass(IClassicDesktopStyleApplicationLifetime desktop)
        {
            var args = desktop.Args;
-           if (args == null || args.Length != 1 || !args[0].StartsWith("Enter passphrase", StringComparison.Ordinal))
+           if (args == null || args.Length != 1)
                return false;

-           desktop.MainWindow = new Views.Askpass(args[0]);
+           var param = args[0];
+           if (!param.StartsWith("enter passphrase", StringComparison.OrdinalIgnoreCase) &&
+               !param.Contains(" password", StringComparison.OrdinalIgnoreCase))
+               return false;
+ 
+           desktop.MainWindow = new Views.Askpass(param);
            return true;
        }
```

**Comment by popolony2k** [comment]
Hi @love-linger sorry by delaying to respond you. Your commit is working fine.

Thanks a lot.
