### ISSUE TITLE
Redundant pull operation prompt

### ISSUE THREAD

**Issue by hpfs0** [sourcegit-scm/sourcegit#273]
Today, after I switched to 8.22, I found that a pull operation prompt would be displayed on the local branch that did not track the upstream branch. before 8.21 did not have this problem.

**Comment by love-linger** [comment]
Could you provide a screenshot? 

I'm not sure what do you mean

**Comment by gadfly3173** [comment]
I think he means this:
![image](https://github.com/user-attachments/assets/86620ff1-c860-48a5-ac13-f7f07f8621d4)

5.1.x is branch with upstream, others are just local branch

**Comment by hpfs0** [comment]
> I think he means this: ![image](https://private-user-images.githubusercontent.com/28685179/350883458-86620ff1-c860-48a5-ac13-f7f07f8621d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MzU0NDksIm5iZiI6MTcyMTYzNTE0OSwicGF0aCI6Ii8yODY4NTE3OS8zNTA4ODM0NTgtODY2MjBmZjEtYzg2MC00OGE1LWFjMTMtZjdmMDdmODYyMWQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDA3NTkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3N2JhYThmMmM5MDlkNTY5MWQ3MWJmNWNjYTM0YjQwZjg0ZTBjN2Y4MmU2MzExZjc1ZWMzZTQ4ZTE3M2Y3YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BuiEjlOABmy5QkVeR0FlzX25JiuJRQVJDSkwTvkx0I4)
> 
> 5.1.x is branch with upstream, others are just local branch

Thank you for your screenshot

**Comment by love-linger** [comment]
My fault. I forget to check the content of `%(upstream:trackshort)`

**Comment by love-linger** [comment]
You can download the lastest build from https://github.com/sourcegit-scm/sourcegit/actions/runs/10036955859

**Comment by hpfs0** [comment]
> My fault. I forget to check the content of `%(upstream:trackshort)`

Ok, thanks for the fix

**Comment by love-linger** [comment]
I decided to release a hotfix version `8.22.1`, since this is a serious issue.
