### ISSUE TITLE
[SUGGESTION]Optimize macOS release.

### ISSUE THREAD

**Issue by htw128** [sourcegit-scm/sourcegit#274]
当前的macOS下载下来以后需要手动`xattr -d -r com.apple.quarantine /Application/SourceGit.app`，直接打开会提示已损坏。
大佬什么时候有时间可以参考一下[这个链接](https://developer.apple.com/documentation/xcode/packaging-mac-software-for-distribution/)处理一下？

Currently, after downloading on macOS, you need to manually run `xattr -d -r com.apple.quarantine /Application/SourceGit.app` . Opening it directly will prompt that it is damaged.
Could you please take some time to refer to [this link](https://developer.apple.com/documentation/xcode/packaging-mac-software-for-distribution/) to handle this issue?

**Comment by love-linger** [comment]
关键是我没有开发者证书……挺贵的……哈哈

**Comment by htw128** [comment]
那没事了_(:з」∠)_等啥时候我有起色了连着大佬的App一起给签名了！
