### ISSUE TITLE
[FEATURE] Make SourceGit run on all the latest MacOS versions, from 10.14 Mojave and above

### ISSUE THREAD

**Issue by ozmium** [sourcegit-scm/sourcegit#275]
SourceGit is very useful, but it does not work on the following Apple Mac OS operating systems:

* MacOS [Mojave (10.14)](https://en.wikipedia.org/wiki/MacOS_Mojave)
* MacOS [Catalina (10.15)](https://en.wikipedia.org/wiki/MacOS_Catalina)
* MacOS [Big Sur (11)](https://en.wikipedia.org/wiki/MacOS_Big_Sur)
* MacOS [Monterey (12)](https://en.wikipedia.org/wiki/MacOS_Monterey)
* MacOS [Ventura (13)](https://en.wikipedia.org/wiki/MacOS_Ventura)

![Screen Shot - Trying to launch SourceGit 8.22.1 on MacOS 12.7.4 Monterey](https://github.com/user-attachments/assets/bce3f795-6ca1-400a-8587-5b0eeb8edf62)

The above 5 OS versions are still very widely used, and popular. Therefore many users cannot use it.

It currently only works with:

* MacOS [Sonoma (14)](https://en.wikipedia.org/wiki/MacOS_Sonoma)
* MacOS [Sequoia (15)](https://en.wikipedia.org/wiki/MacOS_Sequoia)

Tested with SourceGit version 8.22.1 -- `sourcegit_8.22.1.osx-x64.zip` (released on 22 July 2024)

Please make SourceGit work on all of these Mac OS versions, starting from MacOS 10.14. Thank you.

**Comment by love-linger** [comment]
I've add `-mmacosx-version-min=11.0` argument to linker to allow this app running on macOS 11.0+

**Comment by AdriZ** [comment]
Hi,
The last comment, from @love-linger, gives the impression that the problem has been solved at least for macOS 11. But SourceGit can't run on macOS 11, it requires macOS 12 minimum.
![Image](https://github.com/user-attachments/assets/2653eded-23fb-459d-8f04-20fbbd3b9835)
Sorry for the french, last sentence translation: "You have macOS 11.7.10. The app requires macOS 12.0 or later"

macOS 11 is still common as a lot of mac cannot be upgraded to a later version. Is it possible to fix it? Do I have to create a new issue?

**Comment by love-linger** [comment]
I haven't changed the packaging configuration for macOS, and `-mmacosx-version-min=11.0` is still used to build macOS binaries.

**Comment by AdriZ** [comment]
> I haven't changed the packaging configuration for macOS, and `-mmacosx-version-min=11.0` is still used to build macOS binaries.

Weird.
To be clear, I've never install SourceGit on my mac so I don't if it worked before.
If you know an old version that works on macOS 11, I'm interested.

**Comment by love-linger** [comment]
I have no device running macOS 11 too...

**Comment by love-linger** [comment]
It seems like the Xcode installed on Github Action macOS runner has dropped support for macOS 11 (Big Sur)

![Image](https://github.com/user-attachments/assets/29ace396-cab9-4ae9-ae0c-2a608c95c3be)

**Comment by AdriZ** [comment]
> It seems like the Xcode installed on Github Action macOS runner has dropped support for macOS 11 (Big Sur)

Thanks a lot @love-linger .

Don't know if it's the fault of Apple or GitHub but that's really annoying.
Anyway, I've tested different releases of SourceGit, the most recent I can launch is SourceGit 8.38.
https://github.com/sourcegit-scm/sourcegit/releases/tag/v8.38
But when I try to use it I've Xcode errors.
![Image](https://github.com/user-attachments/assets/38b3d358-6608-444c-9c33-daac39c933a1)
I'll try to continue a bit to find a workaround but not sure it's worth it.

**Comment by AdriZ** [comment]
Actually I had to reinstall an old Xcode version (13.2.1), the last one compatible with macOS 11: https://xcodereleases.com
SourceGit v8.38 looks to work now.
