### ISSUE TITLE
[regress] 无法识别 samba 文件夹 git 仓库

### ISSUE THREAD

**Issue by heartacker** [sourcegit-scm/sourcegit#276]
以前可以识别，因为我配置了启动时候恢复之前的标签页面。
所以我现在依旧可以使用之前打开的samba 的git 的仓库。
但是我想打开新的samba 仓库，无法识别。

无论是 通过这种windows 映射驱动器。

![image](https://github.com/user-attachments/assets/241af7c4-d973-470c-88de-abdc1cd12bf6)

还是直接使用就 // 服务器地址

**Comment by heartacker** [comment]
曾经打开的记录都还在，
![image](https://github.com/user-attachments/assets/2421d175-b856-418e-b410-342f81cdd4e8)

**Comment by love-linger** [comment]
你可在仓库目录执行`git rev-parse --show-toplevel`命令，看是否识别

**Comment by heartacker** [comment]
![1721701182488](https://github.com/user-attachments/assets/ac44bb9a-7807-477e-905a-248a19b73ccb)

**Comment by love-linger** [comment]
哦，你需要修改一下该文件夹的所有者（可能是系统升级或是什么原因，导致git无法正确访问该文件夹）
