### ISSUE TITLE
[FR] 分组功能优化

### ISSUE THREAD

**Issue by heartacker** [sourcegit-scm/sourcegit#278]
- [ ] 优化现有
> 分组功能但是不知道如何添加仓库到这个分组？新建分组之后，如何将仓库添加到这个分组合。
> 看起来是拖动。
- [ ] 类似浏览器的分组
![image](https://github.com/user-attachments/assets/d18f49c6-c0ba-4c43-89ad-1a669faedb4f)

（挺需要这个功能的）比如，同一个仓库，不同的项目分支，但是显示都是一个名字，暂时只能标记颜色区分。
![image](https://github.com/user-attachments/assets/f8778f07-08f5-41f9-b066-0d5cf951a7a8)

_Originally posted by @heartacker in https://github.com/sourcegit-scm/sourcegit/issues/195#issuecomment-2244143587_

**Comment by love-linger** [comment]
目前没有计划做标签分组的功能，且本身颜色的设计就是给用户用来分组的。您也可以将标签以`GROUP:TITLE`的方式来重命名，也可达到分组的目的。

**Comment by heartacker** [comment]
好的，期待后续有可能实现
