### ISSUE TITLE
Compile error with dotnet 8.0.106

### ISSUE THREAD

**Issue by aikawayataro** [sourcegit-scm/sourcegit#281]
I'm unable to build the latest sourcegit release and develop with dotnet `8.0.106`:

```
$ dotnet publish src/SourceGit.csproj -c Release -r linux-x64 -o publish
MSBuild version 17.8.5+b5265ef37 for .NET
  Determining projects to restore...
  Restored /sourcegit/src/SourceGit.csproj (in 1.13 min).
/sourcegit/src/Commands/QueryTrackStatus.cs(22,35): error CS0121: The call is ambiguous between the following methods or properties: 'string.Split(char[]?, StringSplitOptions)' and 'string.Split(string?, StringSplitOptions)' [/sourcegit/src/SourceGit.csproj]
```

proposed fix:
```diff
diff --git a/src/Commands/QueryTrackStatus.cs b/src/Commands/QueryTrackStatus.cs
index abd5d5f..206ecc0 100644
--- a/src/Commands/QueryTrackStatus.cs
+++ b/src/Commands/QueryTrackStatus.cs
@@ -19,7 +19,7 @@ namespace SourceGit.Commands
             if (!rs.IsSuccess)
                 return status;
 
-            var lines = rs.StdOut.Split(['\n', '\r'], StringSplitOptions.RemoveEmptyEntries);
+            var lines = rs.StdOut.Split(["\n", "\r"], StringSplitOptions.RemoveEmptyEntries);
             foreach (var line in lines)
             {
                 if (line[0] == '>')
```

**Comment by love-linger** [comment]
I'm using the latest .NET sdk 8.0.303. There's no compile error on my Debian 11 & Debian 12

**Comment by aikawayataro** [comment]
I use ArchLinux, where the latest version available from repositories is `.106`. Can you test it on Debian?

**Comment by love-linger** [comment]
https://packages.microsoft.com/debian/11/prod/pool/main/d/dotnet-sdk-8.0/

**Comment by gadfly3173** [comment]
I encountered this problem on Windows and it was solved after upgrading the dotnet sdk. I think this is a problem with the early dotnet 8 sdk.
Ref: https://github.com/dotnet/roslyn/issues/70831

**Comment by love-linger** [comment]
each commit have been tested by github actions automatically. for example https://github.com/sourcegit-scm/sourcegit/actions/runs/10058084388

**Comment by aikawayataro** [comment]
I'm aware that there is no problem with the latest dotnet, which is why I specified my version.
I see, it's more of a stale dotnet problem then.
Im sticking with dotnet from the repository which is outdated, so patch will work for me. Thanks for your time!
