### ISSUE TITLE
感觉当前所处的分支显示不是很明显,是否可以考虑在顶部或底部增加显示当前的分支

### ISSUE THREAD

**Issue by wangsen3** [sourcegit-scm/sourcegit#283]
感觉当前所处的分支显示不是很明显,是否可以考虑在顶部或底部增加显示当前的分支

**Comment by love-linger** [comment]
尝试加了一版
![image](https://github.com/user-attachments/assets/2f27dc17-801b-4977-8f97-0d3c3c1da9d4)
但遇到分支名很长的，就显得很难看，不和谐
![image](https://github.com/user-attachments/assets/b844165b-4966-4f68-895b-4b740fe86758)

**Comment by love-linger** [comment]
重新排布了一下工具栏的按钮
![image](https://github.com/user-attachments/assets/fcdb00ab-c586-4f70-909d-1820ab6fb800)
感觉稍微好点

**Comment by heartacker** [comment]
体验了一下，建议还是放在底部比较合适。
大家的焦点还是左边为主。
另外，增加底部状态栏也很有意义。

**Comment by love-linger** [comment]
这个项目不会增加底部状态栏

* 状态栏关注频率远低于Tab/Toolbar/Content区域
* 当前没有太多需要在状态栏显示的内容
* 对于目前主流屏幕大多为 16:9 16:10 或是更宽的带鱼屏来说，竖直方向的空间很金贵。从之前的ISSUE来看，竖直方向上连用户显示分支、远程、tag的需求都无法满足，后面不得不重新实现了Sidebar的Layout计算。
* 底部显示并不比直接在Toolbar上显示更合理。比如 JetBrains 系列产品就将当前的分支显示在了Toolbar上。

所以这个项目不会单独占用底部的空间来显示当前的分支
