### ISSUE TITLE
[UX] Page Switcher for Right Panel should use the default font

### ISSUE THREAD

**Issue by gadfly3173** [sourcegit-scm/sourcegit#285]
The current font used is monospaced, which looks very different from other UI parts.
![image](https://github.com/user-attachments/assets/2b15af9c-2c1b-4cd1-b4f2-7cf8c5c52787)

**Comment by love-linger** [comment]
这是完全不同的两部分内容。一个是分组标题，一个是选择项目。同时因为颜色也与下方的分支/Tag/Submodule等选择列表/树相同，这里就统一使用了一种字体。否则，同一颜色的文字（而且还是比较突出的颜色），使用不同的字体更违和
