### ISSUE TITLE
How do I override/change submodule update options?

### ISSUE THREAD

**Issue by pfeerick** [sourcegit-scm/sourcegit#287]
I can see that SourceGit is using `submodule update --rebase --remote` as the command  when I do an "update submodule" from the left sidebar... however this is introducing I don't want - as I *want* to use the superproject’s recorded SHA-1  - not the upstream hash... etc... 

Is there some way I can configure SourceGit to behave, or do I need to stick with the cli (at least for now). For reference... at most I usually run `git submodule update`, and sometimes `git submodule update --init --recursive`.

Fantastic program btw.

**Comment by love-linger** [comment]
I've pushed a commit that rewrites the behavior of updating submodules.

![image](https://github.com/user-attachments/assets/8620f95e-a0ea-4f06-a991-23cb921611a5)

You can test it from this build https://github.com/sourcegit-scm/sourcegit/actions/runs/10110052003

**Comment by pfeerick** [comment]
Thank you so much... that seems to be working perfectly! :)
