### ISSUE TITLE
Question about the native Select Dialog

### ISSUE THREAD

**Issue by SoftExpert** [sourcegit-scm/sourcegit#289]
Hello,

First, congrats and thank you for designing and building this great application, it has a very nice, intuitive and consistent look and feel !

There is a question, however about the **Select Directory** dialog - at least on Linux. 
Different desktop environments have different feature sets and users have, sometimes, their own customizations and expectations.
When an application replaces the native select dialogs with its own, the custom settings are not present and it can make the select operation unnecessarily harder.
For example, on KDE Plasma, the users can drag and drop on the sidebar of the Select Dialog shortcuts to the frequently used folders or network paths.
With the current select dialog, I have to always start from the same point (the home folder) and work my way towards the folder I want to use, and there are no custom links on the side.

Long story short, here is what I want to say:

1. the best option from user point of view would be to let me use the native Select Dialog; this could be by default or I should, at least, have a choice to activate it in the application preferences
2. memorize the last used folder and next time when the Select Dialog is displayed, start from the last used path, instead of the default one
3. if the option of having the native Select Dialog (1) is technically difficult to implement, at least offer the possibility to add shortcuts to the left side of the current Select Dialog (with drag and drop would be wonderful) and also memorize the last used path (2).

I'm not sure how this fits with your vision on how the application should be implemented, but I hope you will consider adding them at some point.

Thank you and best wishes !
SoftExpert

**Comment by gadfly3173** [comment]
According to https://github.com/sourcegit-scm/sourcegit/issues/183 and https://github.com/AvaloniaUI/Avalonia/issues/10320 , Avalonia has some compatibility issues when using the system file picker.

**Comment by love-linger** [comment]
> I read the issue [#183](https://github.com/sourcegit-scm/sourcegit/issues/183) just before opening my question; that's also the reason why there are 3 points in my suggestion - I think point 2 could be platform / back-end agnostic (and the easiest to implement), and point 3 would mean an improvement on the current Select Directory dialog.
> 
> Do you think it is worth the effort ?
> 
> edit: fixed a typo.

I'll consider how to implement this. 

* It's an issue that only happens on Linux platform.
* The native Open/Save File/Folder Dialog can not be the default one, since it will crash this application when not supported by use's OS.

**Comment by gadfly3173** [comment]
Since I have upgraded to a system that has better support for FreeDesktop, I am currently unable to confirm if #183 is fixed.

**Comment by love-linger** [comment]
#183 also has a related PR https://github.com/AvaloniaUI/Avalonia/pull/14548 that merged into `11.1.3`
