### ISSUE TITLE
[FEATURE] Horizontal\Vertical Layout Switch for commit changes

### ISSUE THREAD

**Issue by alekk84** [sourcegit-scm/sourcegit#291]
Please add a option to switch layout for commit changes

![image](https://github.com/user-attachments/assets/ae5e7194-cad5-43e4-b0fb-7ff7448591c9)

**Comment by love-linger** [comment]
The layout in the screenshot is intended for users those have a Ultra-Wide Display screen. I do not recommanded users switch to this layout with 16:9 or 16:10 displays. By the way, I can not see the advantages:
![image](https://github.com/user-attachments/assets/c697901f-3b83-4209-91f8-e192c0634159)

**Comment by alekk84** [comment]
When I write code, I like the default layouts of graph and changes. But when I need to see what my team has been doing for a couple of days, it would be more convenient for me to switch to the layout that I suggested, since it contains more commits. With the option to switch the layout of changes, the graph layout would be useful not only for ultra-wide screen but also for 16:9.

**Comment by love-linger** [comment]
目前（至少短期内）没有计划实现该功能。
