### ISSUE TITLE
[Feature request] Use non mono fonts

### ISSUE THREAD

**Issue by julaudo** [sourcegit-scm/sourcegit#292]
Currently it is possible to configure a default font and a monospace font

But mono font is used almost everywhere:
![image](https://github.com/user-attachments/assets/78b0f8af-a438-4bf8-8d19-9a451cb87fd3)

I'm also using Fork for Windows. It uses mono font only for code view, and I think is makes UI more clear. Would it be possible to have this possibility in sourcegit? For example, have 3 kinds of fonts:
- Default font (current option) -> All fonts allowed
- (don't know how to name it, but all places using current mono font, except code view) -> All fonts allowed
- Code view font (current mono font) -> Only mono allowed

**Comment by love-linger** [comment]
This app use monospace font for all dynamic contents. The only exception is the view switcher below:
![image](https://github.com/user-attachments/assets/af938040-555a-4764-b223-e56f929a53f0)
> This is because it is an item selection list and use the primary foreground color. I want to keep its font the same with the branches list just under it, which also selectable and use the primary foreground color.

**Comment by love-linger** [comment]
> It uses mono font only for code view, and I think is makes UI more clear

Sorry, I can not get the point about `more clear`

![image](https://github.com/user-attachments/assets/31fdd094-4c0c-4dd7-bf8a-cb58685973ad)

As you can see above, these are two different clients with different UI/UX styles.

**Comment by julaudo** [comment]
For commit messages, for example, I think Fork UI is better because
- Regular font are more readable (maybe just my opition)
- Mono fonts make it difficult to distinguish bold/non-bold text (to quickly identify HEAD commit)
- Regular font will be truncated less often (for example branches in the branch list, or event commit messages)

**Comment by love-linger** [comment]
I'm a programmer, and in any case monospace is much more readable to me than Proportional fonts, such as commit SHA: 111111ffff vs `111111ffff`. But I still respect yours.

I've pushed a commit that provides a toggle button in `Preference > Appearance` page.
![image](https://github.com/user-attachments/assets/ae8437c1-d18b-4bcc-be16-64d643ec7cfb)

**Comment by julaudo** [comment]
> I'm a programmer, and in any case monospace is much more readable to me than Proportional fonts, such as commit SHA: 111111ffff vs `111111ffff`. But I still respect yours.
> 
> I've pushed a commit that provides a toggle button in `Preference > Appearance` page. ![image](https://private-user-images.githubusercontent.com/4075673/353053951-ae8437c1-d18b-4bcc-be16-64d643ec7cfb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNjcxNTIsIm5iZiI6MTcyMjI2Njg1MiwicGF0aCI6Ii80MDc1NjczLzM1MzA1Mzk1MS1hZTg0MzdjMS1kMThiLTRiY2MtYmUxNi02NGQ2NDNlYzdjZmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjlUMTUyNzMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDZlZDljMjBlMmQ2OWFlYmY1YzA2YTdjNDM1Zjk1NDQ5ZTQxYmQwZjg2MDgxZmU0YjA5YWY4NWM0MmRhYjg1NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1qhcZn19aOHdJrxj-fi0QrBLV1FM-QCgUJD9RwP6PpM)

Thank you. I agree for sha1 field but not other ones (commit messages, author name, for example)
