### ISSUE TITLE
[Feature request] Interactive rebase onto another branch

### ISSUE THREAD

**Issue by julaudo** [sourcegit-scm/sourcegit#294]
In some cases, it is useful to interactive rebase onto another branch (git rebase --onto parameter)
Currently it seems that sourcegit only allows interactive rebase for ancestor commits, so it would be useful to allow it everywhere

**Comment by love-linger** [comment]
I've revert the commit 65bcffa because it need totally rewrite to support full-featured interactive rebase.

**Comment by love-linger** [comment]
Recently, I tried to implement it, but finally failed. It's hard to calculate the commit list to be deal with between two branches before running `rebase -i`, which will invoke another sequencer process that I do NOT want in that time.

Please forgive my poor ability.  

Therefore, the following two alternatives are recommended:

* use `cherry-pick`
* run `rebase` first, then `interactive rebase`

This issue will be closed and will not be planed in near future
