### ISSUE TITLE
[BUG] The Preference "Enable Auto CRLF" should be turned OFF by default

### ISSUE THREAD

**Issue by ozmium** [sourcegit-scm/sourcegit#297]
When SourceGit is used on a local Git repository, it enables the following **global** git setting, which is unwanted by some users:

`$HOME/.gitconfig`

```shell
[core]
	autocrlf = true
```

### This causes several unexpected problems:

* Visual diff tools may start showing additional line-ending changes that are not relevant or not important.
* Users will become confused, because the additional newline changes ([CRLF or LF](https://en.wikipedia.org/wiki/Newline)) only started when SourceGit was being used.
* Git will start automatically converting line endings on text files, which the user may not want.
* The problem starts affecting all Git clients, not just SourceGit.

### Suggestions:

* **The "Enable Auto CRLF" setting should be switched off by default.**

![Screen Shot SourceGit - Preferences - Git](https://github.com/user-attachments/assets/40d1af05-5542-4be8-8b91-ce8613e662f1)

* Also **SourceGit should not modify the global gitconfig of this setting**. Or it should set it to false like this:

`$HOME/.gitconfig`

```shell
[core]
	autocrlf = false
```

**Comment by love-linger** [comment]
> When SourceGit is used on a local Git repository, it enables the following global git setting, which is unwanted by some users

If you read `Preference.axaml.cs`, you will see that `core.autocrlf` is read directly from your global settings. The only exception is whe you do not set it, it will be `true`. 

> Also SourceGit should not modify the global gitconfig of this setting

This is a GUI tool to help people work with git, and this page is intends to modify global git settings. User can turn off the `core.autocrlf` from this page just like they do it from command line.

**Comment by love-linger** [comment]
I've push a commit that unchange the global `core.autocrlf` if user do NOT set it yet.
