### ISSUE TITLE
[Feature] - Customizable fonts

### ISSUE THREAD

**Issue by ennerperez** [sourcegit-scm/sourcegit#30]
Allow to the user to pick the font for the UI

- [x] Default font per OS
- [x] Switchable font from preferences

**Comment by love-linger** [comment]
@ennerperez I don't quite understand what kind of situation "User Custom Font" refers to. 

Now, users can choose their favorite fonts from the system-installed fonts.

**Comment by ennerperez** [comment]
You'r right!, User custom font now not make sense.
