### ISSUE TITLE
[Bug] "Revert Commit" process does not respect the "Commit revert changes" checkbox option

### ISSUE THREAD

**Issue by ZaLiTHkA** [sourcegit-scm/sourcegit#303]
discovered this with version `8.23` running under Windows 11 Pro. I do also use SourceGit on Linux, but I'm not close to that machine at the moment; I can test this process there later on today if need be.

while checked out at the `HEAD` of a branch with no working tree changes, the following steps should reproduce this behaviour consistently:

- right click any commit and choose "Revert Commit"
- clear the "Commit revert changes" checkbox and click OK
  - notice a new status bar across the top ofthe window to show a revert is currently in progress
- click the "Continue" button to complete the revert process
  - notice that the current branch has a new commit with a `Revert "old commit message"` message

my "revert" action _did not_ result in any conflicting changes, which does tend to mess with the revert process a little..

I also have not tried this same process with the "Commit revert changes" checkbox in it's default "checked" state, but I expect that would commit the changes exactly as it currently does, which is correct.

**Comment by love-linger** [comment]
The `Commit revert changes` checkbox is used to determine whether the `--no-commit` parameter is enabled in the `git revert` command. See `src/Commands/Revert.cs`:
```csharp
namespace SourceGit.Commands
{
    public class Revert : Command
    {
        public Revert(string repo, string commit, bool autoCommit)
        {
            WorkingDirectory = repo;
            Context = repo;
            Args = $"revert {commit} --no-edit";
            if (!autoCommit)
                Args += "  --no-commit";
        }
    }
}
```

* Without `--no-commit`, and no conflicts detected, `git revert` will just create a commit. The in-progress bar will not be displayed.
* With `--no-commit` or conflicts detected, `git revert` command will result in a reverting state. For example, after running `git revert SHA --no-edit --no-commit`, use `git status` to see the current state:
![image](https://github.com/user-attachments/assets/2eed42da-9128-4bf1-864d-485c3e898262)
this is why the in-progress bar displayed

**Comment by ZaLiTHkA** [comment]
hmmm, yeah.. in hindsight, that is gow Git itself works, so this makes perfect sense.

my apologies, didn't sleep last night, obviously I'm not thinking too clearly today. 🤦🏼
