### ISSUE TITLE
[Feature] Add arm64 builds for Linux

### ISSUE THREAD

**Issue by notpushkin** [sourcegit-scm/sourcegit#309]
I'm currently running [Asahi Linux](https://asahilinux.org/) on MacBook Air M1, and would love to try SourceGit!

**Comment by love-linger** [comment]
I'm sorry, I do not have a linux arm device, and it seems that Github hosted runners does not provide such a image.

**Comment by aikawayataro** [comment]
@love-linger
It is possible to cross compile dotnet even with NativeAOT enabled:

```
$ uname -m
x86_64

$ dotnet publish -p SysRoot=/usr/aarch64-linux-gnu/ ./src/SourceGit.csproj -c Release -r linux-arm64 -o publish
MSBuild version 17.8.5+b5265ef37 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  SourceGit -> /sourcegit/src/bin/Release/net8.0/linux-arm64/SourceGit.dll
  Optimizing assemblies for size may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
  SourceGit -> /sourcegit/publish/

$ file publish/SourceGit
publish/SourceGit: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, BuildID[sha1]=e4b5436cab1ce4e3dd8eefff48e0953bdeed4eee, for GNU/Linux 3.7.0, stripped
```

(I did this on Arch Linux, but it's also possible on Debian, since all the needed packages are in the repository).
Let me know if you want a pull request with an aarch64 CI build.

**Comment by love-linger** [comment]
Thank you @aikawayataro. Please help me to add this feature in github CI workflow!

**Comment by love-linger** [comment]
Thanks to @aikawayataro. There's portable package generated by Github Action workflow. @notpushkin you can test it from https://github.com/sourcegit-scm/sourcegit/actions/runs/10213711452
