### ISSUE TITLE
[Linting] - Solution Code Format

### ISSUE THREAD

**Issue by ennerperez** [sourcegit-scm/sourcegit#31]
Update the existing code format to compliance the editorconfig rules

- [x] Format CS files
- [x] Format AXAML files
- [x] Format RESX files
- [ ] Others files

**Comment by love-linger** [comment]
I don't have a particular preference for which code style to use. You can submit a PR for this.  See issue #25

**Comment by ennerperez** [comment]
I ran a solution format but still have to change some rules in .editorconfig especially for XML files and others...

**Comment by love-linger** [comment]
> I ran a solution format but still have to change some rules in .editorconfig especially for XML files and others...

I'm not very familiar with .editorconfig. I need someone to help me to do this job.

**Comment by Rwing** [comment]
maybe we can just use avalonia's editorconfig
https://github.com/AvaloniaUI/Avalonia/blob/master/.editorconfig

**Comment by love-linger** [comment]
I have found that using the Avalonia project's editorconfig does have benefits. It helped me find a lot of potential bugs.
