### ISSUE TITLE
[Bug] Missing underscore in branch name (commit contextual menu)

### ISSUE THREAD

**Issue by julaudo** [sourcegit-scm/sourcegit#313]
![image](https://github.com/user-attachments/assets/78dbfd69-04fe-4e72-b4fa-d78ccdc2a257)

"testbranch" is displayed instead of "test_branch"

**Comment by love-linger** [comment]
try to choose another font for 'Default Font'

**Comment by love-linger** [comment]
Confirmed that `RecognizesAccessKey` property of `ContentPresenter` in the `MenuItem` should not be enabled.
