### ISSUE TITLE
[FEATURE] Offer Windows specific executable setup package

### ISSUE THREAD

**Issue by LouieTian0209** [sourcegit-scm/sourcegit#314]
This issue is created following suggestion from @ZaLiTHkA in #175 to have a dedicated issue on Windows specific executable setup package (standalone .exe installer) available for Sourcegit.

The main point, although already mentioned in related issue referenced above, is referenced again here as follows:

> In addition, some actions that help with user experience can also be achieved using an installer, such as the ability to create a desktop shortcut as well as add a new start menu entry when installation completes, so that the user can have multiple ways to launch the program out of the box.

With some insights from @ZaLiTHkA:

> in my opinion, since this issue is technically resolved (by making SourceGit available through Winget), perhaps a separate issue could be opened for a Windows-specific executable setup package? there are numerous systems that can do this, some of which are OSS, and some of which can even be done through GitHub Actions..

**Comment by gadfly3173** [comment]
> https://github.com/sourcegit-scm/sourcegit/issues/312#issuecomment-2268709698 @aikawayataro 
 
Here is a closed PR https://github.com/sourcegit-scm/sourcegit/pull/202 which you can check.

**Comment by love-linger** [comment]
It's not recommanded to use a standalone installer without self-update feature.

**Comment by kemsky** [comment]
@love-linger, 

> It's not recommanded to use a standalone installer without self-update feature.

Many software products use simple update checker that notifies users when a new version is available and suggest to download a new version.

Another option is to use something like https://velopack.io/.
