### ISSUE TITLE
支持 issue link

### ISSUE THREAD

**Issue by heartacker** [sourcegit-scm/sourcegit#315]
希望添加对issue 连接的自动检测，
#num 已经是git commit 的一个不成文的规范了。
希望app 可以添加整个自动检测（全局可配置）+每个仓库手动可以更改的功能

```git-commit
fix #315
support issue link
```
1. 默认配置 检测仓库remote 并自动匹配问题单。
   - ssh: 如检测到仓库是 `git@github.com:sourcegit-scm/sourcegit.git`，这自动检测到 https://github.com/sourcegit-scm/sourcegit/issues/315 `https://github.com/sourcegit-scm/sourcegit/issues/315`
   - http(s): `https://github.com/sourcegit-scm/sourcegit.git`, 也是同理
2. 用户可以配置，通过正则等，直接检测并配置。
   如: vscode 的 git-graph
    ![image](https://github.com/user-attachments/assets/616dfbd2-0a76-4548-bb7c-d1dafcefd293)

**Comment by love-linger** [comment]
提交了个简单的实现。
![image](https://github.com/user-attachments/assets/3af6275b-99c2-4ac5-bc53-580f800db607)

目前有两个点需要注意：

* 不支持全局。意味着您需要为每个仓库配置独立的ISSUE。目前对Github仓库URL会自动生成
* 对于多个规则，会有先后顺序。比如：第一个匹配 #NUMBER 第二个匹配 XXX #NUMBER时，由于两个会有都配置成功的情况，这时仅第一个会生效。

**Comment by heartacker** [comment]
这个设置之后不生效啊

**Comment by love-linger** [comment]
需要重新选择一下commit，在Detail面板中重新显示其message.
![image](https://github.com/user-attachments/assets/b58be2ea-354c-4a96-8b83-3b30d8fef032)

**Comment by heartacker** [comment]
1. 噢噢，设置之后要重启才能生效
2.  commit list 不能直接点击。必须点击cmmmit node，然后在commit detail 才可以点击，希望添加在commit node 也可以点击。
3. commit node 显示和之前一摸一样，用户很难指导这里有 issue i按揭，是否和 commit detail 一样，让用户直接辨别

**Comment by love-linger** [comment]
> 3\. 很

1. 是的，目前需要刷新一下，比如重新打开repository，或是重新选择commit
2. 这个实现很简单，但是有点浪费，因为该功能会使用正则匹配检测提交信息，但Commit列表中，一是经常显示不全，二是ISSUE很多人会习惯写在SUBJECT的最后。这样检测就完全浪费了。我看了一下 fork，也是没有实现的。
3. 同2

**Comment by love-linger** [comment]
这个不难，但要测试一下效率，要测试一下使用多个正则同时检测全部显示的列表的性能表现

**Comment by love-linger** [comment]
测试了一下，实际性能损耗可以忽略，已经加上，可下载 https://github.com/sourcegit-scm/sourcegit/actions/runs/10259537406 测试

**Comment by heartacker** [comment]
![image](https://github.com/user-attachments/assets/a8b52ccc-f646-4b5c-9708-a08a346af18e)

**Comment by heartacker** [comment]
不同主题下，都显示不是很清楚，建议弄成链接的的样式

**Comment by love-linger** [comment]
这个软件的高亮色与系统主题色相关

https://github.com/sourcegit-scm/sourcegit/assets/4075673/783c561a-7724-4b6e-9a58-ee1382c49784

![image](https://github.com/user-attachments/assets/7c53aca3-0870-4998-8585-fd5424ca294b)

**Comment by heartacker** [comment]
我是说链接部分，不是说选中的行

**Comment by heartacker** [comment]
理解你的意思了，链接是主题色
但是我觉得这个链接，无论是啥主题，很多都是以蓝色为主，很少有和主题色一样的。

**Comment by love-linger** [comment]
> 我是说链接部分，不是说选中的行

都是一个，上面的视频只是之前的ISSUE中的，用于说明如何修改主题色。

**Comment by heartacker** [comment]
倾向于蓝色为主：
参考

https://blog.mozilla.org/en/internet-culture/deep-dives/why-are-hyperlinks-blue/

![image](https://github.com/user-attachments/assets/8c138810-ba58-404a-ac76-595989698bdc)

**Comment by love-linger** [comment]
我决定不在历史记录中显示链接了，有以下原因：

* TextBlock不支持超链接，现在是上层代码模拟的，后面为解决无法复制链接中的文字以及全选后右键都失效的问题又增加了一些代码处理，有一定的性能损耗
* 我自己在使用过程中，出现了多次想要选择提交，但却误点击了链接，直接弹出到浏览器。体验并不好。尤其是处理winget这样的库时，大量的issue连接，很容易误点

**Comment by heartacker** [comment]
建议添加选项，而不是直接删除，可以吗

**Comment by heartacker** [comment]
这一删除，我们的习惯又不见了

**Comment by love-linger** [comment]
我再改改，看一下能否保留吧

**Comment by love-linger** [comment]
点击跳转到网页后，会出现渲染失效的问题。
![image](https://github.com/user-attachments/assets/edbaebf0-6c05-4e7d-9683-f404cfc6343e)

我决定还是以Fork为参考，不在列表中显示ISSUE链接了

**Comment by heartacker** [comment]
为啥我这边不会呢，好奇怪，我这边这几天用起来很方便，也没有遇到你这边的问题。

**Comment by heartacker** [comment]
再次恳求，添加选项而不是删除。你这边遇到的问题也许是bug，后面 可以修复。可以标记这个功能为 preview，可能存在bug

**Comment by love-linger** [comment]
好消息。我终于定位到渲染失效的问题了 - 频繁设置`Run`的样式导致。这很奇怪……
不过目前，该问题只是少了鼠标移上去后显示的下划线，其他不受影响。
马上将功能加回去

https://github.com/user-attachments/assets/48b3d7dd-89c5-442e-b86a-6bf7377031d4
