### ISSUE TITLE
error: stash@{0} is not a valid reference

### ISSUE THREAD

**Issue by heartacker** [sourcegit-scm/sourcegit#316]
error: stash@{0} is not a valid reference

莫名其妙的消息

**Comment by love-linger** [comment]
这个消息是捕获得git stderr输出。你是在操作什么时有这个输出的呢？

**Comment by love-linger** [comment]
我猜测应该是启用了`Stash & Reapply`的相关操作的输出。尝试改了一下。先关闭这个问题。
