### ISSUE TITLE
[Blocker] - Use SVG icons instead StreamGeometry

### ISSUE THREAD

**Issue by ennerperez** [sourcegit-scm/sourcegit#32]

**Comment by love-linger** [comment]
Why?

**Comment by ennerperez** [comment]
How I supposed to add new icons? specifically if I have an SVG I wan to use as icon for a "Open with..."?

**Comment by love-linger** [comment]
@ennerperez you can just open the svg image with your favorite text editor. 
![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/f8ff8213-9954-40a9-ac58-3395c3a089d9)
And then copy data in `d` attribute of `path` element

**Comment by ennerperez** [comment]
And what about complex svg files?

I'm adding extra "Open with..." actions, like:
- Open in Fleet
- Open in Visual Studio
- Open in Rider

So my initial work on this is just add open in fleet using this icon:

![](https://resources.jetbrains.com/storage/products/company/brand/logos/Fleet_icon.svg)

More info at: https://www.jetbrains.com/company/brand/#brand-guidelines

Then I want to add a context menu to display a wide IDE options.

**Comment by love-linger** [comment]
My suggestion is that you can create a new subdirectory in the `Resources` directory, such as `ExternalToolIcons`, to store all these SVG images.

I'll keep to use StreamGeometry for all the other icons.

**Comment by ennerperez** [comment]
Recommended folder by Avalonia is Assets but I'll keep on resources.

![image](https://github.com/sourcegit-scm/sourcegit/assets/1206858/f58664fa-6ed2-4496-962d-3a25aa41ca17)

Thanks.
