### ISSUE TITLE
Copy info from multiple commits

### ISSUE THREAD

**Issue by Nevenit** [sourcegit-scm/sourcegit#321]
Selecting multiple commits and copying just copies a bunch of empty strings:

""	""	""	""
""	""	""	""
""	""	""	""
""	""	""	""

It would be nice if it copied the actual commits like this:

b059423391 - feature: enable using drag-drop to re-order commits (#319)
85d3f0993c - refactor: load default github avatar
91daa42c08 - ux: margins between textbox and its label in issue tracker configure page
dfd098e131 - refactor: merge sourcegit.issuetracker.setting to sourcegit.settings.

**Comment by love-linger** [comment]
You can try this implementation from https://github.com/sourcegit-scm/sourcegit/actions/runs/10259013783
