### ISSUE TITLE
Issues in rebase workflow in case of conflict

### ISSUE THREAD

**Issue by julaudo** [sourcegit-scm/sourcegit#327]
I'm rebasing 1 commit, and have conflicts.

After clicking on rebase, "Rebase current branch" appears -> I click "OK" to rebase
An error popup appears : Rebasing (1/1)...Conflicting commit
BUT "Rebase current branch" is still visible. It's not logical, instead we should lead the user to the "Resolve" button. 

I think neither the "Error" popup nor the "Rebase current branch" should be displayed here.
Proposition : A specific popup with 2 buttons : "Resolve" and "Abort"

**Comment by love-linger** [comment]
I've pushed a commit f41f8266d2e86d26bc12cb0206f6774dcec3e37f for this.

https://github.com/user-attachments/assets/ac4fd1a0-6223-4bd1-b24e-c401a27ad7f4

**Comment by julaudo** [comment]
Is it really useful to display the error popup?

**Comment by love-linger** [comment]
It's comes from the `stderr` of git process. We can't judge all the error output individually to decide whether to display it, so keep the behavior consistent with the command line.
