### ISSUE TITLE
[error] appimage could not lauch on ubuntu22.04

### ISSUE THREAD

**Issue by stilwellsun** [sourcegit-scm/sourcegit#329]
os: ubuntu 22.04 lts
appimagelauncher:  2.2.0-travis995~0f91801+bionic

AppImageLauncher error: appimage_shall_not_be_integrated() failed (returned -1)
Squashfs image uses (null) compression, this version supports only xz, zlib.

**Comment by love-linger** [comment]
can you start sourcegit by double-click the appimage? BTW, it is recommanded install *.deb on Ubuntu.

**Comment by gadfly3173** [comment]
https://github.com/TheAssassin/AppImageLauncher/issues/602 It seems to be an issue with AppImageLauncher.
