### ISSUE TITLE
Discard warning is displayed ony for the last chunk

### ISSUE THREAD

**Issue by julaudo** [sourcegit-scm/sourcegit#330]
On unstaged file, with multiple modified chunks.

When discarding a chunk, no warning is displayed. A warning is displayed only when discarding the last chunk. I guess this is not intended.

**Comment by love-linger** [comment]
I've pushed a commit f8bc48c49c7e7abf3cec01b8d30fcf5619c01427 to exec git command directly in text diff view instead of calling method from WorkingCopy.
