### ISSUE TITLE
调节字体标签页不会生效

### ISSUE THREAD

**Issue by heartacker** [sourcegit-scm/sourcegit#332]
![image](https://github.com/user-attachments/assets/55ee7376-5e19-4d4a-a6df-f263619f0451)

标签页的字体和标签的高度都不会变。

**Comment by gadfly3173** [comment]
#292 截图中的亮色部分都是等宽字体，并且不会回落到默认字体而是系统字体

**Comment by heartacker** [comment]
那我该如何调节标签的字体大小呢，有点小，希望跟随编辑器的字变化

**Comment by love-linger** [comment]
上传了提交 1ab0ea27df9f6b65c88187f7cd487c4969b05ba4，移除了TabBar的固定字体大小。

> [!NOTE]
> 如果不喜欢到处都是等宽字体，可在软件设置中，启用【仅在文本编辑器中使用等宽字体】
