### ISSUE TITLE
Issue with Amend function

### ISSUE THREAD

**Issue by itcotta** [sourcegit-scm/sourcegit#336]
Hi,
When performing an amend on a local commit, if I just update the commit message without changing any of the staged files I get the following error:

"No files added to commit!"

In my experience the expected behavior should be for the amend to be successful and just simply update the commit message, even if no files have been removed/added.

**Comment by love-linger** [comment]
currently, you can use `Reword` from context menu of Head commit to do this. since more than one people mentioned this feature request, i'll consider to add it later

**Comment by love-linger** [comment]
I've pushed a commit eb441852b0d950b2cb3417ca9a75286d6725b722 to allow editing commit message only with `Amend`. You can try it from https://github.com/sourcegit-scm/sourcegit/actions/runs/10297698119
