### ISSUE TITLE
[Bug] Sometimes the counter badge will show blank or 0 

### ISSUE THREAD

**Issue by gadfly3173** [sourcegit-scm/sourcegit#338]
![1723106254332](https://github.com/user-attachments/assets/09f260d9-682e-4eaa-b844-5e7111e4ebc1)

Usually it appears after I frequently switch between multiple opened repository tabs. It is unable to reproduce stably. It seems to be related to asynchronous execution and https://github.com/sourcegit-scm/sourcegit/issues/286

**Comment by love-linger** [comment]
I can not reproduce this issue. I suggest that the next time you are in this situation, you can use DevTools (press F12 in debug mode) to see if the data is binding correctly.

**Comment by gadfly3173** [comment]
![image](https://github.com/user-attachments/assets/007dbe67-dfaa-417b-b4da-3b7b1ea540ad)
Do you mean check this? It's easier to reproduce in debug mode, maybe because debug mode runs slower.

**Comment by love-linger** [comment]
I'm sorry, I still can not reproduce it with debugging on my PC (i7-14700KF) and mac (M3Max). 

https://github.com/user-attachments/assets/cc54e482-4d29-425a-830a-fd0ec7f4e0ba

Could please you help me debug it?

**Comment by heartacker** [comment]
I have same issue

**Comment by gadfly3173** [comment]
![image](https://github.com/user-attachments/assets/04b3ab38-c44d-40c5-8c15-f8aa07c06ec1)
I tried to print `WorkingCopyChangesCount` when it was called and found that the count obtained was correct, but the UI showed 0.

**Comment by gadfly3173** [comment]
I tried adding `Mode=TwoWay` to the Binding, which did not solve the problem. I also confirmed through debugging that the `WorkingCopy._count property` is not reassigned when switching tabs

**Comment by gadfly3173** [comment]
It seems that Avalonia 11.0.13 does not have this problem. This may be an issue with Avalonia's TextBlock.

**Comment by love-linger** [comment]
I finally reproduced this issue by **switching branches and check the REFS of commit in details view**. `CommitRefsPresenter` has no asynchronous operation, and by outputting its value, I can confirm that the data is correct.

**Comment by love-linger** [comment]
> It seems that Avalonia 11.0.13 does not have this problem. This may be an issue with Avalonia's TextBlock.

This also works for me.

**Comment by gadfly3173** [comment]
I think https://github.com/AvaloniaUI/Avalonia/issues/16456 is related to this issue, and the PR is not released yet.

**Comment by love-linger** [comment]
maybe not. you can see that the bug shows in my screen shot, which is a custom control binding with same data and render it directly without any other controls

**Comment by love-linger** [comment]
@gadfly3173 Avalonia team has released a new version `11.1.3` which contains some changes that seems related with this issue. And I can not reproduce this issue with the way I made it before. Could you please test this for me? It seems that you can reproduce this issue easily 😀……

**Comment by love-linger** [comment]
@gadfly3173 I've pushed a new commit that try to fix this issue. Could you please test it for me? 😅

**Comment by gadfly3173** [comment]
![image](https://github.com/user-attachments/assets/4d19e8aa-c329-4e81-b891-836726e07602)

Unfortunately, this problem has not been solved.

**Comment by love-linger** [comment]
I've totally replace the badge control with a custom control. @gadfly3173 please try again 🤣

**Comment by gadfly3173** [comment]
> I've totally replace the badge control with a custom control. @gadfly3173 please try again 🤣

It works fine now. What a strange problem.
