### ISSUE TITLE
[Feature] Add Indication when submodule has changes

### ISSUE THREAD

**Issue by esierp** [sourcegit-scm/sourcegit#339]
If there is a change of files in a submodule, there is currently no indication of the top project that a submodule has changes pending. So you must enter each submodule and look if there are changes, that are currently not commited.
Adding a indicator that a submodule has pending changes would improve the administration of submodules.

![submodule_view](https://github.com/user-attachments/assets/ebd7da1e-9ce1-4f8e-9caa-eecabd9ee940)

**Comment by love-linger** [comment]
I've pushed a commit 1fe2be11a7bc303b81383c8aa8bbbbaaa92f5045 for this feature request. You can download https://github.com/sourcegit-scm/sourcegit/actions/runs/10302791781 to test it.

**Comment by love-linger** [comment]
Here is the screenshot:

![image](https://github.com/user-attachments/assets/585743f8-802a-439f-ae82-276dd9c0e83f)

**Comment by esierp** [comment]
it works like a charm!

Thank you!

**Comment by esierp** [comment]
Unfortunately, there's a minor bug. When you change the head in a submodule, the indication is shown in the top module, even if there are no file changes in the submodule—just a commit switch. This might be acceptable because it allows you to see that there was indeed a change in the submodule.

However, if you change the submodule head, the change is not immediately reflected in the changes window. It only appears after you restart the software or click the "Include Untracked Files" button. Additionally, if the submodule is switched back to its original head, the change remains visible in the top module.


https://github.com/user-attachments/assets/847272e3-097a-4580-9275-206532d3ec2a

**Comment by love-linger** [comment]
> Unfortunately, there's a minor bug. When you change the head in a submodule, the indication is shown in the top module, even if there are no file changes in the submodule—just a commit switch. This might be acceptable because it allows you to see that there was indeed a change in the submodule.

Yes, the indicator displays after HEAD changed or you have local changes.

> However, if you change the submodule head, the change is not immediately reflected in the changes window. It only appears after you restart the software or click the "Include Untracked Files" button. Additionally, if the submodule is switched back to its original head, the change remains visible in the top module.

I've pushed a new commit d37f53a4f31dc0832e3251d1153adf01b88bf70c to fix this issue. It's my mistake.

**Comment by love-linger** [comment]
You can download https://github.com/sourcegit-scm/sourcegit/actions/runs/10314797701.
Look forward to your feedback.

**Comment by esierp** [comment]
Works as intended. 
Thank you very much! 
I eally appreciate your effort and work.

**Comment by esierp** [comment]
If i update a submodule to an other commit, the indication on the top module is shown as intended.
When i commit the submodule update on the top, the indication should be removed, because there are no pending changes - the indicator is only removed if i close the repository and open it again



https://github.com/user-attachments/assets/2d22df57-63fc-4a2a-bd20-cf8d5e379d7c

**Comment by esierp** [comment]
The fix is working!
