### ISSUE TITLE
增加统计（更新，提交等）

### ISSUE THREAD

**Issue by bkwangbj** [sourcegit-scm/sourcegit#340]
如题：
![image](https://github.com/user-attachments/assets/8b639ed2-6462-41ba-a121-612192529f1e)

**Comment by love-linger** [comment]
不太明白你指的是什么

**Comment by heartacker** [comment]
如果 add 了 3个文件，add 的按钮显示 3

**Comment by heartacker** [comment]
pull 按钮。如果远程有10 待pull ，显示 10

**Comment by heartacker** [comment]
推送，如果有几个推送，显示数字几。类似这个意思

**Comment by love-linger** [comment]
> 如果 add 了 3个文件，add 的按钮显示 3

![image](https://github.com/user-attachments/assets/d0726932-fedb-4f08-9e4b-106920706f90)

> pull 按钮。如果远程有10 待pull ，显示 10
> 推送，如果有几个推送，显示数字几。类似这个意思

你指的是git object中的`%(upstream:track)`吗？，如果是，现在已经显示了呀
![image](https://github.com/user-attachments/assets/62b92a30-6d0d-4284-b506-0382ec90dfbd)

**Comment by heartacker** [comment]
希望在上面的快捷按钮直接显示，比较直观

**Comment by love-linger** [comment]
1. Stage/Unstage以及总的本地变更数，都分别在各自的区域，其中本地总的变更数在一级界面上采用主前景色，已经可以提示到用户本地有变更。且Commit操作与staged changes数量不挂钩（比如启用了自动stage功能，则unstaged changes也会被提交）
2. Push按钮可以推送非当前分支，这里如果仅显示当前分支与remote的ahead/behind则不合适
3. 如果未进行过fetch，则Pull操作前并不知晓远端的最新状态。再者，即使实现了该功能，如果Pull按钮上没有提示数字，我们就不需要Pull了吗？我持怀疑态度
4. 本软件的工具栏并不适合显示上标数字。一是本身太窄，二是如果数字很大则又会显得横向太挤
