### ISSUE TITLE
Mouse pointer off centre 

### ISSUE THREAD

**Issue by johas97** [sourcegit-scm/sourcegit#341]
Hi, must say I really like the code base & program. In my job I must use WSL. I have tried to do it with relative success. (Running the Linux deb version via WSL) 

However the mouse placement is not aligned with "click surface" if you maximise the window. I will investigate this if I have  the time.

**Comment by love-linger** [comment]
The software has not been tested in WSL. Thanks very much.

**Comment by johas97** [comment]
![Animation](https://github.com/user-attachments/assets/e127b109-9f6f-4558-a193-1e63e4de0c26)

You can see it in action here.

**Comment by love-linger** [comment]
> Performance is ok, but that might also just be WSLg.

I find there's a related issue https://github.com/microsoft/wslg/issues/1015

**Comment by love-linger** [comment]
This is problem is solved in SourceGit by providing an option to use system native window frame in preference panel. See #390
