### ISSUE TITLE
remote 切换，分支不会自动跟踪

### ISSUE THREAD

**Issue by heartacker** [sourcegit-scm/sourcegit#342]
https://github.com/user-attachments/assets/fc6b9201-ac5a-4201-865d-47eea181db34

**Comment by love-linger** [comment]
这里采用的与Fork相同的逻辑。如果是直接点击的工具栏的Pull按钮，则本地分支锁定为当前分支。如需Pull其他分支，需要在分支树上右键操作

**Comment by heartacker** [comment]
我觉得默认应该主动跟踪同名分支，好几次，都是因为这个bug，pull到别的分支了。

**Comment by love-linger** [comment]
![image](https://github.com/user-attachments/assets/72031968-082b-4b57-a0cf-ed96f8d919fc)

这是GIT PULL命令的说明，明确了PULL操作中merge的目标分支为当前分支

**Comment by heartacker** [comment]
我理解你的意思，但是我这个场景是在多个remote 下

**Comment by love-linger** [comment]
这个与多少个remote或源分支无关，PULL操作merge的目标就是当前分支

**Comment by love-linger** [comment]
哦，我大概理解你的意思了。这是因为只能跟踪一个分支，如果选择的remote中没有当前分支跟踪的分支，就没法自动选择

**Comment by love-linger** [comment]
而且进入手动选择模式后，就不再自动选择了

**Comment by heartacker** [comment]
是的，你看我的视频，切换remote你默认选择第一个

**Comment by love-linger** [comment]
改了一下，目前分三种情况

1. 如果选择的remote中有当前分支的upstream，则在remote变化后，自动选择该分支
2. 如果第1条不满足，尝试在当前remote中找到相同名字的分支，如果有，自动选择该分支
3. 如果连第2条都不满足，直接选择当前remote中的第一个分支
