### ISSUE TITLE
[Enhancement] Create branch on detached Head

### ISSUE THREAD

**Issue by esierp** [sourcegit-scm/sourcegit#344]
When I'm in a detached HEAD state in Git, I encounter an error when trying to create a branch from it. I can make commits while in the detached HEAD state, but these commits don't appear in the graph and subject window, indicating they're on a detached head. Additionally, I can't create a branch from these commits within the tool. However, when using another tool, I can see the commit and create a branch from it, which then becomes visible in the graph and subject window. If this occurs in a submodule, I can see the commit ID and the changes in the top-level module.

https://github.com/user-attachments/assets/bd4430ad-7746-4f8f-a36c-dd7b21cabeed

**Comment by love-linger** [comment]
You can test it from https://github.com/sourcegit-scm/sourcegit/actions/runs/10315857949

**Comment by esierp** [comment]
Head is now shown in the graph - which is realy fine!
I can create a branch on the detached head - which is good!
If i create a commit on the detached head, without create a branch previously. I can't create the branch over the local branches window - but with right click on commit and create a branch it works

Really great work!


https://github.com/user-attachments/assets/323eeff2-500a-487c-a995-8e47d8489d0a

**Comment by love-linger** [comment]
I've pushed a new commit e05264e35dae30a3b141bbd871a0f891b33b8c3e to fix the issue that users can not create branch based on detached HEAD with extra commits. You can test it from https://github.com/sourcegit-scm/sourcegit/actions/runs/10316558339

**Comment by esierp** [comment]
Bugfix is working like a charm!

Thank you!
