### ISSUE TITLE
[Enhancement] Add Warning message when submodule has pending changes or commits which arent pushed to remote when trying to push top module

### ISSUE THREAD

**Issue by esierp** [sourcegit-scm/sourcegit#345]
Could you add a hint window, when someone is trying to push a repository which includes submodules which are in a dirty state or the commit of the submodule is not yet on a remote branch?
The hint popup window should have the ability to ignore that there are pending changes or/and a button to jump to the submodule which is affected

Like:
<img width="273" alt="image" src="https://github.com/user-attachments/assets/83eb3c53-6bdd-4f7d-b6d3-4bd9ec92f5f6">

**Comment by love-linger** [comment]
Can someone give me a script (or git hooks) for this feature?

**Comment by esierp** [comment]
https://git-scm.com/book/en/v2/Git-Tools-Submodules#:~:text=Those%20changes%20will%20only%20exist,or%20%E2%80%9Con%2Ddemand%E2%80%9D.

https://stackoverflow.com/questions/29924360/how-to-list-git-submodules-that-have-not-been-pushed-to-origin

<img width="575" alt="image" src="https://github.com/user-attachments/assets/62433560-1eee-4583-a321-29eeb155cbee">

**Comment by love-linger** [comment]
an option has been added to enable `--recurse-submodules=check` on push.
![image](https://github.com/user-attachments/assets/89d33f48-2d58-456b-8418-391c6e8f0151)
