### ISSUE TITLE
Feature request: Allow manual configuration of external tools

### ISSUE THREAD

**Issue by AbraxasDMG** [sourcegit-scm/sourcegit#347]
Hi everyone.

On windows, the program will attempt to find external tools (vscode, fleet, sublitext, etc.) based on some predefined/expected locations for them to show up. This is not allowing portable setups of such tools to be viable combination with sourcegit.

If extending the preferences window by these additional fields is too much work or unwanted, would it be possible to leave the option to configure appropriate paths directly into the preference.json file?

Thank you very much in advance.

**Comment by love-linger** [comment]
Currently, you can use environment variables to help this app find external editors. See `README.md`

**Comment by love-linger** [comment]
> <s>Currently, you can use environment variables to help this app find external editors. See `README.md`</s>

I've pushed a commit 0c6af27b40b5c9290c6b3438f3d730c279e743a5 that changes the way to help this app finding external editors.
