### ISSUE TITLE
Feature request: Allow fully portable mode on windows

### ISSUE THREAD

**Issue by AbraxasDMG** [sourcegit-scm/sourcegit#348]
Hi everyone.

Would it be possible to allow for possibility to have the sourcegit configuration/log/avatar folder located side by side with the executable? That way the installation could be truly portable and movable between the computers, if needed.

Right now the preference.json, logs and avatars are located in the AppData folder of the person that ran the program.

Thank you in advance.

**Comment by love-linger** [comment]
For the following reasons, the storage location of user data will not change:

* The writable permission of the directory where the executable file is stored is uncertain.
* It is not desired to affect the old users who have used the software.
* The number and paths of repositories on different machines are not necessarily the same, and it is impossible to be portable.

**Comment by AbraxasDMG** [comment]
Hi. Thank you for the feedback.

I accept the fact that this is not going to be implemented. However, I still wanted to provide further details on what I meant with this feature.

The idea was to offer "also" the portable mode, in addition to the default mode. This can be achieved easily in different ways, for example, the presence of the file named "portable" or a folder named "settings" next to the executable could be enough. In that way, existing users who prefer to have their configuration stored in appdata are unaffected, while the others who want to "carry" the configuration elsewhere, have the option to do so.

For the portability of the repositories, I could agree. However, if someone is looking for a portable mode in git client, usually, they are interested in carrying the repositories around with it as well. Portable mode could/should implement a modification in how the paths are saved for the repositories located on the same drive as the sourcegit portable deployment. Saving them as relative instead of absolute paths would allow for such scenarios to be truly portable. 
Repositories on other drives would have to stay defined by their absolute paths.

**Comment by love-linger** [comment]
I'm sorry. This application relies heavily on data that is independent of the application, such as, but not limited to, basic git/gpg tools, user repositories, and third-party tools (external editors, DIFF/MERGE tools). All these determine that its configuration data can not be portable.
