### ISSUE TITLE
[Feature Request] - Use `/` character in tags to display folder tree

### ISSUE THREAD

**Issue by trauty-is-me** [sourcegit-scm/sourcegit#350]
Seen in Ubuntu version 8.24

When viewing the list of tags, it would be nice if the tag name was interpreted and as a folder path. This is already done for branches. See the example screenshot:

![image](https://github.com/user-attachments/assets/970de3aa-712d-44ba-b68f-611326cc3a6c)

**Comment by love-linger** [comment]
I've explained why tags appear as lists before. 

* I strongly recommend against using non-semantic tag naming. Most code hosting servers also do not recommend naming tags this way. For example, the API to search a release information by tag name in Github is `https://api.github.com/repos/sourcegit-scm/sourcegit/releases/tags/${tag_name}`.
* The time attribute of the tag is very strong. The list of tags sorted by the most recent time is very convenient to find out what the latest version of a software is. The tree structure breaks this property.
* The vertical space on the left information panel is valuable. For the case of the label, which wants the same height, more information is displayed.

**Comment by love-linger** [comment]
Since many people have asked for this, I will submit the implementation, but it needs to be turned on manually.
![image](https://github.com/user-attachments/assets/1ee4a5f9-78e8-4841-ab90-299ca83ec981)

**Comment by trauty-is-me** [comment]
Thanks for the quick implementation of this enhancement. I really appreciate it.
