### ISSUE TITLE
[feature] filter commits by branch、user、data and etc.

### ISSUE THREAD

**Issue by Vixb1122** [sourcegit-scm/sourcegit#352]
just like idea git panel
![image](https://github.com/user-attachments/assets/2691cf69-2473-487c-855d-df7db4febaf1)

**Comment by love-linger** [comment]
You can filter commits by branch with the toggle button on the right of branch name
![image](https://github.com/user-attachments/assets/def74103-2281-49ce-80b9-27cf3f9c8a6c)

Search commits by SHA/user/message/file is supported.
![image](https://github.com/user-attachments/assets/a61d8b93-4bc2-44f0-a06a-5a7ebd3ac787)

**Comment by Vixb1122** [comment]
thx
