### ISSUE TITLE
[Bug] UI scaling is broken in 8.25

### ISSUE THREAD

**Issue by lebeshev** [sourcegit-scm/sourcegit#354]
UI scaling is not working in version 8.25 in Ubuntu 24.04 with Wayland. Version 8.24 worked as expected.

**Comment by love-linger** [comment]
have you configure the environment for wayland displays? https://github.com/AvaloniaUI/Avalonia/wiki/Configuring-X11-per-monitor-DPI

**Comment by love-linger** [comment]
`8.24` use Avalonia `11.1.1`, which provides severals providers for screen scaling. In `8.25`, I downgrade the Avalonia to `11.0.13` for some reasons, see #338.

So you need follow the original way (https://github.com/AvaloniaUI/Avalonia/wiki/Configuring-X11-per-monitor-DPI) to tell this app the screen scale factor.

**Comment by love-linger** [comment]
If you only have one monitor, you use anothor environment variable `AVALONIA_GLOBAL_SCALE_FACTOR`.

See `src/Avaloia.X11/X11Screens.cs`
```csharp
public static X11ScreensUserSettings DetectEnvironment()
{
    var globalFactor = Environment.GetEnvironmentVariable("AVALONIA_GLOBAL_SCALE_FACTOR");
    var screenFactors = Environment.GetEnvironmentVariable("AVALONIA_SCREEN_SCALE_FACTORS");
    if (globalFactor == null && screenFactors == null)
        return null;

    var rv = new  X11ScreensUserSettings
    {
        GlobalScaleFactor = TryParse(globalFactor) ?? 1 
    };

    try
    {
        if (!string.IsNullOrWhiteSpace(screenFactors))
        {
            rv.NamedScaleFactors = screenFactors.Split(';').Where(x => !string.IsNullOrWhiteSpace(x))
                .Select(x => x.Split('=')).ToDictionary(x => x[0],
                    x => double.Parse(x[1], CultureInfo.InvariantCulture));
        }
    }
    catch
    {
        //Ignore
    }

    return rv;  
}
```

**Comment by lebeshev** [comment]
For some reason setting neither `AVALONIA_SCREEN_SCALE_FACTORS` nor `AVALONIA_GLOBAL_SCALE_FACTOR` worked for me (maybe I did something wrong idk, but `echo $AVALONIA_GLOBAL_SCALE_FACTOR` printed 2 after relogin). 
I will use 8.24 for now and patiently wait for new version.
Is there maybe something I could provide to help with the issue? If you feel like investigating ofc

**Comment by love-linger** [comment]
Thanks for your patient. Issue #338 has been fixed in SourceGit and I've restore `Avalonia` to `11.1.3` which version supports screen scaling on Linux.
