### ISSUE TITLE
Feature request: Open remote in web browser

### ISSUE THREAD

**Issue by bernd-wechner** [sourcegit-scm/sourcegit#357]
I quite like SourceGit (the best free, FOSS git gui I know!). 

Something I often want to do is share a link to the remote repo for a given commit on the graph. I right click the commit and look for it, but no joy. 

The remote is generally equipped with a web interface I think, be that GitHub, a GitLab instance or some other ....

It would be nice if I could right-click a commit and open the link in the remote in my browser, or just copy the link to the clipboard (which I'd want to test by opening it ;-).

Under REMOTES in the left panel, I can right click one and I see Open in Browser. 

This would be an extension of that to commits. Of course, each provider will have its own URL schema for that. For example, our GitLab instance:

remoteURL/-/commit/hash-code

and on GitHub it looks more like:

remoteURL/commit/hash-code

Meaning of course if such a link is to be created the template needs to be configurable somehow at a guess, adding a slight complexity to the job. But the idea is nice ;-).

**Comment by love-linger** [comment]
I've pushed a commit that supports commit web links. 

![image](https://github.com/user-attachments/assets/c0fda5cf-373d-45a3-ae56-62d2f0aacbca)

Currently these remote servers are supported:

* Github
* GitLab
* Gitee

**Comment by love-linger** [comment]
If there's only one remote, clicking on this button will open browser directly.
If there's more than one supported remote, clicking on this button will show a dropdown menu to choose which server to visit
