### ISSUE TITLE
Feature Request - File context menu item: reset to current file version or to first-parent file version

### ISSUE THREAD

**Issue by yitzchak-ben-ezra-ecoplant** [sourcegit-scm/sourcegit#359]
this can be easily done via git commands

reset to selected revision: `git checkout COMMIT_SHA -- file1/to/restore`
reset to first-parent revision: `git checkout COMMIT_SHA~1 -- file1/to/restore`
mutiple files also supported: `git checkout COMMIT_SHA -- file1/to/restore file2/to/restore`

this is very helpful - you can go back to a bad commit.. select the file you want to revert, and reset to first-parent - this will efficiently restore it to a good state - next phase is to commit =]

this was the feature I loved most in `git-extensions` tool, but now I'm using mac - and your tool looks the most promising one!

**Comment by love-linger** [comment]
![image](https://github.com/user-attachments/assets/f856d0c3-915a-414b-bb2a-c583f934192a)

**Comment by yitzchak-ben-ezra-ecoplant** [comment]
@love-linger you're amazing...
I'm starting to be eager to contribute to this repo!!
