### ISSUE TITLE
[Feature] Syntax highlighting for TOML files

### ISSUE THREAD

**Issue by fgimian** [sourcegit-scm/sourcegit#365]
Hey there, amazing job on this application!

I noticed that TOML files (which are quite prominent in Rust and Python projects) don't have syntax highlighting. Any chance of adding support for them please?

Thanks
Fotis

**Comment by gadfly3173** [comment]
I think this need to add configuration from https://github.com/textmate/toml.tmbundle/blob/master/Syntaxes/TOML.tmLanguage into https://github.com/danipen/TextMateSharp .

**Comment by aikawayataro** [comment]
There also is https://github.com/tamasfe/taplo/blob/master/editors/vscode/toml.tmLanguage.json that is fresher and in a supported JSON format

**Comment by love-linger** [comment]
Here's how to add unsupported syntax highlighting in this program.

* create your `TextMateSharp` compatible language grammar under the `src/Resources/Grammars/` directory
* modify `src/Models/TextMateHelper.cs` file, find the constructor of `RegistryOptionsWrapper`, then add the filename of your grammar to the `extraGrammarFiles` array.
```csharp
public RegistryOptionsWrapper(ThemeName defaultTheme)
{
    _backend = new RegistryOptions(defaultTheme);
    _extraGrammars = new Dictionary<string, IRawGrammar>();

    string[] extraGrammarFiles = ["toml.json"]; // Add the filename of your grammar here
    foreach (var file in extraGrammarFiles)
    {
```
