### ISSUE TITLE
[Feature] Fallback font for CJK characters in file preview pane

### ISSUE THREAD

**Issue by ChiahongHong** [sourcegit-scm/sourcegit#366]
In the file preview pane, the default fallback font is set to `Microsoft YaHei` for Chineses characters because monospaced fonts often don't support CJK characters.

https://github.com/sourcegit-scm/sourcegit/blob/2e7d742851c5151216e5859fdb8c946ccab3c35e/src/Native/Windows.cs#L65-L69

Would it be possible to align the fallback font with the font selected under [Preference] -> [Default Font], or perhaps introduce a setting to specify a fallback monospaced font?

This request comes from the fact that `Microsoft YaHei`, while designed for Simplified Chinese, isn't well-suited for displaying Traditional Chinese characters. Characters with complex strokes or uncommon glyphs can appear distorted.

I would greatly appreciate your thoughts on this. Thank you for developing such an awesome Git GUI tool!

<img src="https://github.com/user-attachments/assets/7f2f82c1-aef5-4b84-8b6f-cac56ab9306d" height="450">

**Comment by love-linger** [comment]
I've pushed a commit that try to use the default font family that configured by user. But since the `Avalonia Framework` does not allow users to change the fallback settings dynamically, you need restart this app to get font fallback works.

**Comment by gadfly3173** [comment]
I found a simple way to make monospace fallback to DefaultFont (#369 ). I've tested this on my Deepin V23.

**Comment by love-linger** [comment]
I'm working on this feature too. The `fallback` feature has been done, but I found that `Avalonia` does not support localized font family names, for example: '微软正黑'. However, on Windows, `Avalonia.Skia.FontManagerImpl.GetInstalledFontFamilyNames()` return localized font names. 

I am reworking the implementation about font settings. Currently no PR about font settings will be merged.

**Comment by love-linger** [comment]
You can try from https://github.com/sourcegit-scm/sourcegit/actions/runs/10450595502 now.

**Comment by gadfly3173** [comment]
> You can try from https://github.com/sourcegit-scm/sourcegit/actions/runs/10450595502 now.


![image](https://github.com/user-attachments/assets/24a55df7-168d-45da-a68d-b1b07dcb7959)
```json
  "DefaultFont": "\u6587\u6CC9\u9A5B\u5FAE\u7C73\u9ED1",
  "MonospaceFont": "Cascadia Mono PL",
```
the font selector seems not right.

**Comment by love-linger** [comment]
It's a textbox instead of a combobox. Just like VSCode.

**Comment by love-linger** [comment]
The `FontManager.Current.SystemFonts` return localized font family name which not supported by Avalonia. Currently, user need input the family name manually.

BTW, the keys for fonts in preference.json are changed to these two:
```json
"DefaultFontFamily": "Microsoft YaHei UI",
"MonospaceFontFamily": "CodeNewRoman Nerd Font Mono",
```

**Comment by ChiahongHong** [comment]
Thanks to @love-linger and @gadfly3173 for your attention to this!

As @love-linger mentioned, it seems that the localized font name isn't supported. It appears to fall back to `Yu Gothic` (a Japanese font). However, since my Windows language is set to Traditional Chinese, I'm not sure why this happens.

When specifying the font name in English, it works perfectly fine!

![](https://github.com/user-attachments/assets/8efc654b-7336-46ee-b5b9-35b0f3cf4a27)

![](https://github.com/user-attachments/assets/6ac37680-96a6-4d0c-95e9-0817a1f78295)

**Comment by love-linger** [comment]
![image](https://github.com/user-attachments/assets/03fdad14-b16d-431c-9900-e07dea480af4)

You can simple using `Consolas` in `Monospace Font`. The app appends default font to it automatically.
```csharp
if (string.IsNullOrEmpty(monospaceFont))
{
    if (!string.IsNullOrEmpty(defaultFont))
        monospaceFont = $"fonts:SourceGit#JetBrains Mono,{defaultFont}";
}
else
{
    if (!string.IsNullOrEmpty(defaultFont) && !monospaceFont.Contains(defaultFont, StringComparison.Ordinal))
        monospaceFont = $"{monospaceFont},{defaultFont}";

    resDic.Add("Fonts.Monospace", new FontFamily(monospaceFont));
}
```
