### ISSUE TITLE
Is there any way to donate?

### ISSUE THREAD

**Issue by alangrainger** [sourcegit-scm/sourcegit#374]
I recently switched to using Linux, and SourceGit is by far the best replacement for [Fork](https://git-fork.com/) on Windows.

Is there any way I can donate to you? Github sponsoring, Patreon, Paypal, even Bitcoin?

Thank you for the wonderful tool! :)

**Comment by love-linger** [comment]
I'm very glad that you like this software. There are no plans to open donations currently. Maintaining this project and making it better is something I enjoy doing.

**Comment by alangrainger** [comment]
Understood, and thank you again for the great app. I will close the issue as it doesn't need to stay open, but it will be available for people who search in the future so they can also find the answer.

**Comment by hyunbinseo** [comment]
@love-linger It's been 2 years, any plans to receive donations? LOVE this app!

**Comment by love-linger** [comment]
@hyunbinseo Thanks. Still not planned.
