### ISSUE TITLE
Feature Request: MacOS - support configuring other terminals

### ISSUE THREAD

**Issue by yitzchak-ben-ezra-ecoplant** [sourcegit-scm/sourcegit#375]
Hi, thanks for the previous feature - it's awesome
I've cloned this repo and have it compiling and running
I might contribute in the future because git is my hobby

as for the request:
I'm using iTerm2 as my terminal, but when opening terminal in MacOS it always opens the default terminal

in order to allow it we need to be able to select the terminal in settings
then running this command:
```
builder.AppendLine("on run argv");
builder.AppendLine("    tell application \"iTerm2\"");
builder.AppendLine("        create window with default profile");
builder.AppendLine("        tell the current session of the current window");
builder.AppendLine($"            write text \"cd {dir}\"");
builder.AppendLine("        end tell");
builder.AppendLine("    end tell");
builder.AppendLine("end run");
```

for reference - this is the current command:
```
builder.AppendLine("on run argv");
builder.AppendLine("    tell application \"Terminal\"");
builder.AppendLine($"        do script \"cd {dir}\"");
builder.AppendLine("        activate");
builder.AppendLine("    end tell");
builder.AppendLine("end run");
```

Thanks!! this is the best git client - I'm going to spread it all over!!

**Comment by love-linger** [comment]
I'll consider how to add this feature

**Comment by yitzchak-ben-ezra-ecoplant** [comment]
I can help too
I saw in Linux you create multiple instances of Terminal (in _terminal variable) then you just use it...
maybe we can do the same

**Comment by yitzchak-ben-ezra-ecoplant** [comment]
but I' not familiar with configuration yet :)

**Comment by love-linger** [comment]
The reason of having a `FindTerminal` method in `Native.Linux` is that there are so many Linux Desktop Environments. And mostly, after users choose the DE for his/her Linux, they usually also like the the terminal app that come with this DE.

**Comment by love-linger** [comment]
BTW, try to use `iTerm2` if it is installed and fallbacks to system default Terminal is not a bad idea. You can create a PR for this first.

**Comment by yitzchak-ben-ezra-ecoplant** [comment]
ok thanks
