### ISSUE TITLE
Corners are rounded when window is maximized

### ISSUE THREAD

**Issue by aikawayataro** [sourcegit-scm/sourcegit#378]
When I maximize the Source Git window, the corners of the window are rounded. When I reach the upper right corner to close the window, I move the mouse pointer very close to the actual screen corner, and the click does not hit the close button.

Other applications that use a custom title bar (Firefox, Electron) will display fine, with rounded corners when not maximized and square corners when maximized.
I'm using KDE6, and when I disable rounded corners in my theme settings, Source Git is still rounded.

![image](https://github.com/user-attachments/assets/e42be598-aeee-4cc4-90e0-d7134cf4f060)
![image](https://github.com/user-attachments/assets/a09cf167-07d9-422e-9db2-b09d085b2aeb)
(Maximized window)

**Comment by love-linger** [comment]
Try commit c1c1e1f0c896b46f4112a5460b50a345ee903210

**Comment by love-linger** [comment]
Try again? 

f4f5ae7430 - ux: remove rounded corner when window is maximized using TemplateBinding (#378)

**Comment by aikawayataro** [comment]
Now it displays correctly, but clicking still doesn't hit the button, even though the button behaves as if it was clicked

For some reason GitHub doesn't like the video so I archived it 
[output.zip](https://github.com/user-attachments/files/16676217/output.zip)

**Comment by love-linger** [comment]
I can see nothing in your video 😅

https://github.com/user-attachments/assets/c915c552-48b0-4fab-8383-85cee3b70a29

**Comment by aikawayataro** [comment]
That was awkward :grin: for some reason it plays just fine for me
Hope re-encoding will help:

https://github.com/user-attachments/assets/24f8050e-a611-4027-b926-3753eb07efcc

**Comment by love-linger** [comment]
I reproduce this issue on Windows. It is very strange.
![image](https://github.com/user-attachments/assets/30dffdf0-2b1a-4ae7-8eeb-811d447a431c)

According to the event, it has been handled by Button

**Comment by love-linger** [comment]
This issue seems not blongs to this software and it has little impact. I'm not going into it.
