### ISSUE TITLE
Proposal to Add SourceGit to Git-SCM's GUI List

### ISSUE THREAD

**Issue by kushagra10025** [sourcegit-scm/sourcegit#38]
Hi,
I came across this wonderful project via the Avalonia Showcase. Am wondering if you guys plan to add it to [git-scm/gui-clients](https://git-scm.com/downloads/guis/)

If it is already planned, great. If not please kindly take it into your consideration, might highly boost the visibility of the Project.

Link :  [Add New GUI to git-scm.com](https://github.com/git/git-scm.com/blob/main/README.md#adding-new-gui)

Best,
Kushagra ✌️

**Comment by love-linger** [comment]
I'm so glad that you like this app. I thought about it at first, but I gave up. I am afraid that the project is far from satisfying the users.

**Comment by kushagra10025** [comment]
I'm finding it a lot intuitive to use and I can't vouch for other but to the people I've shared the project with all seem to like it for the Clean and Intuitive UI. I would say that as long as this is under development I'll be using it personally and would also highly recommend to my peers. Request you to kindly consider the proposal :)

**Comment by love-linger** [comment]
I'll consider this after the next release

**Comment by love-linger** [comment]
I've create a pr to git-scm.com. https://github.com/git/git-scm.com/pull/1841
