### ISSUE TITLE
indicate the commit hash in commit log as internal navigation URL

### ISSUE THREAD

**Issue by heartacker** [sourcegit-scm/sourcegit#382]
![image](https://github.com/user-attachments/assets/28fe0d97-8d25-4e82-9362-fe95b27642d1)

**Comment by love-linger** [comment]
If you are using current stable release of this app, you can add an issue tracker with follow settings:

![image](https://github.com/user-attachments/assets/5be178af-0395-4718-ba29-62e9b0a2f6c6)

And if you can build this app by yourself, you can simply add the issue tracker rule from the dropdown button

![image](https://github.com/user-attachments/assets/75520805-2d8c-4c24-a2e1-2225918181ed)

> [!NOTE]
> Remember replace the result URL with yours

**Comment by heartacker** [comment]
thank, and what I mean is that we could navigate to the commit list of sourcegit, not the webside

**Comment by love-linger** [comment]
> thank, and what I mean is that we could navigate to the commit list of sourcegit, not the webside

Yea, navigating commit inside this app is better than web links. And using issue tracker has several limitations such as the way it works is different with commit web links in `SHA` property.

I'll revert this commit and try to add the navigation links.

**Comment by love-linger** [comment]
![image](https://github.com/user-attachments/assets/5bdff246-85f3-4d63-a8ce-3856dd97030d)
