### ISSUE TITLE
Icon of rename diff seems strange

### ISSUE THREAD

**Issue by gadfly3173** [sourcegit-scm/sourcegit#384]
![image](https://github.com/user-attachments/assets/e7267831-26c5-4778-af02-66e520cb21ef)

**Comment by love-linger** [comment]
It's now depends on the monospace font you are using.

**Comment by love-linger** [comment]
What's the font you are using?

**Comment by gadfly3173** [comment]
> What's the font you are using?

Cascadia Code PL . I checked that Consolas/FreeMono also show this, maybe this icon is not in most monospace fonts?

**Comment by love-linger** [comment]
I've pushed a commit that using `JetBrains Mono` font for change status icon.

**Comment by gadfly3173** [comment]
> I've pushed a commit that using `JetBrains Mono` font for change status icon.

It works fine now.
