### ISSUE TITLE
[feature] small ux request

### ISSUE THREAD

**Issue by Jayllyz** [sourcegit-scm/sourcegit#388]
It's sometimes difficult to know which branch a commit is on (eg the first time you open a repo, you don't know which colors is which branch, etc.).

![image](https://github.com/user-attachments/assets/6e900466-a226-4930-9aee-3cca3be59c12)

Using git graph, if you move your cursor over a commit, you can quickly find out which branch it is.

for example :
![image](https://github.com/user-attachments/assets/54bcbe14-a2a9-4b46-82af-1ca38e71c396)

Even a small tooltip with the name of the branch could be enough

**Comment by love-linger** [comment]
I'm a little confused about the need to _**collect which branches a commit is contained in**_. 

Instead, this software focuses on _**whether a commit is merged by the current branch**_, since this is the branch we are working on.

**Comment by love-linger** [comment]
![image](https://github.com/user-attachments/assets/7723db21-5076-4eaf-870a-7725173318ed)

**Comment by Jayllyz** [comment]
Thanks a lot!
