### ISSUE TITLE
添加本地仓库，却一直报错“Repository does NOT exists any more”？可 sourcetree、gitg、tig 都能正常打开。。

### ISSUE THREAD

**Issue by wuxunfeng666** [sourcegit-scm/sourcegit#39]
![image](https://github.com/sourcegit-scm/sourcegit/assets/25447739/36261ae0-131a-42b8-abec-c4e31d6d9899)

**Comment by love-linger** [comment]
非常感谢您能使用SourceGit，这是一个功能缺失。我并未测试过与MSYS GIT的兼容性（当前支持的是官方的 [Git For Windows](https://git-scm.com/download/win) 版本）。看上去msys git返回的路径是unix like的路径，C# System.IO接口无法正确处理。后面我会尝试加入对MSYS GIT的支持。

**Comment by love-linger** [comment]
@wuxunfeng666 您能提供一下，您所使用git的版本及安装途径吗？非常感谢

**Comment by love-linger** [comment]
@wuxunfeng666 非常抱歉，我刚刚测试了SourceTree，它也是无法支持MSYS GIT的。能正常打开，可能它在使用内嵌的GIT+libgit2，或是它找到一个系统安装的GIT。你可以查看一下。对于内嵌的GIT，它的路径是`C:\Users\User\AppData\Local\Atlassian\SourceTree\git_local\bin\git.exe`。你可以该路径下的GIT指定为SourceGit使用的GIT路径。再次尝试
