### ISSUE TITLE
[Feature] - "Search Repository" improvements

### ISSUE THREAD

**Issue by wlazlomarek** [sourcegit-scm/sourcegit#391]
~~**Feature 1**: Automatically set the cursor focus on the "Search Repository" bar after a new tab is created. This would allow users to immediately type the desired repository after pressing (Ctrl + T) :)~~ Duplicated https://github.com/sourcegit-scm/sourcegit/issues/368#issue-2472559065

**Feature 2:** Once the desired repository is typed, users should be able to navigate through the results using the arrow keys and select a repository by pressing Enter.

Ps. Great app!

**Comment by love-linger** [comment]
I've pushed a commit for this feature. But the `Enter` key is hard-coded in the `TreeViewItem`, so currently this app use `Space` to open selected repository instead.

**Comment by wlazlomarek** [comment]
Thanks for the update :) I've checked and found a small issue while switching through repositories. When you type some repo part name like **test** I can't switch to **test_ini** repo in my example video. 

https://github.com/user-attachments/assets/bcebacd4-9c79-407d-a0cb-676542001090

**Comment by wlazlomarek** [comment]
Almost working. Right now, the down navigation works, but when I go back up, I can't select the first item (with index 0) from filtered list.

**Comment by love-linger** [comment]
Please try again. The original `TreeView` has many limitations such as virtualization, navigation with invisible node, and many hard-coded hotkey bindings, etc. I've totally rewrite the welcome page using a custom tree view.

**Comment by love-linger** [comment]
Now, you can use `Enter` key to open repository and `Ctrl/Command + F` to back to search box.

**Comment by wlazlomarek** [comment]
Yep, everything is working fine! Good job and thanks for update!
