### ISSUE TITLE
The current branch highlight in the graph

### ISSUE THREAD

**Issue by minzdrav** [sourcegit-scm/sourcegit#395]
Hi source git team
Nice work! I like your client.

In the graph, it's hard to find the current branch. Is it possible to highlight it somehow? Bigger font, border, or anything else? 
![image](https://github.com/user-attachments/assets/03d55ea3-15ea-49e6-a8f5-a152cf483444)

P.S. The branch on the screenshot looks better than on the actual screen because github scaled the image :)

**Comment by love-linger** [comment]
There're two ways to locate current branch HEAD in commit histories.

* Click the `Navigate to HEAD` button on the right of toolbar (just behind the name of current branch)
* Select current branch from local branch tree

BTW, you can toggle the `Only use monospace font in text editor` option from Preference panel. It makes the HEAD commit more clear.

**Comment by minzdrav** [comment]
"Navigate to HEAD" - wow, so cool.
But it should be more obvious which branch is selected in the graph. It would be awesome if you could improve it :)

**Comment by Shimoon** [comment]
Git Extension does have pretty nice commits graph visual guides that could be taken as inspiration maybe
![gitextension_graph](https://github.com/user-attachments/assets/218f69ac-f434-45a6-b231-de6b7cc507e6)

**Comment by love-linger** [comment]
![image](https://github.com/user-attachments/assets/3c9da477-adff-48e6-beb8-02d60e92fb40)

**Comment by minzdrav** [comment]
> Git Extension does have pretty nice commits graph visual guides that could be taken as inspiration maybe ![gitextension_graph](https://private-user-images.githubusercontent.com/17713307/360722143-218f69ac-f434-45a6-b231-de6b7cc507e6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzOTU1NjQsIm5iZiI6MTcyNDM5NTI2NCwicGF0aCI6Ii8xNzcxMzMwNy8zNjA3MjIxNDMtMjE4ZjY5YWMtZjQzNC00NWE2LWIyMzEtZGU2YjdjYzUwN2U2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDA2NDEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkZGY0OGI2MjAzN2JhNzcwZmYxZGQxMDQ0NDk4ZTFjMmNlMWNkOGE3ZjAxZWMwYTIyN2RmMjRkMzI1N2QyNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1oi30xGxye4bJP1iZf0bSfR2Hv2iOm72n-b_leZ4pyw) Also, seems quite similar to #388

Git Extensions also uses a bold font for the current branch.
![image](https://github.com/user-attachments/assets/8025751c-9395-4cf0-a106-91c305ea8fbc)

**Comment by love-linger** [comment]
SourceGit also use bold style current branch name and HEAD commit subject, you can turn on the `Only use monospace in text editor` option (bold style of monospaced font is a little bit hard to tell)

**Comment by minzdrav** [comment]
> SourceGit also use bold style current branch name and HEAD commit subject, you can turn on the `Only use monospace in text editor` option (bold style of monospaced font is a little bit hard to tell)

Yes, I know. It's just not enough. It needs to be a bit bolder or bigger font size or something like that :)
It's not just me, I also showed the UI to my wife before creating the issues. She also can't tell which one is the current.

**Comment by love-linger** [comment]
> Yes, I know. It's just not enough. It needs to be a bit bolder or bigger font size or something like that :)
> It's not just me, I also showed the UI to my wife before creating the issues. She also can't tell which one is the current.

I know the reason that why it is still hard to tell when you toggle the `Only use monospace in text editor` option. It is still a font issue. I've pushed commit that try to fix it.

![image](https://github.com/user-attachments/assets/adfa9baf-b21a-487b-bb48-e7a4cf2b84d8)

**Comment by minzdrav** [comment]
Thank you! Looks much better! I hope I'll be able to try it myself soon :)

**Comment by love-linger** [comment]
you can download the latest build from https://github.com/sourcegit-scm/sourcegit/actions/runs/10523555062

**Comment by minzdrav** [comment]
Cool! Yes, it's better. But I think it's possible to do it a bit better. Maybe you can change the checkmark background color? Maybe blue color like you doing with selected elements?
Thank you!
![image](https://github.com/user-attachments/assets/7b8425d9-72b0-4a7d-845d-9391a7032510)

**Comment by heartacker** [comment]
>It's not just me, I also showed the UI to my wife before creating the issues. She also can't tell which one is the current.

me too

**Comment by love-linger** [comment]
> Cool! Yes, it's better. But I think it's possible to do it a bit better. Maybe you can change the checkmark background color? Maybe blue color like you doing with selected elements? Or green? Thank you! ![image](https://private-user-images.githubusercontent.com/1764392/360892416-7b8425d9-72b0-4a7d-845d-9391a7032510.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MDk1MTEsIm5iZiI6MTcyNDQwOTIxMSwicGF0aCI6Ii8xNzY0MzkyLzM2MDg5MjQxNi03Yjg0MjVkOS03MmIwLTRhN2QtODQ1ZC05MzkxYTcwMzI1MTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjNUMTAzMzMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWNmNmI2OWMyYmVlMWNlNmUwZDAxYTI4YWFmYzQwNzZhMzBiZDg1Zjc5NTQ4OGYwYTdiZGI2N2NmMGJhNDlmMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2lnVR8HSH5X1MUrxGczJyKxFYUFEIZFeoRySkGYbW8Q)

It's even more invisible than the one next to it.
![image](https://github.com/user-attachments/assets/8b12c382-6acf-4016-a4b2-c77bce906cec)

**Comment by minzdrav** [comment]
> > Cool! Yes, it's better. But I think it's possible to do it a bit better. Maybe you can change the checkmark background color? Maybe blue color like you doing with selected elements? Or green? Thank you! ![image](https://private-user-images.githubusercontent.com/1764392/360892416-7b8425d9-72b0-4a7d-845d-9391a7032510.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MDk1MTEsIm5iZiI6MTcyNDQwOTIxMSwicGF0aCI6Ii8xNzY0MzkyLzM2MDg5MjQxNi03Yjg0MjVkOS03MmIwLTRhN2QtODQ1ZC05MzkxYTcwMzI1MTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjNUMTAzMzMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWNmNmI2OWMyYmVlMWNlNmUwZDAxYTI4YWFmYzQwNzZhMzBiZDg1Zjc5NTQ4OGYwYTdiZGI2N2NmMGJhNDlmMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2lnVR8HSH5X1MUrxGczJyKxFYUFEIZFeoRySkGYbW8Q)
> 
> It's even more invisible than the one next to it. ![image](https://private-user-images.githubusercontent.com/4075673/360899326-8b12c382-6acf-4016-a4b2-c77bce906cec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MTA1MTQsIm5iZiI6MTcyNDQxMDIxNCwicGF0aCI6Ii80MDc1NjczLzM2MDg5OTMyNi04YjEyYzM4Mi02YWNmLTQwMTYtYTRiMi1jNzdiY2U5MDZjZWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjNUMTA1MDE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjIxZjIzYmI2NmZiNDdiY2ZjNmIyYmI1YjllZDk0ZmM5NWRkMmE5NDg2ZjQxMzUxMTIwZWIyNDYwYTExNjIwMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.DfFyfmjIY25bMjtfCNKNvtaOZtU3xzvtSPVNSIJ09fU)

I mean background color, not a checkmark color. Blue background with a white icon. Or a green background with a white icon. 
Can you try both variants? Sorry for bothering you.

**Comment by minzdrav** [comment]
![image](https://github.com/user-attachments/assets/665211af-a47b-44b3-9553-6e1c419658da)
I did it in ms paint 😂

**Comment by love-linger** [comment]
![image](https://github.com/user-attachments/assets/7a6b731c-5a0b-4c0b-af10-a69baf3c3a06)

**Comment by minzdrav** [comment]
Yes, I think you are in the right direction. It can be an icon background color or a branch name background color. 
The color is not ideal for your color scheme. If you can play with it a bit more, it will be ideal.

**Comment by minzdrav** [comment]
I'm using this tool when I need additional color: https://coolors.co/

**Comment by love-linger** [comment]
Dark Theme

![image](https://github.com/user-attachments/assets/92d8fb43-12d2-48ee-8dca-67e0eb6e8359)

Light Theme
![image](https://github.com/user-attachments/assets/053185cf-0e8f-44f7-b14f-e3a3ae7be404)

**Comment by minzdrav** [comment]
@love-linger amazing! I love the dark one!

**Comment by minzdrav** [comment]
@love-linger 
![image](https://github.com/user-attachments/assets/82dd1780-b4d4-49a2-8c9b-b8f2f0d07f12)
please try a white font color for the white theme. I think it looks better.

**Comment by love-linger** [comment]
i'm not good at choosing colors, and I'm also not satisfied with the color scheme with the light theme...

It's a little difficult for me to find a suitable color. This needs to meet some conditions

* it must be very different from existed colors, such as tags and normal branches
* it should not use common accent colors

it would be nice if someone can help

**Comment by Shimoon** [comment]
> * it must be very different from existed colors, such as tags and normal branches
> * it should not use common accent colors

Maybe plain black could be enough for the light theme ? As it would be consistent with the white background that work rather well with the dark theme.
It's pretty simple but would stay unique in the current UI guidelines.

**Comment by minzdrav** [comment]
@love-linger please try inverted color from the dark theme - #0c0e21 with font color.
![image](https://github.com/user-attachments/assets/63db82b8-ebe9-4c49-a8da-abf101595809)

**Comment by love-linger** [comment]
thank you very much. it looks nice. I will try it later

**Comment by minzdrav** [comment]
![image1Win](https://github.com/user-attachments/assets/2669bd49-b007-4df4-bd96-db7e01810294)
Look how Fork did it. They are using branch color for the branch name background and check mark for the current branch.

**Comment by love-linger** [comment]
I do not want to make the UI/UX so complex.

<img width="571" alt="image" src="https://github.com/user-attachments/assets/53fdf85f-138a-49c2-8388-15ab27e41981">

**Comment by minzdrav** [comment]
Love it, it's much better!

**Comment by love-linger** [comment]
So, I'm going to close this issue as complete.

**Comment by minzdrav** [comment]
Yep! Please push release to winget :)

**Comment by love-linger** [comment]
The next version will be released next Monday, but WinGet users may need to wait one more day. This is because the PR submitted to WinGet is usually merged after one day.
