### ISSUE TITLE
bug: fixed width in fetch/pull popups 

### ISSUE THREAD

**Issue by JeanFranz73** [sourcegit-scm/sourcegit#396]
The fixed width in the popup almost completely remove the local changes' last option in pt-BR. Is there a way to make a "min-width" and then the popup expands when needed? Or perhaps a breakline when the option does not fit

Tested on Ubuntu 22.04

![image](https://github.com/user-attachments/assets/ce4916ba-c8f1-4ffb-91f6-83ebf1604b57)

![image](https://github.com/user-attachments/assets/d99f1814-ecbd-4533-b7f7-a094591a9aa2)

**Comment by love-linger** [comment]
![image](https://github.com/user-attachments/assets/f6508238-10ae-4c8c-aed1-cfe51c076e42)
