### ISSUE TITLE
Some more ux suggestions

### ISSUE THREAD

**Issue by aikawayataro** [sourcegit-scm/sourcegit#398]
Follow-up to #391

* Press ESC to clear search bar and clear focus on it (behavior followed by many apps)

Things to improve:

* Don't focus on the search bar on the home screen after the app just started. (Optional, but I find focused from start search bar a bit attention-grabber)
* Add `/` hotkey for search (Optional)
* When you click the title bar or create bar with the title bar button, the CTRL + F hotkey does not work
* It looks like all empty tabs is the single object - if I enter some text on one of them and open the repository, the tab created after that will show my previous input in the search bar. The same thing happens with just a few empty tabs - they look "synced". Somewhat confusing

**Comment by love-linger** [comment]
> Don't focus on the search bar on the home screen after the app just started. (Optional, but I find focused from start search bar a bit attention-grabber)

Em... I add this feature just because someone wants it works in this way……

> Add `/` hotkey for search (Optional)

Instead we already has a hotkey `Ctrl/Command + F`

> When you click the title bar or create bar with the title bar button, the CTRL + F hotkey does not work

This is a bug

> It looks like all empty tabs is the single object - if I enter some text on one of them and open the repository, the tab created after that will show my previous input in the search bar. The same thing happens with just a few empty tabs - they look "synced". Somewhat confusing

Yes. This page modifies the repository tree that will save to the preference.json. The data must look `synced`.

**Comment by aikawayataro** [comment]
> Em... I add this feature just because someone wants it works in this way……

No, I mean I'd like it to work like this: you open the app - no focus, you open a new tab - focus

> Instead we already has a hotkey Ctrl/Command + F

That's true, but `/` is also a well-known search hotkey

> Yes. This page modifies the repository tree that will save to the preference.json. The data must look synced.

It's very confusing and requires to clean up the search query in a new tab after you open the repository, also you can't keep different queries in different tabs. I think it's better to assign search query to tab and restore it when active tab is changed, this way you can keep synced repository view while keeping query in its tab

**Comment by love-linger** [comment]
> No, I mean I'd like it to work like this: you open the app - no focus, you open a new tab - focus

So, at the first time we open the Welcome page, we do not want to search, but if it is not opened at the first time, we want to search?

BTW, removing the highlighted border can make it better?

> That's true, but `/` is also a well-known search hotkey

I think having `Ctrl/Command + F` is enough for this app

> It's very confusing and requires to clean up the search query in a new tab after you open the repository, also you can't keep different queries in different tabs. I think it's better to assign search query to tab and restore it when active tab is changed, this way you can keep synced repository view while keeping query in its tab

It's hard and dangerous to make it multi-instanced. For example, you need notify all instance to re-calculate visible tree with searching filter if you have just renamed then display name of a repository.

**Comment by aikawayataro** [comment]
> It's hard and dangerous to make it multi-instanced. For example, you need notify all instance to re-calculate visible tree with searching filter if you have just renamed the display name of a repository.

No, not multiple instances! Keep single instance, just restore search query after active tab is changed.

> So, at the first time we open the Welcome page, we do not want to search, but if it is not opened at the first time, we want to search?

Not what I want to say. I would see it like this: when I start the application (empty window) the focus is not set. But when I open a new tab or use the new tab hotkey, the focus is set.
Now I'm understanding that it could just be more confusing :grin:  If you can make border less "catchy" it would be better I think.

**Comment by aikawayataro** [comment]
Yes, it's better with no border at all
Looks perfect in my opinion

**Comment by love-linger** [comment]
> No, not multiple instances! Keep single instance, just restore search query after active tab is changed.

If the ViewModel of Welcome page is singleton, there's no way to store the multiple search filter contents (the view will be recreated when its DataContext changed). And the view will not changed when you switch between two Welcome page tab, because the DataContext of this view is never changed.

If the ViewModel of Welcome page is multi-instanced, the view will still look `synced`. It is because the tree structure and some of it's property (such as `IsExpanded`) is saved into the `preference.json` file. For example, the `sync` action will take place in the follow conditions:

* a new repository/group is added into the tree
* a repository/group is removed from the tree
* toggle a node's `IsExpanded` property
* rename a node
* move a node to anther group

**Comment by aikawayataro** [comment]
Thank you for your thorough response!
I'm not really familiar with Avalonia's MVVM, but I'll try to dig into it, maybe will come up with a working concept
