### ISSUE TITLE
git历史显示不完整

### ISSUE THREAD

**Issue by whgfu** [sourcegit-scm/sourcegit#4]
我对一个仓库 同事使用 sourcegit 与 sourcetree 进行操作对比，发现了一个 问题

使用Git flow 操作 创建 hotfix ，然后 完成 hotfix 并合并的 develop 分支 ，同时加注 TAG，删除hotfix分支。。

两个软件 tag 都正常，删除hotfix分支都正常

但是 从 Git 历史中 两个软件显示效果不同
SourceTree 可以完整显示 hotfix 相关的历史记录。
但是**Sourcegit  却不能显示 hotfix相关的历史记录。**

不论这个 gitflow 是从 sourcetree操作还是 sourcegit操作，都是一样。

我所使用的版本，是  v6.0版本

**Comment by whgfu** [comment]
GitServer => GitLab
GitLab中的 git 历史记录，也是正常的。

**Comment by sourcegit-scm** [comment]
可否发一个对比的截图？或是确保分支未被启用filter（就是分支名后面的过滤图标）
