### ISSUE TITLE
about yourself

### ISSUE THREAD

**Issue by heartacker** [sourcegit-scm/sourcegit#40]
please add about yourself here， your self link

![image](https://github.com/sourcegit-scm/sourcegit/assets/1876302/ed60f3ee-1525-47b6-b644-15ee9df9836e)

**Comment by love-linger** [comment]
重新设计了一下About界面显示的内容
![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/6c9749c5-4b1f-4c7b-9ede-6729f9c1dc19)
