### ISSUE TITLE
Commit Message not fully visible

### ISSUE THREAD

**Issue by NilsPvR** [sourcegit-scm/sourcegit#400]
I am not fully sure why this is happening, but the description for the commit is not visible in the GUI.

![grafik](https://github.com/user-attachments/assets/5316fb96-9914-483f-8f47-7c4668e20f32)

See the commit on github e9a269f which does have the description.

**Comment by love-linger** [comment]
I can NOT re-produce this issue. It's find on my PC.
![image](https://github.com/user-attachments/assets/4d78527a-652f-4dd4-8a51-516b16b6bd9c)

**Comment by NilsPvR** [comment]
I does indeed seem to be quite inconsistent on when this is happening. I'll try to figure out why or at least when this is happening tomorrow.

**Comment by ozmium** [comment]
I experience this problem as well. It happens on about 15% of the commits in this GitHub repository. SourceGit truncates some of the final part of the Git commit message.

![SourceGit truncates some of the Git commit message, 2024-08-26 at 13:46](https://github.com/user-attachments/assets/edb08b51-56c2-45fe-b0fa-f8f487ceac89)

![The expected full mesage, 2024-08-26 at 13:48](https://github.com/user-attachments/assets/a49005f4-6006-4677-9c3d-3ccbb1298c66)

Tested on SourceGit version 8.27.

**Comment by love-linger** [comment]
![image](https://github.com/user-attachments/assets/d6a2cb30-c2a3-4258-ba38-fea949f7936e)

I still can not reproduce this issue. I've switch commits more than 20+ times.

**Comment by love-linger** [comment]
Could you please remove all font settings and theme overrides, the try it again?

**Comment by NilsPvR** [comment]
Haven't built from dev myself yet, however I noticed that changing to "Only use monospace font in text editor" has an impact on the bug. But still don't see the pattern.
![grafik](https://github.com/user-attachments/assets/9ae5ae1d-dd65-4f85-b0a0-575081f3269f)
![grafik](https://github.com/user-attachments/assets/58fd81fa-0a51-4f76-acbc-7ec4ff037ec5)

**Comment by NilsPvR** [comment]
Also different fonts behave differently

**Comment by love-linger** [comment]
@NilsPvR please upgrade your sourcecode to latest. The font settings and the content message presenter has been totally rewrited.

**Comment by NilsPvR** [comment]
> @NilsPvR please upgrade your sourcecode to latest. The font settings and the content message presenter has been totally rewrited.

My bad I indeed had an outdated version. I just built from the latest dev commit (959805d63c3) and the issue still exists. Seems to be strongly related to the font tho. The only case where the commit message was off was when using "JetBrains Mono" as monospace font with 13 pt. 
All other fonts and sizes I tested so far show the commit message correctly.

**Comment by love-linger** [comment]
Can you share your appearance settings?

**Comment by NilsPvR** [comment]
With these settings the message disappears. I have installed the JetBrains Mono font locally. 
![grafik](https://github.com/user-attachments/assets/d62b2e8e-babb-4c3e-8c6d-4d8ca71116a1)

**Comment by love-linger** [comment]
You can clear the settings for `Monospace Font`, it will using built-in `JetBrains Mono` font instead

**Comment by NilsPvR** [comment]
Alright, but that doesn't change the behaviour for the commit message :/

**Comment by love-linger** [comment]
It's so strange. The only difference between us is that I'm using Windows 11……
![image](https://github.com/user-attachments/assets/510711f8-baa7-402d-ae02-effbbe136e60)

**Comment by love-linger** [comment]
It seems that the text layout commit message in your screenshot do not works correctly. The result of `Measure` shows that it is a 3-lines text, but when drawing content, the first line breaks at the wrong text position

**Comment by love-linger** [comment]
I've pushed another commit that forces using `Stretch` for `HorizontalAlignment` property of `SelectedTextBlock`

**Comment by NilsPvR** [comment]
That's indeed super odd. Don't get how this behaves different depending on the OS. But what you described did indeed seem to be the issue.

The commit did fix the issue 🥳. Just tested with the latest commit and same settings, now it's properly displayed and fully visible.

**Comment by love-linger** [comment]
So, I'm going to close this issue as complete.
