### ISSUE TITLE
Change user avatar?

### ISSUE THREAD

**Issue by ScruffyDerHausmeister** [sourcegit-scm/sourcegit#401]
Hello guys,

how to change the (git)user avatar? There is a folder called avatars has it "the power"?

**Comment by love-linger** [comment]
The user avatar are fetched from `gravatar.com`. If you mean refetch it after you hava changed your avatar from `gravatar.com`, you can use right click to open the context menu of avatar control in commit detail panel. There's a `Refresh` option to do that.

**Comment by ScruffyDerHausmeister** [comment]
So, if I do not have an avatar on gravatar.com it's not possible?

**Comment by love-linger** [comment]
it also supports github user avatar when your email is provided by github

**Comment by ScruffyDerHausmeister** [comment]
It is not also. :-) Would be nice to leave a jpeg file in the avatar folder named as the user email or something.

**Comment by love-linger** [comment]
you can do that. but the file name is md5 hash of your email address with lower case. you can go app data dir via main menu then you'll find a folder named avatars. put you avatar image there, then restart this app.

**Comment by ScruffyDerHausmeister** [comment]
Sorry, didn't work out. No change.

**Comment by love-linger** [comment]
* your image file must named after `to_lower(MD5(to_lower(${EMIAL}))`, no extensions
* move this file to the app data dir. You can go there via main menu of this app

**Comment by ScruffyDerHausmeister** [comment]
![image](https://github.com/user-attachments/assets/53e296af-b176-4cc0-aae0-e1eeec9f7ebc)
Sorry, still no luck. Also not if I move the file to the avatars dir.

**Comment by love-linger** [comment]
You should remove the `.jpg` extension of your avatar image. Then put it into the avatars folder

**Comment by ScruffyDerHausmeister** [comment]
Yes! This does the trick! Thank you very much.
