### ISSUE TITLE
[i18n | WIP] French locale

### ISSUE THREAD

**Issue by UchiTesting** [sourcegit-scm/sourcegit#402]
Hello,
I am currently working on a French locale for the software in my free time. 
As it is a time consuming process (and I do not necessarily put all my free time in it neither), I was wondering if I should wait for it to reach a certain amount of completion or I could send it in batches.

For now I am aiming my efforts on the 1st level items without having any repo opened yet.

I still need to translate the preferences and keyboard shortcut to finish that 1st step.

Kind Regards

**Comment by love-linger** [comment]
First of all, thank you very much for taking the time to help this project become better.

> I was wondering if I should wait for it to reach a certain amount of completion or I could send it in batches.

As long as your translation have used `en_US` as fallback locale in this way:

```xml
<ResourceDictionary.MergedDictionaries>
  <ResourceInclude Source="avares://SourceGit/Resources/Locales/en_US.axaml"/>
</ResourceDictionary.MergedDictionaries>
```

you can send you PR to this project anytime.

**Comment by UchiTesting** [comment]
Thanks for the answer.
It was indeed missing.
I just made the change.

I shall rather go in batches.
I will finish preferences and keyboard shortcut for this week-end and I'll pursue likely with the main window when a repo is opened for the next batch.

**Comment by UchiTesting** [comment]
PR #405
