### ISSUE TITLE
[ENHANCEMENT / FEATURE] - File history design

### ISSUE THREAD

**Issue by Shimoon** [sourcegit-scm/sourcegit#403]
# Problems
The `File History` view does not really fill up its mission, and so for two main reasons:
1. The viewed code is the actual diff of the selected commit, not the state of the whole file at this point in time.
	- *This could be fixed by increasing the context line amount to its maximum but it doesn't really make sense for really big files, especially if the user need to do it by hand every time.*
2. The commit list (left side) only show a linear set of commits that doesn't really represent the way the graph behind actually works. For example, if the selected file has been modified in multiple branches (merged or not) or which change did happen in which branch. Also, being able to track down a file's history in multiple branches simultaneously is rather a good thing!

Some things doesn't really make sense either in this view, for instance:
- Since the `Changes` tab is also present in this view, the diff of the selected commit can be seen twice which is not really useful.
- The `Files` tab is also present and, to be honest, doesn't really belong here anyway since this view is focused on the history of one particular file. Moreover, this tab can be accessed through the main window which is completelly enough for what it does.

# Proposal
What I propose is to revamp this view by doing the following:
- Instead of the current commit list (left side), a DAG that would only show all the commits that contains a change of the selected file, and so by branches.
- Instead of the current main diff pane, the state of the whole file (without any diff) at this point in time (selected commit).
- Removing the `Files` tab that clutter the UI without brining much useful feature for the history task.
- Keeping the `Information` and `Changes` tabs in order to keep track of whats going on in the selected commit (commit's infos and/or which file·s are involved and the actual diff for each ones of them if this need to be checked).

# Mockups
Here is some mockups to better illustrate the idea:
*Information view*
![sourcegit_file_history_info](https://github.com/user-attachments/assets/9f6aa314-eb4f-4e55-9bf6-6293cb147828)

*Changes view*
![sourcegit_file_history_changes](https://github.com/user-attachments/assets/a0f4a979-91da-407a-a51f-c5d2460fbdd8)

Thanks a lot for this awesome tool! ;)

**Comment by love-linger** [comment]
I've pushed a commit that rewrites the file histories page. Now it only focus on the selected file, and if you want to see other changes you can click the commit SHA textblock - it will select this commit in main window if this repo is opened.

<img width="1284" alt="image" src="https://github.com/user-attachments/assets/eaed0794-5262-401c-a210-c1e0d2b9148f">

**Comment by love-linger** [comment]
One more thing, the file histories page shows the commits that related with selected file in **current branch** and it always end up with the revision of `HEAD`. 

It's very important.

**Comment by love-linger** [comment]
And if you want to see all commits that related to some file, you should using `Search Commit`, for example:
<img width="947" alt="image" src="https://github.com/user-attachments/assets/e2bf4e85-1de8-42e7-9fd0-da5c1ce75aba">

> [!NOTE]
> If you want to know which branches or tags that contains selected commit，you can click the `Check refs that contains this commit` button.
<img width="709" alt="image" src="https://github.com/user-attachments/assets/bf215c8b-9173-4ed6-83bc-463b3944d013">

**Comment by Shimoon** [comment]
It is much better already! Thank you! 😃

> One more thing, the file histories page shows the commits that related with selected file in **current branch** and it always end up with the revision of `HEAD`.
> 
> It's very important. Only in this way can we know the reasons for the content of this file in the current branch from nothing to existence and then to the current content. Other modifications related to this file that have not been merged into the current branch will not mislead our judgment

Is there a practical reason for not displaying the whole file history (all branches included) at the same time?
To me, while I can understand the decision of limiting the history to the current branch, this can sometimes lead to more complexity.
For instance, if I'm working on some changes in a particular file and I want to check for some past modifications but I don't know either the commit message, the SHA, who did it and the actual branch where the modification did happen, I would have to:
1. stach my WIP (if I don't work with worktrees)
2. checkout a branch where I think the modification could have happened
3. see if the modification I am looking for is there, if not...
4. checkout another branch then search through its history

This is quite a lot of steps just for looking at one modification I think.
I actually do find that a DAG would be a way better tool for this task. Plus, the branch display could be set with dropdown filtering options like so:
- Filtering:
   - `All` *(see all the branches)*
   - `Current branch` *(only see the current branch, could be the default setting)*
   - `Branch selection` *(select a branch to view)*

This would be extremely helpful to have the ability to track down if a change in the current file is actually happening in another branch then acting accordingly to prevent future conflicts or maybe wasting time developping similar feature in multiple branches simply because one didn't know that was already happening elsewhere.

**Comment by love-linger** [comment]
there is way to collect all the commit that related to some file. You can do it from `Search Commit` panel. Please read my comment above https://github.com/sourcegit-scm/sourcegit/issues/403#issuecomment-2308082486

**Comment by love-linger** [comment]
> For instance, if I'm working on some changes in a particular file and I want to check for some past modifications but I don't know either the commit message, the SHA, who did it and the actual branch where the modification did happen, I would have to:

If this modification comes from some other branches but has been merge into current branch (the file in the current branch has this modification), the file history can handle this commit.

**Comment by love-linger** [comment]
BTW, `Blame` is anthor better way to do that.

<img width="1392" alt="image" src="https://github.com/user-attachments/assets/0e0b08ca-43fb-46b8-8744-2a6cfd5c52b0">

**Comment by Shimoon** [comment]
Fair enough, the way you changed the `File History` view is already way better than before! Tanks a lot for that!

When testing your modifications, I do have one last comment on this: the default `Changes` tab context lines amount is currently set way to high.
In the case of a diff, I think it's better to keep it low/at the minimum by default an let the user increase it if needed. Since this view start at the very top of the file, high number of contextual lines can be inconvenient if the modifications happen at the middle or at the end of it (especially on really long files), it wont directly shows up to the user.
What's your thought on this?

**Comment by love-linger** [comment]
> In the case of a diff, I think it's better to keep it low/at the minimum by default and let the user increase it if needed. Since this view start at the very top of the file, high number of contextual lines can be inconvenient if the modifications happen at the middle or at the end of it (especially on really long files), it wont directly shows up to the user.
What's your thought on this?

It's saved in `preference.json` and available for all the text diff viewer. I've pushed a new commit that do not store this value in `preference.json`. It's now an runtime value and always starts with git default value - `4` and the view will keep the current value you are using until it is destoried.

**Comment by Shimoon** [comment]
Awesome! This is working greate, thanks!
