### ISSUE TITLE
Feature Request: Add Option to Squash Selected Contiguous Commits

### ISSUE THREAD

**Issue by thomaschampagne** [sourcegit-scm/sourcegit#408]
Hi there!

First of all, I want to express my appreciation for the incredible work you've done with this project! I've been searching for a well-designed, open-source Git client across Windows, macOS, and Linux for years. This tool is a breath of fresh air compared to others like SmartGit, Sublime Merge, SourceTree, LazyGit, GitHub Desktop, Gitkraken, ...

I was wondering if there's any plan to add an option to squash selected contiguous commits via a right-click menu? This feature is available in several other clients like SmartGit, GitHub Desktop, LazyGit, and Fork (if I recall correctly).

**Example**:

Here's a quick example of the usage from GitHub Desktop:

![Animation](https://github.com/user-attachments/assets/8605c426-3acb-4591-91ab-e010fb8d1524)

This feature would be incredibly useful for streamlining commit history and making the tool even more powerful.

Thanks again for your amazing work, and I look forward to hearing your thoughts on this feature request!

Best regards,  

Thomas

**Comment by love-linger** [comment]
There are several ways to do that.

* You can use `Interactive Rebase` context menu item of selected commit. For example:
<img width="1192" alt="image" src="https://github.com/user-attachments/assets/b9ae5f57-3537-4bff-8cd9-78d3eed31d02">
* You can use `Squash` context menu item of commit if the target commits are starts with HEAD.
* You can use `Reset` context menu item of the selected commit with soft mode. The re-commit the contents

**Comment by love-linger** [comment]
BTW, you can enable `Amend` option while committing if you want amend your HEAD commit

**Comment by thomaschampagne** [comment]
@love-linger Thanks for your response. I had tested interactive rebase before posting this issue :).

My main concern is actually to find a way to quickly squash multiple consecutive commits without the need to manually select each one or figure out the right parent commit to start an interactive rebase for this purpose. The current method requires squashing manually each commit individually except for the last one which is the direct child of parent commit selected for interactive rebase (the one we have to figure out).

The feature can essentially be summed up as: "A convenient way to squash/fixup a large selection of commits."

Thanks again for your amazing work !

Thomas

**Comment by love-linger** [comment]
But usually, the historical commit view is very complex, such as: 
<img width="741" alt="截屏2024-08-25 20 45 36" src="https://github.com/user-attachments/assets/a822d34b-0d97-4318-b212-131c5d5d8999">
it mixes the commits both in current branch and other branches. It need more options to select the commits you want to squash via `Ctrl+Click`.

**Comment by love-linger** [comment]
I'd like add a context menu item - `Squash Commits Since This Into Parent`, for the commit 
that meets the following conditions:

* Contains in current branch
* Not the current HEAD commit

**Comment by love-linger** [comment]
<img width="471" alt="截屏2024-08-25 21 46 05" src="https://github.com/user-attachments/assets/dd31c633-fd1e-47ff-b0e8-bd440e812214">

You can try it from https://github.com/sourcegit-scm/sourcegit/actions/runs/10547463901

**Comment by thomaschampagne** [comment]
I tested ! It's a nice quick win !! THANKS !!!

About formulation what about:

- "Squash child commits into this one" ?
- "Squash child commits into to here"?

Adding "child" word helps to refer to _"Contains in current branch"_  & _"Not the current HEAD commit"_ IMO.

To thanks you, I can provide you a _fr_FR.axaml_ file if you want (I seen that french translations are missing, and I'm french)

Thanks again for your work !

**Comment by love-linger** [comment]
thanks very much. 

there is already a French translation in 'develop' branch.

**Comment by thomaschampagne** [comment]
> there is already a French translation in 'develop' branch.

Do you need a review?

**Comment by love-linger** [comment]
I think they have done this job. See #405.

**Comment by thomaschampagne** [comment]
> I think they have done this job. See #405.

It's not completely translated. Many values remains in full english. I will give a look ;)
