### ISSUE TITLE
对于任何git的操作，请将git 命令附带上，无论是直接的写出来，还是tooltip

### ISSUE THREAD

**Issue by heartacker** [sourcegit-scm/sourcegit#41]
![image](https://github.com/sourcegit-scm/sourcegit/assets/1876302/3748766b-af55-4e4c-993c-e7491c796433)

英文指令和中文翻译，有时候意思差别很大，有经验的人都可能一下子难以分辨。
新手更是云里雾里

**Comment by love-linger** [comment]
这里的翻译多数是参考了SourceTree。确实需要加入原始的命令进行区分

**Comment by ZCShou** [comment]
那不如直接集成一个 log 的 panel（要是再能附带 Terminal 功能那就更完美了），可以直接查看所有 SourceGit 中所有 UI 操作执行的详细命令

**Comment by heartacker** [comment]
> 那不如直接集成一个 log 的 panel（要是再能附带 Terminal 功能那就更完美了），可以直接查看所有 SourceGit 中所有 UI 操作执行的详细命令

这是另外一回事了

**Comment by heartacker** [comment]
> 他的意思是，对于中文翻译的意义是不明确的，比如一个按钮叫拉回，一个叫拉取，对于常使用命令行操作的人来说，并不知道指的是什么操作。
> 
> 目前的改法是在部分中文翻译上加入英文的翻译比如：
> 
> ![image](https://private-user-images.githubusercontent.com/4075673/318610185-4700db60-4320-46f4-9aa4-c554c619d542.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMjQ4MDIsIm5iZiI6MTcxMjAyNDUwMiwicGF0aCI6Ii80MDc1NjczLzMxODYxMDE4NS00NzAwZGI2MC00MzIwLTQ2ZjQtOWFhNC1jNTU0YzYxOWQ1NDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDJUMDIyMTQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTZiNWU3MWI0ZTBjY2RmN2Q5MWE1MjMxZTQyZmYyNTNkYTYwMzNjOTM1MmEyMjc1NTAzYzA1ZjM5Y2IwNjA4MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.IXZi99H9zrF1DZFOx8Em88LO06ty5YdBtNmI-BJikrg) ![image](https://private-user-images.githubusercontent.com/4075673/318610213-0c713584-3c7f-47a3-8bdf-d247b17f37c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMjQ4MDIsIm5iZiI6MTcxMjAyNDUwMiwicGF0aCI6Ii80MDc1NjczLzMxODYxMDIxMy0wYzcxMzU4NC0zYzdmLTQ3YTMtOGJkZi1kMjQ3YjE3ZjM3YzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDJUMDIyMTQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTIyNGQxMzA0MGQ4OTlmZWRlMjBiM2RkZGJkZmEzOTA2Y2VjYjhhMDhmMjRkZmM3MTA4MDg5ZWYzMDA3Mjg0MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9yX9AmHoTlv9_I_GfpLg27ASibB0DmIGgTuKmV7PKXA) ![image](https://private-user-images.githubusercontent.com/4075673/318611066-56d42d01-90af-4abe-b999-a2051e9d2c51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMjQ4MDIsIm5iZiI6MTcxMjAyNDUwMiwicGF0aCI6Ii80MDc1NjczLzMxODYxMTA2Ni01NmQ0MmQwMS05MGFmLTRhYmUtYjk5OS1hMjA1MWU5ZDJjNTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDJUMDIyMTQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTYzMjA0ZGEwOGQ4NDRhMWMzZDllNzI4ODRkYTBhNDVkNmYwODQzNDk2NTQyODU1N2VjMGNlMDkyNGQ5Nzc3YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nH64NS-x5Mntkz1Sq6xBEc8WdqhbyxzMyGq3Q9LdCmA)
> 
> 否则，即便是有Terminal，按钮的作用还是不明确（也就是说，不试一下，就不清楚这个按钮是执行的什么GIT操作）。

我个人觉得，不建议是仅仅是在中文 ，应该在所有语言和翻译中，都保存原始的指令。
如  

*checkout<kbd>checkout</kbd>*

*签出<kbd>checkout</kbd>*

**Comment by love-linger** [comment]
我参考了一下其他的软件，感觉英文是不需要加上这些辅助的。但是如果有其他的语种，的确是需要加入这些辅助信息。
