### ISSUE TITLE
[Feature Request] Choose account for each repo

### ISSUE THREAD

**Issue by angeousta** [sourcegit-scm/sourcegit#410]
### The feature request

It would be nice to be able to set git credentials (user, email, psw/token) for each repo.

Very useful to people working on different projects with different github users

### Proposed solution

A new setting for each repo for choosing github account associated to that repo

**Comment by sourcegit-scm** [comment]
You can do this by change your repository's remote URL to `https://{USER_NAME}@github.com/{GROUP}/{REPO}`

**Comment by love-linger** [comment]
After you do that and login successfully. The next time you fetch/pull/push some commits, you will get a prompt like this:
![image](https://github.com/user-attachments/assets/2f9ac3a2-8bd6-408e-a57b-145d32bc31ee)

**Comment by love-linger** [comment]
see https://github.com/git-ecosystem/git-credential-manager/blob/main/docs/multiple-users.md
