### ISSUE TITLE
The configured user limit (128) on the number of inotify instances has been reached...

### ISSUE THREAD

**Issue by ScruffyDerHausmeister** [sourcegit-scm/sourcegit#411]
I've got an error when opening a repository on linux (Zorin OS / Ubuntu).

> Crash::: System.IO.IOException: The configured user limit (128) on the number of inotify instances has been reached, or the per-process limit on the number of open file descriptors has been reached.
[crash_2024-08-25_20-48-56.log](https://github.com/user-attachments/files/16741572/crash_2024-08-25_20-48-56.log)

**Comment by gadfly3173** [comment]
You can add these to `/etc/sysctl.conf` .
```conf
fs.inotify.max_user_instances=1024
fs.inotify.max_user_watches=1048576
```
This error occurs when listening for a large number of files on Linux.

**Comment by ScruffyDerHausmeister** [comment]
It'd be nice to find a solution without changing systemfiles which never were needed to be changed.

**Comment by love-linger** [comment]
Using `lsof -c sourcegit` command to show the file descriptors opened by SourceGit on Ubuntu 20.04 (WSL 2).

* After `SourceGit` started (Without any repository opened) 
[empty.txt](https://github.com/user-attachments/files/16745386/empty.txt)
* After a repository was opened in `SourceGit`
[open_sourcegit_repo.txt](https://github.com/user-attachments/files/16745393/open_sourcegit_repo.txt)

> [!NOTE]
> When a repository is opened in `SourceGit`, we will create two `FileSystemWatcher` - one for repository's git dir and another for repository's worktree.

The main difference:

![image](https://github.com/user-attachments/assets/98c41cf6-efc6-4c79-8e73-8eb66ce01076)

**Comment by love-linger** [comment]
Another test

* Start without repository opened
[open_0_repo.txt](https://github.com/user-attachments/files/16745513/open_0_repo.txt)
* Start with 1 repository opened
[open_1_repo.txt](https://github.com/user-attachments/files/16745511/open_1_repo.txt)
* Start with 2 repositories opened
[open_2_repo.txt](https://github.com/user-attachments/files/16745515/open_2_repo.txt)

![image](https://github.com/user-attachments/assets/c641c594-5c8e-4a5f-9095-882706078b98)

It seems like that when we create a new `FileSystemWatcher`, a `a_inode` FD will be opened.

**Comment by gadfly3173** [comment]
> According to the test results, the FDs did not increase beyond the expected situation.

The upper limit that is usually reached is `fs.inotify.max_user_instances`. When I opened 4 IDEAs, 1 Rider, 2 Tomcats, and 1 SourceGit (opened 6 repositories), I could see that the number of instances reached 105. Opening another SourceGit will bring the number to 117.

```log
   INOTIFY   INSTANCES
   WATCHES      PER   
    COUNT     PROCESS   PID USER         COMMAND
------------------------------------------------------------
   24131        12      152313 homolo      /home/homolo/Documents/sourcegit/src/bin/Debug/net8.0/SourceGit
   15703        13       40694 homolo      /opt/sourcegit/sourcegit
   14907         1        3981 homolo      /snap/intellij-idea-ultimate/524/bin/fsnotifier
    3415         1      140759 homolo      /snap/rider/489/bin/fsnotifier
      60         3       98184 homolo      /usr/libexec/dde-file-manager -d
      48         3       40197 homolo      /usr/bin/dde-select-dialog-x11
      21         3        1172 homolo      /usr/bin/dde-desktop
      19         4       22666 homolo      /opt/google/chrome/chrome

========ignore=============

INotify instances per user (e.g. limits specified by fs.inotify.max_user_instances): 

INSTANCES    USER
-----------  ------------------
105          homolo
```

It can be observed that IDEA only creates two instances. I think SourceGit can also consider reducing the number of inotify instances created.

```log
   14907         1        3981 homolo      /snap/intellij-idea-ultimate/524/bin/fsnotifier
       9         1        3848 homolo      /snap/intellij-idea-ultimate/524/bin/idea
```

**Comment by love-linger** [comment]
https://github.com/user-attachments/assets/8a789bea-68a0-4d43-bbfa-48d6dbfc0554

@gadfly3173 I've test with this script https://github.com/fatso83/dotfiles/blob/master/utils/scripts/inotify-consumers

It shows when a repository is opened, 2 instances (needed by 2 FileSystemWatcher) are created.

Could you help me to test that what's the result when multiple instance of IDEA opened with different project? (We need to listen different paths not just one project)

**Comment by gadfly3173** [comment]
> Could you help me to test that what's the result when multiple instance of IDEA opened with different project? (We need to listen different paths not just one project)您能否帮我测试一下，当使用不同项目打开多个 IDEA 实例时，结果是什么？（我们需要倾听不同的路径，而不仅仅是一个项目）

The previously mentioned IDEA creates only two instances when four different projects are opened.

```log
   14907         1        3981 homolo      /snap/intellij-idea-ultimate/524/bin/fsnotifier
       9         1        3848 homolo      /snap/intellij-idea-ultimate/524/bin/idea
```

**Comment by aikawayataro** [comment]
I think we can use single instance of inotify subsystem on Linux if we use P/Invoke and call `inotify_add_watch` with single subsystem
This will not reduce the number of watches, though

**Comment by gadfly3173** [comment]
Here is Gitkraken with 6 opened repositories. And I think this is an dotnet-runtime issue: https://github.com/dotnet/runtime/issues/62869

```log
    2289         3      168727 homolo      /persistent/data/Gitkraken/gitkraken --type=renderer --crashpad-handler-pid=1686
       6         4      168590 homolo      /persistent/data/Gitkraken/gitkraken
       2         1      168648 homolo      /persistent/data/Gitkraken/gitkraken --type=utility --utility-sub-type=network.m
```

**Comment by love-linger** [comment]
I took a look at how to listen for filesystem changes in Java and found that starting Java 7, it provides 'java.nio.file.WatchService' and it allows register multiple paths. For example:
```java
WatchService watchService = FileSystems.getDefault().newWatchService();
Path path1 = Paths.get("path1");
path1.register(watchService, StandardWatchEventKinds.ENTRY_CREATE);
Path path2 = Paths.get("path2");
path2.register(watchService, StandardWatchEventKinds.ENTRY_CREATE);
```

But in C#, the `FileSystemWatcher.Path` is a simple string. We need to create multiple instance of `FileSystemWatcher` to listen multiple paths.

**Comment by gadfly3173** [comment]
After observing the performance of Gitkraken, I found that it would prompt `File watching failed to start for this repository.`. Then the repository would be opened normally, but the file status would not be automatically updated until I switched to this tab again.

**Comment by love-linger** [comment]
I've pushed a commit that deals with this in the way `Gitkraken` does and these two method still works without a `Watcher` instance:

```csharp
public void MarkBranchesDirtyManually()
{
    if (_watcher == null)
    {
        Task.Run(() =>
        {
            RefreshBranches();
            RefreshCommits();
        });

        Task.Run(RefreshWorkingCopyChanges);
        Task.Run(RefreshWorktrees);
    }                
    else
    {
        _watcher.MarkBranchDirtyManually();
    }
}

public void MarkWorkingCopyDirtyManually()
{
    if (_watcher == null)
        Task.Run(RefreshWorkingCopyChanges);
    else
        _watcher.MarkWorkingCopyDirtyManually();
}
```
