### ISSUE TITLE
Suggestion Shortcut Key

### ISSUE THREAD

**Issue by hule-fadv** [sourcegit-scm/sourcegit#412]
![image](https://github.com/user-attachments/assets/afb35909-8679-4e3c-b9e8-d995d838fe39)

Can we have a shortcut key for Pull and Stage? Also, can we customize the hotkey instead of having it harded?

**Comment by love-linger** [comment]
For staging changes, you can use `Ctrl+A` to select all changes in unstaged list, the `Space` to stage them.

There is not a hotkey for buttons in the toolbar now.

This app do not support custom hotkeys, and have no plan to add this feature.
