### ISSUE TITLE
Statisitics can't find last year or last month. please add it,thanks

### ISSUE THREAD

**Issue by Delay-n-days** [sourcegit-scm/sourcegit#414]
Statisitics can't find last year or last month. please add it,thanks

**Comment by love-linger** [comment]
I've pushed a commit that collects the commits for the most recent year instead of just the current year. 

![image](https://github.com/user-attachments/assets/947ed823-d813-4c1a-b752-696618a1ebe8)

**Comment by love-linger** [comment]
closed since no feedback
