### ISSUE TITLE
Diff 界面提供忽略换行符的选项

### ISSUE THREAD

**Issue by ameaninglessname** [sourcegit-scm/sourcegit#417]
希望可以添加这个功能，让内置的diff更好用。

目前准备用vscode替代

**Comment by love-linger** [comment]
目前内置DIFF命令默认启用`--ignore-cr-at-eol`参数，这是因为目前实现方案中，`Process.OutputDataReceived`事件返回的GIT子进程输出是按行读取且去掉了换行符。如果文本仅是换行符的修改，界面中会提示。

同时，软件偏好设置中，也可对`core.autocrlf`配置

**Comment by ameaninglessname** [comment]
我目前在Linux，`core.autocrlf`设置的`input`,不然更代码的时候会有换行符的改动。 类似#46。

可以像tortoisegit那样，在diff界面提供空格的处理选项么？

**Comment by love-linger** [comment]
我没有使用过TortoiseGit，能否提供一下参考视频什么的？

**Comment by love-linger** [comment]
顺便提一句，软件支持使用外部对比/合并工具。您可在偏好设置面板更改。如果软件的DIFF视图无法满足需求，您可以在其工具栏打开您配置的外部对比/合并工具。如图所示：
![image](https://github.com/user-attachments/assets/450605fd-c802-432a-95b5-40962c86f4cd)
![image](https://github.com/user-attachments/assets/5e5bd493-e4cf-49ec-a06b-ddf4b23d1ce1)

**Comment by love-linger** [comment]
之前的回答已经提到了，关于换行符由于`Process.OutputDataReceived`的返回值会去掉换行符，所以程序内直接启用`--ignore-cr-at-eol`选项，不再显示换行符变化。如果文件只是换行符发生变化时，界面会如下提示：
![image](https://github.com/user-attachments/assets/274182c7-2d80-4e6f-b5fa-17354b632775)

对于行内空白符，您可点击DIFF工具栏的这个按钮开启
![image](https://github.com/user-attachments/assets/85d2b0d9-a445-4234-8294-83041fdbeea6)

我认为行内的空白符变更也是需要展示的，一是考虑到代码风格审核需求，二是一些语言对于缩进对齐有一定要求，比如clang在编译c/c++时，如果混用空格与tab导致if (condition) 与其 exp 代码块缩进不统一时，会直接报编译错误。
![image](https://github.com/user-attachments/assets/36464f35-4dfe-42bb-a430-0ccf3db95b41)

**Comment by ameaninglessname** [comment]
懂了。

> 我认为行内的空白符变更也是需要展示的

我也赞同您的观点，我自己在IDE设置都是`保存时移除所有行的多余空白符号`的。

我只是觉得加一个开关可以更方便点：
比如我改了一个文件，并且把它里面多余的空白“修复”了，但我看diff的时候，会看到大量的空白符改动，这个是影响我检阅的。

目前这个需求可以完全用code替代，所以我先关issue了，谢谢您。
