### ISSUE TITLE
同样的按钮，同样的图标，不同的功能，让人很困惑，

### ISSUE THREAD

**Issue by heartacker** [sourcegit-scm/sourcegit#42]
![image](https://github.com/sourcegit-scm/sourcegit/assets/1876302/5022975a-a91e-4cbd-8048-781474ec32a6)

![image](https://github.com/sourcegit-scm/sourcegit/assets/1876302/aa2445d3-75d3-4299-a9cf-e4f87ef5cd06)

一会是打开文件夹，一会是在文件夹中打开，这确实是令人困惑的操作和设计

**Comment by love-linger** [comment]
非常感谢您的建议。软件使用的图标来自于 [iconfont](https://www.iconfont.cn/)，确实有大量相似，但功能不同的按钮使用了同样的图标。后面尽量做出区别。

**Comment by heartacker** [comment]
另外，也不建议放在同一个地方。 嘿嘿，容易误触
