### ISSUE TITLE
不支持预览 webp 图片内容

### ISSUE THREAD

**Issue by shuperry-antler** [sourcegit-scm/sourcegit#421]
<img width="765" alt="image" src="https://github.com/user-attachments/assets/2d9fb17e-004a-4f22-a560-57a2ce9d27f3">

**Comment by love-linger** [comment]
added:

![image](https://github.com/user-attachments/assets/65669c06-4172-4045-bb4f-ae469684aa66)

**Comment by shuperry-antler** [comment]
@love-linger good work 👍
