### ISSUE TITLE
[Feature] Backspace and Delete keys activate Discard Changes dialog

### ISSUE THREAD

**Issue by BrodyB** [sourcegit-scm/sourcegit#423]
## Overview
If the user wants to discard changes, they need to select one or more items in the Unstaged Changes list, then right-click and select Discard Changes. It would be convenient if you were able to use the Delete or Backspace key in lieu of the right-click context menu option.

## Expected Result
When the user selects one or more items in the Unstaged Changes list, hitting Backspace or Delete will open the Discard Changes dialog to confirm discarding those changes.

**Comment by love-linger** [comment]
added:
![image](https://github.com/user-attachments/assets/32daf80d-ba7f-44aa-a148-2b783c50fbf3)
