### ISSUE TITLE
[BUG] The "AUTHOR" column of the Git history keeps resetting itself to the smallest size

### ISSUE THREAD

**Issue by ozmium** [sourcegit-scm/sourcegit#425]
On the Git history section of SourceGit, the Author column is always resetting itself to be a small width. When the user makes this column large, the app keeps resetting it to be small. Also, the app does not remember what custom size was set by the user. Here are some examples, tested in SourceGit version 8.27:

https://github.com/user-attachments/assets/a1d71580-ec69-4ac8-a03b-791ad69ee2ea

https://github.com/user-attachments/assets/5391ce50-4895-4e86-92fa-412263270102

It happens in several ways:

* Resize the AUTHOR column to be large, then display the search sidebar and keep resizing it left and right - as shown in the first video. The Author column will end up being very small.
* Resize the AUTHOR column to be large, then maximize the SourceGit window to fill the full display area. Then restore the window size back to the previous size (as shown in the second video). Repeat this process 1-3 times: Maximize the window then restore it. The Author column will now be very small.
* Resize the AUTHOR column to be large, then Quit SourceGit, then relaunch it. The Author column will now be very small.

This is bad, because the app is always resetting a custom user preference, and this is not what the user wants. The app also forgets the user's settings, causing the user to keep re-applying it very often.

**Comment by love-linger** [comment]
done. You can test it from https://github.com/sourcegit-scm/sourcegit/actions/runs/10607533427
