### ISSUE TITLE
[Feature] 支持指定默认克隆位置，并可以从默认克隆位置中扫描代码库

### ISSUE THREAD

**Issue by Vixb1122** [sourcegit-scm/sourcegit#427]
支持指定默认克隆位置，并可以从默认克隆位置中扫描代码库
就像 Fork https://git-fork.com/ 一样。
![image](https://github.com/user-attachments/assets/ad60bc04-aac1-4b5b-8f8d-3a46e27b0ed4)

**Comment by love-linger** [comment]
done:

![image](https://github.com/user-attachments/assets/2f7fc02e-a1e0-4d14-85bc-a618b159f3bb)

**Comment by love-linger** [comment]
BTW, the settings for default clone dir is here:
![image](https://github.com/user-attachments/assets/3dffdd94-e5c2-4b27-a273-b872ab5a3d43)
