### ISSUE TITLE
Make buttons work on-press, instead of on-release

### ISSUE THREAD

**Issue by caioraphael1** [sourcegit-scm/sourcegit#435]
The buttons are programmed to work based on the position the RELEASED action is made, so if you click the button and drag out of it, the button does nothing.

https://github.com/user-attachments/assets/32c2bcf4-82bd-4209-b441-c3d2d857be37

This can be fixed by "changing the signal to be emitted at press, not on release" (I have no idea what I'm talking about, I have not seen the source code).

Why is this important? On big monitors, it's often the case that the user (me) clicks and drags by accident, so it's a bit unresponsive.

**Comment by ChiahongHong** [comment]
To avoid users accidentally triggering actions, this behavior design is generally the default for most applications. I’m simply curious if there are any well-known software programs that use a release-to-trigger button mechanism instead?

In most cases, actions are typically triggered when the mouse click is released, whereas for keyboard keys, the action is triggered upon pressing the key.

**Comment by love-linger** [comment]
> To avoid users accidentally triggering actions, this behavior design is generally the default for most applications. I’m simply curious if there are any well-known software programs that use a release-to-trigger button mechanism instead?
> 
> In most cases, actions are typically triggered when the mouse click is released, whereas for keyboard keys, the action is triggered upon pressing the key.

I agree. 

The click event triggers only _**when the control that triggered `PointerPressedEvent` is the same control that triggered `PointerReleasedEvent`**_. 

This can avoid users accidentally triggering actions.

**Comment by caioraphael1** [comment]
I do see this as a pattern in softwares, but I don't get it, for me, it seems to just make it a bit more unresponsive. 

What about "if the action is released, execute the action regardless of where the mouse is", so in this case the action is only triggered on release, but ensures responsiveness in case of dragging the mouse accidentally.

**Comment by love-linger** [comment]
> I do see this as a pattern in softwares, but I don't get it, for me, it seems to just make it a bit more unresponsive.
> 
> What about "if the action is released, execute the action regardless of where the mouse is", so in this case the action is only triggered on release, but ensures responsiveness in case of dragging the mouse accidentally.

The triggering of events is independent of each other, for example: the sender of `PointerPressedEvent` and the sender of `PointerReleasedEvent` may not be the same control, and may not be implemented in the same class. If you need to implement the feature you mentioned, you need to record the sender of the mouse press event in the global, and trigger the event bound to the sender of the record when the mouse is released. This may lead to unexpected results easily.
