### ISSUE TITLE
Request to enhance Welcome page grouping

### ISSUE THREAD

**Issue by gadfly3173** [sourcegit-scm/sourcegit#437]
When the number of `RepositoryNode` on the Welcome page exceeds one page, the `RepositoryNode` in the group cannot be moved to the root node. Maybe you can consider adding padding to the ListBox, or handle dragging outside the ListBox, or add the parent node option to the RepositoryNode edit popup.

**Comment by love-linger** [comment]
In fact, you can move a child node from group to root by simply drop on the front of its icon, for example:

https://github.com/user-attachments/assets/7f8c9c3e-79bf-4049-8166-e8d1711a5ec7

**Comment by gadfly3173** [comment]
I discovered that it can only be dragged in front of a child node, not in front of the other root nodes. . .

**Comment by love-linger** [comment]
a context menu item has been added to help users moving repository nodes.
![image](https://github.com/user-attachments/assets/a1db156e-b0b6-4b2a-8ca5-0b89c7aefde4)

**Comment by gadfly3173** [comment]
> a context menu item has been added to help users moving repository nodes. 

It seems good to me.
