### ISSUE TITLE
项目很好,还没具体试用，布局UI可能再细致化

### ISSUE THREAD

**Issue by qx4235** [sourcegit-scm/sourcegit#44]
UI和功能我觉得可以参考下  fork  ,这个是我试用多个以来，最喜欢的一个git 图形操作。sourcetree动不动就卡死。fork对 cherry-pick,rebase这些操作，也是棒的。希望你们可以结合两都优点来做。
![image](https://github.com/sourcegit-scm/sourcegit/assets/4419557/3f2f74c7-237b-4b23-840b-2b180a84886e)

**Comment by love-linger** [comment]
呃……这个项目之前是在Gitee上开源的。后面移到了github。如果之前有关注过的话，就会知道我之前也在用fork，而且是在fork出来不久就用了。直到后来fork计划收费（大概在19年或20年，当然，到了现在也没强制收费），那时就想自己做一个得了。

SourceGit目前基本上已经实现了常用的Git操作（包括你说的cherry-pick、rebase），目前对比fork来说（我好久不用了，印象中），好像只有interactive rebase和bisect是缺失的（不算Github集成这样的外围功能）。

另外，能否将你认为需要改进或参考fork的地方，更加详细的说明一下呢。我光看上面那个图，没有GET到。万分感谢！！！

**Comment by love-linger** [comment]
哦，我有点明白你的意思了

**Comment by heartacker** [comment]
可以试试 git graph ， vscode 插件，我觉得也是一个不错的借鉴。
