### ISSUE TITLE
Usage of .axaml instead of .resx for locales

### ISSUE THREAD

**Issue by NilsPvR** [sourcegit-scm/sourcegit#440]
When working on the localizations I was wondering why this project uses `.axaml` files for locales. I have seen the use of `.resx` files elsewhere. Looking at the Avalonia [localizing documentation](https://docs.avaloniaui.net/docs/guides/implementation-guides/localizing) they also suggest using ResX for locales. 

For me personally the translation process would be much simpler with ResX since I could use tooling. My current process is just manually looking and editing the axaml. If there is some tool to simplify this let me know!

**Comment by love-linger** [comment]
It's because this is simpler to me - no tool dependencies, easier to edit with text editors.

**Comment by NilsPvR** [comment]
Fair point, even tho I do think once setup it would not be that much more complicated to edit in a normal editor.
