### ISSUE TITLE
Minimize button is dimmed

### ISSUE THREAD

**Issue by warappa** [sourcegit-scm/sourcegit#442]
Just a minor issue:
The minimize button is dimmed a little bit compared to maximize/close in both themes (dark and light).
Once you see it you cannot un-see it 😉

![image](https://github.com/user-attachments/assets/a6ae7ea0-3c0f-452e-a448-29942b749d66)

SourceGit 8.28
Windows 10 22H2

**Comment by love-linger** [comment]
how about now?

**Comment by NilsPvR** [comment]
Yes looks much better. Not sure if it's 100% the same shade now but can't really tell any difference.
175% scaling:
![grafik](https://github.com/user-attachments/assets/7a2373ad-40d6-4aa2-a3ff-8ca32639663e)
100% scaling:
![grafik](https://github.com/user-attachments/assets/0303f241-84ad-4096-a191-c7395a65e4f8)

In light mode a minor difference might be visable 🤔 
<details><summary>Light mode warning!</summary>
175% scaling:<br>
<img src="https://github.com/user-attachments/assets/e2744c01-8291-4e21-8d8c-2e1f86701980"><br>
100% scaling:<br>
<img src="https://github.com/user-attachments/assets/5745269d-3242-491c-ae65-9a20ca11b33d">
</details>

**Comment by love-linger** [comment]
So, I'll close this issue as completed.

**Comment by warappa** [comment]
Thank you for fixing it so fast (again) 👍
