### ISSUE TITLE
[Feature] Improve search by adding submodules

### ISSUE THREAD

**Issue by AntoninHuaut** [sourcegit-scm/sourcegit#443]
Hi, a feature request about the search bar. When working on a project with a lot of submodules, it might be useful for the search bar to also filter the list of submodules, thanks!

![image](https://github.com/user-attachments/assets/c8ca9ef7-c08f-4288-896a-7704b9c06e68)

**Comment by love-linger** [comment]
added:
![image](https://github.com/user-attachments/assets/e788611b-5d81-4f2a-9e20-552fae735ae3)

**Comment by AntoninHuaut** [comment]
Thanks you, I close the issue
