### ISSUE TITLE
[Feature] Add ability to rename tab

### ISSUE THREAD

**Issue by abeham** [sourcegit-scm/sourcegit#444]
I have several repositories in a similar fashion to submodules, but not using git submodules. They're living in different folders and are named the same. Like e.g. "CoreLibraries" and then I have CoreLibraries in Project A and CoreLibraries in Project B and those projects are in different folders. When I have the the two CoreLibraries repositories open in SourceGit the tab name is the same. Using colors the tabs can be distinguished, but it's not that easy to associate the right color with the right project. Like in Green is Project A and Yellow is Project B and Purple is Project C, etc. Just renaming the tabs would be a lot simpler.

Making Tab Groups would also be a possibility.

**Comment by love-linger** [comment]
You can do it by the context menu of repository node in Welcome (Repositories) page. 

![image](https://github.com/user-attachments/assets/4aa6a124-5567-4847-82fc-ec9776759263)

**Comment by love-linger** [comment]
> Making Tab Groups would also be a possibility

The bookmark color is designed for grouping tabs. After you opened some repository, you can use `Drag & Drop` to reorder the tabs, and make sure the repositories with same bookmark color next to each other.

**Comment by abeham** [comment]
Ok, the functionality is already there, thanks!
