### ISSUE TITLE
Group Opend Repos

### ISSUE THREAD

**Issue by Mike710Shine** [sourcegit-scm/sourcegit#445]
This is just a suggestion for an improvement. It would be great if you could group the open repos. If you have a relatively large number of repos open, this would make things much clearer.
The Chrome browser grouping could be used as an example. Alternatively, a menu that switches between different workspaces would also be possible.

**Comment by love-linger** [comment]
The bookmark color is designed for grouping. After you opened some repositories, you can drag & drop the tabs to make the repositories with same bookmark color next to each other.

**Comment by Mike710Shine** [comment]
Ok that's quite ok but not quite what I meant. That's right, you can use it to group but you still have the problem that you have to scroll back and forth for quite a long time if you have a lot of repos open.

**Comment by love-linger** [comment]
done. You can test it from the latest build https://github.com/sourcegit-scm/sourcegit/actions/runs/10772443853.
![image](https://github.com/user-attachments/assets/f535013c-e2bf-4ee9-bddf-7bb486a158d5)

**Comment by michael-konrad-itk** [comment]
I checked it out. It's very cool thanks this is exactly what i mean. Very big thanks and very cool implementations
