### ISSUE TITLE
在ubuntu 24.04.1 升级v8.28 无法打开没有任何日志输出

### ISSUE THREAD

**Issue by zyimm** [sourcegit-scm/sourcegit#447]
系统环境
```
Operating System: Ubuntu 24.04.1 LTS              
Kernel: Linux 6.8.0-41-generic
ubuntu:GNOME
```

降级v8.26 是没有问题的

**Comment by zyimm** [comment]
使用Wayland.

**Comment by love-linger** [comment]
请问，您是以何种方式安装SourceGit的呢？deb? AppImage? 还是自编译的呢？

在命令行中，输入`sourcegit`，是否有输出呢？

**Comment by zyimm** [comment]
> 请问，您是以何种方式安装SourceGit的呢？deb? AppImage? 还是自编译的呢？
> 
> 在命令行中，输入`sourcegit`，是否有输出呢？

.deb 安装，cli 下 输入sourcegit  提示命令不存在

**Comment by love-linger** [comment]
那就有点奇怪了，我手动检查了一下 https://github.com/sourcegit-scm/sourcegit/releases/download/v8.28/sourcegit_8.28-1_amd64.deb 文件，没发现文件遗漏呢
<img width="633" alt="image" src="https://github.com/user-attachments/assets/780285ed-5e99-4027-9720-8f2a6b77a7ab">

**Comment by love-linger** [comment]
今天我身边没有Ubuntu机器，但我在WSL2中测试一下安装包，也是没问题的，不清楚为什么你那里会缺失文件。
![image](https://github.com/user-attachments/assets/08eca8d2-10e1-4eef-9ffb-0c83f545b206)

**Comment by zyimm** [comment]
> 今天我身边没有Ubuntu机器，但我在WSL2中测试一下安装包，也是没问题的，不清楚为什么你那里会缺失文件。 ![image](https://private-user-images.githubusercontent.com/4075673/365423403-08eca8d2-10e1-4eef-9ffb-0c83f545b206.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3ODc5MTksIm5iZiI6MTcyNTc4NzYxOSwicGF0aCI6Ii80MDc1NjczLzM2NTQyMzQwMy0wOGVjYThkMi0xMGUxLTRlZWYtOWZmYi0wYzgzZjU0NWIyMDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDhUMDkyNjU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NThmYjVlMjk5ZDYyMzJiOTRmOTZiYzg4Mjg3NzhhMjExNTU1ZmUzMDI2MzkwNGU1Y2U2N2M4OTU2ZjYzYWIyMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.KnCHwdzqtT8twPpPmKHb0ku8TFJVCS8JomFtQTh_Fic)

最好是 使用ubuntu 24.04.1 最新版本，系统依赖更新最新看看

![图片](https://github.com/user-attachments/assets/00d15c22-d158-4afe-a740-26ba8020e566)

**Comment by zyimm** [comment]
还有希望有日志输出，否则真不好排查是什么原因导致的

**Comment by zyimm** [comment]
> > 今天我身边没有Ubuntu机器，但我在WSL2中测试一下安装包，也是没问题的，不清楚为什么你那里会缺失文件。 ![image](https://private-user-images.githubusercontent.com/4075673/365423403-08eca8d2-10e1-4eef-9ffb-0c83f545b206.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3ODc5MTksIm5iZiI6MTcyNTc4NzYxOSwicGF0aCI6Ii80MDc1NjczLzM2NTQyMzQwMy0wOGVjYThkMi0xMGUxLTRlZWYtOWZmYi0wYzgzZjU0NWIyMDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDhUMDkyNjU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NThmYjVlMjk5ZDYyMzJiOTRmOTZiYzg4Mjg3NzhhMjExNTU1ZmUzMDI2MzkwNGU1Y2U2N2M4OTU2ZjYzYWIyMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.KnCHwdzqtT8twPpPmKHb0ku8TFJVCS8JomFtQTh_Fic)
> 
> 最好是 使用ubuntu 24.04.1 最新版本，系统依赖更新最新看看
> 
> ![图片](https://private-user-images.githubusercontent.com/13979159/365427916-00d15c22-d158-4afe-a740-26ba8020e566.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3ODg2MDMsIm5iZiI6MTcyNTc4ODMwMywicGF0aCI6Ii8xMzk3OTE1OS8zNjU0Mjc5MTYtMDBkMTVjMjItZDE1OC00YWZlLWE3NDAtMjZiYTgwMjBlNTY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA4VDA5MzgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4YThlYzcwNWM2NGJhZDU4YzVlMjdjOGFlM2IwMjVhZjQ4OTFjYjYzZmJmZGRmNDg2NGRhZWVkODAzYzk1NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1lg3drGo53uDMvEZo5HhOQSDLUvA7Cw70pFI7F08FzI)
### 看了错误日志如下：

```
Crash::: System.InvalidOperationException: Could not create glyphTypeface. Font family: $Default (key: ). Style: Normal. Weight: Normal. Stretch: Normal

----------------------------
Version: 8.28.0.0
OS: Unix 6.8.0.41
Framework: .NETCoreApp,Version=v8.0
Source: <unknown>
---------------------------

   at Avalonia.Media.Typeface.get_GlyphTypeface() + 0x352
   at Avalonia.Rendering.Composition.Compositor.get_DiagnosticTextRenderer() + 0xf1
   at Avalonia.Rendering.Composition.Compositor.CreateCompositionTarget(Func`1) + 0x2e
   at Avalonia.Rendering.Composition.CompositingRenderer..ctor(IRenderRoot, Compositor, Func`1) + 0xb3
   at Avalonia.Controls.TopLevel..ctor(ITopLevelImpl, IAvaloniaDependencyResolver) + 0x5f3
   at Avalonia.Controls.WindowBase..ctor(IWindowBaseImpl, IAvaloniaDependencyResolver) + 0x35
   at Avalonia.Controls.WindowBase..ctor(IWindowBaseImpl) + 0x4b
   at Avalonia.Controls.Window..ctor(IWindowImpl) + 0x6c
   at SourceGit.Views.ChromelessWindow..ctor() + 0x79
   at SourceGit.Views.Launcher..ctor() + 0x63
   at SourceGit.App.TryLaunchedAsNormal(IClassicDesktopStyleApplicationLifetime desktop) + 0x10a
   at SourceGit.App.Main(String[] args) + 0x1cb%          
```

**Comment by love-linger** [comment]
看输出是由于找不到字体。从`8.27`版本开始，字体配置逻辑重写了。你现在可以手动改一下preference.json，指定一下`DefaultFontFamily`。后面，我会针对这一问题提交相应的修改。

**Comment by love-linger** [comment]
如果可以的话，您也可以下载最新的包 https://github.com/sourcegit-scm/sourcegit/actions/runs/10759160381 帮忙测试一下是否问题已经解决了（不手动修改`preference.json`）

**Comment by zyimm** [comment]
> 如果可以的话，您也可以下载最新的包 https://github.com/sourcegit-scm/sourcegit/actions/runs/10759160381 帮忙测试一下是否问题已经解决了（不手动修改`preference.json`）

这个最新版本是正常了
