### ISSUE TITLE
是否可以新增一个git 仓库文件树状管理器 

### ISSUE THREAD

**Issue by heartacker** [sourcegit-scm/sourcegit#45]
方便用户查看当前仓库的文件。如果是文本，还可以直接点击查看或者编辑。 
![image](https://github.com/sourcegit-scm/sourcegit/assets/1876302/ba6cb1c4-4521-479d-93a5-86d9232267ed)

**Comment by love-linger** [comment]
有的，目前Files是针对每个Commit(Revision)的状态。即选中一个Commit版本，在CommitDetail面板的Files（文件列表）分页，可看到当前选中Revision的文件列表，右键可对其进行另存、历史、Blame等操作

![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/c6fb795b-3c5d-4725-babf-773f24a7328f)

**Comment by heartacker** [comment]
建议，主栏也有一个。而且这个显示的是当前工作区 
感动:D

**Comment by love-linger** [comment]
看了一圈其他的软件，文件列表，基本上都是基于 revision 的。如果想要对当前工作区的文件查看、编辑，建议直接使用 `Open In External Tool` 功能。

![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/250ae7c6-0468-4693-a8a4-1d37fbcdb0fc)

**Comment by heartacker** [comment]
其实也赞同你的观点。毕竟这个也是一个版本管理器，而不是编辑器。
但是说回来
1. 版本管理，有冲突，肯定要处理，甚至编辑，所有必备编辑的功能
2. 还是本软件是版本管理器，不是编辑器，但是我在版本管理的时候，发现还有部分要改动。又要切换回别的编辑器。也许是一个很小的改动。     
这就造成了不方便

还是建议。
1. 主栏添加文件管理器。
2. 优先不支持用户进行直接编辑，但是方便查看。
3. 或者提供最基本的txt 编辑，只是附带了语法高亮。

**Comment by love-linger** [comment]
文本编辑等功能已经超出了该软件的设计初衷。不在开发计划之内。
