### ISSUE TITLE
[UI] The text inside the button while pulling changes does not align vertical

### ISSUE THREAD

**Issue by successgo** [sourcegit-scm/sourcegit#451]
![image](https://github.com/user-attachments/assets/b34141da-bb6c-4713-bf7d-763be85d006d)

**Comment by love-linger** [comment]
It's a known issue with `AvaloniaUI`. It's not only affects the button. 
![image](https://github.com/user-attachments/assets/6e5c0b6a-4ebb-4cb8-a66e-28beedb7d062)
Currently, you can change anthor font for `Default Font` in preference window.

Maybe they will fixed this in future.
