### ISSUE TITLE
[feature] Hide branch and directory for local and remote

### ISSUE THREAD

**Issue by successgo** [sourcegit-scm/sourcegit#452]
This feature is very useful when we have lots of working branches and we want to hide some branches.
Currently we can filter others and just show one branch. Sometime we want to see a main branch and some of the feature branches.

**Comment by love-linger** [comment]
Why not enable filtering for both the main branch and the others you want to show?
![image](https://github.com/user-attachments/assets/3e4ac339-3dbd-4bec-a31b-f8bba4b99e70)

**Comment by successgo** [comment]
It works in this way.
