### ISSUE TITLE
Commit subject - dropdown with several previous subjects

### ISSUE THREAD

**Issue by minzdrav** [sourcegit-scm/sourcegit#455]
Hi @love-linger 
It would be nice to have a dropdown where users can select one of the latest subjects.
I usually do several commits for a single task and use task ID from Jira as a commit subject. This feature will save me time for alt-tabbing, switching tabs in the browser, and coping task id.

**Comment by love-linger** [comment]
I'm not sure if this is what you're talking about.
![image](https://github.com/user-attachments/assets/5be63a23-9211-4222-bb0d-9fb79f41edd6)

**Comment by minzdrav** [comment]
Thank you! Never noticed it here. Sorry 😅
