### ISSUE TITLE
Commit description - AI generation

### ISSUE THREAD

**Issue by minzdrav** [sourcegit-scm/sourcegit#456]
Hi @love-linger 
Is it possible to add a little button to generate a commit description (and new fields in the app config to select the model and endpoint)?
Sometimes I use https://github.com/anjerodev/commitollama Visual Studio Code plugin for that. The results are very good.
This plugin uses Ollama https://ollama.com/ to run the model locally. Which is perfect, because I don't want to send my code to OpenAI servers.
Here you can see a prompt example: https://github.com/anjerodev/commitollama/blob/main/src/generator.ts
Ollama C# library: https://www.nuget.org/packages/OllamaSharp
Thank you.

**Comment by love-linger** [comment]
For this feature, I seriously thought about it. At present, I don't have a good idea of how to integrate AI in this project, such as how to support users to configure other similar third-party services.

**Comment by Zuppremo** [comment]
I don't know if this is a good idea or feature, adding AI implementing another repository means that the mantainers in this project have now two concerns, if there's any problem with ollama project a lot of people will ask here why isn't working, and makes a bidirectional dependency.

**Comment by minzdrav** [comment]
Ollama and some other open-source services have an OpenAI compatibility layer: https://github.com/ollama/ollama/blob/main/docs/openai.md
If you worry about possible Ollama issues, you can use the official OpenAI library - https://www.nuget.org/packages/OpenAI/
Just don't forget to allow users to enter custom endpoint for alternative services like Azure, Ollama, etc.

**Comment by love-linger** [comment]
I've pushed a new branch `feature/openai-support`. 

https://github.com/user-attachments/assets/9a6e63b0-5d87-4fea-966c-0c48f7537f08

**Comment by love-linger** [comment]
It used only the OpenAI's standard HTTP API, and should work with all services that is compatible with OpenAI.

**Comment by love-linger** [comment]
The main reason why it is not submitted directly to the `develop` branch is that

* This implementation refers to the implementation of [anjerodev/commitollama] (https://github.com/anjerodev/commitollama) mentioned by @minzdrav, and since I am not familiar with AI Prompt, the prompt used in the software is completely copied from [anjerodev/commitollama] (https://github.com/anjerodev/commitollama).

**Comment by minzdrav** [comment]
@love-linger looks amazing!

**Comment by love-linger** [comment]
I have merged this feature into `develop`. close this issue

**Comment by minzdrav** [comment]
Hi @love-linger 
I've tested and it's perfect for me. But for newcomers, it would be nice to have options for quick setup.
Dropdown with option: OpenAI, Ollama, Custom
OpenAI - the user can enter the model name and API key
Ollama - the user can enter the model name
Custom - the user can enter the server URL, model name, API key

Thank you!
