### ISSUE TITLE
smba 查看 linux 仓库提示很多改动，但是实际上没有

### ISSUE THREAD

**Issue by heartacker** [sourcegit-scm/sourcegit#46]
linux 通过 smba 共享文件夹。
然后用 本软件查看，提示很多改动。
我该如何处理让他显示正确。

**Comment by love-linger** [comment]
这个是文件换行符的问题，取决于你的设置。Windows平台Git默认为CRLF，Linux为LF。

![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/949bdf78-70d0-4258-89a0-0942da08fc3e)

具体参见 https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration 中关于 Formatting and Whitespace

**Comment by heartacker** [comment]
已经更改了，我默认就是这样，试了好多次都这样
![image](https://github.com/sourcegit-scm/sourcegit/assets/1876302/30c65c99-def4-45d1-a43e-aa1cb1ae067e)
 
强制reset 后，还是这样

**Comment by love-linger** [comment]
如果 `core.autocrlf` 为 `true`，当检测到有变化，且文件中换行符一致（如果混用 CRLF 与 LF，GIT无法正确处理），手动add（也就是软件中的stage）后，不会产生提交的内容，它会自动转换。

当混用了CRLF与LF时，可先使用VSCode等文本编辑器，统一一下换行符

**Comment by love-linger** [comment]
这个与使用的软件与关，你手动执行 `git status`，也会看到这些文件变化。尽量保持文件中的换行符统一，并建议启用 `core.autocrlf`

**Comment by heartacker** [comment]
明白，但是我发现这个暂时无法避免，毕竟有很多文件，整个项目工程不是我一个人维护
是否可以添加有个按钮，点击这个按钮。就可以排除那些只有换行符的改动。让我能够看到真正的改动。方便做版本管理

**Comment by heartacker** [comment]
建议reopen

**Comment by love-linger** [comment]
> 明白，但是我发现这个暂时无法避免，毕竟有很多文件，整个项目工程不是我一个人维护 是否可以添加有个按钮，点击这个按钮。就可以排除那些只有换行符的改动。让我能够看到真正的改动。方便做版本管理

目前，我并没有查到相关的GIT指令可以过滤掉CRLF变化的文件。该操作需要对每个变更文件进行 `git diff --ignore-cr-at-eol` 并查看结果。有点难搞。

我自己无论什么提交，都需要一个个文件review变更，以确认是需要提交的内容。

**Comment by gadfly3173** [comment]
除了换行符，fileMode的变化也会导致这个问题，考虑到你是linux，这个情况可能性很高。
![image](https://github.com/sourcegit-scm/sourcegit/assets/28685179/db4b80f3-6d2a-4437-8111-3fc141f3c219)

用这个命令应该可以解决你的问题
```bash
git config core.filemode false
```
