### ISSUE TITLE
Feature request: Hide column, adjust column width, re-order column position, adjust spacing as per font size

### ISSUE THREAD

**Issue by lamyergeier** [sourcegit-scm/sourcegit#461]
- In the following image would be nice if one could Hide column (AUTHOR), adjust column width (COMMIT TIME), re-order column position (COMMIT TIME as first column), and save these settings when restarted.
- Customization: User-defined date format as per GNU date format (e.g. `Date=$(date +%Y-%m-%d)` so users can specify `+%Y-%m-%d`)

![image](https://github.com/user-attachments/assets/2886e69b-eaa3-42c1-b44c-5bacbcbe3b9c)

# Spacing can be adjusted as per font size so that it doesn't look cluttered on High-DPI screen

On my High resolution screen I would like to use Font size 28 to avoid straining my eyes (please adjust row height (multiple of font size, like 1.5 times or 2 times) and column width (fits column headers and still have some spacing from the edge, Left tab column width) for adequate spacing): 

![image](https://github.com/user-attachments/assets/813cf4d4-c016-41c7-949d-ad49ba1aead9)

**Comment by love-linger** [comment]
This article might be helpful to you https://github.com/AvaloniaUI/Avalonia/wiki/Configuring-X11-per-monitor-DPI.

This app actually has fully DPI awareness on Windows and macOS. On Linux, since there's so many desktop environments, it may not work by default. Currently, the `AvaloniaUI` (which UI framework used by this app) will try to read some global environment variables to do this job. The source code is:

```csharp
static IScalingProvider GetScalingProvider(AvaloniaX11Platform platform)
{
    var envSets = new[]
    {
        ("AVALONIA_GLOBAL_SCALE_FACTOR", "AVALONIA_SCREEN_SCALE_FACTORS", new[] { "AVALONIA_USE_PHYSICAL_DPI" })
    }.ToList();

    if (Environment.GetEnvironmentVariable("AVALONIA_SCREEN_SCALE_IGNORE_QT") != "1")
    {
        envSets.Add(("QT_SCALE_FACTOR", "QT_SCREEN_SCALE_FACTORS",
            new[] { "QT_AUTO_SCREEN_SCALE_FACTOR", "QT_USE_PHYSICAL_DPI" }));
    }

    UserScalingConfiguration? config = null;
    double global = 1;
    bool forceAuto = false;

    
    foreach (var envSet in envSets)
    {
        var envConfig = TryGetEnvConfiguration(envSet.Item1, envSet.Item2, envSet.Item3);
        if (envConfig != null)
        {
            (config, global, forceAuto) = envConfig.Value;
            break;
        }
    }

    IScalingProvider provider;
    if (config != null)
        provider = new UserConfiguredScalingProvider(config.NamedConfig, config.IndexedConfig);
    else if (forceAuto)
        provider = new PhysicalDpiScalingProvider();
    else 
        provider = new XrdbScalingProvider(platform);

    // ReSharper disable once CompareOfFloatsByEqualityOperator
    if (global != 1)
        provider = new PostMultiplyScalingProvider(provider, global);

    return provider;
}
```

**Comment by lamyergeier** [comment]
@love-linger Thanks, but I don't use X11 as most modern Linux desktops are now using Wayland. 

![image](https://github.com/user-attachments/assets/19e09ccb-8cdb-4d4c-9f7e-97f897444fd8)

May I suggest that you could provide users to be able to define line height factor as a multiple of Font size (as shown in the above image). And this line height factor can be defined in the software for all row height (also applicable to above image).

**Comment by love-linger** [comment]
https://github.com/AvaloniaUI/Avalonia/wiki/Configuring-X11-per-monitor-DPI this also works on Wayland since there are many of X11 software runs on XWayland

**Comment by love-linger** [comment]
* Actually, this project is a X11 application.
* The DPI scale affects not only fonts, but also all the visuals elements. 
* The way shows in https://github.com/AvaloniaUI/Avalonia/wiki/Configuring-X11-per-monitor-DPI also works well with multiple monitors those have difference DPI scales.

**Comment by love-linger** [comment]
close due to no more feedback

**Comment by lamyergeier** [comment]
@love-linger 

a side note: Any plans to migrate to Wayland?

**Comment by love-linger** [comment]
> a side note: Any plans to migrate to Wayland?

It depends on `AvaloniaUI` project.
