### ISSUE TITLE
[Bug] Sourcegit overwrites my GPG signature config

### ISSUE THREAD

**Issue by thomaslevesque** [sourcegit-scm/sourcegit#465]
When I just open the Preferences dialog and close it without making any change, Sourcegit adds this at the end of my global git config:

```gitconfig
[commit]
	gpgsign = false
[tag]
	gpgsign = false
[gpg "openpgp"]
	program = c:/Program Files (x86)/GnuPG/bin/gpg.exe

```

This overwrites a previous setting that sets `commit.gpgsign` to true. I only realized because the Github project I push to is configured to only accept signed commits.

Note that my Git config is a bit unusual. I use the same computer for work and personal projects, so I have a setup like this:

```gitconfig
[includeIf "gitdir:C:/Personal/code/"]
	path = C:/Personal/code/.gitconfig
[includeIf "gitdir:C:/Work/code/"]
	path = C:/Work/code/.gitconfig
```

The GPG signature settings (`user.signingkey` and `commit.gpgsign`) are set in the included files, not directly in the global .gitconfig file.

**Comment by thomaslevesque** [comment]
It doesn't overwrite settings that were directly set in the global .gitconfig, only those specified in the included config files.

**Comment by love-linger** [comment]
If some of the configuration data is only used by specified repository, why not use local configure file  of that repository directly?

**Comment by thomaslevesque** [comment]
> If some of the configuration data is only used by specified repository, why not use local configure file of that repository directly?

Because it affects many repositories, and I don't want to repeat the config in each one.
Anyway, it's a valid Git configuration, so it should be handled correctly by Sourcegit.
I don't think Sourcegit needs to specifically handle the `includeIf` part. Just calling `git config commit.gpgsign` in a repo gives the correct value, taking the includes into account.

**Comment by thomaslevesque** [comment]
> Because it affects many repositories, and I don't want to repeat the config in each one.

To clarify, the paths specified in `includeIf` are not paths to a specific repository, but to a directory that contains many repositories.

**Comment by love-linger** [comment]
Another way to resolve this issue is that you can move this settings before `includeIf` section. For example:
```
[commit]
	gpgsign = false
[tag]
	gpgsign = false
[gpg "openpgp"]
	program = c:/Program Files (x86)/GnuPG/bin/gpg.exe

...

[includeIf "gitdir:xxx"]
...
```

**Comment by thomaslevesque** [comment]
I guess I could, but that's a workaround, not a fix 😉 
How is Sourcegit reading the configuration? Doesn't it just use `git config`? Or the libgit equivalent?

**Comment by love-linger** [comment]
> I guess I could, but that's a workaround, not a fix 😉 How is Sourcegit reading the configuration? Doesn't it just use `git config`? Or the libgit equivalent?

Yes, for `Preference` window, it use `git config --global` command to get or set global git configuration.

**Comment by thomaslevesque** [comment]
Ah, I see. With `--global` it won't show the location specific settings.
Not sure what the right solution would be. It would make sense to have my `includeIf` at the end of the global git config, so that it overrides everything that comes before, but every time I set a global setting it will be added at the end, potentially overriding my location-specific config...
I guess it's an issue with Git rather than Sourcegit, then. Feel free to close, unless you have a great idea to fix it!

**Comment by love-linger** [comment]
This project do not use any other libraries to read or write repositories. Instead, it only use official git commands. That's why git is required by this app.

**Comment by thomaslevesque** [comment]
Related: https://stackoverflow.com/questions/78634897/git-config-option-not-being-overriden-in-an-includeif-config-file

**Comment by love-linger** [comment]
In fact, I really don't have a better idea. That's why the label for this issue has changed from `bug` to `question`.

**Comment by thomaslevesque** [comment]
That's fine. I understand the problem better now, and I don't think there's anything Sourcegit can do to fix it. Except, maybe, not touching the git config for settings I didn't changes in the Preferences window?
Anyway, thanks for listening!

**Comment by love-linger** [comment]
> That's fine. I understand the problem better now, and I don't think there's anything Sourcegit can do to fix it. Except, maybe, not touching the git config for settings I didn't changes in the Preferences window?

I tried this way. When implemented in this way, the code feels awkward. And I also need to be very careful about the configuration that may added in the future

**Comment by thomaslevesque** [comment]
> When implemented in this way, the code feels awkward.

I won't fight you on this, but it doesn't sound like a very good reason... The user doesn't care about what the code looks like 😉

**Comment by love-linger** [comment]
You can try the latest build from https://github.com/sourcegit-scm/sourcegit/actions/runs/10823102678

**Comment by thomaslevesque** [comment]
I'll give it a try, thanks!

**Comment by thomaslevesque** [comment]
It just added this:
```gitconfig
[gpg "openpgp"]
	program = c:/Program Files (x86)/GnuPG/bin/gpg.exe

```
Which is much better!
Does it need to be added though? I already had this and it worked fine:
```gitconfig
[gpg]
	program = c:/Program Files (x86)/GnuPG/bin/gpg.exe
	format = openpgp
```

**Comment by love-linger** [comment]
it's because this value has been changed through auto detection

**Comment by thomaslevesque** [comment]
> it's because this value has been changed through auto detection

Yes, I understand that. What I meant is that this setting isn't really necessary. Anyway, that's good enough for me. Thanks!
