### ISSUE TITLE
[Suggestion] repo tabs

### ISSUE THREAD

**Issue by lgranie** [sourcegit-scm/sourcegit#466]
Hi,

I would like to propose to improve the open repo tabs list ( on top ). I have got several repos ( > 10 ) to work on at the same time and navigating with the arrows ( left & right ) is slow.
I see two solutions :
  - right click propose a list of opened tabs
  - the "repositories" tab is always visible

Thx

**Comment by love-linger** [comment]
* Next release will add workspace support, you can use that to switch repositories in group. To test this feature, you can download the latest build from Github Actions.
* You can group your repositories in `Repositories` page. Then you can open all repositories in that group from context menu at once time
* The `Repositories` page can be opened by hotkey `Ctrl+T`. You can trait this hotkey as VSCode's `Ctrl+P` hotkey.

**Comment by lgranie** [comment]
Bravo
Workspaces is even a better solution and work great
Huge thx
