### ISSUE TITLE
Commit button - first click issue

### ISSUE THREAD

**Issue by minzdrav** [sourcegit-scm/sourcegit#467]
Hi @love-linger 
Please watch the attached video. The first click removes the tooltip and the second click executes the actual action.
Windows 11 23H2. I've tested and it's happening on several devices.

https://github.com/user-attachments/assets/af8464c8-8aef-4d24-8b9f-45451688d3a5

**Comment by love-linger** [comment]
Confirmed. It's a bug that exists in all `AvaloinaUI` apps. I'll create a issue to the `Avalonia` project about it.

**Comment by love-linger** [comment]
Currently, it only occurs when there's not enough space bellow the hovered button to display tooltips. And when the tooltip is displayed over the button, you can move your mouse horizontally before clicking the button.

**Comment by love-linger** [comment]
Good news. I've found anthor way to solve this problem. Just move the tooltip to `Top` instead of `Bottom`……
