### ISSUE TITLE
Allow input of arbitrary command for terminal

### ISSUE THREAD

**Issue by aikawayataro** [sourcegit-scm/sourcegit#471]
The current way of handling terminals for Linux is not very user friendly. There are a few of hardcoded terminals, and you have to add each of them to code. There's also no way to choose which terminal to use when there's more than one available

I suggest that this behavior be discarded. Better allow to select detected terminals and allow to specify arbitrary command for terminal (a simple combo box should work)
Current behavior of starting inside specified directory using command argument (`--working-directory`) should be replaced in favor of [specifying the working directory of the process](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.workingdirectory)
This new behavior could also be applied to Windows and Mac

It will be also handy for flatpak, because flatpak container can't see if any terminal installed on host, but user-specified command can be spawned with `flatpak-spawn --host` to workaround this.

**Comment by love-linger** [comment]
I've pushed a commit that rewrites the shell/terminal integration.
![image](https://github.com/user-attachments/assets/8b1c85f9-ee4c-45dc-b0bc-bce25c289ca1)

**Comment by aikawayataro** [comment]
Just what I wanted, thank you
