### ISSUE TITLE
Feature: Make commit info panel's height persistent

### ISSUE THREAD

**Issue by optimized-riyan** [sourcegit-scm/sourcegit#472]
I frequently navigate between the "histories" and "changes" tabs and the height of the commit preview panel always snaps back to the default. It is mildly inconvinient to resize the panel again & again with the activator only being 1px high.
[Screencast from 2024-09-14 14-19-57.webm](https://github.com/user-attachments/assets/6476a46b-e8db-452b-ba7d-94bd73329c59)

**Comment by love-linger** [comment]
done. You can test it from latest build https://github.com/sourcegit-scm/sourcegit/actions/runs/10861302874

**Comment by optimized-riyan** [comment]
That was quick thanks!
