### ISSUE TITLE
[Feature] Add Zed Editor to external tools list

### ISSUE THREAD

**Issue by ZorinFoss** [sourcegit-scm/sourcegit#477]
Hi,

Please add [Zed](https://github.com/zed-industries/zed) to external tools list

Thanks,

**Comment by love-linger** [comment]
done. you can test it from https://github.com/sourcegit-scm/sourcegit/actions/runs/10914196671

**Comment by ZorinFoss** [comment]
It works fine 👍🏻. Thank you ❤️

**Comment by love-linger** [comment]
> **Note**: Zed executable on linux is `zeditor` not `zed` and executable path is `/usr/bin/zeditor `
> 
> I edit it in `external_editors.json` and it works fine 👍🏻. Thank you ❤️

Thank you for your correction. I will correct this mistake tomorrow.
