### ISSUE TITLE
Add Velopack to support automatic installation on Linux/Windows/Mac

### ISSUE THREAD

**Issue by henry-js** [sourcegit-scm/sourcegit#478]
Velopack is a spiritual successor to Squirrel.Windows with cross-platform support

https://docs.velopack.io/getting-started/csharp

I don't mind submitting a PR for this

**Comment by Danielku15** [comment]
@love-linger Just stumbled over this before opening a similar request. Any feedback why this is not planned? Is it a "we don't want it" or more a "we don't have the capacity to do it"? 

I'd love to see a a more system integrated installation including updates.

Velopack seem to have everything built-in what's needed to build this without continuous maintenance efforts:

* GitHub Releases as updating source: https://docs.velopack.io/reference/cs/Velopack/Sources/GithubSource
* Code Signing for Security: https://docs.velopack.io/packaging/signing (I bet [SignPath](https://signpath.org/) would sponsor this project too)

I'd also consider contributing some initial efforts around this. 

Disclaimer: I just moved from another software to SourceGit and might be still be opinionated to the old habbits.
