### ISSUE TITLE
内建终端，而不是直接打开本地的终端。

### ISSUE THREAD

**Issue by heartacker** [sourcegit-scm/sourcegit#48]
又一个实用的大功能。
不知道 .net 是否已经有 ptyhost 管理方案，集成一个终端。
windows 下，可以打开本地的终端host
https://github.com/sourcegit-scm/sourcegit/issues/47 ssh 下，可以打开ssh 下的host。

**Comment by love-linger** [comment]
我并不认为我们需要内置这个功能。

* 本身这个软件指在用GUI的方式来处理GIT操作
* 对于需要手动执行GIT命令的，各平台都已实现`Open In Terminal`的功能
