### ISSUE TITLE
Unable to access the Stage/Unstage buttons in diff viewer when line wrap is enabled

### ISSUE THREAD

**Issue by WrichikBasu** [sourcegit-scm/sourcegit#481]
OS: Ubuntu 22.04.4, 64-bit
DE: Gnome 42.9, x11
Sourcegit version: 8.30.1 (amd64 AppImage)

As the title states, I am unable to click on the Stage/Unstage buttons when line wrap is enabled. When I try to go to the buttons, they disappear because the cursor is no longer hovering over the changes I want to stage. If I turn off line wrap though, I can access the buttons fine.

A screen video will possibly do a better job at explaining the issue:

https://github.com/user-attachments/assets/bbce5f85-a004-490d-b7ce-643d7c11952d

Will be happy to provide any further info, if any.

**Comment by love-linger** [comment]
Solved. You can try the latest build from https://github.com/sourcegit-scm/sourcegit/actions/runs/10905133722

**Comment by WrichikBasu** [comment]
Tested, works absolutely fine!
