### ISSUE TITLE
Make Keyboard Shortcuts Configurable

### ISSUE THREAD

**Issue by DeveloperPaul123** [sourcegit-scm/sourcegit#482]
It would be nice if we could configure shortcuts for the application instead of being forced to use a particular keyboard shortcut configuration.

**Comment by love-linger** [comment]
I'm very sorry, this feature is not in the development plan.

**Comment by DeveloperPaul123** [comment]
That is unfortunate. Would you accept a PR implementing this feature?

**Comment by love-linger** [comment]
Anyone is welcome to submit a PR.
