### ISSUE TITLE
[Bug] New window opened on failing fetch 

### ISSUE THREAD

**Issue by joesponde** [sourcegit-scm/sourcegit#485]
Hi,

When, in the git remote list, there is a server which is resolvable (DNS) but fails during authentication, a new SourceGit window is opened.
When autofetch is on, new windows are opened regularly.

I am using SourceGit in a Ubuntu 22.04 environment.

Here are the steps to reproduce the issue:
- add a "fake" remote git repo with the address `git@toto.fr:toto/toto.git`,
- launch a manual fetch on this remote only,
- a new window opens along with an error message in the parent window.

Here is a trace of this window creation with `ps`:

```
$ ps faux
...
joel      288502  8.1  0.6 274728864 213188 ?    Sl   10:35   0:11  |   \_ /opt/sourcegit/sourcegit
joel      290006  0.0  0.0  15360  4056 ?        S    10:37   0:00  |       \_ /usr/bin/git --no-pager -c core.quotepath=off -c credential.helper=manager -c core.editor="/opt/sourcegit/sourcegit" --core-e
joel      290007  0.1  0.0  19632  8040 ?        S    10:37   0:00  |           \_ /usr/bin/ssh -o SendEnv=GIT_PROTOCOL git@toto.fr git-upload-pack 'toto/toto.git'
joel      290008 41.0  0.6 274686400 196228 ?    Sl   10:37   0:02  |               \_ /opt/sourcegit/sourcegit The authenticity of host 'toto.fr (141.95.173.6)' can't be established. ED25519 key fingerpr
...
```

Regards,

**Comment by love-linger** [comment]
It's a BUG. `/opt/sourcegit/sourcegit The authenticity of host 'toto.fr (141.95.173.6)' can't be established. ED25519 key fingerpr` this commandline is suppose to launcher sourcegit as a SSH_ASKPASS client.

**Comment by love-linger** [comment]
Solved. This issue only appears when your remote is connected via SSH protocol without a valid private SSH key provided.

You can test the latest build from https://github.com/sourcegit-scm/sourcegit/actions/runs/10919275391

**Comment by joesponde** [comment]
I just tested the new AppImage, it works just fine!
I had another slightly different case, in the same area, it is fixed too.
Thanks @love-linger!

**Comment by joesponde** [comment]
I guess this issue is good to be closed.
