### ISSUE TITLE
Open AI commit message generation doesn't work

### ISSUE THREAD

**Issue by srn271** [sourcegit-scm/sourcegit#486]
Hi,

i installed the latest version of SourceGit (8.30) and ollama (0.3.11) and the llama3.1 model.

Whenever i try to generate a commit message, it only outputs a hyphen ("-") per staged file into the subject field.
So i tried the commitollama extension for vscode and there it works.

My settings:
Server: http://localhost:11434/api/generate
Model: llama3.1
API Key: (empty)

Is there any log file that i can investigate?

**Comment by love-linger** [comment]
change the server to OpenAI compatible layer http://localhost:11434/v1/chat/completions

**Comment by love-linger** [comment]
https://ollama.com/blog/openai-compatibility
