### ISSUE TITLE
[feature request] have variables inside commit templates/messages

### ISSUE THREAD

**Issue by catalin560** [sourcegit-scm/sourcegit#487]
have something like `${files}` that would list the updated files and output something like this: "Body.jsx, Navbar.jsx, Footer.jsx"
maybe have some params to limit the number of files, something like `${files:3}` which would output "Body.jsx, Navbar.jsx, Footer.jsx and 7 other files", or another example `${files:1}` to output "Body.jsx and 9 other files"
possible usage "Modified ${files:3} that are new" to output "Modified Body.jsx, Navbar.jsx, Footer.jsx and 7 other files that are new"

**Comment by love-linger** [comment]
Done. Users can use follow parameters in commit template:

- `${files_num}` will be replaced with staged changes count
- `${files}` will be replaced with changed file paths
- `${files:N}` will be replaced with top N changed file paths and with `and {TOTAL - N} other files` at end of replaced string.

**Comment by catalin560** [comment]
awesome job! thank you!

**Comment by catalin560** [comment]
Hello @love-linger it seems there is a bug in the `${files:N}` logic
![Capture](https://github.com/user-attachments/assets/3b1c8e13-f1d4-47ec-9e2a-e560b48e1479)
it seems to only enumerate the 1st file
this happens on version 8.34 of SourceGit

**Comment by love-linger** [comment]
Fixed. You can download the latest build from https://github.com/sourcegit-scm/sourcegit/actions/runs/11322941593
