### ISSUE TITLE
Option to not reopen last session

### ISSUE THREAD

**Issue by caioraphael1** [sourcegit-scm/sourcegit#488]
If I'm not mistaken, in v8.29 the session was not restored automatically when reopening the app, I really prefer that way, so could you please add an option to not restore the session in this case? If this option already exists, I'm not finding it ;/. Thanks

**Comment by love-linger** [comment]
Done. You can turn off the `Restore tabs on startup` from the workspace configuration dialog.

![image](https://github.com/user-attachments/assets/99cd7198-9bab-4add-8792-79edb197f767)
![image](https://github.com/user-attachments/assets/dd89df45-b143-4648-8760-887cb870f822)

You can test the latest build from https://github.com/sourcegit-scm/sourcegit/actions/runs/10923315720
