### ISSUE TITLE
"Open In Terminal" doesn't navigate to project in Windows Terminal

### ISSUE THREAD

**Issue by ZaLiTHkA** [sourcegit-scm/sourcegit#490]
I'm running SourceGit `8.30.1` on Windows 11 Pro 23H2 (build `22631.4169`), configured to use "Windows Terminal", which is currently on version `1.20.11781.0`.

with my project open, clicking the "Open In Terminal" button launches WT, but it stays at my home folder without navigating to my project folder.

switching the terminal selection in SourceGit to "PowerShell" _does_ navigate to my project folder (in WT, because that's my default in Windows), so I think this may only affect configs where SourceGit is explicitly trying to launch WT directly.

have MS perhaps changed the `wt.exe` CLI flags? doesn't looks like much has changed recent on this front in SourceGit.

**Comment by love-linger** [comment]
Solved. You can test the latest build from https://github.com/sourcegit-scm/sourcegit/actions/runs/10954191508

**Comment by ZaLiTHkA** [comment]
> Solved. You can test the latest build from [sourcegit-scm/sourcegit/actions/runs/10954191508](https://github.com/sourcegit-scm/sourcegit/actions/runs/10954191508)

sorted, thanks @love-linger. 🍻
