### ISSUE TITLE
enhanced: squash for multiple commit

### ISSUE THREAD

**Issue by xuthus5** [sourcegit-scm/sourcegit#492]
In the current version, only the `squash into parent` option is provided. Can support right-click and choose the `squash into one` option when multiple commit records are selected? This will help the developer who submits the final PR.
thx.

**Comment by love-linger** [comment]
I think you should be referring to this：

![image](https://github.com/user-attachments/assets/9be77065-6ddf-4dcc-a894-a1fc73443aa4)

> In the image above, `Squash Child Commits to Here` means squash all commits that after selected commit into the selected one

**Comment by xuthus5** [comment]
Thank you, I just started using it, which is a little different from the action of sublime merge and IDEA, and I didn't immediately find this option, I'll try it.
