### ISSUE TITLE
【特性需求】添加gpg sign相关配置属性

### ISSUE THREAD

**Issue by ca1e** [sourcegit-scm/sourcegit#5]
- 公共配置中增加gpg.program指明git所使用的gpg二进制所在路径
- 公共配置中增加commit.gpgsign=true|false表明每次commit是否需要签名
- 公共配置中增加user.signingkey全局指定每次签名用到的id（可选）

- 项目配置中增加commit.gpgsign=true|false表明每次commit是否需要签名
- 项目配置中增加user.signingkey指定当前项目每次签名用到的id

gpg签名可以有效验证commit是否是作者本人提交，有效的保证代码的安全性

**Comment by sourcegit-scm** [comment]
![image](https://user-images.githubusercontent.com/85621660/196930635-6333872d-549d-4df6-a1b5-089a43a9d7c4.png)
![image](https://user-images.githubusercontent.com/85621660/196930739-d3631701-7e23-4a1e-b626-7bff24dc2835.png)
