### ISSUE TITLE
The Chinese translation is garbled on MacOS15

### ISSUE THREAD

**Issue by zhengyongtao** [sourcegit-scm/sourcegit#500]
I am using MacOS, and when I updated to MacOS15, the Chinese translation became garbled
![image](https://github.com/user-attachments/assets/6ea6e991-b31b-4196-b953-0725d036137d)

**Comment by love-linger** [comment]
<img width="1129" alt="image" src="https://github.com/user-attachments/assets/0a3b2249-6f7f-47eb-80c9-def06042471a">


I'm also using macOS 15. It works fine. Which font do you use for `Default Font`?

**Comment by zhengyongtao** [comment]
> <img alt="image" width="1129" src="https://private-user-images.githubusercontent.com/4075673/369735313-0a3b2249-6f7f-47eb-80c9-def06042471a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNTc5OTgsIm5iZiI6MTcyNzA1NzY5OCwicGF0aCI6Ii80MDc1NjczLzM2OTczNTMxMy0wYTNiMjI0OS02ZjdmLTQ3ZWItODBjOS1kZWYwNjA0MjQ3MWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjNUMDIxNDU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzNiNTkwMDM0ZmE3MjE4NzRjM2MzMWQxNDUxYmEzZjk5MjljMjg4OTlmMDM1NDdhNDI0ZDlkYTI1ZGUzMGZmMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.9xA9ngX0A4TiMxdjPCQH--FK2w0v-QU4vBHIIN7DkVg">
> I'm also using macOS 15. It works fine. Which font do you use for `Default Font`?

I searched for the cause of this problem, in MacOS14 and before the system, the font book contains Apple square font (simplified), update to MacOS15 after the need to go to the font book download, no longer include Apple square font (simplified) by default.

**Comment by love-linger** [comment]
So, I'll close this issue because it is not belongs to this project

**Comment by zhengyongtao** [comment]
> So, I'll close this issue because it is not belongs to this project

Ok, thank you very much
