### ISSUE TITLE
It doesn't show or respond when viewing an old commit.

### ISSUE THREAD

**Issue by hieucckha** [sourcegit-scm/sourcegit#502]
Hello,

When I try to view the details of an old commit, the app doesn’t refresh or show the details after I click, but it works for newer commits.

Thanks.

**Comment by hieucckha** [comment]
Hello, when I updated SourceGit to version 8.31 (previously 8.30), the issue was fixed. I will close this issue.

> I don't quite understand what you mean by old commit and newer commit

It's like when I search for a commit from 2016, and when I click to see the details, nothing responds. It doesn't show the new information and leaves the old details displayed.

**Comment by love-linger** [comment]
You are right. This feature is added after 8.30 (available since 8.31) by commit 0ed1f369e9f22ad1e0d03aa08472cca85a51a39b
