### ISSUE TITLE
Remove width limit for changes list

### ISSUE THREAD

**Issue by DanielSWolf** [sourcegit-scm/sourcegit#503]
I can change the width of the changes list, but I can't make it broader than about 480 px. At this width, many file paths are truncated. Would it be possible to remove the width limit?

![image](https://github.com/user-attachments/assets/39c339b8-6fe0-47b6-a84b-ead6d0b25f64)

**Comment by love-linger** [comment]
done. you can download the latest build from https://github.com/sourcegit-scm/sourcegit/actions/runs/11005283063 to test this feature.

BTW, I suggest you use a tree view.
![image](https://github.com/user-attachments/assets/058aa3bc-0a5a-485c-a328-ab4b19b52fff)

**Comment by DanielSWolf** [comment]
I just downloaded the CI build, and it works fine. Thank you!

Regarding the tree view: I like stepping through changes using the cursor keys. In list view, UP/DOWN always gives me the next/previous changed file. In tree mode, I have to press the key multiple times to step over directories (see below), which is why I prefer the list view.

![image](https://github.com/user-attachments/assets/3b7d2b31-0e5c-4f8a-81ae-be7235f904fa)
