### ISSUE TITLE
After switching the repository tab, the selected commit may show wrong commit

### ISSUE THREAD

**Issue by gadfly3173** [sourcegit-scm/sourcegit#506]
Select a ~~non-latest~~ commit which is not at first page in one repository tab and switch to another repository tab where no commit is selected. After switching several times, the scroll offset in the two tabs will increase, and the information of the selected commit will be rendered incorrectly in the tab with the commit selected.

System: Deepin V23 X11

https://github.com/user-attachments/assets/f8f6c764-46b3-4b1c-ac79-7f19b723edf2

**Comment by love-linger** [comment]
Yes. I have noticed this issue before. This seems to be a problem with Avalonia ListBox.
