### ISSUE TITLE
sourcegit could not find git-lfs in my path

### ISSUE THREAD

**Issue by htw128** [sourcegit-scm/sourcegit#507]
When pulling, I encountered the following error:

``` log
This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting the 'post-checkout' file in the hooks directory (set by 'core.hookspath'; usually '.git/hooks').
```

Additionally, when switching branches, the switch command fails with the following error:

``` log
git-lfs filter-process: git-lfs: command not found
致命错误：远端意外挂断了
```

I checked in the terminal using which git-lfs, and it pointed to /opt/homebrew/bin/git-lfs.

The soucegit preferences are shown as follows:

<img width="604" alt="image" src="https://github.com/user-attachments/assets/272121f6-1369-491d-aef0-f451bcf94e6b">

Switching branches in the terminal works as usual. How do I fix this issue?

**Comment by love-linger** [comment]
It's very strange. I've added the `/opt/homebrew/bin` to the `PATH` enviroment variable. You can open `/Applications/SourceGit.app/Contents/Info.plist` to check if the following settings exists in it?

```xml
<dict>
    <key>PATH</key>
    <string>/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
</dict>
```

**Comment by love-linger** [comment]
similar to #168

**Comment by htw128** [comment]
> It's very strange. I've added the `/opt/homebrew/bin` to the `PATH` enviroment variable. You can open `/Applications/SourceGit.app/Contents/Info.plist` to check if the following settings exists in it?
> 
> ```
> <dict>
>     <key>PATH</key>
>     <string>/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
> </dict>
> ```

Yes, it's in the Info.plist file from line 16 to line 19.

**Comment by htw128** [comment]
I think it's worth mentioning that I'm running macOS Sequoia 15.0 (24A335).

**Comment by love-linger** [comment]
I'm also using macOS Sequoia. Currently, you can run `open -a SourceGit` from terminal to avoid this problem. I'll try to fix it later

**Comment by love-linger** [comment]
I found the right way to solve this problem.

1. run `launchctl setenv PATH $PATH`
2. restart your mac

**Comment by love-linger** [comment]
It's an common issue about GUI apps on macOS.

**Comment by love-linger** [comment]
Good news. I found anthor way to solve this problem. 

* Remove `LSEnvironment` from `Info.plist` since it's sometimes not working.
* Call `start.Environment.Add("PATH", "/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin")` before spawn git child-process.

Now, users need not to do extra jobs with this issue.

**Comment by love-linger** [comment]
you can download the latest build https://github.com/sourcegit-scm/sourcegit/actions/runs/11025474864

**Comment by htw128** [comment]
> you can download the latest build https://github.com/sourcegit-scm/sourcegit/actions/runs/11025474864

works for me, gracias!
