### ISSUE TITLE
[suggestion] - Being able to filter the tracking branch when filtering a local branch

### ISSUE THREAD

**Issue by lgranie** [sourcegit-scm/sourcegit#513]
Hi amazing dev,

Could be nice when I filter a local branch to include the tracking branch at the same time.

Thx

**Comment by love-linger** [comment]
done. you can download the latest build from https://github.com/sourcegit-scm/sourcegit/actions/runs/11033285532

**Comment by lgranie** [comment]
Exactly that!
Bravo
