### ISSUE TITLE
[Feature] Add merge and keep to Reset Mode menu

### ISSUE THREAD

**Issue by hellojianqun** [sourcegit-scm/sourcegit#514]
Git has provided two new reset mode, namely --merge and --keep. Please add them to the Reset Mode drop-down menu.

![image](https://github.com/user-attachments/assets/553ae6cb-397b-49a9-998c-ad04348c2540)

**Comment by love-linger** [comment]
done. you can download the latest build from https://github.com/sourcegit-scm/sourcegit/actions/runs/11045046296
