### ISSUE TITLE
Tab order not restored on startup

### ISSUE THREAD

**Issue by AdrienMatricon** [sourcegit-scm/sourcegit#516]
(installed v8.31 on Linux Mint 21.1 through the .deb)

Steps to reproduce :

1. Reorder tab
2. Close sourcegit
3. Reopen sourcegit

Tabs are back in their original order (which I think is the order in which I opened the repos in the first place)

**Comment by love-linger** [comment]
#511

**Comment by AdrienMatricon** [comment]
Oh, sorry, I'll look at the recently closed issues next time
