### ISSUE TITLE
Support for mouse-button copy and paste

### ISSUE THREAD

**Issue by AdrienMatricon** [sourcegit-scm/sourcegit#517]
sourcegit has good integration with the traditional clipboard, but does not seem to interact with Linux's mouse-button copy and paste (select text to copy it, then use a middle click to paste it). It would be nice if that worked too

**Comment by love-linger** [comment]
I'm very sorry. For the follow reasons, this feature will not be planed.

* This is not a cross-platform well-known copy-paste way
* I've seen more than one of my friends that use the middle-button-press action as context menu trigger or other custom functions.
* If you want to paste selected into anthor software, the copied text must exists in the system clipboard. However, this project will use the clipboard in some cases, for example, it will try to read repository URL from clipboard after a new `Clone` popup is just opened

**Comment by AdrienMatricon** [comment]
Hello,

If I understand correctly, your answer is that users on most systems expect copy/paste to happen using ctrl+X and ctrl+V (or an equivalent) and that it would be wrong to mess with that when people are simply selecting text or performing a middle-click, just because some system out there uses a non-mainstream way of performing copy/paste.

If that is indeed what you meant, then I am glad to say that is not what I'm talking about here. I assume that Linux is not your OS of choice, so let me correct a few misconceptions :
- what you call "the system clipboard", singular, is actually two distinct clipboards on Linux (or more accurately, on X11 systems)
  * one is the desktop-environment clipboard, which is the traditional copy/paste using ctrl+X and ctrl+V, it behaves exactly the same way on Linux that it does on Mac or Windows
  * another one is the X clipboard (look up "X selection" for more on this if you're curious), which exclusively relies on select + middle click, and does not interfere at all with the desktop-environment clipboard
- most Linux users, while not necessarily savvy on the details, know they can (and expect to be able to) copy two texts at the same time, through two totally independent clipboards
- adding support for mouse copy/paste therefore does not prevent the application from being cross-platform, on the contrary it allows it to be better integrated into some platforms without taking anything from the others
- cross-platform UI libraries usually have built-in functionalities to handle this; for example I've worked with Qt in C++ in the past, and it has [clipboard modes](https://doc.qt.io/qt-6/qclipboard.html#Mode-enum) that can be used to specify which clipboard to put things into / pull things from

I'd say the real question here is whether the UI library used in this project does have support for this

**Comment by love-linger** [comment]
I checked the ISSUES of AvaloniaUI and found some relevant information, see https://github.com/AvaloniaUI/Avalonia/issues/11011. Unfortunately, AvaloniaUI does not currently support this feature.
