### ISSUE TITLE
Automatically include newly created branch in filters?

### ISSUE THREAD

**Issue by Gama11** [sourcegit-scm/sourcegit#518]
I think it's a bit counterintuitive that when you have a filter on e.g. `origin/master` and create + check out a new branch, you can't see it without performing an additional, manual step (adding a filter for the new branch).

I don't quite remember how this worked in Fork, but I think that was handled better.

Maybe the current branch should be added to the filters automatically?

**Comment by love-linger** [comment]
done. you can download the latest build from https://github.com/sourcegit-scm/sourcegit/actions/runs/11052373393

**Comment by Gama11** [comment]
Nice, thank you!

**Comment by love-linger** [comment]
> [!NOTE]
> if the filter list contains all branches after added the checkout target branch (and its upstream if possible), the filter list will be cleared.
