### ISSUE TITLE
Ctrl+Shift+Enter to stage all + commit

### ISSUE THREAD

**Issue by Gama11** [sourcegit-scm/sourcegit#521]
Currently you can use Ctrl+Enter in the commit message field to commit. I would also like to be able to use Ctrl+Shift+Enter to stage all unstaged files + commit. If I remember correctly, this shortcut existed in SourceTree.

I don't really like using the auto-stage checkbox for this, as I don't _always_ want to stage all files. When I activate it, it usually leads to me accidentally staging all files sometimes because the state is persisted.

**Comment by love-linger** [comment]
it has been used by the 'Commit and Push' button

**Comment by love-linger** [comment]
Done. But the hotkey has been changed to `Alt+Enter` (Windows/Linux) or `⌥+Enter` (macOS).
<img width="342" alt="image" src="https://github.com/user-attachments/assets/4a88c4fd-e442-49e1-b4a4-69cb16bd01a7">

You can download the latest build from https://github.com/sourcegit-scm/sourcegit/actions/runs/11072389854
