### ISSUE TITLE
Links doesn't always trigger mouse pointer change

### ISSUE THREAD

**Issue by Shimoon** [sourcegit-scm/sourcegit#522]
# Problem
Commits hash in file history and blame views don't trigger mouse pointer change which is not makes it really intuitive that we can click on it.
This is actually working well in the "Information" tab (parent commits).

# Examples
_File History view :_
![file_history_links](https://github.com/user-attachments/assets/9f5f1c12-56e2-4e0b-8922-6dacd2920ea7)

_Blame view :_
![file_blame_links](https://github.com/user-attachments/assets/6bd1a4db-8045-4688-86c7-98853770e88f)

_Example of working mouse pointer change :_ 
![working_links](https://github.com/user-attachments/assets/3b2aae6c-9fcf-4539-885c-a0c111d9ba15)

**Comment by love-linger** [comment]
done.

**Comment by Shimoon** [comment]
Awesome, thank you !
