### ISSUE TITLE
[BUG] - Cannot select the last line in blame

### ISSUE THREAD

**Issue by Shimoon** [sourcegit-scm/sourcegit#523]
# Problem
In the blame view, the last line of a file cannot be selected.

# Example
![blame_last_line_issue](https://github.com/user-attachments/assets/35fe8d6a-a5f5-4687-860d-bb9e2d4e69f4)

**Comment by love-linger** [comment]
fixed.

**Comment by Shimoon** [comment]
It's working now, thanks a lot !
