### ISSUE TITLE
[ENHANCEMENT] - Improve the "Commit Is Contained By" popup

### ISSUE THREAD

**Issue by Shimoon** [sourcegit-scm/sourcegit#524]
Right now, when hovering the popup, the mouse pointer is changed and shows a hand which indicate to the user that the listed items can be clicked which is not the case.
But it seems to me that it would be a pretty good addition to this menu.

# Proposal
Make all the listed items clickable so that it would go and select the item in the commits graph.

# Mockup
![clickable_items](https://github.com/user-attachments/assets/a5adec12-3832-4dc9-8f02-b5630dff5990)

**Comment by love-linger** [comment]
In fact, the elements in this list should not respond to click events. Cursor becomes `Hand` due to an bug of `Avalonia` - the `Flyout` control inherits the style of its `PlacentmentTarget`.

**Comment by love-linger** [comment]
I've changed the Cursor of `Flyout` to default

**Comment by Shimoon** [comment]
Why not make the elements clickable ? It would be handy to quickly jump to the wanted item from there.

**Comment by love-linger** [comment]
It's because that currently we only gets the refnames of branches or tags that contains the selected commit. To navigate to some commit, such as branch HEAD, we must know the target commit's SHA

**Comment by Shimoon** [comment]
Okay, make sense.
I'm closing this issue then !
