### ISSUE TITLE
Two unrelated git branches will have curve offset points in the CommitGraph

### ISSUE THREAD

**Issue by gadfly3173** [sourcegit-scm/sourcegit#528]
![image](https://github.com/user-attachments/assets/5c400219-b57d-448b-a037-9cdd0a9b17e2)

**Comment by love-linger** [comment]
Fixed

**Comment by gadfly3173** [comment]
the example in issue is fixed, another situation has similar problem. 
![image](https://github.com/user-attachments/assets/66cfb500-e2c8-48b0-9636-14b3e7f381fb)

**Comment by love-linger** [comment]
Can you provide the example git repository to me?

**Comment by gadfly3173** [comment]
you can check https://github.com/gadfly3173/test-git

**Comment by gadfly3173** [comment]
This is the effect of `git graph` in `vscode`

![image](https://github.com/user-attachments/assets/2bc4d021-cee3-4b52-9c7a-23bd5f7b30d0)

**Comment by love-linger** [comment]
done

**Comment by love-linger** [comment]
Finally:

![image](https://github.com/user-attachments/assets/e51ac670-5014-4762-9459-ca93bf810dfd)

**Comment by love-linger** [comment]
Finally++:

![image](https://github.com/user-attachments/assets/90efb02f-a2ed-40cd-93c0-99a734dfd709)

**Comment by love-linger** [comment]
Finally+++:

![image](https://github.com/user-attachments/assets/52b05d41-0b4c-433c-a363-725906007211)

**Comment by gadfly3173** [comment]
Sorry I was working overtime, perfect job. This works very good for me.
