### ISSUE TITLE
[Feature Request]  外部比较工具

### ISSUE THREAD

**Issue by prime167** [sourcegit-scm/sourcegit#53]
建议支持外部比较工具，如 Beyond Compare

**Comment by love-linger** [comment]
你可按下面步骤启用外部对比工具。

1. 在Preference中，配置对比工具
![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/6dc987ac-d449-4da8-993c-ee289300ec91)
2. 在DiffView中，使用外部比对工具查看
![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/b7dc9a55-bb46-4fd5-8f99-2196d561d131)

**Comment by prime167** [comment]
![image](https://github.com/sourcegit-scm/sourcegit/assets/3722845/3bd5dfcb-db5f-4a1e-84f3-53286068579a)

这个.cs文件是加密过的，右上角没有菜单项。另外能不能在文件右键菜单里加上“使用外部合并工具查看”的选项

**Comment by love-linger** [comment]
您可下载 https://github.com/sourcegit-scm/sourcegit/actions/runs/8531970354/artifacts/1379623886

**Comment by prime167** [comment]
赞，用上了。

期待右键菜单项和快捷方式

**Comment by tosione** [comment]
I'm using v2025.33 and I still have similar issues:
Beyond compare opens correctly when compared files are plain-text files (.c, .h, .csv, .md, ...) but nothings happens when files are binary (I'm trying to open excel files to compare with beyond compare: .xlsm).
