### ISSUE TITLE
[Feature] Add custom actions executed on triggers

### ISSUE THREAD

**Issue by SebastianSchumann** [sourcegit-scm/sourcegit#531]
We're using submodules in our git repo. After switching a branch we've to run `git submodule update` to point to the correct submodule branch/commit. Currently it must be done using bash.
It would be great if a `git submodule update` could run automatically after a branch checkout.
A configuration for this would be nice, where you could link different triggers and git commands.

Triggers might be:
- after branch switch
- after branch create
- before branch delete

Another use case after switching a branch might be running `git clean -ffdx` because C# projects contains unversioned directories like `obj` and `bin` that should be removed to prevent using wrong references/binaries.

**Comment by love-linger** [comment]
* I'll add the auto-update submodule feature after checking out another branch
* Currently, this project provides a button (next to the SUBMODULES group name) to update submodule
* Untracked files will not be deleted unless you discard those files manually. And you can do it from the context menu of current branch or from the context menu of selected local changes.

**Comment by SebastianSchumann** [comment]
I tested your changes and it works like a charm - this makes branch switching a bit safer. Many thanks.

However, deleting the files does not work using the context menu. The context menu only says `Discard all changes`, which does not include files from `.gitignore`.

There is also a `.gitignore` file in your repository which excludes `bin` and `obj`. The `obj` folder contains information about which NuGet packages are used, including the version number. If you change to a version branch, these can differ from `main`, which can lead to problems. The context menu entry is disabled if there are no changes detected, even if there are ignored files.

`Discard all changes` is not the same as `git clean -ffdx`.

**Comment by love-linger** [comment]
I know that. But I think that this operation should be left to the user to decide on their own. For example, `node_modules` that is usually included in `.gitignore`. Another example is some user-defined local script files and so on. These should not be automatically deleted.

**Comment by SebastianSchumann** [comment]
I'm with you that this should not be called automatically and the user should to that with full awareness.

But it would be nice to configure some custom actions that could be called from context menu on the branch name. That's only an idea. We do that clean operation quite often due to branch switching and it would be nice if this could be done out of the SourceGit-UI directly.

**Comment by love-linger** [comment]
Done. A checkbox has been added to include all ignored files when discard all changes in repo.

<img width="541" alt="image" src="https://github.com/user-attachments/assets/0ca29740-1689-4282-952d-eb8a470d8b09">

**Comment by SebastianSchumann** [comment]
Cool - many thanks.
