### ISSUE TITLE
Merge develop into main as an example and use 'Don't commit' don't work

### ISSUE THREAD

**Issue by Mike710Shine** [sourcegit-scm/sourcegit#532]
If i try to merge the development branch into the main branch and use the option 'Don't commit' it direkt commit all the changes to the main branch. For my expactation it should open the commit site not direkt commit it.

![grafik](https://github.com/user-attachments/assets/407ef3c2-dbf9-4868-8a33-3d9ca510a9db)

click to ok
![grafik](https://github.com/user-attachments/assets/81c05b25-894e-4a14-ac96-d077ebe73577)

an for my point of view it should go into here.
![grafik](https://github.com/user-attachments/assets/26c471cc-083a-4a91-a0ff-d3d7f0318faf)

**Comment by love-linger** [comment]
Fixed. You can try the latest build from Github Action.

**Comment by Mike710Shine** [comment]
Cool it seems to work. Thanks again.
