### ISSUE TITLE
Support file path display modes in staging area

### ISSUE THREAD

**Issue by Gama11** [sourcegit-scm/sourcegit#533]
The changes tab supports different display modes:

![image](https://github.com/user-attachments/assets/69aaeb56-33c8-409e-9511-4c45cd200272)

It would be nice if these were supported in the unstaged / staged areas as well, to have a consistent experience.

**Comment by love-linger** [comment]
<img width="332" alt="image" src="https://github.com/user-attachments/assets/7e202308-4f07-4d0a-9b49-9d8d702382b5">

**Comment by Gama11** [comment]
Oh, I guess I'm blind. :sweat_smile:

I didn't realize those were buttons, I thought that's just an icon like the ones here (same color and same position before the text, and all the other buttons in the staging area are on the right and brighter):

![image](https://github.com/user-attachments/assets/9ebf10f7-a220-4020-a955-d1464fe3282c)

**Comment by love-linger** [comment]
I'll move these buttons to the right group
