### ISSUE TITLE
[Feature] Default remote

### ISSUE THREAD

**Issue by srn271** [sourcegit-scm/sourcegit#534]
We work with more than a handful of remotes due to forks.
When a new branch is created, the first remote defined for pushing changes is always preselected.
This is rarely the correct remote.

Let's say we have defined the following remotes:
- bar
- foo
- origin
- upstream

I would like to be able to push new (untracked) branches to **origin** by default.
Instead, **bar** is preselected, as this is the first remote alphabetically.

This feature could also improve the solution made for #469 (auto-selection).
Another GIT client (SourceTree) has this feature integrated, I would be happy if it were also possible here.

**Comment by love-linger** [comment]
Done. You can try the latest build from Github Actions
<img width="712" alt="image" src="https://github.com/user-attachments/assets/01164727-19d8-4e14-96f9-17eb01e19b61">

The new rule to auto select push targets is:

* If the current local branch is tracking with some remote branch, select it directly.
* If the current local branch has no upstream remote branch
  - If you have set the `Default Remote` in repository's configuration window, select the default remote, and the try to find a branch with same name or just create a new branch
  - If you never set the `Default Remote`, select the first remote and do the same job.

**Comment by srn271** [comment]
Works! Super! Great that it was implemented so quickly! (not even an hour 😅)
