### ISSUE TITLE
[Feature] Add a way to only stash staged files

### ISSUE THREAD

**Issue by step-ani-motion** [sourcegit-scm/sourcegit#535]
As per [git docs](https://git-scm.com/docs/git-stash#Documentation/git-stash.txt-Savingunrelatedchangesforfutureuse)

`git stash push --staged -m "Stashed Stuff"`

Allows for stashing selected lines/hunks instead of whole files.

**Comment by ameaninglessname** [comment]
It's already supported in the built-in diff window, move your mouse to these lines, there would be buttons appearing.

**Comment by love-linger** [comment]
> It's already supported in the built-in diff window, move your mouse to these lines, there would be buttons appearing.

In fact, you misunderstood what he meant. This function is indeed not available at present.

**Comment by love-linger** [comment]
done. you can try the latest build from Github Action https://github.com/sourcegit-scm/sourcegit/actions/runs/11160464442
