### ISSUE TITLE
[UX improment] add tooltips for files in the staged/unstaged area

### ISSUE THREAD

**Issue by ameaninglessname** [sourcegit-scm/sourcegit#537]
![image](https://github.com/user-attachments/assets/628ad9cb-e54b-41db-ab9a-b25b8fef4c9a)
These icons is beautiful but I don't know all the meanings of them. A tool-tip would help users like me have a better understanding about what these actions are(added, removed, moved, renamed, etc.). Or is there a place to take reference of what exactly it means?

More related information could be considered adding to the tool-tip.

Thanks for this great tool.

**Comment by love-linger** [comment]
done. you can try the latest build from Github Action.

<img width="164" alt="image" src="https://github.com/user-attachments/assets/0546b836-ce5c-47a7-a1fe-faf5b0e2dcbd">
