### ISSUE TITLE
Inconsistent fonts after recent updates

### ISSUE THREAD

**Issue by vrnvorona** [sourcegit-scm/sourcegit#538]
Hi, first of all wanted to say big thank you for this client, it's awesome and works great on Ubuntu which is rare. Good replacement for Fork client.

However one note since i finally updated from 8.26 to latest version. Honestly can't say it not harsh, but new font selection is outright bad.

Some things are CAPS, some are Normal, some fonts are very bold, some are very thin. Very inconsistent.

Personally I love most font from this part 
![image](https://github.com/user-attachments/assets/c3a34a05-4734-423b-83f1-01d30eb2882d)

font for commit names and info is also fine as well for plain text. But other stuff is weird. Search field, menu items etc.

**Comment by love-linger** [comment]
I'm not a native English speaker. Welcome everyone to create a pull request and make corrections to some places that do not conform to English language habits.。

**Comment by vrnvorona** [comment]
It's not about language/wording, but font itself aka how letters look like

**Comment by love-linger** [comment]
there are only two fonts used by this software. if you don't enable the 'Only use monospace font in text editor' option, the software will only use a single monospace font for all the text

**Comment by love-linger** [comment]
Could you use pictures and text to illustrate which places seem to have problems or areas that need improvement? You can also provide reference solutions from other softwares, and it would be best if they are also illustrated with pictures and text?

**Comment by love-linger** [comment]
Since there's no feedback, I'll close this issue first.
