### ISSUE TITLE
error: `env: node: No such file or directory`

### ISSUE THREAD

**Issue by BeLi4L** [sourcegit-scm/sourcegit#539]
When I try to commit some changes, I have the following error: `env: node: No such file or directory`as you see on this screenshot:

![image](https://github.com/user-attachments/assets/13cd53cc-9467-41de-9b8d-10f4c3c3f2f1)

I guess it's due to a pre-commit in my repo that uses yarn/node. Usually `node` is on my PATH, because I run `nvm` setup scripts in both .bashrc and .zshrc.

Any idea of why Sourcegit can't find `node`? Does it use a special shell or path? 🤔

**Comment by love-linger** [comment]
it's because your sourcegit process is not started via bash or zsh. Are you using Sourcegit on macOS?

**Comment by BeLi4L** [comment]
Yes I'm on macOS

**Comment by love-linger** [comment]
The simplest way to solve this problem is changing the hook script's interpreter to `/bin/zsh`. For example:

```shell
#!/bin/zsh

node xxxxxx
```

**Comment by aikawayataro** [comment]
`.*rc` files are only sourced when the shell is called interactively so to make it work with zsh, you should do PATH magic at `.zshenv'. There is no direct equivalent to bash though.

**Comment by BeLi4L** [comment]
Thanks for your quick answers! ❤️ 

My hook scripts actually use `#!/bin/sh` so I just added `[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"` to every script, and it works 🥳

**Comment by BeLi4L** [comment]
I noticed that **VS Code** doesn't have this issue (whereas sourcegit & some other git GUIs have it) @love-linger

Any idea why? Are they doing anything differently? 🤔 

I'm asking because to fix this in my company, I'd have to update every git hook in every repo, which is a huge pain, and may cause issues on some people's environments 😅

**Comment by gadfly3173** [comment]
I guess it's because vscode reads various shell configuration files by itself.

https://github.com/microsoft/vscode/blob/3ae1a2259222266236891f983a0a9229b491998d/src/vs/workbench/contrib/terminal/common/scripts/shellIntegration-bash.sh

**Comment by BeLi4L** [comment]
Not sure I understand 🤔 

Doing that would only allow me to access the `nvm` command, which isn't what I want, since the `nvm.sh` script is only a config script, which defines a `nvm` command, and adds the correct node/npm versions to PATH, which is what I want.

In a perfect world, I'd like to have the git GUIs I use do this kind of thing, because I don't want to update EVERY git hook and tell EVERY developer in the company to add a symbolic link somewhere, whereas it's not necessary in VS code 😅

**Comment by BeLi4L** [comment]
> I guess it's because vscode reads various shell configuration files by itself.
> 
> https://github.com/microsoft/vscode/blob/3ae1a2259222266236891f983a0a9229b491998d/src/vs/workbench/contrib/terminal/common/scripts/shellIntegration-bash.sh

Oh right I see thanks! ;)

**Comment by love-linger** [comment]
If you are using the latest build from Github Action, you can start SourceGit from commandline `open -a SourceGit`. It will introduce the `PATH` environment variable to SourceGit

**Comment by BeLi4L** [comment]
Thanks for the tip ;)

Unfortunately it didn't work: I just downloaded v8.33, tried `open -a SourceGit` and it still can't find node, even though it is on the PATH of the shell where I ran the command

**Comment by love-linger** [comment]
not the latest release, i mean the latest ci build from github action

**Comment by love-linger** [comment]
here https://github.com/sourcegit-scm/sourcegit/actions/runs/11290039325

**Comment by love-linger** [comment]
this feature was added by PR #546 which is not included by `8.33`

**Comment by love-linger** [comment]
I've pushed a new commit that try to read the `PATH` environment variable from `zsh`. You can download the latest build from https://github.com/sourcegit-scm/sourcegit/actions/runs/11324273608

**Comment by BeLi4L** [comment]
I downloaded v8.34 and it works! 🥳 (using `open -a SourceGit`)

Thank you very much 😉

**Comment by love-linger** [comment]
@BeLi4L If it's convenient for you, you can download the latest CI build from Github Action - instead of needing to start from the command line, it will read the `PATH` variable from `zsh` at startup

**Comment by BeLi4L** [comment]
Oh nice! Thank you :innocent: 

I prefer to use stable & versioned builds though, I guess I'll wait, since it's not an issue right now ;)
