### ISSUE TITLE
SourceGit not respecting system wide Git settings

### ISSUE THREAD

**Issue by leo-liar** [sourcegit-scm/sourcegit#544]
Hello, I'm using a portable version of Git for Windows and have all of my general configuration not in repository or user specific `.gitconfig` files but use instead a _systemwide_ git config (i.e. the `gitconfig` file in the install / portable Git folder).

Until recently SourceGit did respect this configuration (and showed my `gitconfig` settings in the preferences accordingly) but one of the recent updates (due to vacation I skipped some but I was on 8.28 previously) changed this and now said preferences are emtpy (e.g. especially Git and GPG settings) and if I configure them via SourceGit then a new and otherwise empty `.gitconfig` file is created in my user folder – which I do not want and which conflicts with my system wide settings.

Maybe related: Previous versions of SourceGit also did pass environment variables to git subprocesses spawned by it (which I used for some proxy specific port configurations for git via ssh by setting `GIT_SSH_COMMAND`) but the recent version doesn't do that anymore.

As a result with SourceGit 8.32 I can't pull/push to repositories via ssh due to port errors because my specific configuration isn't used.

**Comment by love-linger** [comment]
> Until recently SourceGit did respect this configuration (and showed my gitconfig settings in the preferences accordingly) but one of the recent updates (due to vacation I skipped some but I was on 8.28 previously) changed this and now said preferences are emtpy (e.g. especially Git and GPG settings) and if I configure them via SourceGit then a new and otherwise empty .gitconfig file is created in my user folder – which I do not want and which conflicts with my system wide settings.

The `Commands/Config.cs` file has not been changed since version `8.24`. The project obtains GIT configurations from this interface. In theory, the runtime behavior should not change.

> Maybe related: Previous versions of SourceGit also did pass environment variables to git subprocesses spawned by it (which I used for some proxy specific port configurations for git via ssh by setting GIT_SSH_COMMAND) but the recent version doesn't do that anymore.

This is because before the program creates a GIT subprocess, `GIT_SSH_COMMAND` is set in the code. The code is: 
```csharp
if (!string.IsNullOrEmpty(SSHKey))
    start.Environment.Add("GIT_SSH_COMMAND", $"ssh -o StrictHostKeyChecking=accept-new -i '{SSHKey}'");
else
    start.Environment.Add("GIT_SSH_COMMAND", $"ssh -o StrictHostKeyChecking=accept-new");
```
Therefore, the `GIT_SSH_COMMAND` set by the user will be overwritten.

**Comment by leo-liar** [comment]
Thanks for the reply and explanation!

Is it possible to enable SourceGit to respect system wide Git settings and/or use previously defined environment variables like `GIT_SSH_COMMAND`?

**Comment by love-linger** [comment]
Let me think about how to better support these features

**Comment by love-linger** [comment]
At present, changing the global configuration will still write to the user-scope `.gitconfig` file, but scope parameter, such as `--system`, `--global` and `--local`, has been removed while reading git configuration.

**Comment by love-linger** [comment]
So, I'll close this issue

**Comment by leo-liar** [comment]
Small problem:
SourceGit is reading my system wide settings correctly but if I open the preferences dialog (even if I don't change anything) then, upon closing SourceGit, a user `.gitconfig` file is created containing only one line regarding the GPG executable. (Which is already defined in my system wide config.)

**Comment by love-linger** [comment]
git supports both `gpg.<format>.program` or `gpg.program`. While saving git configuration, we use the first one to avoid override the path for other format

**Comment by love-linger** [comment]
You can try the latest build from Github Action or just modify your system-wide git configuration by using the new `gpg.<format>.program` format

**Comment by leo-liar** [comment]
I tried the latest build and it worked as intended!

Thanks for taking the time and quickly implementing solutions for both issues!
