### ISSUE TITLE
[Regression Issue] - MacOS - sourcegit can't find npm global modules

### ISSUE THREAD

**Issue by yitzchak-ben-ezra-ecoplant** [sourcegit-scm/sourcegit#545]
Hi @love-linger 

Since you delivered this:  #507 I have an issue

the environment I'm using is this

1. shell: `zsh`
2. upon changing directory - `nvm` sets the correct `npm` version to be used
3. with the correct npm version I installed `pnpm` globally (`npm i -g pnpm`)
4. we have precommit hook that triggers something with `pnpm`
5. In order for source git to work with the correct `npm` version I'm launching it from `zsh` on the repo folder (to have the correct `npm` version) with this command: `open -a /Applications/SourceGit.app`

it used to work
now when I commit I see this message:
```
nx/.husky/pre-commit: line 4: pnpm: command not found
husky - pre-commit script failed (code 127)
husky - command not found in PATH=node_modules/.bin:/Applications/Xcode.app/Contents/Developer/usr/libexec/git-core:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

my full PATH from zsh is:
```
/Users/USERNAME/.pyenv/plugins/pyenv-virtualenv/shims:/Users/USERNAME/.pyenv/shims:/Users/USERNAME/.pyenv/bin:/opt/homebrew/opt/libpq/bin:/Users/USERNAME/.nvm/versions/node/v20.15.0/bin:/usr/local/share/dotnet:/opt/homebrew/bin:/Users/USERNAME/.local/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/GPAC.app/Contents/MacOS/:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/iTerm.app/Contents/Resources/utilities:/Users/USERNAME/Library/Application Support/JetBrains/Toolbox/scripts
```

I believe the important part is: `/Users/USERNAME/.nvm/versions/node/v20.15.0/bin`

do you see it as a bug?
what can we do with this?

**Comment by aikawayataro** [comment]
I believe a8685f2047bb226761453d0db57cb4c0cc82372f is the culprit. It should append to PATH not override it

**Comment by aikawayataro** [comment]
Do you mind test this?

```diff
diff --git a/src/Commands/Command.cs b/src/Commands/Command.cs
index 55fc6d17..13c7b7ad 100644
--- a/src/Commands/Command.cs
+++ b/src/Commands/Command.cs
@@ -199,7 +199,15 @@ namespace SourceGit.Commands
 
             // Fix sometimes `LSEnvironment` not working on macOS
             if (OperatingSystem.IsMacOS())
-                start.Environment.Add("PATH", "/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin");
+            {
+                var path = start.Environment["PATH"];
+                if (path is null) {
+                    path = "/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin";
+                } else {
+                    path = "/opt/homebrew/bin:/opt/homebrew/sbin:" + path;
+                }
+                start.Environment.Add("PATH", path);
+            }
 
             // Force using this app as git editor.
             switch (Editor)
```

**Comment by love-linger** [comment]
> I believe [a8685f2](https://github.com/sourcegit-scm/sourcegit/commit/a8685f2047bb226761453d0db57cb4c0cc82372f) is the culprit. It should append to PATH not override it

In fact, this operation is applicable in most cases. Because, after packaging the program as an app (not debuging in IDE), double-clicking to start does not introduce any PATH variables set in any bash (such as `zsh`), but always '/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin'.

I have tried to use `LSEnvironment` in `Info.plist`, but the operation has sometimes failed, as described in the ISSUE quoted above.

I have also guided users to use the `launchctl setenv PATH $PATH` command to import the `PATH` variable set in bash into `LaunchAgent`, but this issue has still been reported in some cases, such as #168.

So far, I have not found the most suitable solution to this problem

**Comment by aikawayataro** [comment]
> In fact, this operation is applicable in most cases. Because, after packaging the program as an app (not debuging in IDE), double-clicking to start does not introduce any PATH variables set in any bash (such as zsh), but always '/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin'.

Yes, I was aware of this, and it looks like there's no way to globally append to the PATH on Mac.

> So far, I have not found the most suitable solution to this problem

What about the patch I attached in the previous message? It will keep PATH if you run SourceGit from an interactive shell.

**Comment by love-linger** [comment]
> What about the patch I attached in the previous message? It will keep PATH if you run SourceGit from an interactive shell.

I like this patch, you can create a PR for this enhancement.

**Comment by yitzchak-ben-ezra-ecoplant** [comment]
I don't know how to test it
because when launching from VSCode is not the same like launching from terminal
but I believe that your solution will fix it :)
I'll wait for next release

**Comment by aikawayataro** [comment]
> I don't know how to test it

https://github.com/sourcegit-scm/sourcegit/actions/runs/11231132796/job/31219903749?pr=546

You can grab package from CI once it is finished

**Comment by love-linger** [comment]
I've pushed a new commit that try to read the `PATH` environment variable from `zsh`. You can download the latest build from https://github.com/sourcegit-scm/sourcegit/actions/runs/11324273608
