### ISSUE TITLE
[Feature] Show stash in commit graph

### ISSUE THREAD

**Issue by bwachtendorf** [sourcegit-scm/sourcegit#548]
Currently stashes are only visible on the "Stashes" menu and its hard to see where they fit in on the commit graph.
Would it be possible to show stashes in the commit graph and allow things like pop and apply stash via the context menu?

**Comment by duke1995** [comment]
Knowing which commit you were at when the changes were stashed is valuable information about the stash, in my opinion. Seeing the stashes in the commit graph (similarly to how it's done in Sublime Merge for example) makes them more useful, I think.
