### ISSUE TITLE
[Bug] Python syntax highlighting bugged on multiline string

### ISSUE THREAD

**Issue by bwachtendorf** [sourcegit-scm/sourcegit#549]
When displaying changes with a python multiline string where the start of the string is not visible in the diff, the syntax highlighting will break and interpret everything as a string.
Example:
![syntax_highlighting_bugged](https://github.com/user-attachments/assets/c2c0d42c-9088-466c-a817-ecf913f01cd3)

The bug disappears when increasing visible lines until the start of the string is visible.
Example:
![syntax_highlighting_works](https://github.com/user-attachments/assets/af2f8792-3ff7-4951-871c-a6b6efee6ee1)

**Comment by love-linger** [comment]
...
In fact, it's not a BUG. Syntax highlighting does not guarantee exactly correct execution in git hunks, since the context lines that have not been changed may not be included.

**Comment by aikawayataro** [comment]
I think it can be fixed if whole file is highlighted first, but then it will add a whole lot of complexity to reconstruct diff view.
Better to mark it as not-planned than invalid?
