### ISSUE TITLE
Default mode for `git reset`

### ISSUE THREAD

**Issue by AdrienMatricon** [sourcegit-scm/sourcegit#551]
- The `git reset` command can be performed with various modes (`--soft`, `--mixed`, `--hard`, `--merge`, `--keep`)
- Trying to perform a reset through sourcegit opens a pop-up asking to choose a mode among those
- The default choice in the pop-up (`--soft`) does not match the default mode in the git command line (`--mixed`)
- I assume that this is not on purpose (though if there is an actual demand for changing the default to `--soft`, I suggest adding a field in the Preferences menu instead to let the users tune the behavior)

**Comment by love-linger** [comment]
Now the default reset mode has been changed to `--mixed`, you can download the latest build from Github Action.
