### ISSUE TITLE
[Bug] Python multiline string in diff hunk header breaks syntax highlighting

### ISSUE THREAD

**Issue by bwachtendorf** [sourcegit-scm/sourcegit#552]
Similar to #549 but not quite the same, so I figured it warrants a new issue.

When git diff interprets an object instantiation with a multiline string as a function header and includes the quotation marks in the header of the hunk, syntax highlighting breaks and interprets everything as a string:
Example:
![syntax_highlighting_bugged_hunk_header](https://github.com/user-attachments/assets/43968c8e-cf14-43f1-af40-9540886fb267)

This fixes itself when the quotation marks are not included in the hunk header anymore.
Example:
![syntax_highlighting_works_hunk_header](https://github.com/user-attachments/assets/ac08efa7-6540-4920-89c3-eba638e38973)

**Comment by love-linger** [comment]
Same reason as #549

**Comment by bwachtendorf** [comment]
Can the hunk header not be excluded from syntax highlighting?
I understand, that the issue in #549 requires a different approach to syntax highlighting, because the quotation marks are part of the changed code, but in this case the header is not part of the code.
Is the complete diff highlighted instead of just the parts inside the hunks?

**Comment by love-linger** [comment]
I've checked the source code if AvaloniaEdit. To implement this feature, it is probably necessary to rewrite a `AvaloniaEdit.TextMate`. This is not in the development plan.
