### ISSUE TITLE
Changing the repository URL only changes the fetch url

### ISSUE THREAD

**Issue by DaKaLKa** [sourcegit-scm/sourcegit#553]
Using version 8.33 with git version 
![grafik](https://github.com/user-attachments/assets/f34126dd-17fd-4b6a-923f-5abf495f3854)

I have changed the remote URL of the origin to a new URL:
![grafik](https://github.com/user-attachments/assets/04f8244a-31ad-4fc2-b2c3-4441f12ea2d6)

But this only changes the url for the fetch - push is still using the "old" url.
![grafik](https://github.com/user-attachments/assets/573a3679-c12d-4e38-a8ae-cd6c4f414889)

I think the 
https://github.com/sourcegit-scm/sourcegit/blob/master/src/Commands/Remote.cs#L37 
should execute a second git command with the "--push"-option 
or there should be two options to set the fetch and pull url (maybe one is optional and use the fetch if no pull url is defined)

**Comment by pmandalka** [comment]
Ok, this is not really am issue. In one of my repositories the push-url was set to some value.
After removing it with
`git remote set-url --delete --push origin <url>`
sourcegit changes both url correctly. 

But maybe this should be optional possible to change both (fetch and push url) if defined.

**Comment by DaKaLKa** [comment]
I added a PR draft for this issue https://github.com/sourcegit-scm/sourcegit/pull/554

**Comment by love-linger** [comment]
I prefer to force using the same URL for both fetch and push while changing the URL of remote. As the git manual says, when fetch and push URLs are different, we should use multiple remotes instead of multiple URLs in one remote.

![image](https://github.com/user-attachments/assets/4255bb5f-859d-4e34-9e59-3795614f0ecd)

**Comment by love-linger** [comment]
I've pushed my modification to solve this issue. It will checking the push url with the new one, and update it when they are not equal

**Comment by DaKaLKa** [comment]
Seems legit for me. I also have no use case for separating fetch and push URL. 
Thanks for the solution.
