### ISSUE TITLE
feature: CLI support

### ISSUE THREAD

**Issue by alumni** [sourcegit-scm/sourcegit#555]
I'd like to open SourceGit from an external application automatically (e.g. VSCode).

So some CLI options that open SourceGit would be nice, e.g., for opening a certain repo or blaming a certain file.

**Comment by love-linger** [comment]
currently, it only supports open repository from command line by using `sourcegit <repo_path>` (Linux) or `SourceGit.exe <repo_path>` (Windows)

**Comment by alumni** [comment]
> currently, it only supports open repository from command line by using `sourcegit <repo_path>` (Linux) or `SourceGit.exe <repo_path>` (Windows)

Good to know, I was looking for some CLI flags by passing `--help`, but nothing showed up, so I assumed there is no CLI support.
