### ISSUE TITLE
Request to Enlarge Error Messages for Better Visibility

### ISSUE THREAD

**Issue by enricocap** [sourcegit-scm/sourcegit#556]
The current error messages displayed in the application are too small, making them difficult to read, especially for users with visual impairments or those working on smaller screens. A larger, more visible error message would improve the overall user experience and accessibility.

Impact: This enhancement will provide a better user experience, especially for users with accessibility needs, and reduce the likelihood of missed error notifications.

**Comment by love-linger** [comment]
In fact, the error messages uses the same font size as the main window, and you can change it from preference window.

**Comment by enricocap** [comment]
I didn’t explain my problem correctly. The issue is that the error message popup needs more space to display longer error messages. For instance, when using commit message policies, the text isn’t very readable, as window width is too narrow.

![image](https://github.com/user-attachments/assets/a2861b15-4a6f-4d1c-b27a-01a2d817d827)

**Comment by love-linger** [comment]
Done. You can download the latest CI build from Github Action.
