### ISSUE TITLE
Add some key bindings

### ISSUE THREAD

**Issue by Jogai** [sourcegit-scm/sourcegit#557]
I've been searching for a decent git-gui, but mostly I kept using the cli because nothing gave me a decent experience. Luckily I found sourcegit which is miles (yes, I mean that literally) ahead on the rest (for linux at least, on windows fork was okay I guess). 

During rebase it would be nice to do ALT+ arrow up/down for moving a commit one position up/down. I was used to a tui wich had this, plus some others, so for inpiration maybe check https://github.com/MitMaro/git-interactive-rebase-tool/?tab=readme-ov-file#common-default-key-bindings

**Comment by love-linger** [comment]
done. you can download the latest CI build from github action.
