### ISSUE TITLE
commit node 可以查看改动，merge node无法查看任何 改动。

### ISSUE THREAD

**Issue by heartacker** [sourcegit-scm/sourcegit#56]
1. 理论上应该显示整个改动的总和

- 普通的提交

![image](https://github.com/sourcegit-scm/sourcegit/assets/1876302/0a76e0c2-db92-43fc-afd6-e407adc2deed)

-  合并的提交 

![image](https://github.com/sourcegit-scm/sourcegit/assets/1876302/515ab67f-1ed4-400e-8f0d-9cf386a82786)

**Comment by love-linger** [comment]
merge 是否有Files变更，取决于merge操作本身是否对文件增加了改动。比如，我在merge的同时 amend 了其他的文件修改。

如果merge仅仅包含简单的合并，是不会显示其变更的（因为它有两个parent）

如果单独查看对每个parent的差异，请使用Ctrl选择merge的commit与需要比对的parent的commit. 比如：

![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/f92eb817-d0a9-45d1-84a4-95bbaf51be9c)

该操作的意义是，对比merge完成后，与绿色标示的提交路线上的差异

**Comment by love-linger** [comment]
又比如，选中 SourceGit 的 7866a1103725a4cf1f77670d80a88136b9bf32c6 提交，可看到，该merge节点是存在变更列表的
![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/e0af567b-cf99-425d-8c11-fc4af26d7ba2)
它指明了，我合并两个提交的同时加入了自己的修改（或冲突合并）操作

**Comment by heartacker** [comment]
这是 vscode 的一个插件
如果点击合入的node，显示合入的总和，
我觉得无论是github还是很多软件都是这样的哦  
Meged 本身就是也提交。应该能够显示 所有的改动  

merge
![image](https://github.com/sourcegit-scm/sourcegit/assets/1876302/a6f89ffd-c383-46d1-9381-60c690842a6d)

commit
![image](https://github.com/sourcegit-scm/sourcegit/assets/1876302/a2c9b3f1-1106-42bf-b78f-b5ab01177a47)

**Comment by love-linger** [comment]
看了GitGraph与Github的功能。

* 它们是默认与第一个parent对比。这就将本身这个commit附带的修改合并计算了。该软件采用`git show HASH` 查看本commit的修改理念是仅显示本提交涉及的更改，且这时显示author可以明确为作者，而非commiter。 
* 软件提供了 revision diff 的功能，以方便查看合并操作相对于其某一提交路线的差异

基于上述两点，不会做出修改

**Comment by heartacker** [comment]
好的，那能否添加一个快捷 option，选项之类的。
默认不变和现在一样，但是一键显示所有改动。

对于你提供的方式，也是一个方式，只是这个方法比较隐蔽，不是很符合大众的习惯。
