### ISSUE TITLE
[Feature] Mark conflict file as resolved

### ISSUE THREAD

**Issue by hpfs0** [sourcegit-scm/sourcegit#560]
There is a suggestion, could you add a menu to mark the conflict file as resolved by right-clicking the file in the conflict file list?

![image](https://github.com/user-attachments/assets/d2452b29-c057-488f-a27e-ff1d38900186)

**Comment by love-linger** [comment]
I'm not sure what you mean by "mark conflict file as resolved". How does this behavior work in the git command line?

**Comment by love-linger** [comment]
If you have manually resolved all conflicts in selected file, the diff view will show a tip like this:

![image](https://github.com/user-attachments/assets/e8316d1c-7a42-4fb8-9459-ba181d34cca8)

**Comment by love-linger** [comment]
For conflict files:

* You can use context menu item `Use Theirs (checkout --theirs)` to resolve all the conflicts by using incoming changes
* You can use context menu item `Use Mine (checkout --ours)` to resolve all the conflicts by keep current changes in index
* If you have configure the external diff/merge tool in perference, you can use context menu item `Open External Merge Tool` to resolve conflicts in the external editor. And after you save and close the editor, the selected file will be staged automatically when all the conflicts have been resolved.

**Comment by hpfs0** [comment]
Sourcetree has such a menu, which is convenient to use. My understanding is that it only marks the file as non-conflicting.
![image](https://github.com/user-attachments/assets/dd063ef0-1609-4a55-bd10-aaae6159a5f8)

**Comment by love-linger** [comment]
I've downloaded SourceTree and tested it.

I found out that it will stage this file directly.

https://github.com/user-attachments/assets/46002992-28b6-428b-9491-32134af0e55b

**Comment by love-linger** [comment]
I found the SourceTree provides a window to watch the background git commands, and it shows the same with what I thought:

![image](https://github.com/user-attachments/assets/572b8efe-1ac0-48ed-8a6d-5b81fb040556)

**Comment by hpfs0** [comment]
> I've downloaded SourceTree and tested it.
> 
> I found out that it will stage this file directly.
> 
>  test.mp4

That's right, I mean you can directly modify the file conflict status when you click the menu.

**Comment by love-linger** [comment]
> > I've downloaded SourceTree and tested it.
> > I found out that it will stage this file directly.
> > test.mp4
> 
> That's right, I mean you can directly modify the file conflict status when you click the menu.

So, why not just stage this file by double-clicking it?

**Comment by hpfs0** [comment]
> > > I've downloaded SourceTree and tested it.
> > > I found out that it will stage this file directly.
> > > test.mp4
> > 
> > 
> > That's right, I mean you can directly modify the file conflict status when you click the menu.
> 
> So, why not just stage this file by double-clicking it?

SourceGit will always prompt that the file has a conflict until the conflict status changes.

**Comment by love-linger** [comment]
https://github.com/user-attachments/assets/ea3b787e-a0b4-4957-b933-cdfb002d2eb3

You can see the video. Staging a file that has conflicts directly in SourceGit is the same with `Mark as resolved` in SourceTree.

**Comment by love-linger** [comment]
It's because what `Mark as resolve` does in SourceTree is the same that staging (which actually runs `git add`) in SourceGit. After a file is added into the index, the status of it can not be `Conflict`.

**Comment by hpfs0** [comment]
> test.mp4 
> You can see the video. Staging a file that has conflicts directly in SourceGit is the same with `Mark as resolved` in SourceTree.

After watching the video, I found that the file was `commit directly` after clicking the solve button. Sometimes I don’t want to commit immediately, but just want to resolve the file conflict.

**Comment by hpfs0** [comment]
When all conflicting files are marked as `non-conflicting`, SourceGit will no longer prompt conflicts. Is that better?

**Comment by love-linger** [comment]
It's because you are in merging progress see the `git status` output:

![image](https://github.com/user-attachments/assets/cfdc5afb-5a4f-4161-8b86-c36c436e883f)

And SourceGit will display the in-progress bar if your are merging/cherry-picking/rebasing/reverting.

![image](https://github.com/user-attachments/assets/212e5510-3bb7-4eed-b14a-ba733b1d861d)

**Comment by hpfs0** [comment]
If all conflicting files are merged manually, can I commit manually instead of clicking the Next or Abort Merge button in the conflict prompt bar?

**Comment by hpfs0** [comment]
> Reference in

If all conflicting files are merged manually, can I commit manually instead of clicking the Next or Abort Merge button in the conflict prompt bar?

**Comment by hpfs0** [comment]
> It's because you are in merging progress see the `git status` output:
> 
> ![image](https://private-user-images.githubusercontent.com/4075673/375941301-cfdc5afb-5a4f-4161-8b86-c36c436e883f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MjI4ODEsIm5iZiI6MTcyODcyMjU4MSwicGF0aCI6Ii80MDc1NjczLzM3NTk0MTMwMS1jZmRjNWFmYi01YTRmLTQxNjEtOGI4Ni1jMzZjNDM2ZTg4M2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTJUMDg0MzAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2ExNTgzOTlmNzBlZmJmOGY3OWFhMmVjMjhmYTlmMDY2YjRlYjY4MzcxNjMxMTBmYjNjNWRlOGE3YWNmZDIxNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.bMOo1L7Qnf2SutLmULE9JNnIFS_YNmqkrTwx9j4hC80)
> 
> And SourceGit will display the in-progress bar if your are merging/cherry-picking/rebasing/reverting.
> 
> ![image](https://private-user-images.githubusercontent.com/4075673/375941439-212e5510-3bb7-4eed-b14a-ba733b1d861d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MjI4ODEsIm5iZiI6MTcyODcyMjU4MSwicGF0aCI6Ii80MDc1NjczLzM3NTk0MTQzOS0yMTJlNTUxMC0zYmI3LTRlZWQtYjE0YS1iYTczM2IxZDg2MWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTJUMDg0MzAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDFkNTIwZjA3MWRiOWRhYjRkZWEzNjRhNjUxYTMzYzgxYjYyZTI0OTRlZTIyM2IxYmNhMDExNDJjNzRiNjEyZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.EP6eT0jNTs_CP7p-NMErR7EgLDCIF1VzPezD4Y-rc4o)

If all conflicting files are merged manually, can I commit manually instead of clicking the Next or Abort Merge button in the conflict prompt bar?

**Comment by love-linger** [comment]
The yellow background bar indicates that current job (merge/cherry-pick/rebase/revert) is interrupted due to a conflict or an empty commit, rather than necessarily a conflict.

上面的黄色的背景栏指的是正在进行的某些操作（比如merge/cherry-pick/rebase/revert）因某个提交存在冲突或是产生了空的提交（存在已被cherry-pick的提交）而中止，并非一定是存在冲突。

For example, during the execution of a rebase operation involving multiple commits, there may be multiple conflicts. The In-progress bar above will remain until it is completed or aborted.

比如，当执行涉及多个提交的rebase操作时，其实际上是先切换到目标分支，再将源分支的新提交一个接一个的pick到该分支上，这时就可能会产生多次冲突。这时continue操作表示冲突已解决，可以继续rebase。（当然，点击Commit按钮也会产生与continue相同的作用）。而rebase-inprogress-bar会一直显示，直到rebase操作彻底完成或被提前终止。

**Comment by love-linger** [comment]
To make it simple - it represents the part that marked in picture below, rather than the state of the file.

![image](https://github.com/user-attachments/assets/06a691ee-da19-452e-b90d-7888bf06eb61)

**Comment by love-linger** [comment]
Another example - rebasing:

![image](https://github.com/user-attachments/assets/f1de62eb-72ed-44cf-a6d2-684615b174ee)

**Comment by hpfs0** [comment]
The yellow background bar is not directly related to the file conflict, it just indicates that there is a conflict in the merge operation. Since you can click the commit button, the yellow background bar will automatically disappear after the merge conflict is completed manually. Then I will close this issue.

**Comment by love-linger** [comment]
> The yellow background bar is not directly related to the file conflict, it just indicates that there is a conflict in the merge operation. Since you can click the commit button, the yellow background bar will automatically disappear after the merge conflict is completed manually. Then I will close this issue. Thank you so much !

It needs to be corrected - The yellow background bar is not directly related to the file conflict, it just indicates that there is a <s>conflict in the merge operation</s> git operation that is still in progress, and you need to choose `continue` or `abort`.

**Comment by hpfs0** [comment]
> > The yellow background bar is not directly related to the file conflict, it just indicates that there is a conflict in the merge operation. Since you can click the commit button, the yellow background bar will automatically disappear after the merge conflict is completed manually. Then I will close this issue. Thank you so much !
> 
> It needs to be corrected - The yellow background bar is not directly related to the file conflict, it just indicates that there is a conflict in the merge operation git operation that is still in progress, and you need to choose `continue` or `abort`.

I see ! Thanks again !
