### ISSUE TITLE
cherry-pick of merge-commit lacks -m option

### ISSUE THREAD

**Issue by SebastianSchumann** [sourcegit-scm/sourcegit#563]
We use merge commits for merging branches into main to make it easier to transfer them to other branches.

If you try to cherry-pick such a commit in SourceGit, it will be rejected with the following error message:

```
error: commit 9f79b0cbd4df08b9b237d65395a9e449a1e593cb is a merge but no -m option was given.
fatal: cherry-pick failed
```

But you have no chance at all to specify or select anything. A cherry-pick of a merge commit simply does not seem to be possible.

In order to be able to reproduce the problem directly, the following script initializes a repo, provides a `main` branch with a merge commit and creates a `release` branch into which this merge commit can be cherry-picked:

```bash
# init
git init --initial-branch main .
echo "init" > init.txt
git add .
git commit -m "init"

git branch release

# dev
git checkout -b dev
echo "first" > first.txt
git add .
git commit -m "first added"
echo "second" > second.txt
git add .
git commit -m "second added"

# merge into main using merge commit
git checkout main
git merge --no-ff -m "Merge branch 'dev'" dev
git branch -D dev

# switch to release
git checkout release
```

Afterwards, you can try to cherry-pick this commit to the `release` branch in SourceGit.
The above error message will appear.

**Comment by love-linger** [comment]
done, you can download the latest build from Github Action.

**Comment by SebastianSchumann** [comment]
thx. tested it - works perfectly
