### ISSUE TITLE
[Feature Request] Matching colour between branch line and branch name background

### ISSUE THREAD

**Issue by Cirtoyt** [sourcegit-scm/sourcegit#564]
Hiya,

I've just started to use SourceGit as I'm finally fed-up with SourceTree, and have so far been very happy with everything SourceGit has to offer!

One thing I did want to suggest perhaps was that the background colour of branch names were to match the colour of the branch line they are currently next to? So far for me my first branch is Orange, but subsequent branch lines all have different colours, yet the branch names' background all match that first orange colour. It would be great if there was an option to sync these colours together, so that in this following example image the background of the "QA-Testing" branch name was Yellow, and the "NPCMenuFixes" was Cyan to match their corresponding branch colours where their commits are currently on:

![image](https://github.com/user-attachments/assets/ccaeb152-4eed-4691-a93a-e72182a1aac3)

**Comment by love-linger** [comment]
As I said before in issue #395, I don't want to make the graph too complex.

* Regarding your suggestion, the purpose is to make it easier to find out which path in graph is associated with the target commit. This is not difficult in the current implementation - there will be three kinds of identifiers on the path where the current commit is located. This is much easier than looking at the color of the branch name (or background color) first, then find path in graph by this color.
* Under the current implementation, the name and its background have good contrast. If its background is the same as the color of path in graph, there is no guarantee that the color of the text will be well distinguished from the background.

**Comment by Cirtoyt** [comment]
For me, I'm a very visual person, so I find it much more complex when everything is the same colour, and much cleaner and easier to read when the branches are colour matched with their line colours.

I can understand the inconsistent contrast being a possible issue though. To fix this, perhaps it could be good to add an outline around branch name blocks? Otherwise, so far I feel the line colours themselves stand out enough, so would be worth adding this option in to at least demo it I guess. Better yet, for users who like me are more visual, it could be good to offer this as an appearance option in the preferences menu.

**Comment by Cirtoyt** [comment]
Wow! That looks amazing!
So much clearer now! Thanks so much!

My last change would be to either revert the currently checked out branch name to show as white/black (invert of light/dark theme), as that also helped clarify where I was, or make the background colour match the full colour of the border. I know currently it shows slightly lighter, but it's hard to see from being too subtle on some colours:

![image](https://github.com/user-attachments/assets/43157ef1-781d-4e1f-bffe-b465db9923a2)

**Comment by love-linger** [comment]
I've pushed a new style for current HEAD

![image](https://github.com/user-attachments/assets/5c9cf751-7cdb-4f49-9e4a-8e40b5bf70e6)

**Comment by love-linger** [comment]
One more thing, from your screenshot, it can be seen that you have chosen an inappropriate font for `Default Font` - it is not vertical aligned properly.

**Comment by Cirtoyt** [comment]
Yup this higher contrast looks great for the head! Thanks so much!

Yes I see what you mean with my font. I currently have it set to Calibri, which is pretty popular online, but guess it isn't setup to handle the vertical alignment properly as you mentioned, as other fonts I type in do format correctly.

**Comment by love-linger** [comment]
Then I'll close this issue as completed
