### ISSUE TITLE
[ feature request ] - open remote git repository from button / context menu of the remote branch

### ISSUE THREAD

**Issue by wlazlomarek** [sourcegit-scm/sourcegit#565]
Just an option (shelf button, option in branch context menu) to open remote repository in the browser, if available. 
You can get a remote URL of the repo by using: `git config --get remote.origin.url`

Cheers!

**Comment by love-linger** [comment]
there is already a context menu item to do this from remote

**Comment by wlazlomarek** [comment]
yes, my bad :) Found it
