### ISSUE TITLE
Gitflow not working on version 8.34 in Mac OS

### ISSUE THREAD

**Issue by filipeRmlh** [sourcegit-scm/sourcegit#566]
The issue might be due to the change on how PATH enviroment variable are obtained in Mac OS.

SO: MacOS Sonoma
SourceGit Version: 8.34
Hardware: Macbook Pro - 2020 (intel x64)

-- With 8.33 I have no problem using gitflow.

Message: 
"git: 'flow' is not a git command. See 'git --help'.
The most similar commands are
	reflog
	show"

**Comment by love-linger** [comment]
did you try the latest ci build from github action？

**Comment by love-linger** [comment]
https://github.com/sourcegit-scm/sourcegit/actions/runs/11337556020

**Comment by love-linger** [comment]
#539
