### ISSUE TITLE
How to show the message of tag ?

### ISSUE THREAD

**Issue by ChiaYen-Kan** [sourcegit-scm/sourcegit#567]
hi
tag be created with some message, but in sourcegit i can't see this message
how i can see the message of tag ?
thank you

**Comment by love-linger** [comment]
Currently, there's no way to display the message for annotated tag.

**Comment by ChiaYen-Kan** [comment]
is it possible support it in the future ?

**Comment by love-linger** [comment]
The command to show the message of a tag is `git tag -l --format="%(contents:subject)%0a%0a%(contents:body)" $TAG`. The main problem now is that I haven't figured out where and how to display this information.

**Comment by love-linger** [comment]
Done. You can download the latest CI build from https://github.com/sourcegit-scm/sourcegit/actions/runs/11379915691
![image](https://github.com/user-attachments/assets/55c90d75-81da-45df-bb7e-78d490f081e0)

**Comment by ChiaYen-Kan** [comment]
Hi

a little difference from my imagine

1
long tag message will become a big tooltip
![tooltip-mode](https://github.com/user-attachments/assets/252fd82b-c280-47a4-b9c5-45ae5c2810a1)

2
if tag message is empty tooltip will show the commit message

3
tag message can't be copy just like commit message

may be can reference TortoiseGit display approach, upper is commit message, lower tag message
![tortoise-git](https://github.com/user-attachments/assets/77221c91-1d2a-4b9c-8311-662e227c5566)

thank you

**Comment by love-linger** [comment]
> long tag message will become a big tooltip

Yes, it should be displayed entirety. Otherwise, there is nowhere else to display this information.

> if tag message is empty tooltip will show the commit message

I do no think so. The tooltip should only shows the message of tag. If you want to check the message of commit. You can just click this tag. Then the commit detail will shows the info it.

> tag message can't be copy just like commit message

I'll add a context menu item to copy the message of commit
