### ISSUE TITLE
change the max width of left panel?

### ISSUE THREAD

**Issue by tiancj** [sourcegit-scm/sourcegit#569]
if the branch name is too long, left panel may not shows the full name of the branch.

![image](https://github.com/user-attachments/assets/72f80cc9-bc2f-4cb6-813e-786c123f39b0)

**Comment by love-linger** [comment]
I know this. That's why I added a mouse hover tooltip to show the full name of a branch.

**Comment by love-linger** [comment]
Done. The max width of left panel in repository view has been changed to 500px. You can download the latest CI build from Github Action https://github.com/sourcegit-scm/sourcegit/actions/runs/11360921843
