### ISSUE TITLE
[Feature] Checkout and Fast-Forward when double-clicking on remote branch in graph 

### ISSUE THREAD

**Issue by jeffwlawson** [sourcegit-scm/sourcegit#572]
When your local branch is behind the remote branch and you double-click on the remote branch in the graph view, would it be possible to have it prompt you to checkout the local branch and fast-forward it to the remote branch.  Similar to how Fork does it?

![image](https://github.com/user-attachments/assets/c0dd55a3-61a3-4a8b-9642-aba8b4281f3b)

Currently it prompt you to create a new branch, which for me isn't what I would expect that action to perform.

![image](https://github.com/user-attachments/assets/4b9d23aa-c380-4aeb-b8b8-a99a9d0493b2)

**Comment by love-linger** [comment]
The behavior of double-clicking a branch is unified in this software as `Checkout Branch`. It will be different on following situations:

* Already the current branch, do nothing
* Local branch that is not the current branch
  - If there are uncommitted local changes, the `Checkout Branch` panel will pop up, asking the user to confirm the action on the changes
  - No uncommitted local changes, checkout the target branche directly
* Remote branch
  - If there is a local branch tracks the remote branch, switch to the local branch as described above
  - If there is not a local branch tracks the remote branch, switch to a new branch - the `Create Local Branch` panel pops up

**Comment by love-linger** [comment]
`Fast-Forward` is a context menu item of the selected local branch, which is always enabled. You can simply do it without checkout the target local branch.

**Comment by love-linger** [comment]
And if you are talking about double-clicking some commit in histories, as I said in issue #337, it is a little different between with double-clicking the branch in left panel:

The behavior of double-clicking a commit in histories view is limited to the fact that it must be strongly related to the target commit. For example, in the above case, if the double-click target commit contains only the remote branch, that is, when the local branch is different from the remote branch it tracks, the software will pop up a branch creation panel based on the revision.
