### ISSUE TITLE
[Feature] Add Support for Conventional Commits

### ISSUE THREAD

**Issue by idamachmadfaizin** [sourcegit-scm/sourcegit#574]
I would like to request the addition of support for [Conventional Commits](https://www.conventionalcommits.org/) in Sourcegit. This feature would help in maintaining consistent commit messages across the project and improve the overall readability of the commit history. It can also provide better integration with tools like semantic versioning and changelog generation.

Additionally, I suggest adding an option in the Preferences menu to enable or disable this feature, allowing users to choose whether or not to use it.

Thank you for considering this request!

**Comment by love-linger** [comment]
Done. You can download the latest CI build from https://github.com/sourcegit-scm/sourcegit/actions/runs/11400133098

![image](https://github.com/user-attachments/assets/d21aaa3e-fd68-4b16-8409-2f3157672380)

**Comment by idamachmadfaizin** [comment]
So fast, many thanks.
