### ISSUE TITLE
Remote URL doen't accept URLs with special encoded characters e.g. %20

### ISSUE THREAD

**Issue by pmandalka** [sourcegit-scm/sourcegit#575]
I have an azure git repository which contains special characters that are correctly escaped in the URL (e.g. as %20).
Example: https://sombody@dev.azure.com/sombody/TEST%20WHAT%C3%A4ver/_git/WebApi
In the Remote-Edit-Dialog the URL is shown as invalid.

Maybe the regex should be expanded with "%" to allow this kind of URLs. (Beside this dialog, It seems to work file)

http[s]?://([\w\-%]+@)?[\w\.\-%]+(\:[0-9]+)?/[\w\-/~%]+/[\w\-%\.]+(\.git)?$

**Comment by love-linger** [comment]
Done. You can download the latest CI build.

**Comment by pmandalka** [comment]
Thank you, it works without problems now.
