### ISSUE TITLE
How to clear github login data?

### ISSUE THREAD

**Issue by ChiaYen-Kan** [sourcegit-scm/sourcegit#580]
i am login github with access token in sourcegit, but i can't find the function for clear github login data
how to clear github login data?

**Comment by love-linger** [comment]
What is your operating system?

**Comment by ChiaYen-Kan** [comment]
> What is your operating system?

windows 10

**Comment by love-linger** [comment]
`SourceGit` use [git-credential-manager](https://github.com/git-ecosystem/git-credential-manager/releases) to manage user's accounts.

On Windows, you can manually clear it via `Windows Credential Manager` 

https://support.microsoft.com/en-us/windows/accessing-credential-manager-1b5c916a-6a16-889f-8581-fc16e8165ac0

**Comment by ChiaYen-Kan** [comment]
> `SourceGit` use [git-credential-manager](https://github.com/git-ecosystem/git-credential-manager/releases) to manage user's accounts.
> 
> On Windows, you can manually clear it via `Windows Credential Manager`
> 
> https://support.microsoft.com/en-us/windows/accessing-credential-manager-1b5c916a-6a16-889f-8581-fc16e8165ac0

thank you, i am success clear login data
