### ISSUE TITLE
[Regression Issue] - `git-lfs` command not found in v8.35

### ISSUE THREAD

**Issue by htw128** [sourcegit-scm/sourcegit#581]
In the latest release (v8.35), the git-lfs command not found bug has resurfaced. The old workaround still resolves the issue:

```bash
launchctl setenv PATH $PATH
open -a SourceGit
```

It's worth noting that this bug is not present in v8.34.

Related issues: #168, #507

**Comment by love-linger** [comment]
Currently, I've removed the code that setting `PATH` for `git` subprocess. Instead, SourceGit will try to read `PATH` env from `zsh` at startup. If it is failed, `open -a SourceGit` from commandline will still work.

PS: `launchctl setenv PATH $PATH` is not needed

**Comment by love-linger** [comment]
I have pushed my final solution on this issue. The solution no longer depends on the user's environment, but instead reads the `PATH` variable from a file. 

You can download the latest CI build from https://github.com/sourcegit-scm/sourcegit/actions/runs/11435321999

After download it, you must run `echo $PATH > ~/Library/Application\ Support/SourceGit/PATH` to generate the custom PATH file for SourceGit. Once it is created, SourceGit will use the content of it for `PATH` env used by `git` subprocess.
