### ISSUE TITLE
Allow empty commits

### ISSUE THREAD

**Issue by AdrienMatricon** [sourcegit-scm/sourcegit#587]
The context:
- By default, running `git commit` with nothing staged returns an error code, with a message `nothing to commit, working tree clean`
- To create an empty commit, an option must be passed : `git commit --allow-empty`

The issue:
- In `sourcegit`, trying to commit with nothing staged matches the default behavior and prints an error message saying `No files added to commit!`
- There is no way to tell it that it is on purpose

Possible solutions:
- Adding a "Commit anyway" button to the error message
- Adding an `Allow empty` checkbox besides the ones for `Auto-stage` and `Amend`

**Comment by love-linger** [comment]
If you just want to modify the message of the HEAD commit, you can select this commit and click the 'Reword' option in the context menu.

Another way to do this job is enable 'Amend' option while committing

**Comment by love-linger** [comment]
Pure empty commit is not recommended in SourceGit, and currently there is no plans to add this feature

**Comment by AdrienMatricon** [comment]
Really? Why is that?

My company relies on pure empty commits quite a lot in our workflow; typically we create a release from a release candidate by creating an empty commit carrying the tag `vX.Y.Z-release` as a child of the candidate commit (carrying the tag `vX.Y.Z-rc0` or some such). The information is used by our build system through `git describe --tag` so that each release or RC is uniquely named

**Comment by love-linger** [comment]
Done. You can download the latest CI build from Github Action.
