### ISSUE TITLE
Can't start portable Visual Studio Code (Windows platform) - VSCODE_PATH environment variable ignored

### ISSUE THREAD

**Issue by agb2008** [sourcegit-scm/sourcegit#59]
Got issue while trying to setup portable **VSCode** working with **SourceGit** v. 8.6, while trying to open **VSCode** from  "Open in Visual Studio Code" menu option got error message: **_"Visual Studio Code can NOT be found in your system!!!"_**

Check documentation and found option to set full path to Code.exe file using environment variable **VSCODE_PATH**.

But unfortunately, on Windows 10 planform **SourceGit** completely ignored such environment variable and I've got exactly the same error message regardless setting this environment variable or not. I've tried setting it as local user environment variable or global environment variable - no difference. System just ignored it and showed me that error message.

The only temporary workaround was to copy VSCode files to: _"C:\Users\UserName\AppData\Local\Programs\Microsoft VS Code\"_ folder (don't forget to replace UserName with your real user name !), so that Code.exe file located in that folder. Only after doing so I've manage to get it working - but that for sure is not a good workaround - cause portable **VSCode** should be located in different folder (in my case on an external USB disk)

P.S. Instead of **VSCode** one could put different code editor in mentioned above folder, such as **Cudatext** or **Lite-xl** and rename (or set a hardlink) executable file to Code.exe and work with preferable editor. But much better option would be if **VSCODE_PATH** variable would work.

**Comment by love-linger** [comment]
This feature is added after the release 8.6.

You can try the latest from https://github.com/sourcegit-scm/sourcegit/actions/runs/8536483685/artifacts/1380601405 which is based on commit bcb83af576ecd1460be158ba44a356e34401fc1a
