### ISSUE TITLE
Add support for customizable template for AI-generated commit messages

### ISSUE THREAD

**Issue by dougcunha** [sourcegit-scm/sourcegit#592]
Hello,

First of all, thank you for the great work on SourceGit. It has been a very useful Git client.

I would like to request a feature to allow users to customize the commit message template generated by the "Use OpenAI to generate commit message" functionality. Currently, the generated commit message is always in English, but in my company, we need to write commit messages in Portuguese.

A customizable template would allow users to define their preferred language and format for commit messages, which would make this feature more versatile and adaptable to different team requirements.

Thank you for considering this improvement. I'm happy to provide more details if needed.

**Comment by love-linger** [comment]
The current implementation that `SourceGit` uses `OpenAI` to generate commit message is:

1. Take the result of `git diff` for each staged file and pass it to the `OpenAI` service to summarize the changes to that file
2. Merge all the summaries generated by step 1 and send them to OpenAI to generate the `Subject` of commit message.
3. Combine the `Subject` generated by step 2 with the per-file-summaries in step 1 as the final commit message.

From the above steps, it can be seen that `SourceGit` currently uses two prompts, one for generating a summary of changes in a single file, and the other for get the main goal of all changes. And one more thing, these two steps are linearly related.

The idea comes from: https://github.com/anjerodev/commitollama

**Comment by love-linger** [comment]
I am not familiar with writing prompts, and to implement this feature, I need someone to help me rewrite the `Commands.GenerateCommitMessage` and provide a default prompt that can generate conventional commit message.

**Comment by dougcunha** [comment]
I understand. The current implementation differs slightly from other solutions like GitKraken, which send the entire diff plus a prompt at once for commit message generation. 

However, I believe we could adjust step 3 to send the prompt, title, and summary to OpenAI for reformatting as needed. The main issue with this solution is that the prompt can only be applied to the data obtained from the diff beforehand. If additional diff data is required, such as the line where a change was made, that information will not be included in the summary.

**Comment by dougcunha** [comment]
A potentially simpler and more readily implementable solution would be to offer the option of selecting the response language, which could be appended to existing prompts like this: "always respond without Spanish."

**Comment by dougcunha** [comment]
What do you think?

It was just an idea. If you like, I can try to implement it.

![image](https://github.com/user-attachments/assets/15989aaa-e4b0-4af8-b0dd-1b6cba141df0)

**Comment by dougcunha** [comment]
I've just created a pull request.
