### ISSUE TITLE
Colorblind mode

### ISSUE THREAD

**Issue by thomaslevesque** [sourcegit-scm/sourcegit#593]
Would it be possible to add a colorblind mode?
I'm colorblind, and for me the colors in the diff are very difficult to distinguish.

![image](https://github.com/user-attachments/assets/2decc436-9306-4552-b07a-b3c79adb19be)

I realize it probably looks fine to people with normal vision, but I can't clearly see which lines are added or removed, which makes the diff almost unusable for me.

Short of adding a real colorblind mode, adding a `+`/`-` prefix on each line would be helpful.

**Comment by love-linger** [comment]
Done. You can download the latest CI build from Github Action.

![image](https://github.com/user-attachments/assets/db58367c-3d34-4d9c-9631-9d631e76b113)

**Comment by tlevesque-ueat** [comment]
Wow, that was fast! I'll try it tomorrow. Thanks!

**Comment by love-linger** [comment]
I've pushed a new implementation of this feature.
![image](https://github.com/user-attachments/assets/db4b2876-37a3-41a2-a46a-d2858c2664eb)

**Comment by thomaslevesque** [comment]
Even better!

I still think it would make sense to add an actual colorblind more, with more contrasted colors. It would certainly make the diffs more comfortable to read for me and other CB people. In the meantime, the +/- prefix really helps. Thanks!

**Comment by love-linger** [comment]
This software supports custom themes, see https://github.com/sourcegit-scm/sourcegit-theme.
PS: I'm not very good at choosing colors.

**Comment by thomaslevesque** [comment]
Oh, nice, I wasn't aware of that. Thanks!
