### ISSUE TITLE
appimage don't work with appimagelauncher

### ISSUE THREAD

**Issue by Mike710Shine** [sourcegit-scm/sourcegit#595]
When i download the .appimage for amd64 is runs very well. But when i install the appimagelauncher to integrate the appimage in the System i get every time the error "execv error: No such file or directory" when i try to start the appimage. When i uninstall the appimagelauncher, reboot i can start the appimage again. I don't know exactly what is the problem in this case. 

I'm on the newest CachyOS. 
I install the appimagelauncher only with "pacman -Sy appimagelauncher". After that i download the appimage and run it with the option only run once. To see the error you need to run the image in an terminal.

**Comment by gadfly3173** [comment]
See https://github.com/sourcegit-scm/sourcegit/issues/329#issuecomment-2272559761
AppImageLauncher is too old for new appimages

**Comment by aikawayataro** [comment]
> CachyOS
You can install `sourcegit-bin` from AUR. 

Since this is not the first issue on AppImageLauncher, I guess it might be worth thinking about migrating to the older AppImage runtime? However, I don't know what kind of regressions and security problems this might cause.

**Comment by gadfly3173** [comment]
Considering that AppImageLauncher hasn't released a new version over 4 years, I suggest you look for other alternative tools, such as https://github.com/ivan-hc/AM

**Comment by Mike710Shine** [comment]
Ohh ok thanks for the Information then i will use the `sourcegit-bin` from AUR.

**Comment by Mike710Shine** [comment]
For my case i will go fine with the am tool. This works fine. For my point i don't think you have to do anything, because the appimage don't open with the appimagelauncher but with the am tool or with gearlever it works an without any tool it works too. Therefore i guess all is fine with the appimage.

**Comment by love-linger** [comment]
OK. So, I'll close the this issue as `not-belongs-to-this-app`
