### ISSUE TITLE
Numerical Sorting in file listing

### ISSUE THREAD

**Issue by og-sims** [sourcegit-scm/sourcegit#597]
Hi,

in some projects the naming of files begins with numbers. On Windows system the default behavior ist sorting the files by string as follows:

```
T1
T10
T11
T2
T22
T25
T3
...
```

This behavier can be changed by GPO to a so called numeric sort:

```
T1
T2
T3
T10
T11
T22
T25
...
```

Here is an example file listing:

![image](https://github.com/user-attachments/assets/1b2f7e76-74c0-46f9-b587-63a3a5447014)

In larger Projects with 1000 and more objects, it is very hard to review code, because of scrolling up an down and searching numbers. 

Is there a way to change the sorting of file listings? When not, is this possible to implement this as option?

**Comment by love-linger** [comment]
I've pushed a commit that enables numeric sorting in tree view. You can download the latest CI build from Github Action.

PS: For changes, you must change the display mode to `Show as Filesystem Tree` to use numeric sorting.
