### ISSUE TITLE
6.2版本没有了收藏/书签的分类

### ISSUE THREAD

**Issue by xqsapper** [sourcegit-scm/sourcegit#6]
希望加上这个功能，这个还是很有必要的

**Comment by sourcegit-scm** [comment]
![image](https://user-images.githubusercontent.com/85621660/197734408-00e28768-d9ca-4587-b1a9-9aec585030e5.png)

**Comment by sourcegit-scm** [comment]
![image](https://user-images.githubusercontent.com/85621660/197735054-6e5725f7-a85d-4f69-b093-fa5d45547096.png)
