### ISSUE TITLE
检测软件更新失败

### ISSUE THREAD

**Issue by hong5010** [sourcegit-scm/sourcegit#60]
点击【检测更新】提示：获取最新版本信息失败！Reponse status code does not indicate success:403(Forbidden)

**Comment by love-linger** [comment]
你可使用浏览器访问一下 https://api.github.com/repos/sourcegit-scm/sourcegit/releases/latest 看是否能正确输出Release信息呢

**Comment by hong5010** [comment]
可以正常访问

**Comment by love-linger** [comment]
那就很奇怪了，SourceGit目前只是下载这个Json，并将版本号和更新内容展示，并提示用户有更新下载（不会自动更新）

**Comment by ZCShou** [comment]
> 那就很奇怪了，SourceGit目前只是下载这个Json，并将版本号和更新内容展示，并提示用户有更新下载（不会自动更新）

我调试看了看，更新的报错是因为 SourceGit 访问 github 的 API （https://api.github.com/repos/sourcegit-scm/sourcegit/releases/latest） 超过了每天的限制！
详见：https://docs.github.com/en/rest/using-the-rest-api/getting-started-with-the-rest-api#rate-limiting
