### ISSUE TITLE
Cannot resolve conflict using Meld tool

### ISSUE THREAD

**Issue by zrpfpr** [sourcegit-scm/sourcegit#603]
Hi, recently installed sourcegit and I can see that I cannot resolve a simple conflict merge using Meld, always appear this message:
![image](https://github.com/user-attachments/assets/0bca33e8-294f-4a6f-a0a6-9544b78504c7)

If I try to resolve using VSCode, for instance, no error shown.

OS: Linux Mint 22
Sourcegit: 8.35
Git: 2.43.0
Meld: 3.22.2

![image](https://github.com/user-attachments/assets/ba6cfaa1-9484-43f5-88f2-85eb8d8772d9)

Thanks for this fantastic tool BTW! Amazing features and support!

**Comment by love-linger** [comment]
I've pushed a commit that tries to fix this issue. You can download the latest CI build from Github Action https://github.com/sourcegit-scm/sourcegit/actions/runs/11539127971.

PS: My Linux device is not with me and I cannot test it...

Looking forward to your feedback.

**Comment by love-linger** [comment]
Tested. You can just download the latest release 8.36

![image](https://github.com/user-attachments/assets/fe9681f6-1d68-40e7-88e8-3d112f18a487)

**Comment by zrpfpr** [comment]
Superb! Works like a charm. Thanks for your work!! @love-linger
