### ISSUE TITLE
GPT Commit Feature.

### ISSUE THREAD

**Issue by dev-zkf** [sourcegit-scm/sourcegit#608]
When having alot of changes for example in unity. the ai will freak out when trying to read stuff like .unity or .meta or stuff like that could you make it where you can make the ai ignore stuff and mainly focus on like .cs (scripts) beacuse its a pain to select one by one the items that the ai will type a commit to then add the rest to the stage

**Comment by love-linger** [comment]
Now, you can generate commit message with selected staged changes.
![image](https://github.com/user-attachments/assets/67e5e51c-a8d8-4d72-9132-923f1877edf7)

**Comment by dougcunha** [comment]
@dev-zkf  What I usually do when I have many modified files is the following: I stage only the important files and generate the commit message, then I stage everything and complete the commit. This way, the generated commit message will be more accurate and will also consume fewer tokens if using the OpenAI server.

**Comment by love-linger** [comment]
> This way, the generated commit message will be more accurate and will also consume fewer tokens if using the OpenAI server.

Let me recommend a tool that I personally use - [Ollama](https://ollama.com/) which provides self-hosting OpenAI comaptible service.

**Comment by dougcunha** [comment]
> > This way, the generated commit message will be more accurate and will also consume fewer tokens if using the OpenAI server.
> 
> Let me recommend a tool that I personally use - [Ollama](https://ollama.com/) which provides self-hosting OpenAI comaptible service.

Thanks for the tip, but while I'm familiar with Ollama, I've found that the quality of messages generated by models like gpt-4o-mini are better suited for my specific use cases.

**Comment by dev-zkf** [comment]
> @dev-zkf What I usually do when I have many modified files is the following: I stage only the important files and generate the commit message, then I stage everything and complete the commit. This way, the generated commit message will be more accurate and will also consume fewer tokens if using the OpenAI server.

well yeah. but i wish it would automatically just like only read the .cs and like other related stuff and not like .unity or .meta beacuse it usually gets errors doing so
