### ISSUE TITLE
Suggested to update README - how to install with Homebrew

### ISSUE THREAD

**Issue by ybeapps** [sourcegit-scm/sourcegit#609]
Hi @love-linger

first thing, I would like to say thanks
the recent changes are quite amazing!! (colors, ENV fix, reflog support and more)!!!

second thing,
I know it was too much for you and you didn't want to waste time on it..
but I did it - for my own usage...
now every Mac user can easily install sourcegit via homebrew
it only requires to run the following commands:
```
brew tap ybeapps/homebrew-sourcegit
brew install --cask --no-quarantine sourcegit
```

it's maintained in this repo: `https://github.com/ybeapps/homebrew-sourcegit`

twice a day, it fetches the latest version from official sourcegit repo and compare with the version in Homebrew.. if newer version found, it automatically updates the references =]

I'm suggesting:
1. updating readme to notify users about this support - you can specify this is third-party if you like
2. **OPTIONAL:** if you want we can try to setup auto action trigger upon release publish... if you can trigger the action in my repo I can remove the schedule =]
3. **OPTIONAL FUTURE:** if you like you can just take it to your repo, and I can archive my repo =]

thanks again for all!!

**Comment by love-linger** [comment]
Thank you VERY VERY MUCH for your support of this project!!!

I'll update the `README.md` to let users notice this.
