### ISSUE TITLE
Show full file when comparing diffs (question)

### ISSUE THREAD

**Issue by Christof-P** [sourcegit-scm/sourcegit#611]
I was wondering if there is a setting somewhere where I can set it to always show the full file in when comparing changes?

**Comment by love-linger** [comment]
I recommend that you configure a fully functional external diff/merge tool and use it to do this job.

![image](https://github.com/user-attachments/assets/c7a28ad6-62ff-4fb9-9b6b-359487568ac9)
![image](https://github.com/user-attachments/assets/5f29d878-9996-4eac-a19c-ed312bc64237)

**Comment by Christof-P** [comment]
I see. Thanks! :+1:
