### ISSUE TITLE
Git log not displayed in 8.36 on MacOS ARM

### ISSUE THREAD

**Issue by alumni** [sourcegit-scm/sourcegit#613]
The git graph (histories tab) is not displayed (the loading animation never ends) for a certain repository. Local branches and remotes are not displayed either. Stashes are displayed.

I have auto fetch enabled for this repository. I also tried deleting it and adding it again, the issue persists. Also tried removing `.git/sourcegit.settings`.

Using SourceGit 8.36 on MacOS arm64 downloaded from GitHub releases and Git 2.47.0 installed via Homebrew.

After downgrading SourceGit to 8.35, it works again fine.

**Comment by love-linger** [comment]
Could you please test the package from Github Releases? I'm also using SourceGit 8.36 on macOS arm64

**Comment by alumni** [comment]
Sorry, I meant Git was installed via Homebrew.

SourceGit was installed by downloading the arm64 release from GitHub (and removing the quarantine attribute that MacOS sets).

**Comment by alumni** [comment]
It seems it does not happen for all repos, only for some. 

Probably the OS doesn't matter, I can try later on Windows/Linux with the same repository.

**Comment by love-linger** [comment]
8.36 has changed the way SourceGit reads system PATH env. Does it matter?

You can try it via `open -a SourceGit` command

在 2024年10月28日，21:49，Lucian Mocanu ***@***.***> 写道：

﻿

It seems it does not happen for all repos, only for some.

Probably the OS doesn't matter, I can try later on Windows/Linux with the same repository.

**Comment by alumni** [comment]
Still the same if started from the terminal with `open -a SourceGit`.

**Comment by yitzchak-ben-ezra-ecoplant** [comment]
@love-linger this is the issue I experienced today
So I created the PR with the int.Parse removal

I believe it's the same issue
Latest build should work in my opinion 

I wonder if I can somehow configure homebrew to support merged builds

**Comment by ybeapps** [comment]
@love-linger  this is the issue I experienced today
So I created the PR with the int.Parse removal

I believe it's the same issue
Latest build should work in my opinion 

I wonder if I can somehow configure homebrew to support merged builds

**Comment by alumni** [comment]
I can confirm it was fixed by https://github.com/sourcegit-scm/sourcegit/pull/612. We do have a few branches that contain longer base10 numbers, haven't seen one greater than 2<sup>32</sup>, but I can't say for certain.
