### ISSUE TITLE
[Feature] Show if commit is signed with gpg

### ISSUE THREAD

**Issue by Masgalor** [sourcegit-scm/sourcegit#614]
Commits can be signed using gpg so my expectation was to see some information about cryptographic signatures for every commit.

I would imagine to have some indicator that shows me if a commit is:
- unsigned
- signed, signature is broken
- signed, signature is good

Maybe an icon changing colors depending on the status (grey/red/green).

It would already be an improvement to have access to the output of `git verify-commit` without using the cli.

**Comment by dougcunha** [comment]
I have a few ideas on how to implement this. If @love-linger is okay with it, I'd be happy to take a look.

**Comment by love-linger** [comment]
To verify a commit, the public key is needed...

**Comment by love-linger** [comment]
For example, without public keys:

![image](https://github.com/user-attachments/assets/e707d0bb-f4d8-43ee-96a7-609505ef6613)

According to the `git log` document
![image](https://github.com/user-attachments/assets/62f35052-d286-4d66-8e5b-3f9cffec1727)

There's no 'G' printed.

**Comment by love-linger** [comment]
One more thing, the above command sometimes takes more than 1 second on my PC (14700K)...

**Comment by gadfly3173** [comment]
> One more thing, the above command sometimes takes more than 1 second on my PC (14700K)...

GPG signature checking is calculated for each commit individually, so the more commits you check, the more time it takes to complete. Github's commit list also displays signature status very slowly and asynchronously.

GitKraken, which has a GPG signature check feature, only displays the signature status in the commit details and does not seem to rely on the `gpg.ssh.allowedSignersFile` configuration. It may have implemented additional signature checks on its own.

![image](https://github.com/user-attachments/assets/ee74ed4e-51cf-475d-9fc3-435475ac5439)

**Comment by love-linger** [comment]
> GitKraken, which has a GPG signature check feature, only displays the signature status in the commit details and does not seem to rely on the gpg.ssh.allowedSignersFile configuration. It may have implemented additional signature checks on its own.

You can just set `-c gpg.ssh.allowedSignersFile=/dev/null` in `git log` command if `gpg.ssh.allowedSignersFile` is not set by user. For example: 
```shell
git -c gpg.ssh.allowedSignersFile=/dev/null log -10 --date-order --no-show-signature --decorate=full --pretty=format:"%H %G?"
```

**Comment by dougcunha** [comment]
> GitKraken, which has a GPG signature check feature, only displays the signature status in the commit details and does not seem to rely on the `gpg.ssh.allowedSignersFile` configuration. It may have implemented additional signature checks on its own.

I don't see a problem with this approach. SublimeMerge only displays the signature status in the commit details as well and it works very well.

**Comment by love-linger** [comment]
![image](https://github.com/user-attachments/assets/488fc2e3-b470-46d6-95c4-c22d75920074)

**Comment by love-linger** [comment]
I've pushed the commit that shows the gpg signing status in commit details panel.

**Comment by Masgalor** [comment]
Works like a charm, thank you very much!
