### ISSUE TITLE
Add toggle "Show entire file" for built-in Diff viewer

### ISSUE THREAD

**Issue by goran-w** [sourcegit-scm/sourcegit#615]
The built-in Diff viewer has options to "Increase/Decrease Number of Visible Lines", with icon-buttons in its top (mini-)bar. If we want to show the entire file contents, we would have to press "Increase ..." a large number of times, which becomes very tedious.

Therefore, I'd suggest adding another icon-toggle for "Show entire file".

For reference, the "Fork" Git client has exactly this feature, and a similar feature can be found in GitSmart as a "Compact" toggle. GitKraken instead allows switching between 3 diff views: "Hunk" (unified, compact) / "Inline" (unified, whole file) / "Split" (side-by-side, whole file).

**Comment by love-linger** [comment]
duplicated #611

**Comment by gadfly3173** [comment]
> we would have to press "Increase ..." a large number of times

Maybe change that 2 buttons to `RepeatButton` would be better? @love-linger

**Comment by love-linger** [comment]
> > we would have to press "Increase ..." a large number of times
> 
> Maybe change that 2 buttons to `RepeatButton` would be better? @love-linger

I don't think so. Because when the value of `--unified` parameter changed, SourceGit will re-generate the diff result by start a new `git diff` process, which costs too much to me.

I think it's a good idea to leave all these advanced operations to the external diff/merge tool.

**Comment by goran-w** [comment]
Sorry about the duplicate. And I don't think the Increase/Decrease buttons need to be changed - they are fine as they are, and were never meant to be used for "show entire file".

However, I find it unfortunate to not have instead a separate option for that, and to have to resort to external tools for this when the built-in Diff is much more convenient for quick (re)viewing of changes.

I understand the need to leave more advanced stuff to external diff tools, but this seems like a rather "basic" addition - wouldn't it be even simpler to implement than the current partial/compacted view? The feature has already been requested by more than one person (hence the duplicate) and it's available in several other similar Git clients. (Would you be willing to accept a PR for this, eventually?)

**Comment by love-linger** [comment]
Of course you can submit a PR, but I'm afraid it is not a simple job:

* We can not just use large number for `--unified=N` parameter. For example, I'm a game developer and using `UnrealEngine`. There are more than 170K+ lines in `https://github.com/EpicGames/UnrealEngine/blob/release/Engine/Build/Commit.gitdeps.xml` file.
* There are many other source code files those were generated by tools, such as language bindings or library definations. Which may also have many lines in a single file.
* The new implementation must be compatible with `Hunk based selection` and `Patch generation` which used to stage/unstage/discard partial changes in a single file.
* Most fully-featured diff/merge tool will has a minimap in scrollbar to help people find the changes quickly with scrollbar.
* I am concerned about the performance of the new implementation, both loading/building data and rendering data.

**Comment by goran-w** [comment]
Thank you for this excellent feedback! The difficult part would be compatibility with Hunk/Patch code, as you say. Minimap is not necessary, whole file + navigation to prev/next change would still be a big improvement. As for very large files, I think we could accept slower performance for these as it would only affect the build and render of Diff when the new view-style is enabled.

**Comment by gadfly3173** [comment]
I tried to view the file history and blame of https://github.com/infinilabs/analysis-ik/blob/master/config/extra_main.dic (398716 lines) in sourcegit, and it took about 2 seconds to open (i3-7350k), which seems to be not so unacceptable.
