### ISSUE TITLE
[BUG] Drag panels offscreen.

### ISSUE THREAD

**Issue by FardinHaque70** [sourcegit-scm/sourcegit#619]
https://github.com/user-attachments/assets/662a1c8a-01a6-4811-98ff-47cb14d98cdb

Panels can move offscreen when dragging or resizing window. 
Also disconnecting external monitor from my mac basically produces the same problem as the windows needs to resize to match the mac's smaller display. 

Having a separate button on SourceGit > Preference > Appearance > Reset Panel Layout would be a handy feature as well.

**Comment by love-linger** [comment]
Done. You can download the latest CI build from Github Action

**Comment by FardinHaque70** [comment]
Resizing window still has the issue. Maybe a fixed minimum width for the side panel will help it stay in view. 
Adding a gif to show how SourceTree handles it. 

https://github.com/user-attachments/assets/9269dcee-4724-483a-974e-61520672acf3


https://github.com/user-attachments/assets/af41b48f-e1bf-428c-ab79-84ac9c4a03bf

**Comment by love-linger** [comment]
> Maybe a fixed minimum width for the side panel will help it stay in view.

In fact commit ee20eba04769bf287576999de37d866544d5f5d8 did exactly that, see:

![image](https://github.com/user-attachments/assets/07ea7cc6-ae51-40d1-a793-5bad4fc34356)

**Comment by love-linger** [comment]
Done. You can download the latest CI build from Github Action

**Comment by FardinHaque70** [comment]
Thanks it's perfect now!
