### ISSUE TITLE
Suggestion: "Open In Terminal" supports other shells not only git bash

### ISSUE THREAD

**Issue by walterlv** [sourcegit-scm/sourcegit#62]
# Interactions

1. Change "Open In Terminal" and "Open In External Tools" from button or drop down to "Split Button"
2. The click of the "Split Button" uses the default shell or default external tool to open
3. The drop down of the "Split Button" list all the supported shells or tools find on this machine

# Functions

I suggest add "pwsh" support to the "Open In Terminal".

This is my pwsh, I like it more than git bash.

![image](https://github.com/sourcegit-scm/sourcegit/assets/9959623/e060d434-b4e6-4859-be4b-47c6dcb3068c)

# Contribution

If you agree with my suggestion, I'd like to fire a new PR to support it.

**Comment by love-linger** [comment]
It sounds great. You can create a PR for this feature. I may need to test it first, or I may need to unify the style of the buttons.

**Comment by love-linger** [comment]
I thought a little bit about this feature.

On macOS and Linux platforms, click on "Open In Terminal" button will open the system built-in terminal, and which shell to use depends on the configuration of this terminal. On Windows, it will open git bash instead because that git provides a built-in bash specifically for Windows.

So I prefer to trait Powershell as an external tool, and try to support it by myself.

**Comment by walterlv** [comment]
> I thought a little bit about this feature.
> 
> 
> 
> On macOS and Linux platforms, click on "Open In Terminal" button will open the system built-in terminal, and which shell to use depends on the configuration of this terminal. On Windows, it will open git bash instead because that git provides a built-in bash specifically for Windows.
> 
> 
> 
> So I <s>prefer to trait Powershell as an external tool, and</s> will try to support it by myself.
> 
> 
> 
> 

Agree. But I prefer that the default terminal can be configured on Windows.

My terminal is the Windows Terminal and the default shell is PowerShell which is profiled for git repositories(See the screenshot above). I know that most PowerShells of Windows users do not support git commands so git-bash exactly should be treat as a default shell on Windows.

I think we can provide a config for the user to change the default terminal or shell on Windows, otherwise, I will always reveal the repo in the file explorer and then open the foler in my Windows Terminal instead of simply click the git bash button.

I'm working on a PR:

1. Keep the open in terminal button as it is now.
2. Change the open in external tools from a button to a split button. Clicking on the button will open the repo using the default extern tool and clicking on the drop down button will open a list of external tools found on this machine.
3. Add two configurations in the settings window, the default terminal/shell and the default external tool.

**Comment by love-linger** [comment]
> > I thought a little bit about this feature.
> > On macOS and Linux platforms, click on "Open In Terminal" button will open the system built-in terminal, and which shell to use depends on the configuration of this terminal. On Windows, it will open git bash instead because that git provides a built-in bash specifically for Windows.
> > So I prefer to trait Powershell as an external tool, and will try to support it by myself.
> 
> Agree. But I prefer that the default terminal can be configured on Windows.
> 
> My terminal is the Windows Terminal and the default shell is PowerShell which is profiled for git repositories(See the screenshot above). I know that most PowerShells of Windows users do not support git commands so git-bash exactly should be treat as a default shell on Windows.
> 
> I think we can provide a config for the user to change the default terminal or shell on Windows, otherwise, I will always reveal the repo in the file explorer and then open the foler in my Windows Terminal instead of simply click the git bash button.
> 
> I'm working on a PR:
> 
> 1. Keep the open in terminal button as it is now.
> 2. Change the open in external tools from a button to a split button. Clicking on the button will open the repo using the default extern tool and clicking on the drop down button will open a list of external tools found on this machine.
> 3. Add two configurations in the settings window, the default terminal/shell and the default external tool.

Looking forward to your PR. I'll try it out to decide which solution to take.

**Comment by love-linger** [comment]
I've pushed two braches that supports PowerShell in different ways.

* `feature/powershell_supports` adds a Windows-only option `Use Powershell instead of Git Bash`.
* `feature/powershell_supports2` traits PowerShell as an external tool.

You can try these out or create your PR.

**Comment by walterlv** [comment]
I've tested your two branches and my PR #64 is very similar to your branch `feature/powershell_supports2`. What the difference is that my PR provide a more flexible option for the users because the user get a `ComboBox` instead of a `CheckBox` to select any terminals or shells installed on the machine.

Actually, I've also tested an unexpected behavior of the PowerShell as the picture shows below. If I start a Windows Terminal with my pwsh as the default shell, all the special texts renders correctly but if I start pwsh.exe directly, the special texts are broken. I've written a post before to describe the difference font behaviors of them. In conclusion, the Windows Terminal is more modern.

So I think the PR #64 is a more flexible implementation to give the user a free choice.

![image](https://github.com/sourcegit-scm/sourcegit/assets/9959623/9e6152ba-88f8-4088-b477-702d2f522fff)

**Comment by walterlv** [comment]
My system default terminal is the Windows Terminal. My default shell on the Windows Terminal is PowerShell.

So the Windows Terminal can open Shells in it, and it can also capture other newly started shell instances into it. So the user have so many options:

1. Start the Windows Terminal using `wt` command. The user will get a default Shell running in the Windows Terminal.
2. Start any shells installed on the machine such as `bash.exe` `cmd.exe` `pwsh.exe` etc. The user will also get a Windows Terminal window with the newly started shell in it.

For the first option, only the default shell of the Windows Terminal will start. But for the second option, the user can run any other shell instead of only the default shell of the Windows Terminal.

Before our branches, the SourceGit start `git-bash.exe` only so the users who don't use the Git Bash will be not be happy. After your `feature/powershell_supports` branch, the users have their new option to start a `pwsh.exe` instead of the `git-bash.exe`. After my PR #64 , the users have more option to start the Windows Terminal and start its default shell not only start the `git-bash.exe` or the `pwsh.exe`.

On the branch `feature/powershell_supports2`, the user will select `Open in PowerShell` every time when they want to open in a shell. Thus the "Open in terminal` button is useless.

**Comment by love-linger** [comment]
In my opinion, the starting point of this problem is that under Windows platform, users can choose their favorite shell, rather than git's built-in bash. Note: I'm talking about Shell and not Terminal (because the default terminal program on Windows can be modified).

macOS and Linux do not have this problem.

So, I think what we should offer users is an option like the Windows Terminal:

![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/a7733825-f997-43d7-88a8-2c52cbbe41ea)

**Comment by walterlv** [comment]
The PR #64 list the shells like the Windows Terminal.

You can view the screenshot there and give some suggestions.

For example:

1. Remove the Windows Terminal from the list so that all items on the list are shells.
2. Rename the Windows Terminal to "The Default Shell of Windows Terminal" so that all items on the list are shells.
3. Reorder the list and put the Windows Terminal above the shells so that the list does not confuse terminals and shells.
4. Use Windows Terminal as the default terminal on Windows, and the user can change it to git bash in the Preference.
5. Use the System Default Terminal as the default terminal on Windows (I do not like it because the default terminal of most Windows is the Console Host which is very hard to manage git repository).

Any reply appreciated.

**Comment by love-linger** [comment]
I've write a similar one and push it to branch `feature/powershell_supports`. It provides a Shell selection list of fixed entries instead of being generated by finders. The reasons for this are:

* All of these tools exist on Windows 11
* This feature is not required for non-Windows platforms

**Comment by love-linger** [comment]
> I am a user of Deepin OS, and the default terminal is `deepin-terminal`, which is not in the current support list of SourceGit. It would be great if this function could allow users who use other terminals like me to choose which terminal to use.

I've added the deepin-terminal to the support list on Linux. You can try it out on branch `develop`.

```csharp
public void OpenTerminal(string workdir)
{
    var dir = string.IsNullOrEmpty(workdir) ? "~" : workdir;
    if (File.Exists("/usr/bin/gnome-terminal"))
    {
        Process.Start("/usr/bin/gnome-terminal", $"--working-directory=\"{dir}\"");
    }
    else if (File.Exists("/usr/bin/konsole"))
    {
        Process.Start("/usr/bin/konsole", $"--workdir \"{dir}\"");
    }
    else if (File.Exists("/usr/bin/xfce4-terminal"))
    {
        Process.Start("/usr/bin/xfce4-terminal", $"--working-directory=\"{dir}\"");
    }
    else if (File.Exists("/usr/bin/deepin-terminal"))
    {
        Process.Start("/usr/bin/deepin-terminal", $"--work-directory=\"{dir}\"");
    }
    else
    {
        App.RaiseException(dir, $"Only supports gnome-terminal/konsole/xfce4-terminal/deepin-terminal!");
        return;
    }
}
```

* As you can see from the code, each terminal has its own command line arguments
* The program needs to fill in the current working path to Terminal
* In fact, every desktop environment has a built-in Terminal, and these terminals are rarely mixed. For example, most people don't use gnome-terminal or konsole ina DDE environment

I'll keep using the system default terminal on non-Windows platforms.

**Comment by gadfly3173** [comment]
>     else if (File.Exists("/usr/bin/deepin-terminal"))
>     {
>         Process.Start("/usr/bin/deepin-terminal", $"--work-directory=\"{dir}\"");
>     }

```bash
$ deepin-terminal -h
load translate "/usr/share/dtk5/DWidget/translations/dtkwidget_zh_CN"
load translate "/usr/share/deepin-terminal/translations/deepin-terminal_zh_CN"
用法：deepin-terminal [选项]
终端是一款集工作区、多窗口、远程管理、雷神模式等功能的高级终端模拟器。

选项：
  -h, --help                      在命令行选项上显示帮助。
  --help-all                      显示包括 Qt 特有选项的帮助。
  -v, --version                   显示版本信息。
  -w, --work-directory <path>     设置终端的启动目录
  -e, --execute <command>         在终端中运行⼀个程序
  -q, --quake-mode                设置终端以雷神模式启动
  -m, --window-mode <state-mode>  设置终端开启的模式 (normal, maximum, fullscreen,
                                  splitscreen)
  --keep-open                     设置终端显示命令或脚本执行后的结果
  -C, --run-script <script>       在终端中允许脚本字符串
```

The argument for deepin-terminal should be `$"--work-directory \"{dir}\""`
