### ISSUE TITLE
Staging changed lines in side-by-side view does not remove replaced lines

### ISSUE THREAD

**Issue by goran-w** [sourcegit-scm/sourcegit#620]
When selecting one or more changed lines and staging them, the resulting staged file contains the changed lines but also the original lines (which should have been replaced by the changed ones).

See attached screenshots, where a couple of selected changed lines (with an empty line between them) are staged. One would expect the changed lines to replace the old version of these lines in the staged file, but instead the original lines are left intact and the changed lines are added as well. (Unstaging works fine and returns the unstaged file to its original state.)

The same issue is present in the Fork git-client, and has been reported there too. The SublimeMerge and GitKraken git-clients, on the other hand, does this correctly, and the last two screenshots are from doing the same operation (stage selected lines) in these tools...

NOTE: The Diff view of the staged file is consistent with the output of `git diff --cached` (alias for `git diff --staged`), so the problem is not in the display but in how the selected lines are staged against Git!

Staging selected lines (5-7) :
![image](https://github.com/user-attachments/assets/993f8976-830f-4dc1-96a3-56e907bde80d)
Unstaged file after stage-operation:
![image](https://github.com/user-attachments/assets/1db485a6-855a-451c-84cf-71c2061ac824)
Staged file after stage-operation:
![image](https://github.com/user-attachments/assets/a40f854d-3707-4f2b-beec-2d4b83fc49b9)
Cached diff from Git, after staging lines 5-7 in Sourcegit:
![image](https://github.com/user-attachments/assets/f807855c-02b8-481c-a09e-72233099878e)

SublimeMerge:
![image](https://github.com/user-attachments/assets/83477408-346d-4b40-9d69-a0e026bd1b26)
GitKraken:
![image](https://github.com/user-attachments/assets/5e2ce344-b8d5-427d-8ce6-157a865488f4)
Cached diff from Git, after staging the same lines in Sourcegit / GitKraken:
![image](https://github.com/user-attachments/assets/a2cfb9a3-2676-48b2-a8f9-81fd9b17ff7e)

**Comment by love-linger** [comment]
This is because, in `Combined` diff mode, you just stage/unstage/discard `add` or `delete` changes in the same line, for example:

![image](https://github.com/user-attachments/assets/071f3e59-2fe8-4250-872d-b69465f5b3fb)

So we must make sure it can be also done in the `Side-By-Side` mode.

![image](https://github.com/user-attachments/assets/5c828c39-d12d-4fba-9dd9-715c0faa723c)

**Comment by love-linger** [comment]
This feature is very useful for configuration files such as CSV and ini.

**Comment by goran-w** [comment]
Hmm, I see, but that feels quite un-intuitive to me and is not how these two other tools implement it even in their side-by-side diff. When I select a changed line in the side-by-side diff I expect it to be staged as a complete representation of that change (i.e replacing the old line with changed content).

I can see its use in some cases, but I'd at least suggest adding an option to set which one of these two possible behaviors is wanted here. What these two other tools do is that they show the line-selection on both sides of the (aligned) side-by-side diff, which makes more sense for their alternative interpretation of "stage selected lines"...

**Comment by goran-w** [comment]
For reference, here's how these two other tools display their two-sided selection in the unstaged file (here in a more interesting case where the changes cause mismatching lines (which are then aligned by empty lines in the diff view).

SublimeMerge:
![image](https://github.com/user-attachments/assets/eff68e32-1bbd-4f88-a23c-0d6494f84dec)

GitKraken:
![image](https://github.com/user-attachments/assets/f87793fb-c291-42b3-9080-93b01b0fc563)

**Comment by love-linger** [comment]
I'd like to keep current implementation. And as you have mentioned, the `Fork` uses the same rule.

**Comment by love-linger** [comment]
One more thing, if we sync seletion on both sides, it will lead to unexpected situations, for example: 

![image](https://github.com/user-attachments/assets/efc14689-a974-473f-aa4e-37f88ef6425e)

you can not just apply the changes on both side in selected range
