### ISSUE TITLE
当焦点处于变更对比时，切换不同的节点的时候，默认显示文件改动的第一个文件

### ISSUE THREAD

**Issue by heartacker** [sourcegit-scm/sourcegit#63]
![image](https://github.com/sourcegit-scm/sourcegit/assets/1876302/1bd278d4-dece-4de5-9039-d00cf4796607)

在这个视图下，点击不同的提交，建议都显示第一个改动文件对比视图。
而不是还需要用户去点击下面的文件列表去看对比

**Comment by heartacker** [comment]
- 也可以默认全是全部。通过滚动列表显示，类似 GitHub/gerrit 都是这样

**Comment by love-linger** [comment]
非常抱歉。基于以下4点，我认为这个需求是无必要的：

* 直接显示第一个，是否会真正减少用户操作
* 选中提交后，直接进行Diff，这一操作是否是用户需要的
* 内存占用问题。显示变更内容（尤其是在启用语法高亮的情况下）会占用大量内存
* 之前，有人向我提出建议，切换选中的提交时，需要将下方详情面板复位到第一个Tab页，也就是Information页；这又是特定用户，特定场景需求。

所以，在这里，我决定不做过多的用户行为预测。
