### ISSUE TITLE
Failed to generate commit message: System.Exception: AI service returns error code BadRequest

### ISSUE THREAD

**Issue by albgen** [sourcegit-scm/sourcegit#630]
hi,

when trying to generate commit messages with OpenAI API.
The problem is with package-lock.json file so if you wan to reproduce it as a problem.

[package-lock.json](https://github.com/user-attachments/files/17571021/package-lock.json)
[package-lock_new.json](https://github.com/user-attachments/files/17571024/package-lock_new.json)

> Failed to generate commit message: System.Exception: AI service returns error code BadRequest
>    at SourceGit.Models.OpenAI.Chat(String prompt, String question, CancellationToken cancellation) + 0x869
>    at SourceGit.Commands.GenerateCommitMessage.GenerateChangeSummary(Change change) + 0x8d
>    at SourceGit.Commands.GenerateCommitMessage.Result() + 0xff

**Comment by dougcunha** [comment]
The current strategy of sending separate diffs per file helps minimize this issue. However, if a file becomes exceptionally large, a Chunking and Summarization approach is the most suitable solution, IMHO.  It's crucial to remember that the maximum chunk size depends on the specific model being used.

**Comment by love-linger** [comment]
Currently, we have no plan to fix this issue.
