### ISSUE TITLE
Add possibility to review changes with external diff tool

### ISSUE THREAD

**Issue by dalbocha** [sourcegit-scm/sourcegit#633]
Please add a possibility to view changes with external diff tool. It should be configurable from settings menu.

**Comment by love-linger** [comment]
![image](https://github.com/user-attachments/assets/e36c5fcb-cce2-41b9-83aa-2caa4506c390)
![image](https://github.com/user-attachments/assets/fe7df0e8-8665-402f-9b33-74814cd51411)
![image](https://github.com/user-attachments/assets/b9c83f4d-a051-4965-b905-71331ceb5b07)

**Comment by dalbocha** [comment]
Ok, I missed it
