### ISSUE TITLE
Button text not displaying on macOS after upgrading Avalonia to 11.2.0

### ISSUE THREAD

**Issue by ChiahongHong** [sourcegit-scm/sourcegit#635]
Upgrading Avalonia to version 11.2.0 results in some button text not displaying, as shown in the screenshot below.

![button_text_missing](https://github.com/user-attachments/assets/e3af73ab-1dc1-4a1b-becb-842d60934339)

This appears to be a known issue as referenced in https://github.com/AvaloniaUI/Avalonia/issues/17376. (since that issue occurs on Windows, it may not be OS-specific and might instead happen under certain conditions)

While I believe this is likely an upstream issue, I have not yet identified the exact cause of this bug or found a workaround.

**Comment by love-linger** [comment]
Confirmed. It occurs on my macOS too, and can not re-produce on my PC. I'll revert the recent two commit those upgrade the project dependencies.

**Comment by love-linger** [comment]
Done.

**Comment by gadfly3173** [comment]
Confirmed on Linux, it seems to be a problem caused by center alignment. 
![image](https://github.com/user-attachments/assets/6b58604a-e94a-46ef-a407-1f3603ff992a)

https://github.com/AvaloniaUI/Avalonia/issues/17396
