### ISSUE TITLE
[feature request] Support for custom command.

### ISSUE THREAD

**Issue by htw128** [sourcegit-scm/sourcegit#638]
In my workflow, I often need to pull from the main branch first, then commit to my current branch, and finally push to main. With so many branches in my project, selecting the right branch from the list each time can be quite frustrating. Would you consider adding a custom command feature like the one in Sourcetree?

我的工作流中需要经常先从main pull后，先提交本分支，再推送至main。且项目分支众多，每次从分支列表中选择分支都很痛苦。是否考虑增加如sourcetree中的自定义命令功能？

**Comment by love-linger** [comment]
I've pushed a simple implementation of this feature. You can download the latest CI build from Github Action.

**Comment by love-linger** [comment]
1. You need to add a custom action from repository's configuration window
<img width="712" alt="image" src="https://github.com/user-attachments/assets/5b75ed98-1e16-48b9-8765-1864edc86dd0">

2. You can run repository's actions from the toolbar button:
<img width="1154" alt="image" src="https://github.com/user-attachments/assets/adf0b332-61b1-4ec7-9e50-68f39460a2cf">
or run commit's actions from the context menu of selected commit:
