### ISSUE TITLE
ubuntu 升级最新版本，无法打开！

### ISSUE THREAD

**Issue by zyimm** [sourcegit-scm/sourcegit#639]
### 错误截图

![图片](https://github.com/user-attachments/assets/f0c35d5a-a007-4efd-9e93-8390f2c4d94a)

错误原因好像与之前问题类似，相关问题：https://github.com/sourcegit-scm/sourcegit/issues/447

**Comment by zyimm** [comment]
> 你手动删除一下preference.json中的DefaultFontFamily呢？该文件在 `${HOME}/.config/SourceGit` or `${HOME}/.sourcegit`

试了一下，没有用。

**Comment by gadfly3173** [comment]
参考 https://blog.lindexi.com/post/dotnet-%E8%A7%A3%E5%86%B3-Avalonia-%E5%9C%A8-OpenKylin-%E9%BA%92%E9%BA%9F%E7%B3%BB%E7%BB%9F%E8%BF%90%E8%A1%8C%E6%89%BE%E4%B8%8D%E5%88%B0%E9%BB%98%E8%AE%A4%E5%AD%97%E4%BD%93%E5%90%AF%E5%8A%A8%E5%A4%B1%E8%B4%A5.html  ，我觉得问题出在FontManager可能不返回默认字体。

**Comment by love-linger** [comment]
但是删除了自定义配置后，SourceGit会使用内置的Inter字体

**Comment by love-linger** [comment]
如果删除字体没有用，那就手动指定一个字体呢，比如：`"DefaultFontFamily": "Ubuntu Monospace"`

**Comment by love-linger** [comment]
> 参考 https://blog.lindexi.com/post/dotnet-%E8%A7%A3%E5%86%B3-Avalonia-%E5%9C%A8-OpenKylin-%E9%BA%92%E9%BA%9F%E7%B3%BB%E7%BB%9F%E8%BF%90%E8%A1%8C%E6%89%BE%E4%B8%8D%E5%88%B0%E9%BB%98%E8%AE%A4%E5%AD%97%E4%BD%93%E5%90%AF%E5%8A%A8%E5%A4%B1%E8%B4%A5.html ，我觉得问题出在FontManager可能不返回默认字体。

Linux发行版太多了，不像Windows和macOS，没法指定DefaultFamilyName
* 我不清楚哪一种字体是所有Linux或是大部分常见Linux都可用的字体
* 同理Fallback也没法给个默认值，设置了DefaultFamilyName后，如果没有的字形都会默认Fallback到DefaultFamily上来。基于这个原因，我还是倾向于使用系统默认字体，至少它会与用户当前的显示语言挂钩。

**Comment by love-linger** [comment]
我修改了一下，使用Inter字体作为程序的默认字体。

**Comment by gadfly3173** [comment]
> 但是删除了自定义配置后，SourceGit会使用内置的Inter字体

![image](https://github.com/user-attachments/assets/c9e235d2-222e-4829-82e6-32e3e9c1c572)
inter.ttf中只有英文字体，它还是会回落到系统默认的吧

**Comment by love-linger** [comment]
嗯，看你的截图是一定会执行的。

**Comment by gadfly3173** [comment]
> * 同理Fallback也没法给个默认值，设置了DefaultFamilyName后，如果没有的字形都会默认Fallback到DefaultFamily上来。基于这个原因，我还是倾向于使用系统默认字体，至少它会与用户当前的显示语言挂钩。

考虑到在Avalonia中反馈的大部分也都是中文用户，可以考虑在初始化时如果读不到默认字体就设置为前述文中的字体

**Comment by love-linger** [comment]
这样的体验反而不好，我个人认为最好的解决方案是Linux下的包依赖于某字体包，需要用户安装相关字体，同时该字体为默认字体。但就目前的代码来看，还是需要上游的AvaloniaUI先修复$Default字体的问题。

**Comment by love-linger** [comment]
还有一个可能是，系统升级后，Linux需要重新生成font cache?

**Comment by gadfly3173** [comment]
> 还有一个可能是，系统升级后，Linux需要重新生成font cache?

我在openkylin V2试了一下，`fc-cache --force` 执行也没有效果。在终端中通过`LANG=en_US sourcegit`启动后，发现字体回落明显不正确，可能是Skia的问题

**Comment by love-linger** [comment]
只要程序不崩溃，我认为就还好。因为程序提供了设置字体的途径，且支持带回落字体的配置格式。

**Comment by gadfly3173** [comment]
> 只要程序不崩溃，我认为就还好。因为程序提供了设置字体的途径，且支持带回落字体的配置格式。

当前的修改看起来不足以解决这问题。在麒麟上调试了一下，获取到的默认字体是仿宋，但是后面依然缺少一些内容导致无法正确处理字体
![image](https://github.com/user-attachments/assets/bbe2dd55-7bcb-4e74-a2e0-d0db27523bd5)
