### ISSUE TITLE
[feature request] Ability to change window tile organization

### ISSUE THREAD

**Issue by HydraCOREY** [sourcegit-scm/sourcegit#640]
It would be nice to have a vertical layout or to be able to move the different sections around.

For example, moving the tree view to the left and the Information/Changes/Files view to the right.

![image](https://github.com/user-attachments/assets/cf2445e7-9e48-4af6-b8a8-17e27f0bbf79)

**Comment by love-linger** [comment]
Click the first button on the right of 'Histories' tab switcher

**Comment by love-linger** [comment]
<img width="1220" alt="image" src="https://github.com/user-attachments/assets/13ab7f59-d37b-4ea4-92a4-2c794fc9411f">

**Comment by HydraCOREY** [comment]
I totally didn't see that. 
Thank you so much for pointing it out. 
It seems to remember the placement, which was going to be my next question.
