### ISSUE TITLE
Window freeze on OpenKylin after open a dialog

### ISSUE THREAD

**Issue by gadfly3173** [sourcegit-scm/sourcegit#642]
1. Chromeless window shadow position display error. (popups or system style is normal)

![image](https://github.com/user-attachments/assets/2f00f595-801c-4098-85ba-8a752f246be8)

2. Create a new window and then close it(such as open Preference). The main window would be frozen and cannot be clicked and will penetrate to the following windows. Switching to other applications cannot restore it.

Maybe they are all issues in Avalonia, I'm not sure.

**Comment by love-linger** [comment]
I think this should be a problem with the OpenKylin window compositor. 

To solve the problem of different display effects on different Linux distributions, SourceGit uses a custom window frame (that is, SystemDecorations is None and ExtendClientAreaChromeHints is NoChrome) on Linux platforms. The window shadow is self-drawn by the program. There should not be the outer window shadow shown in your screenshot.

**Comment by love-linger** [comment]
For this issue, `SourceGit` provides the `Use native window frame` option in `Preference > APPEARANCE`.

**Comment by gadfly3173** [comment]
> For this issue, `SourceGit` provides the `Use native window frame` option in `Preference > APPEARANCE`.

The first problem can be solved with native windows, but the second problem cannot. I am not sure if it is a problem with Avalonia or OpenKylin's window management.

**Comment by gadfly3173** [comment]
I tried remove the `await` symbol before `window.ShowDialog` and add these code in ChromelessWindow, they all have no work.
```csharp
        protected override void OnClosing(WindowClosingEventArgs e)
        {
            base.OnClosing(e);
            if (!e.Cancel && IsActive)
            {
                Owner?.Activate();
            }
        }
```
After open the new dialog, the owner window will just freeze and cannot be actived or handle any operations... This should be a compatibility issue between Avalonia and OpenKylin, but I don’t know how to solve it. Since there is no feedback from others, you can close this issue.

**Comment by love-linger** [comment]
I'll keep this issue open for a month, and hope someone can solve this problem.

**Comment by love-linger** [comment]
@gadfly3173 one more thing, can you test `FileHistories` or `Blame` window? These two windows is not opened as a modal dialog. I want to confirm if this issue only affects the modal dialogs.

**Comment by gadfly3173** [comment]
> @gadfly3173 one more thing, can you test `FileHistories` or `Blame` window? These two windows are not opened as modal dialogs. I want to confirm if this issue only affects the modal dialogs.

These two worked fine. And I found that when I opened other applications, `ShowDialog` would cause the window to freeze. If there were no other windows running in the desktop environment, it would work normally.

**Comment by love-linger** [comment]
So, it is only affects the modal dialogs.

**Comment by love-linger** [comment]
I can confirm the modal dialogs also work fine on Debian 12 (Wayland). Maybe as you said:

> This should be a compatibility issue between Avalonia and OpenKylin`

**Comment by love-linger** [comment]
Closed as no more feedback
