### ISSUE TITLE
How to Contribute

### ISSUE THREAD

**Issue by AleksandrLiakhavetsEPAM** [sourcegit-scm/sourcegit#643]
Hi, source git team. I am trying to contribute - just small fix. But i can't create a PR 

The error is:
```
Git failed with a fatal error.
unable to access 'https://github.com/sourcegit-scm/sourcegit.git/': The requested URL returned error: 403
```

Do you have an instruction how to contribute to your project

Thank you.

**Comment by gadfly3173** [comment]
From your repository list and your issue, it seems that you have not forked this repository. You need to fork it, modify it based on the latest `develop` branch, submit it to any branch of your own repository, and then create a PR from your branch to the `develop` branch of this repository on GitHub.

**Comment by AleksandrLiakhavetsEPAM** [comment]
Thank you @gadfly3173. Clear now.
