### ISSUE TITLE
[Feature] Add Groq AI

### ISSUE THREAD

**Issue by ZorinFoss** [sourcegit-scm/sourcegit#649]
Hi,

Please add support for [Groq AI](https://groq.com/).

Thanks,

**Comment by gadfly3173** [comment]
It seems that groq is compatible with openai https://console.groq.com/docs/openai

**Comment by love-linger** [comment]
For groq ai, the service url must be https://api.groq.com/openai/v1/chat/completions

**Comment by love-linger** [comment]
For example:

![image](https://github.com/user-attachments/assets/d0f386a0-8ba5-495f-ad51-5ca6613cb60d)

**Comment by ZorinFoss** [comment]
Correct the name, it's `Groq AI` not `Grop AI`

**Comment by ZorinFoss** [comment]
The correct api_url "https://api.groq.com/openai/v1"

**Comment by love-linger** [comment]
![image](https://github.com/user-attachments/assets/a90c52d8-e838-4fc4-9986-483af4bd868e)
