### ISSUE TITLE
形如url和邮箱的字符串显示为深蓝色，在深色模式下难以阅读

### ISSUE THREAD

**Issue by gadfly3173** [sourcegit-scm/sourcegit#65]
形如url和邮箱的字符串显示为深蓝色，在深色模式下难以阅读

![image](https://github.com/sourcegit-scm/sourcegit/assets/28685179/627caf0a-33bf-48e2-9e10-c44d9385d4f0)

**Comment by love-linger** [comment]
这是因为集成的TextMate将*.lock文件视为一般文本文件，后面优化一下

**Comment by gadfly3173** [comment]
在ejs、yml文件中也有相同情况。

![image](https://github.com/sourcegit-scm/sourcegit/assets/28685179/a017a173-4b2b-4c6f-9a49-bc7e086f2dae)

![image](https://github.com/sourcegit-scm/sourcegit/assets/28685179/87442244-0b4d-4144-8b51-7b0645d67888)

**Comment by love-linger** [comment]
非常抱歉，是我搞错了。这不是TextMate主题的问题，而是因为AvaloniaEdit默认启用了Hyperlinks支持。为了不影响到TextMate语法高亮，目前已关闭了AvaloniaEdit内置的Hyperlinks和EmailHyperlinks
