### ISSUE TITLE
[Feature] Add Emojis support

### ISSUE THREAD

**Issue by ZorinFoss** [sourcegit-scm/sourcegit#650]
Hi,

Please add support for emojis.

Thanks

**Comment by love-linger** [comment]
![image](https://github.com/user-attachments/assets/7f6594f9-d248-4b1e-b4e0-2e16636fc4db)

In fact, it depends on the font you use.

**Comment by love-linger** [comment]
![image](https://github.com/user-attachments/assets/2651483c-f2eb-4faa-872d-c8d4b0c76f6b)

**Comment by ZorinFoss** [comment]
> ![image](https://private-user-images.githubusercontent.com/4075673/382647374-7f6594f9-d248-4b1e-b4e0-2e16636fc4db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MDMxMDEsIm5iZiI6MTczMDcwMjgwMSwicGF0aCI6Ii80MDc1NjczLzM4MjY0NzM3NC03ZjY1OTRmOS1kMjQ4LTRiMWUtYjRlMC0yZTE2NjM2ZmM0ZGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDRUMDY0NjQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjA1NWU2MjNiZmI2MDAwZTM2MzcwODA3NzAyZWViM2NhNzQzNGYyZDFkY2M0OGVhZTk4M2EyOGI2OTVjZDc1ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.kLE7fSLx6MPzgs18dnNkS6V6dEq00QCFf8tK2tLWzb4)
> 
> In fact, it depends on the font you use.

Which font `Default Font` or `Monospace Font`?

**Comment by love-linger** [comment]
If you toggle the `Only use monospace font in text editor`, the monospace font is only used in the text editors, such as `Text Diff View`, `File Content Preview Editor`, `Blame View`.

**Comment by love-linger** [comment]
In fact. You just need customize the `Default Font` - we will use it as the fallback font of `Monospace Font`
