### ISSUE TITLE
support copy issue link with right click

### ISSUE THREAD

**Issue by heartacker** [sourcegit-scm/sourcegit#651]
![image](https://github.com/user-attachments/assets/9c8647ee-1431-4ad9-acd0-a87ef363f241)

1. copy link with right click
2. open a menu with right click
   3. sub menu opened and have one opt: copy link

**Comment by love-linger** [comment]
![image](https://github.com/user-attachments/assets/67dbe1d5-453e-431c-a21c-782dc33c7eb6)

But there's known issue with context menu in SelectableTextBlock. See https://github.com/AvaloniaUI/Avalonia/issues/16820

**Comment by love-linger** [comment]
Currently, if you click the issue link with left mouse button, it will open the issue link in browser. And if you click the issue link with right mouse button, it will NOT open the issue link in browser, but show the context menu instead.
