### ISSUE TITLE
[Feature] Ollama Support

### ISSUE THREAD

**Issue by CoolCoderSuper** [sourcegit-scm/sourcegit#653]
It would be kind of neat to support [Ollama](https://ollama.com/library) with https://github.com/awaescher/OllamaSharp.
This would allow us to use any model that Ollama supports which is quite a bit.

**Comment by love-linger** [comment]
You can also use different models with multiple AI service configurations.

**Comment by CoolCoderSuper** [comment]
Hmmm, I couldn't seem to find anything other than OpenAI in the settings

**Comment by love-linger** [comment]
I'm sorry for this. It's just called `OpenAI`. You can configure for a self-host AI serivce with OpenAI compatible HTTP API. For example:

![image](https://github.com/user-attachments/assets/602fc8e3-acba-4574-b038-3028cc3891c8)

**Comment by love-linger** [comment]
Remember for Ollama, the server is `http://localhost:11434/v1/chat/completions` instead of `http://localhost:11434/api/generate`. See https://ollama.com/blog/openai-compatibility
