### ISSUE TITLE
How to remove origin branches from side panel if branch has already been deleted?

### ISSUE THREAD

**Issue by BernatBC** [sourcegit-scm/sourcegit#654]
Greetings,

I would like to ask if there's a way to remove from the side panel a branch in remotes/origin that has already been deleted. This happens when another user deletes a branch from GitHub. When trying to delete the remote branch, it cannot as it does not find the reference (cause it's already deleted).

The error I get is the following:
`error: unable to delete 'branch-name': remote ref does not exist
error: failed to push some refs to 'github.com:user/repo.git'`

**Comment by gadfly3173** [comment]
see #590 , there a few ways to deal
- there is a new setting in repository configure dialog 
- right click the remote to prune
- use configuration of git itself

**Comment by BernatBC** [comment]
Thank you so much @gadfly3173, I didn't know that pruning was the answer to my question
