### ISSUE TITLE
bitbucket not remembering password

### ISSUE THREAD

**Issue by Hyphaed** [sourcegit-scm/sourcegit#656]
hi people

first of all thanks for the great job

I'm using sourcegit with a bitbucket account

everytime I do a push is asking for password, shouldn't be remembering it? or have a checkbox to remember the password?

I'm on SourceGit 8.37

**Comment by love-linger** [comment]
What operating system are you using? Is `git-credential-manager` already installed? `SourceGit` itself does not manage user accounts, but relies on the `git-credential-manager`

**Comment by Hyphaed** [comment]
I'm on ubuntu 24.10

installed the app from the deb you share here on Release section

I do not see package under the name git-credential-manager

I do have installed git-credential-oauth package

**Comment by love-linger** [comment]
https://github.com/git-ecosystem/git-credential-manager/releases

**Comment by Hyphaed** [comment]
installed it (gcm-linux_amd64.2.6.0.deb)

and then did 
git-credential-manager configure

still without remembering the passwords

Do you have any ppa for sourcegit?

**Comment by love-linger** [comment]
> installed it (gcm-linux_amd64.2.6.0.deb)
>
> and then did
> git-credential-manager configure
>
> still without remembering the passwords

Do you unconfigure the `git-credential-oauth` you used before? See doc https://github.com/hickford/git-credential-oauth.
PS. It's better to restart SourceGit to make sure there's no cached configuration in runtime.

> Do you have any ppa for sourcegit?

Unfortunately, there is currently no PPA for SourceGit.

**Comment by Hyphaed** [comment]
Amazing, now is working  

seems git-credential-oauth is working along git-credential-manager without need of using App Password token from bitbucket


after getting an error message from SourceGit (that I've just posted later)

I typed on console

git config --global credential.credentialStore cache

then on first fetch SourceGit open OAuth authentification to get access to bitbucket


```
fatal: No credential store has been selected.
Set the GCM_CREDENTIAL_STORE environment variable or the credential.credentialStore Git configuration setting to one of the following options:
  secretservice : freedesktop.org Secret Service (requires graphical interface)
  gpg           : GNU `pass` compatible credential storage (requires GPG and `pass`)
  cache         : Git's in-memory credential cache
  plaintext     : store credentials in plain-text files (UNSECURE)
See https://aka.ms/gcm/credstores for more information.
fatal: No credential store has been selected.
Set the GCM_CREDENTIAL_STORE environment variable or the credential.credentialStore Git configuration setting to one of the following options:
  secretservice : freedesktop.org Secret Service (requires graphical interface)
  gpg           : GNU `pass` compatible credential storage (requires GPG and `pass`)
  cache         : Git's in-memory credential cache
  plaintext     : store credentials in plain-text files (UNSECURE)
See https://aka.ms/gcm/credstores for more information.
error: unable to read askpass response from '/opt/sourcegit/sourcegit'
fatal: could not read Password for 'https://myprivateaccount@bitbucket.org': No such device or address
```

**Comment by love-linger** [comment]
So I'll close this issue as completed

**Comment by love-linger** [comment]
Yes. The `git config --global credential.credentialStore cache` or `GCM_CREDENTIAL_STORE` is needed by `git-credential-manager`. And the `git-credential-oauth` is not needed any more

**Comment by love-linger** [comment]
I'm only use `git-credential-manager` on my Debian 12. And it works fine for me.

**Comment by Hyphaed** [comment]
@love-linger are you using the OAuth with 2 factor from bitbucket with git-credential-manager ? or have you created an App password

I was working with App Password

I do find amazing being able to use the OAuth plus SourceGit now doesn't ask each time for the App Password token

**Comment by love-linger** [comment]
Yes. I'm using the OAuth with 2 factor but from github
