### ISSUE TITLE
是否可以支持 某一个范围的 commit 的时候生成patch

### ISSUE THREAD

**Issue by heartacker** [sourcegit-scm/sourcegit#658]
现在只能将某一个commit 生成 patch

**Comment by love-linger** [comment]
现在增加了两个`另存为补丁`的地方：

1. 多个Commit的右键菜单。由于多个commit可能对同一文件进行修改，该方式会为每个commit生成patch文件，并在用户选择的保存目录下创建patches子目录，存放生成的patch文件
![image](https://github.com/user-attachments/assets/97683b43-d3e8-4691-8b21-802ad254c605)
2. 可直接使用Revision Compare的结果，另存为单一的一个补丁文件
![image](https://github.com/user-attachments/assets/b82baa18-be7d-4295-a594-a83349816665)

**Comment by heartacker** [comment]
thanks and FYI
```
$ git format-patch HEAD^       #生成最近的1次commit的patch
$ git format-patch HEAD^^      #生成最近的2次commit的patch
$ git format-patch HEAD^^^     #生成最近的3次commit的patch
$ git format-patch HEAD^^^^    #生成最近的4次commit的patch
$ git format-patch <r1>..<r2>  #生成两个commit间的修改的patch（生成的patch不包含r1. <r1>和<r2>都是具体的commit号)
$ git format-patch -1 <r1>     #生成单个commit的patch
$ git format-patch <r1>        #生成某commit以来的修改patch（不包含该commit）
$ git format-patch --root <r1> #生成从根到r1提交的所有patch
```

**Comment by love-linger** [comment]
右键使用的就是`git format-path`，但是由于用户可以使用Ctrl键选择不连续的提交，所以只能循环对每个选中的提交执行format-path。

Revision Compare由于是diff的结果，所以就直接程序拼接了一个最终的patch文件

**Comment by heartacker** [comment]
理解
1. 如果用户选择不同的分支，或者选择的是不在同一个分支的。那么可以逐个导出
2. 如果用户选择的是同一个分支
   - 如果用户使用 使用 shift 键盘选择，那么就是连续的提交 or 如果用户ctrl 选择多个>=2，刚好也是连续的。
      - 提供逐个导出，
      - 或者连续导出。
   - 如果用户使用 ctrl 选择 = 2 个，且不连续
      - 提供逐个导出选项。
      - 提供以这两个为起点和终点的连续导出选项。

**Comment by love-linger** [comment]
* 我不明白连续导出指的是什么。git format-patch 如果涉及多个提交，也是一个个生成patch的，唯一的区别是序号有了意义。
* 选中的提交列表中的元素顺序取决于你先选择了哪个（这是ListBox控件的行为）。这带来一些问题：
  - 如果要根据parent判断是否连续，必需对该列表排序。且排序不会按时间先后，因为有些人本机的时间不正确，导致提交时间是不对的。目前想到的算法是有消耗的，会导致在配置差的机器上，右键菜单不能及时弹出。
  - 同时git format-patch R1..R2对于R1与R2的顺序也有要求 - 如果R1与R2无关，或是R2是R1的祖先，是不会生成patch的。
