### ISSUE TITLE
默认窗口大小下，对于commit信息较长的提交，基本信息页无法滚动到下方的变更列表

### ISSUE THREAD

**Issue by gadfly3173** [sourcegit-scm/sourcegit#66]
默认窗口大小下，对于commit信息较长的提交，比如gitlab的MR，基本信息页无法滚动到下方的变更列表，这个tab可以滚动的区域只有下方的文件列表，可以考虑 让整个tab都可以滚动/默认提交信息只显示一行 之类的形式进行一下优化？

![image](https://github.com/sourcegit-scm/sourcegit/assets/28685179/bc75fc83-fbe9-4b4a-863a-a071ad4914cb)

**Comment by love-linger** [comment]
提交信息本身是做了最大长度限制的。我是以我的4K屏上的显示效果来设计布局的。默认窗口大小下，我这里是显示出两行：
![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/7e567501-983c-4359-8484-3ae029723b64)

* 同时提供了GridSplitter来调整上下两部分的大小
![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/982aa585-8f35-45f0-8ba9-801c8c0cfed8)

* 同时，由于针对目前主流的宽屏显示器，提供了水平/垂直Layout排布切换
![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/f8566c4e-e6da-4100-bb8c-9b42f0a459c7)

**Comment by love-linger** [comment]
还有一个不做整个tab页滚动的原因：

如果ListView的Size为Auto（不使用滚动），则其无法启用Virtualization优化，所有的节点都会创建。对于大工程（比如：我上面截图的Unreal Engine仓库）的合并节点的变更列表显示，会变得很卡。

**Comment by gadfly3173** [comment]
观察你的截图后我发现似乎区别在于我选中的提交是我本地分支的最新一条，有[相关引用]这一条目，在没有这个条目时我1080p的屏幕也可以看到约1.5行的文件列表
