### ISSUE TITLE
After Fetch/Pull deleted remote branches are still visible

### ISSUE THREAD

**Issue by dalbocha** [sourcegit-scm/sourcegit#660]
Deleted remote branches are still shown after fetch/pull. If I try to delete it from remote branches tree I get a error message that this branch doesn't exit, what is correct.

**Comment by gadfly3173** [comment]
see #654

**Comment by dalbocha** [comment]
For my opition this option [(#654)](https://github.com/sourcegit-scm/sourcegit/issues/654) should be enabled by default, because it is very confusing to see deleted branches.

**Comment by gadfly3173** [comment]
The automatic pruning feature is turned off by default in git, and not all git GUIs have it turned on by default. It might be better to have an operating instruction for this. 🤣
