### ISSUE TITLE
UI: Please add separate font sizes for UI and code

### ISSUE THREAD

**Issue by dalbocha** [sourcegit-scm/sourcegit#661]
At the moment I found only one place to change font size of UI and code: in Preference-Appearance. Increasing/decreasing the "Default Font Size" the font size for UI AND code changes both.
It would be nice to set the font sizes for ui and code separately.

**Comment by love-linger** [comment]
Done. You can download the latest CI build from Github Action.
![image](https://github.com/user-attachments/assets/6f33ce4a-8bca-4a47-8c3a-ea5dae5f1388)

**Comment by dalbocha** [comment]
That was quick. Thanks a lot!
