### ISSUE TITLE
Add a possibilty to define custom diff/merge tool

### ISSUE THREAD

**Issue by dalbocha** [sourcegit-scm/sourcegit#662]
In Preference-Integration I can select diff/merge tool from the list of predefined values. It would be nice to set custom diff/merge tool, than is not on the list. There is a option "Use Git Settings" but the possibility to set own tools is much quicker.

**Comment by love-linger** [comment]
If your preferred diff/merge tool is not in the currently supported list, you can provide the tool's official website, DIFF/MERGE command line parameters, and supported platforms. We'll add it later.

**Comment by dalbocha** [comment]
My idea was to have something like this:
![2024-11-07_102725](https://github.com/user-attachments/assets/6488bd7d-156a-46e2-a481-8f07a20c6fe8)

**Comment by dalbocha** [comment]
I see...
Tool: Diffinity
Params: REMOTE LOCAL
Platform: Windows only

**Comment by love-linger** [comment]
One more question, what's the command for merging?

**Comment by love-linger** [comment]
I'm very sorry. Since `Diffinity` can only be opened as difftool, SourceGit will not add it to the built-in support.
