### ISSUE TITLE
[feature request] Managing repo on remote machine via ssh

### ISSUE THREAD

**Issue by arsh12344** [sourcegit-scm/sourcegit#669]
It will be useful for developing on a remote server via ssh.

**Comment by aikawayataro** [comment]
Cool idea but this will require major rewrite so I believe this is not going to be implemented. I can't see a clear reason for this either. Accessing the repository via ssh on remote machine just looks like "proxying" stuff. Why can't you work locally and then push your work to remote? What is the purpose of remote machine here?

At the end you can use sshfs or run SourceGit with X11 forwarding on remote machine.

**Comment by ruzito** [comment]
The reason:
- Thin client, heavy repo, buildsystem with dependencies on a remote VM
- sshfs is so slow, that git operations take forever

**Comment by gadfly3173** [comment]
> The reason:
> 
> * Thin client, heavy repo, buildsystem with dependencies on a remote VM
> * sshfs is so slow, that git operations take forever

Git itself needs to be able to access the repository directly in the file system to manage the repository. Therefore, if you want to manage a remote repository without cloning, you must have a service on remote, just like `vscode` or `Jetbrains` IDE. This is very different from the current implementation of `SourceGit`. In this case, it would be more convenient to use the built-in git tool in the IDE or X11 forwarding.
