### ISSUE TITLE
Add possibility when creating a new branch

### ISSUE THREAD

**Issue by Kleak** [sourcegit-scm/sourcegit#670]
Would be great to have the possibility to create a new branch with a random name.
If it's possible to also have the possibility to add a prefix that would be awesome.

**Comment by aikawayataro** [comment]
I believe it might not be something that works for everyone. This way SourceGit can become too "feature-crowded".
You can define a custom action for such thing:
![image](https://github.com/user-attachments/assets/313b3af6-44c2-40e6-ad2e-50e9dd76053f)

(could also be a shell/python/whatever script)
