### ISSUE TITLE
Add the ability to open a file from a specific commit (with the default application)

### ISSUE THREAD

**Issue by Cyrillev91** [sourcegit-scm/sourcegit#674]
Hi,
can you add the ability to open a file from a specific commit (in the default program).
For example:
we select a commit, then we go to the Files tab, Right click on a file then Open.

His is useful when the file format is a binary for example and we need to open it with a specific program to view its content.

![image](https://github.com/user-attachments/assets/5b4b5de1-ea11-41af-a458-e0e96fefe98d)

**Comment by love-linger** [comment]
Done.

**Comment by Cyrillev91** [comment]
Hi,

Is it possible that the "Open With ..." function opens the commit file and not the working directory file.
The steps performed by the SourceGit software would be:
- creation of the file (like the Save As of the same menu) but in a temporary folder of the system
- opening of the temporary file with default software (like the current Open With)

The name of the temporary file could be <name>~<sha1>.<ext>
example to open the file README.md from commit 67cf23267a76a5c2727833c5e8716ec34050e03f
name of the temporary file: README~67cf23267.md
