### ISSUE TITLE
keep selected file when change commit (changes and Files Tab)

### ISSUE THREAD

**Issue by Cyrillev91** [sourcegit-scm/sourcegit#675]
Hi,
Can you add this behavior:
keep the selected file (changes or files tab) when selecting another commit (if the file exists in the new selected commit)

current behavior (with changes tab)
![followingFile_before](https://github.com/user-attachments/assets/d2b2076e-4b1f-4ab0-a8a7-be7bc4deb130)

New behavior (with changes tab)
![followingFile_After](https://github.com/user-attachments/assets/ab4e9ea5-4f72-4eb4-bdc7-929ab9f1c422)

**Comment by love-linger** [comment]
* This is not the recommended way to track changes to a given file. In fact, you should use the `File Histories` or `Blame` feature.
* This is also a issue that has been mentioned many times. Some people suggest that after switching commit, you should always switch to the `INFORMATION` page (and then manually switch to other pages if necessary); others suggest that after switching commit, the first file should be automatically selected; and here it is sugguested that the last selected file needs to be automatically selected...
