### ISSUE TITLE
Open Repository does nothing

### ISSUE THREAD

**Issue by LinuxDevon** [sourcegit-scm/sourcegit#677]
Hello, First of all thank you for this application! Doing a great job!

I reinstalled the application after doing a clean linux install. I am having an issue with the `Open Repository` button now. It doesn't open up anything or show any output. Not sure what I am doing wrong. I can open up the `App Data Dir` from the menu. That does pull up `Thunar` correctly.

I am running i3 with X11 and installed the required `xdg-utils` that is on the README.

Running this command does show that I have configured a default:

```shell
$ xdg-mime query default inode/directory
thunar.desktop
$ xdg-open . <- Does open up a window as well.
```

Wondering if there is a window or mode to debug why it isn't doing anything. I don't see a pop up like I have before when there was an issue. Let me know any other information you might need.

Thank you for the support!

**Comment by love-linger** [comment]
`Open Repository` calls `TopLevel.StorageProvider.OpenFolderPickerAsync(FolderPickerOpenOptions opt)` which is an AvaloniaUI's API.

**Comment by love-linger** [comment]
如果您可以自行编译项目的话，你可尝试修改`src/Native/Linux.cs`文件，在`public void SetupApp(AppBuilder builder)`函数的最后，增加一行代码，如：

```diff
 public void SetupApp(AppBuilder builder)
 {
    builder.With(new X11PlatformOptions()
    {
        EnableIme = true,
    });

+   builder.UseManagedSystemDialogs();
 }
```

**Comment by aikawayataro** [comment]
> I am running i3 with X11

Is it Arch? Do you have `xdg-desktop-portal` (and at least one backend) installed?

**Comment by LinuxDevon** [comment]
Yes I am on Arch. I think @aikawayataro is in the right direction. I thought I had this installed and a backend. Indeed I did, but see errors in the service. What tipped me off was my browser was also having troubles but with downloads.

I am running into problems with the backend I have right now. 
* https://bbs.archlinux.org/viewtopic.php?id=292533
* https://bbs.archlinux.org/viewtopic.php?id=294808

Working through the issues right now locally. I'll reach back out when I find a solution so others bumping into this can fix it as well.

**Comment by LinuxDevon** [comment]
Thank you all for your help! This wasn't a bug on the application side. User error :upside_down_face: 

Solution is for those bumping into this is the requirement of the [`xdg-desktop-portal` ](https://wiki.archlinux.org/title/XDG_Desktop_Portal) on startup. If you have Xorg running be sure to initialize the scripts in the `.xinitrc`. Other windows file pickers such as browsers will also be affected by this. 

```
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi
```

https://bbs.archlinux.org/viewtopic.php?pid=2165359#p2165359

Sorry for the noise on the issues here!
