### ISSUE TITLE
issue link is broken

### ISSUE THREAD

**Issue by heartacker** [sourcegit-scm/sourcegit#678]
- list 
![image](https://github.com/user-attachments/assets/47d9279b-15a0-4ee1-bc84-73baef3440fe)

- detail page work
![image](https://github.com/user-attachments/assets/5c0d4b80-b265-4617-9856-d5de0b05f999)

**Comment by love-linger** [comment]
这是因为，`xxx(yyy): `或是`xxx<yyy>: `或是`[yyyy] `开头会被解析为关键字，使用了粗体绘制。后面我会提交一个优化，兼容在关键字中支持ISSUE link

**Comment by love-linger** [comment]
已解决，您可下载最新的CI Build
