### ISSUE TITLE
X11 转发模式下，是否有办法使用本地的浏览器打开各种链接，而不是使用远程 X11 浏览器

### ISSUE THREAD

**Issue by heartacker** [sourcegit-scm/sourcegit#679]
比如，现在使用 Ubuntu X11 转发 打开sourcegit，但是每次点击链接，就会打开火狐，又卡又慢
是否有办法使用本地的edge 打开

**Comment by love-linger** [comment]
X11转发你可以简单的理解为播放器机制。本质上代码还是运行在远端的Linux机器上，本地只是绘制X11的Windows。

**Comment by heartacker** [comment]
明白这个意思，X11 其实只是显示

不过想问问是否有哪些 geek 手段可以解决我上诉的问题。

**Comment by love-linger** [comment]
这个我不太清楚。按道理来说，这种不安全操作应该是会直接被禁止的。

**Comment by gadfly3173** [comment]
https://www.wyr.me/post/723 https://github.com/superbrothers/opener 看起来这种操作需要在客户端和服务端同时做一些特殊的配置/服务

**Comment by heartacker** [comment]
是的，不过看链接，他的守护进程只能在linux 下运行。很需要一个windows的

**Comment by heartacker** [comment]
太神奇了，X11 转发，链接到一个没有安装浏览器的linux， 点击打开问题单，尽然可以转到windows 这里的浏览器打开，这个也太神奇了。

@gadfly3173  看看这个是啥原理

**Comment by gadfly3173** [comment]
这是X11自己的配置吧，比如没有安装浏览器的时候，xdg-open打开浏览器的指令可以被windows代理之类的
