### ISSUE TITLE
Add the ability to open a file from a specific commit (complement of #674)

### ISSUE THREAD

**Issue by Cyrillev91** [sourcegit-scm/sourcegit#681]
Hi,

complement of #674 :

Is it possible that the "Open With ..." function opens the commit file and not the working directory file.
The steps performed by the SourceGit software would be:

-    creation of the file (like the Save As of the same menu) but in a temporary folder of the system
-    opening of the temporary file with default software (like the current Open With)

The name of the temporary file could be name~sha1.ext

example to open the file README.md from commit https://github.com/sourcegit-scm/sourcegit/commit/67cf23267a76a5c2727833c5e8716ec34050e03f
name of the temporary file: README~67cf23267.md

**Comment by love-linger** [comment]
Done. You can download the latest CI build from Github Actions
