### ISSUE TITLE
Commit message disappearing when context menu is opened

### ISSUE THREAD

**Issue by NilsPvR** [sourcegit-scm/sourcegit#682]
**Current behaviour**
When a context menu is open (right click on commit, branch, etc.) and a left mouse click on the commit message is made the text just disappears. After reloading the tab the text comes right back. 

https://github.com/user-attachments/assets/74714e8f-9af6-4ccf-9cda-f1a5abca0051

**Expected behaviour**
I would expect the text to just stay there.

**Tested on:**
Windows 10, Sourcegit Version: v8.38, v8.37 and current dev db66ba82a627449b0da2bcafd901fa2049e2bc36

**Comment by aikawayataro** [comment]
https://github.com/AvaloniaUI/Avalonia/issues/16820

**Comment by NilsPvR** [comment]
> [AvaloniaUI/Avalonia#16820](https://github.com/AvaloniaUI/Avalonia/issues/16820)

Alright thanks for the link. 👌🏼
