### ISSUE TITLE
Fetch tags ignored tag conflict

### ISSUE THREAD

**Issue by gadfly3173** [sourcegit-scm/sourcegit#684]
![image](https://github.com/user-attachments/assets/f4bf85f9-ed04-4fc4-9f28-7ce66e36f153)
![1731374062147](https://github.com/user-attachments/assets/6022e689-d3db-4068-94d5-ec9ed58f4a92)

sourcegit `v8.38` deleted the original tag and then pushed the new tag. sourcegit itself seems to have no way to handle or show the conflict of such tag reference changes.

**Comment by love-linger** [comment]
It's because when you try to fetch remote changes without `Fetch without tags` on, `SourceGit` will enable the `--force` parameter for `git fetch` command.

I'll remove it later

**Comment by love-linger** [comment]
Done.

**Comment by gadfly3173** [comment]
```bash
$ git fetch sourcegit --porcelain  --verbose 
= 4dbc141003bdf2b068eac1ee306998501cb9d1ed 4dbc141003bdf2b068eac1ee306998501cb9d1ed refs/remotes/sourcegit/develop
= 13805f794a9aa6ab0f8b1f07cb99d859c015f601 13805f794a9aa6ab0f8b1f07cb99d859c015f601 refs/remotes/sourcegit/master
```

I think `git-fetch` without `--tags` would not show the conflict.

**Comment by gadfly3173** [comment]
![image](https://github.com/user-attachments/assets/e07d0e6b-eda7-4ee3-8beb-4cae0d6aad09)
maybe `--verbose` is not required? The error message is too long.

**Comment by love-linger** [comment]
`--verbose` is used to get detail progress description.

**Comment by gadfly3173** [comment]
Thx. I think this is good enough for me.
