### ISSUE TITLE
Error install osx-arm64

### ISSUE THREAD

**Issue by Shagrat2** [sourcegit-scm/sourcegit#685]
Hello

Error install osx-arm64 when copy to programs "The SourceGit application is corrupted and cannot be opened. Move the application to the Trash."

PC: MacStudio, Apple M2Ultra
OS: 15.1 (24B83)
Version sourcegit: sourcegit_8.38.osx-arm64.zip

Error workaround: Install sourcegit_8.38.osx-x64.zip - Work from Rosetta

**Comment by love-linger** [comment]
You can run `sudo xattr -cr /Applications/SourceGit.app` to remove the `com.apple.quarantine` attribute added by macOS.

**Comment by love-linger** [comment]
It's because I do NOT hava a valid Apple Developer Account, and the `SourceGit` macOS app is packaged without certificates

**Comment by Shagrat2** [comment]
But sourcegit_8.38.osx-x64.zip works fine

**Comment by love-linger** [comment]
I'm not sure if macOS treats `arm64` packages differently from `x64` packages. The way we package macOS app is exactly the same, the only difference is whether `osx-arm64` or `osx-arm64` is passed to `dotnet publish` while building executable files.

**Comment by ybeapps** [comment]
It behaves differently in my caseJust by the error messageRunning the command to fix it works in all casesOr installing via homebrew with the right flags :)‫ב-12 בנוב׳ 2024, בשעה 9:00, ‏‏leo ***@***.***> כתב/ה:‬﻿
I'm not sure if macOS treats arm64 packages differently from x64 packages. The way we package macOS app is exactly the same, the only difference is whether osx-arm64 or osx-arm64 is passed to dotnet publish while building executable files.
