### ISSUE TITLE
Installation error from rpm package

### ISSUE THREAD

**Issue by unclealexkun** [sourcegit-scm/sourcegit#686]
Alt linux p10.2 / Fedora

Error text:

> Reading Package Lists...
> Building Dependency Tree...
> Selecting sourcegit for '/home/admin/Downloads/sourcegit-8.38-1.x86_64(1).rpm'
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following packages have unmet dependencies:
>  sourcegit: Depends: (libSM or libSM6) but it is not installable
>             Depends: (libX11 or libX11-6) but it is not installable
> E: Broken packages

The required libraries are installed
![image](https://github.com/user-attachments/assets/d4b3fd5d-b162-435e-a7c4-0d5a4764c373)
![image](https://github.com/user-attachments/assets/9e1366c5-e605-4307-a514-c6c6cb050856)

Tried reinstalling, but the result is the same

**Comment by aikawayataro** [comment]
Installs and works just fine on Fedora 41. Looks like an ALT Linux specific problem.
I've tried to workaround this (using a docker container), but even if I install SourceGit ignoring dependency issues, it will cause errors when using the package manager. Would you rather use AppImage?

**Comment by unclealexkun** [comment]
I will try your solution and also check with Alt Linux developers about this problem. I will report back later

**Comment by love-linger** [comment]
If you can compile the project yourself, you can modify the `build/resources/rpm/SPECS/build.spec` file yourself, remove all the `Requires: xxx` lines, and then run the following command to regenerate the `RPM` package:

```shell
dotnet publish src/SourceGit.csproj -c Release -o build/SourceGit -r linux-x64
rpmbuild -bb --target="x86_64" resources/rpm/SPECS/build.spec --define "_topdir $(pwd)/resources/rpm" --define "_version 8.38"
```

**Comment by aikawayataro** [comment]
Please try build from https://github.com/aikawayataro/sourcegit/actions/runs/11794761101
I've refactored rpm's `Requires:` to depend on SO instead. It was like this before, but changed due to problems with arm64. I think I have fixed that now
