### ISSUE TITLE
Add an option to hide a branch (or a folder of branches)

### ISSUE THREAD

**Issue by mdindoffer** [sourcegit-scm/sourcegit#690]
Please add an option to hide individual branches and folders of branches in the commit graph.
When you have a busy repository with many irrelevant branches, the graph is overwhelming and navigation suffers.

Gitkraken has an easy contextual button that appears on mouse hover next to a branch name to hide/show it https://help.gitkraken.com/gitkraken-desktop/hiding-and-soloing/#hide

**Comment by love-linger** [comment]
You can use the `Filter` feature:

Without any filter:
![image](https://github.com/user-attachments/assets/9d7e4f7c-f189-4b82-a7a4-1721ab547f9b)

After filter the master branch:
![image](https://github.com/user-attachments/assets/9f7c21cb-cde3-47ab-88b7-e724294fa782)

**Comment by mdindoffer** [comment]
No, that's not what I want. I don't want to restrict the graph to display just one branch. I want the commit graph to show **all** branches **except** those that I hide.

What the Filter function does is simply solo-ing one branch at a time. Not hiding branches and/or folders of branches.

**Comment by mdindoffer** [comment]
Here' you can take a look at how GitKraken does this:
https://help.gitkraken.com/gitkraken-desktop/hiding-and-soloing/#hide

In this screenshot I have hidden all local `stable/*` branches and all remote `dependabot/*` branches, so they are excluded from the commit graph.
![image](https://github.com/user-attachments/assets/148168d6-bc61-4fa9-b837-3b4a037dd937)

**Comment by love-linger** [comment]
you can filter more than one branches and tags at the same time.

**Comment by aikawayataro** [comment]
> you can filter more than one branches and tags at the same time.

The problem is that it is quite tedious to check all branches except the ones you don't want to see. Also, you can't use filter on "branch tree"
![image](https://github.com/user-attachments/assets/153edce9-f543-46dd-bca5-ca561663e6fb)

I think a quick button to invert all filters and the ability to filter trees will be a good addition. Maybe double click the filter icon to invert them?

**Comment by mdindoffer** [comment]
Yes, but it is still an "include" filter, not an "exclusion" filter. There is no way to "hide" a branch, only to "filter" it, those are different things. If you have a lot of branches, that equals to a lot of clicking and micromanaging. For example I want to have about 25 branches displayed right now, while excluding about 4 or 5 branches. That would mean painstakingly clicking on each of those 25 branches to filter them. There is no option to "exclude" whole group/folder of branches, i.e. all branches that start with `dependabot/` in their name.

What's more, even if I went through all of the branches I want to see and enabled the "filter" on those, it still would not behave like I want, because for each *new* branch that someone else creates I would have to add that to the filter too.

Another way to think about this is the difference between "exclude all by default" and "include all by default" behaviour. Plus the ability to  manage multiple branches at the same time, e.g. include/exclude all `feature/xxx` branches.

**Comment by love-linger** [comment]
I've pushed a branch named `feature/refactor-histories-filter`. Most of the work has been completed, but some minor issues remain. I wish someone can help me finish this feature.

**Comment by love-linger** [comment]
Currently, if you want to hide a branch that is referenced by more than one REFs, you must excludes all these REFs...

For example, if you want to hide the branch `master`, you must exclude `master`, `origin/master` and `v8.38`
![image](https://github.com/user-attachments/assets/1290fd80-c4ae-4296-a5f4-5409d7724934)

![test](https://github.com/user-attachments/assets/fa9554a6-dc9a-4a1f-b2ed-3559ae325564)

Wish someone can help me to improve this

**Comment by love-linger** [comment]
The `include` filter mode just works fine as before.

**Comment by aikawayataro** [comment]
I've tested the feature and I have suggestion: at the moment you can specify both hide and include filters, which is redundant as they are not affect each other. It should ask which type of filter to set only when setting the first one (when nothing is set), next ones user set should be the same type. Same logic when un-setting the filter, it should just remove it

**Comment by love-linger** [comment]
Now the `Unset` menu item is only visible when it is needed.

![image](https://github.com/user-attachments/assets/ec39b136-a5cb-4f17-8693-a76809791a1a)

![image](https://github.com/user-attachments/assets/eda5302c-fcb8-4920-99bb-2f924f471519)

**Comment by aikawayataro** [comment]
No icon is a good idea :grin:! It looks very nice
