### ISSUE TITLE
"git rebase --continue" fail and change Author

### ISSUE THREAD

**Issue by Cyrillev91** [sourcegit-scm/sourcegit#693]
Hi,

I have been using SourceGit for some time and I am very satisfied with it, I would like to share with you an issue I found and suggestions for improvement during continue rebase (after conflit).

Issues found when rebasing a branch and there is a conflict to resolve. SourceGit changes the author of this commit (while with git on the command line the name remains that of the initial author)

I also think the `commit` button should be renamed to `continue rebase` for clarity. (since it should run `git rebase --continue` and not `git commit`)

### Initial state:
```bash
git clone https://github.com/thibault/iwantyoursocks.git
git switch master
git merge --no-ff origin/colors
git switch material
```
### Start Rebase with git command line:
```bash
$ git rebase master
Auto-merging _layouts/default.html
CONFLICT (content): Merge conflict in _layouts/default.html
error: could not apply f99df10... Add link to material page in menu
hint: Resolve all conflics manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply f99df10... Add link to material page in menu
```
Edit _layouts/default.html file to resolve the conflict, then continue by
```bash
$ git add _layouts/default.html

$ git rebase --continue
(edit commit message and close editor)
[detached HEAD 0f8d266] Add link to material page in menu
 Author: Thibault Jouannic <thibault@miximum.fr>
 1 file changed, 1 insertion(+)
Successfully rebased and updated refs/heads/material.

```
show log with your favorite SW

![00 cmdLine](https://github.com/user-attachments/assets/06e76436-f6bf-494d-afea-57b251eade2b)

===> Please note that the last commit (the one with the conflict) does not change author

### Initial state:
```bash
git clone https://github.com/thibault/iwantyoursocks.git
git switch master
git merge --no-ff origin/colors
git switch material
```
### Start Rebase with SourceGit:
right click on `master` branch and select `rebase material on master...`
then clic on `RESOLVE` button
![01 Resolve](https://github.com/user-attachments/assets/e196e4ed-dc4c-40d7-b107-5e937c0abf4d)

Edit _layouts/default.html file to resolve the conflict, then continue by

return to SourceGit software then select default.html and clic STAGE button
then clic on CONTINUE button (see note 1 below)
![02 Continue](https://github.com/user-attachments/assets/97dbda3c-ca2b-490f-9dfb-993be6dc9bc7)
issue n°1 issue :
![03 ErrorOnContinue](https://github.com/user-attachments/assets/db10a70b-9c93-49d3-8822-eb7049f1f281)

workaround ? (or normal button) : clic on `COMMIT` button: (see note 2 below)
![04 commit](https://github.com/user-attachments/assets/4e5cee03-9a07-429d-ab2d-b23679cb9937)

then clic on `CONTINUE` button (see note 3 below)
![02 Continue](https://github.com/user-attachments/assets/97dbda3c-ca2b-490f-9dfb-993be6dc9bc7)

go to Histories
![05 badName](https://github.com/user-attachments/assets/cfeb2081-fd88-4d07-95cc-5783a45b31f0)
issues n°2 : Please note that the last commit (the one with the conflict) : the author's name has been changed

## notes 1, 2 and 3
I think the ergonomics of SourceGit would be improved if
- the `CONTINUE` button did not exist (note 1)
- the `COMMIT` button is renamed to `CONTINUE REBASE` (at note step 2) (or hide the commit button and show a `CONTINUE REBASE` button instead)
- pressing the `CONTINUE` button (at step 3) is not necessary

![02B Continue](https://github.com/user-attachments/assets/ba0e770b-3b54-4d41-bc6e-9d8cb49d0427)

![04b commit](https://github.com/user-attachments/assets/33dc478a-6d4f-4549-bfc5-8d5795735528)

**Comment by love-linger** [comment]
Done. You can download the latest CI build from Github Action.

* Fix the exit code when try to start `SourceGit` as code editor (rebasing).
* Redesign the layout for in-progress states.

![image](https://github.com/user-attachments/assets/666a0527-dd63-47dd-93f0-e4bc89aeb92a)

**Comment by Cyrillev91** [comment]
Hi love-linger,
I just checked by reproducing the steps above. It works perfectly well (tested on Windows).
Thanks
