### ISSUE TITLE
Support for Azure Open AI endpoints

### ISSUE THREAD

**Issue by glconti** [sourcegit-scm/sourcegit#695]
## Problem on commit message AI generation

We use in the company a few Azure Open AI endpoints, the rest api should be 1:1 with the OpenAi apis.

These endpoints use api key authentication and use the `api-key` request header instead of the `Authorization` header I see used in code.

In fact, I can correctly configure the endpoints in sourcegit

![image](https://github.com/user-attachments/assets/a105b275-8826-4b5a-be10-4e075493f316)

But when generating a commit message, I get a 401 error:

![image](https://github.com/user-attachments/assets/c31d6ab9-20a6-4866-a7c0-1f6d452ba1a9)

## Solution

Now I went ahead and simply added also a `api-key` to the http request, as you can see in this PR https://github.com/glconti/sourcegit/pull/1/files

And the message generation works perfectly.

![image](https://github.com/user-attachments/assets/204c9ec1-28f9-4448-92f6-aeb8663ad690)

Since it is my first issue here, I would not propose such a "work-aroundy" solution, without getting your opinion, what would be the preferred approach in this case?
- quick and dirty solution in proposed PR looks good enough
- add a field to the UI configuration section to choose the authorization header?
- ...

**Comment by love-linger** [comment]
Done. You can download the latest CI build from Github Action.

**Comment by glconti** [comment]
HI @love-linger I confirm the fix works, many thanks

![image](https://github.com/user-attachments/assets/331c8f63-634e-43d5-a106-6f603433c5ec)
