### ISSUE TITLE
[Feature] an option to combine multiple continuous commits when selected in the "Histories" view

### ISSUE THREAD

**Issue by ameaninglessname** [sourcegit-scm/sourcegit#698]

**Comment by love-linger** [comment]
Currently, `SourceGit` supports to squash all the _children_ commits of selected one into it.
![image](https://github.com/user-attachments/assets/5ddb093c-3fd8-4a0a-9267-882eec4f08e6)

**Comment by love-linger** [comment]
In fact, the example you provided is not a single operation, but rather:

```
squash 2
squash 3
pick   4
```

You should use the `Interactive Rebase` feature.
