### ISSUE TITLE
[Feature] Advanced Template for commits

### ISSUE THREAD

**Issue by mkozek** [sourcegit-scm/sourcegit#704]
In commit templates allow to filter branch name and file list by regex.

Proposed syntax
`${regex_T:{<filter regex>}:{<replacement regex>}} where T is "b" for branch, "f" for files.`

Example:
`${regex_b:{(.*)\/(issue-\d+).*}:{ID: $2 Type:$1}}`
to convert branch name "feature/issue-1234-add-new-feature"
into: "ID: issue-1234 Type:feature"

**Comment by mkozek** [comment]
Sample regex to match the proposed syntax:

`[GeneratedRegex(@"(\$\{regex_b:{(?<FilteringRegex>(?![*+?])(?:[^\r\n\[\/\\]|\\.|\[(?:[^\r\n\]\\]|\\.)*\])+)}:{(?<ReplacingRegex>(?![*+?])(?:[^\r\n\[\/\\]|\\.|\[(?:[^\r\n\]\\]|\\.)*\])+)}\})")]`

**Comment by aikawayataro** [comment]
Wow, that's too much to handle with regex :grin:
A more extensible and sensible solution would be a simple template engine. I would like to implement it if @love-linger accepts the feature. It is also possible to add a grammar to get highlighting in the commit editor

I also propose a different syntax for this:
`${var/regex/replacement}` => `${branch_name/(.*)\/(issue-\d+).*/ID: $2 Type:$1}` (sed-like)
Stuff like `regex_T` and `regex_b` is not really nice. This can become a real regex hell when new variables are introduced.

**Comment by love-linger** [comment]
@aikawayataro You can try to create a PR for this feature.
