### ISSUE TITLE
Clone or Edit Remote : SourceGit wrongly states that the syntax is invalid

### ISSUE THREAD

**Issue by Cyrillev91** [sourcegit-scm/sourcegit#706]
Hi,
SourceGit wrongly states that the syntax is invalid

To get around this you have to go through the command line.
Can you fix this?

![Clone](https://github.com/user-attachments/assets/15c1d0f4-1e97-4b57-a3df-09ee37f6a122)
![errorAddOrEditLocalRemote](https://github.com/user-attachments/assets/79d08602-5d25-48e2-b3fc-0e25f26035f8)

**Comment by love-linger** [comment]
you should use open instead of clone for local repositories

**Comment by Cyrillev91** [comment]
With open : fatal error
![image](https://github.com/user-attachments/assets/abdba692-cfee-4e35-80cb-fb993021c79d)

with this folder you have to do `git clone`
![image](https://github.com/user-attachments/assets/22f56bb6-9909-427b-ab92-28233f232176)

**Comment by aikawayataro** [comment]
I think the `.git` at the end says that `TestGUI.git` is a bare repository. 

> with this folder you have to do `git clone` ![image](https://private-user-images.githubusercontent.com/12849364/386846899-22f56bb6-9909-427b-ab92-28233f232176.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3NjI5MDEsIm5iZiI6MTczMTc2MjYwMSwicGF0aCI6Ii8xMjg0OTM2NC8zODY4NDY4OTktMjJmNTZiYjYtOTkwOS00MjdiLWFiOTItMjgyMzNmMjMyMTc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE2VDEzMTAwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkYzU4MTFiMmVmZWRmZjBhNzllN2Q1NmQ0NGYxYWE2MjFlMDc4YmYxZjY5ZmI0MTRkZTE5ZmQ5OWQ1ZDU4NDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-Dg9UqgE3ZCDgRkvtKgxwQyql-LTGXapWG5zhZ8ZjNM)

Yes, that's a bare repository. While local remotes are valid, what is the purpose of this?

**Comment by love-linger** [comment]
why not use worktree instead?

**Comment by Cyrillev91** [comment]
A folder XXXX.git can be used instead of a github repository for example.
This can be used if you don't want to put your project on an external server or for testing purposes.

the usage is identical
```
git clone c:\test\mysoftware.git
cd mysoftware
git add xxx
git commit
git push
```

```
git clone https://github.com/sourcegit-scm/sourcegit.git
cd sourcegit
git add xxx
git commit
git push
```

Both of these repositories are valid and should be valid for sourcegit (as they are valid on the command line)
- c:\test\mysoftware.git
- https://github.com/sourcegit-scm/sourcegit.git

**Comment by love-linger** [comment]
I'm very sorry. Currently, SourceGit only supports four kinds of remotes:

* ^http[s]?://([\w\-]+@)?[\w\.\-]+(\:[0-9]+)?/[\w\-/~%]+/[\w\-\.%]+(\.git)?$
* ^[\w\-]+@[\w\.\-]+(\:[0-9]+)?:[\w\-/~%]+/[\w\-\.%]+(\.git)?$
* ^ssh://([\w\-]+@)?[\w\.\-]+(\:[0-9]+)?/[\w\-/~]+/[\w\-\.]+(\.git)?$

And there's no plan to support using local repository as remote.

PS. If you mean self-hosted git server, there're already many choices, such as `Gitea`, `Gogs`.

**Comment by aikawayataro** [comment]
I think it would not hurt to check if other clients handle this. If this is the case, then this feature won't hurt

**Comment by Cyrillev91** [comment]
yes other git GUI allows this (tortoiseGit, Fork, ...). 
If I understand correctly you have to propose a regular expression that authorizes a local path, I will try to propose one

**Comment by love-linger** [comment]
Done. Now we supports using local bare repository as remote.
