### ISSUE TITLE
[Feature Request] Selectively fetch / don't fetch remote branches

### ISSUE THREAD

**Issue by ameaninglessname** [sourcegit-scm/sourcegit#707]
In large repositories, there may be so many big branches, while I only work with two or three of them or I don't want them to show and mess up with my graph view.

I hope there would be a convenient / interactive way to do the [title states.](https://stackoverflow.com/questions/26623867/skip-copying-some-branches-tags-to-local-git-with-git-fetch-all)

Maybe a window to configure it, or ask before (initial) fetch...

BTW, currently, if a remote branch is deleted, the fetch button won't `prune` local branch. Should we provide an `--prune` option in the fetch window?

**Comment by gadfly3173** [comment]
> BTW, currently, if a remote branch is deleted, the fetch button won't `prune` local branch. Should we provide an `--prune` option in the fetch window?

There is an automatic prune option in the repository settings, or you can use the remote right-click menu, `git config fetch.prune true`, etc.

**Comment by ameaninglessname** [comment]
> There is an automatic prune option in the repository settings

![image](https://github.com/user-attachments/assets/63b00a32-8e6b-4bf4-abc1-dbc6e8582a15)

Ah, found it, thank you. I didn't notice it before. Then I could use this to do **one-off** prune on fetching.

**Comment by ameaninglessname** [comment]
@love-linger It's not a question, but yeah, question within the feature request is resolved.
