### ISSUE TITLE
Unable to start on NixOS

### ISSUE THREAD

**Issue by julius-boettger** [sourcegit-scm/sourcegit#71]
When trying to start SourceGit on NixOS (Linux), I get
```sh
> ./SourceGit
bash: ./SourceGit: cannot execute: required file not found
```

Even though the `SourceGit` binary is in the current directory.

```sh
> ls
libHarfBuzzSharp.so  libonigwrap.so  libSkiaSharp.so  SourceGit
```

### Things I have tried
I tried out different versions of SourceGit, from the first one that supported Linux (8.3) to 8.7, they all behave the same. I also tried out if being on Xorg or Wayland changes anything, it doesn't.

Interestingly enough, a different shell (such as `fish` instead of `bash`) gives me a different error message:
```sh
fish: Job 1, './SourceGit' terminated by signal SIGSEGV (Address boundary error)
```

### Steps to reproduce
1. Be on NixOS (23.11?)
2. Download a release tarball of SourceGit for Linux
3. Extract
4. Try to run `./SourceGit` in the same directory as the bundled `.so` files

**Comment by julius-boettger** [comment]
I have an idea what could cause this.

NixOS's directory structure works somewhat different to your average Linux distro. E.g. `/bin/bash` does not exist, instead `bash` is located in `/nix/store/8cx8cg8h9vh65k4vgf6xh6shzbbgsa01-system-path/bin/bash` (at least right now, the path is generated automatically and can change). The proper way to access `bash` in this scenario is through `/usr/bin/env bash`.

Are there any hard-coded paths to binaries or directories on Linux in the codebase that could cause issues like this?

**Comment by love-linger** [comment]
In fact, this software does not use `/bin/bash` directly. Maybe you can find some help from https://github.com/AvaloniaUI/Avalonia/issues/3020

**Comment by julius-boettger** [comment]
> Maybe you can find some help from https://github.com/AvaloniaUI/Avalonia/issues/3020

That looks promising, I will try it out. Thanks!

**Comment by julius-boettger** [comment]
I was able to get it up and running using [this PR](https://github.com/NixOS/nixpkgs/pull/303865) (which even mentioned this issue already). It was an issue with my lacking NixOS knowledge, not with SourceGit itself. But thank you for the fast answer!
