### ISSUE TITLE
[Feature Request] Groups and repo by workspaces

### ISSUE THREAD

**Issue by ennerperez** [sourcegit-scm/sourcegit#713]
Include a way to select to target workspaces where to create the group or the repository

![image](https://github.com/user-attachments/assets/d0f47121-851e-4277-a4de-6a65921508e5)

- [ ] if there is only 1 then don't show anything and create repo/group as it is
- [ ] if there is more than 1 workspace, show all then with a check to include the new repo/group
- [ ] by default, current workspace is checked in the list
- [ ] filter the repositories/group list by workspace

**Comment by love-linger** [comment]
In SourceGit, all repository lists should be accessible under any workspace.

* In the currently activated workspace, we can add other repositories at any time.
* A repository can appear in multiple Workspaces.

**Comment by ennerperez** [comment]
I understand the approach, but I see a value to have filtered repos by workspace, particular to avoid putting personal repos 
 with business or work repos.

I think we can keep the base functionality as it is today, but offer a way to segregate repos/groups by workspaces for those that have multiples works or just want to keep thinking separated.

From my personal perspective as a developer, I see this as a great feature to have, specially for freelancers, agencies or any person that work with multiple clients and likes to keep things in order.
