### ISSUE TITLE
Exception (handled) in TextMate TokenizerThread on repeated LoadDiffContent()

### ISSUE THREAD

**Issue by goran-w** [sourcegit-scm/sourcegit#715]
For large Diff contents, calling LoadDiffContent() repeatedly in quick succession (for example, quickly toggling "Ignore Whitespace Change" a few times) can cause a NullReferenceException inside UpdateTokensInRange() in TextMateSharp.Model.TMModel.TokenizerThread (probably because TextEditor content is reloaded while TokenizerThread is still doing work).

However, this exception is handled by try-catch around RevalidateTokens() and causes a Debug.WriteLine() before moving on. That's probably OK in Release builds, but will cause a halt when debugging (it's possible to continue debugging, though).

If this is deemed to be OK, then this issue can be closed. Just wanted to flag this behavior, for future reference.

**Comment by love-linger** [comment]
I think this ISSUE should be reported in the [AvaloniaText] (https://github.com/AvaloniaUI/AvaloniaEdit/issues) project.
