### ISSUE TITLE
I can't use special characters in a Commit.

### ISSUE THREAD

**Issue by goenaga** [sourcegit-scm/sourcegit#716]
Hello, when I try to write a Commit with accents, it doesn't let me type them. For example, when I write in Spanish: "Información de disponibilidad stock," this text is supposed to have an accent on the "o," but when I press the accent key and then the "o," nothing happens—it just doesn’t type anything. You’re doing an amazing job, but please fix this whenever possible.

EDIT: if i write ó in text editor and do copy paste it works. So the problem is on typing.

Thank you very much in advance!

**Comment by albertodlc** [comment]
I just tested and I can use accents, maybe is OS related. I am using Windows 11. What are you using?

![image](https://github.com/user-attachments/assets/17fa8f85-bc91-4370-af6c-8a31ffe0875b)

**Comment by goenaga** [comment]
I'm on Debian, maybe this can help:

`desarrollo@portatil-hp:~$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
desarrollo@portatil-hp:~$ uname -r
6.1.0-26-amd64
desarrollo@portatil-hp:~$ uname -a
Linux portatil-hp 6.1.0-26-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.112-1 (2024-09-30) x86_64 GNU/Linux
desarrollo@portatil-hp:~$ locale
LANG=es_ES.UTF-8
LANGUAGE=
LC_CTYPE="es_ES.UTF-8"
LC_NUMERIC="es_ES.UTF-8"
LC_TIME="es_ES.UTF-8"
LC_COLLATE="es_ES.UTF-8"
LC_MONETARY="es_ES.UTF-8"
LC_MESSAGES="es_ES.UTF-8"
LC_PAPER="es_ES.UTF-8"
LC_NAME="es_ES.UTF-8"
LC_ADDRESS="es_ES.UTF-8"
LC_TELEPHONE="es_ES.UTF-8"
LC_MEASUREMENT="es_ES.UTF-8"
LC_IDENTIFICATION="es_ES.UTF-8"
LC_ALL=
desarrollo@portatil-hp:~$ echo $LANG
es_ES.UTF-8
`

**Comment by aikawayataro** [comment]
I can type `ó` just fine with Spanish layout on KDE Xorg. What input method/DE you use, IBus/Fcitx?

**Comment by love-linger** [comment]
I think this issue should be reported to Avalonia.

**Comment by love-linger** [comment]
If you are able to compile this project locally, try turning off the `EnableIme` option in `SourceGit.Native.Linux.SetupApp` to see if this issue is resolved.

**Comment by mistnarwhal** [comment]
> If you are able to compile this project locally, try turning off the `EnableIme` option in `SourceGit.Native.Linux.SetupApp` to see if this issue is resolved.

I had to set the Dotnet SDK to version 8.0 because of my environment, but disabling the `EnableIme` option works and I can type any accented character.

**Comment by love-linger** [comment]
Done. You can download the latest CI build from Github Action.

**Comment by mistnarwhal** [comment]
Unfortunately, this doesn't work.
I have to explicitly set `EnableIme = false` for this to work.

``` cs
            builder.With(new X11PlatformOptions()
            {
                EnableIme = false,
            });
  ```

**Comment by love-linger** [comment]
It's not necessary to modify the code. Try to set an environment variable `AVALONIA_IM_MODULE` to `none`

**Comment by love-linger** [comment]
here is the code from avalonia:

```csharp
private static bool EnableIme(X11PlatformOptions options)
        {
            // Disable if explicitly asked by user
            var avaloniaImModule = Environment.GetEnvironmentVariable("AVALONIA_IM_MODULE");
            if (avaloniaImModule == "none")
                return false;
            
            // Use value from options when specified
            if (options.EnableIme.HasValue)
                return options.EnableIme.Value;
            
            // Automatically enable for CJK locales
            var lang = Environment.GetEnvironmentVariable("LANG");
            var isCjkLocale = lang != null &&
                              (lang.Contains("zh")
                               || lang.Contains("ja")
                               || lang.Contains("vi")
                               || lang.Contains("ko"));

            return isCjkLocale;
        }
```

**Comment by love-linger** [comment]
You're right. I'll update the README tomorrow.
