### ISSUE TITLE
['Changes' window] Add shortcut to the right click menu to allow staging specific lines

### ISSUE THREAD

**Issue by albertodlc** [sourcegit-scm/sourcegit#718]
I like the implementation of staging with individual blocks. But I think it is also useful to have an option to stage specific lines.
For example, including a new option on right click menu (the menu is currently implemented with the 'copy' option):
1. Select the line
2. Right click > Stage Selected Line
![image](https://github.com/user-attachments/assets/9b8b85eb-8b61-4ae1-a213-62600eaac4f0)

**Comment by goran-w** [comment]
That's already possible. If you select lines and hover with mouse pointer, then the Stage/Discard buttons will be working on just the selected text, see these screenshots of unselected vs. selected text :

Without selection:
![image](https://github.com/user-attachments/assets/d65259bf-50cb-46cb-b571-4e260f20f01f)

With selection:
![image](https://github.com/user-attachments/assets/2b5c5d18-0e36-4ee6-ad4d-bd425339dec1)

**Comment by albertodlc** [comment]
I didn't notice, it looked like it was the same button... I think it is a bit confusing using the same name for the block and mouse selection. 

Either way, I think the proposed shortcut is a good idea, I have an Ultrawide monitor and when the line is selected it's difficult to stage the implemented way:
![image](https://github.com/user-attachments/assets/193d8a8d-3712-4c9e-b66c-f8d3c83ad1b3)

If the line selection logic is currently implemented, it shouldn't be difficult to add the action to the right click menu

**Comment by love-linger** [comment]
> I didn't notice, it looked like it was the same block selection... I think it is a bit confusing using the same name for the block and mouse selection.

Why use different names for the same operations? The stage/unstage/discard range is already hightlighted both in text view and the line number margins.
![image](https://github.com/user-attachments/assets/4c06c29b-db55-4e7d-95fe-d3a300a16532)

> Either way, I think the proposed shortcut is a good idea, I have an Ultrawide monitor and when the line is selected it's difficult to stage the implemented way:

I've added the hotkeys to stage/unstage/discard changes in text diff view. You can download the latest CI build from Github Actions.
![image](https://github.com/user-attachments/assets/aa643a48-67b8-4db1-84fe-53fe770f7102)
![image](https://github.com/user-attachments/assets/ad3a4140-2292-42f8-9e92-022be7954546)
