### ISSUE TITLE
Commit template editor is way too small

### ISSUE THREAD

**Issue by aikawayataro** [sourcegit-scm/sourcegit#720]
When I was working on #719, I used commit template editor for a while, and it's actually awkward. I can only see 3.5 lines at a time, and it is really hard to navigate in such a tiny space. For better user experience I suggest expanding it at least a bit

**Comment by love-linger** [comment]
![image](https://github.com/user-attachments/assets/47d42aba-32df-48d0-865b-178016b90b42)
