### ISSUE TITLE
[Enhancement] Refactor fetch menu options (--force update local tags)

### ISSUE THREAD

**Issue by albertodlc** [sourcegit-scm/sourcegit#721]
When I execute a fetch I am getting this error. It [looks](https://stackoverflow.com/questions/58031165/how-to-get-rid-of-would-clobber-existing-tag) like the fetch command should include a `--force` argument when fetching the tags
![image](https://github.com/user-attachments/assets/97a08a7d-ec6b-4d4b-ad12-143776da075c)

```bash
git fetch --tags --force
```

Maybe we can add a new checkbox to include the arg on the command 
![image](https://github.com/user-attachments/assets/1aa661dd-2d95-45cd-b8e7-0a14d64df1c1)

For example modify the current menu with these checkboxes:
- (By default) Fetch all remotes (without tags)
- Include Tags
- Force Tags update

**Comment by love-linger** [comment]
In my opinion, I prefer the #684 viewpoint. 

When there are some conflicted REFs between the remote and local, we should draw the attention of the user. It is up to the user to decide whether to re-push the local REF to the remote, or delete the local outdated REF, and then re-pull the remote changes.

**Comment by albertodlc** [comment]
I understand the point, but I think and option to update the local with all the tags (allowing the user to fetch and force overriding outdated tags) is a good option. In my case it was only 1 tag but if you have multiple tags outdated I think is a little bit tedious manually deleting each local tag.

We can keep the same menu (by default draw the attention of the user) but add another checkbox that add the --force to the fetch (and warn the user that all outdated tags will be overrided) ?

**Comment by love-linger** [comment]
Done. You can download the latest CI build from Github Action.
