### ISSUE TITLE
详细面板中提供一个按钮，可以临时隐藏 面板。只有再次点击node 的时候才显示

### ISSUE THREAD

**Issue by heartacker** [sourcegit-scm/sourcegit#723]
有时候，很希望可以隐藏细节面板，只是为了更好的滚动 log node 滚动查看更多的，log node。 找到自己想要的node。只有再次点击node 的时候就显示出来。

**Comment by love-linger** [comment]
这个有点不太好搞。

* 目前Commit列表与详情页的高度（垂直排布）/宽度（水平排布）是绑定在LayoutInfo上的，以便下次恢复大小。即当隐藏一个面板，另一个面板填充后，其大小信息会同步到LayoutInfo。这时再显示隐藏的面板已经无法恢复其大小。
* 空白的Commit详情页，并非全无作用。而是提示用户Commit列表可以使用Ctrl/Shift进行多选。
* 对于这种情况，我建议可以先切换到水平排布，当需要查看详情时，再切回垂直排布

**Comment by heartacker** [comment]
我依旧任务这个是一个很必要的特性。
我想，是否可以使用dock 这种类型的控件进行布局
https://github.com/wieslawsoltes/Dock

![dock](https://github.com/wieslawsoltes/Dock/blob/master/images/Dock.png)
