### ISSUE TITLE
[Feature] Quick shortcut to pick changes of individual file

### ISSUE THREAD

**Issue by hellojianqun** [sourcegit-scm/sourcegit#724]
在commit的改动文件列表这里，文件的右键菜单中希望增加一个 Pick Changes 的选项，可以pick该文件的改动到工作区。可能的实现方式如
`git show <sha1> -- <file> | git apply`

![image](https://github.com/user-attachments/assets/6cd89072-8b41-49cd-9231-e471724227fe)

**Comment by hellojianqun** [comment]
1. 不是的，`git show <revision>`打印的就是diff，大佬可以验证一下
2. 确实一个commit中的各个修改是相关的，不过在开发过程中，自己非常清楚的情况下有时会有pick部分文件修改的需求
当然只是提个建议，因为我自己时不时会用到，今天又用到了就到这里提一嘴😁

**Comment by love-linger** [comment]
> 不是的，`git show <revision>`打印的就是diff，大佬可以验证一下

嗯，我记错了，显示文件内容的命令格式是 `git show <revision>:<file>`

> 确实一个commit中的各个修改是相关的，不过在开发过程中，自己非常清楚的情况下有时会有pick部分文件修改的需求
当然只是提个建议，因为我自己时不时会用到，今天又用到了就到这里提一嘴😁

嗯，主要是这样做可能出各种问题，一是上面说的，二是文件差异大时无法apply

**Comment by love-linger** [comment]
基于上面的原因。我还是打算保守一点。现在提交详情中的变更增加了另存为补丁的右键选项。

![image](https://github.com/user-attachments/assets/767137e7-90bf-49f4-ae15-43f6942cffcb)

**Comment by love-linger** [comment]
你可以在Github Action上下载最新的包来测试该功能
