### ISSUE TITLE
[bug] Sometimes a panel with a commit information is overlapping other apps even when SourceGit is minimized

### ISSUE THREAD

**Issue by elirenato** [sourcegit-scm/sourcegit#727]
Since the version 8.39, i have been facing the issue describe in the title. It happened 3 times already. With previous versions it never happened.

Printscreen when I change from SourceGit to VSCode.
![PanelOverlappingVSCode](https://github.com/user-attachments/assets/023133af-721a-457f-ac6b-156b77c70a58)

Printscreen when I click the "Show Desktop" button to minimize all the applications, the SourceGit panel still overlapping.
![PanelOverlappingDesktop](https://github.com/user-attachments/assets/49ba5152-de02-45f8-ae14-eb351f591a7a)

To remove the panel, I have to close the SourceGit .

My System Info:
[system-info.txt](https://github.com/user-attachments/files/17836789/system-info.txt)

**Comment by love-linger** [comment]
It's the tooltip of parent SHA in commit details panel. I can NOT reproduce this issue on my PC and Mac. But you can close it be hover the SHA again.

**Comment by love-linger** [comment]
I'll try to add some code to avoid this

**Comment by love-linger** [comment]
You can download the latest CI build from Github Action.
