### ISSUE TITLE
建议优化扫描速度，扫描到 .git 后不再扫描子目录

### ISSUE THREAD

**Issue by Vixb1122** [sourcegit-scm/sourcegit#728]
建议优化扫描速度，扫描到 .git 后不再扫描子目录。
不知道这样会不会对 submodule 造成影响，不过貌似可以在打开项目时处理 submodule

**Comment by love-linger** [comment]
![image](https://github.com/user-attachments/assets/6beef5a2-1c9b-4f8f-86ce-e5cd7e5bfb0c)

是这样设计的。对于没有发现仓库的路径，现在的代码会深入8层。但考虑到如果仓库管理比较好，比如不存在太深的目录，这段代码运行太快，界面闪一下弹出页面，体验不好，所以，打开面板后有半秒的延时……

![image](https://github.com/user-attachments/assets/8699d720-c538-486c-88ca-1c06e06a5022)

**Comment by love-linger** [comment]
修改了一下保证扫描面板停留时间不小于0.5s的算法

**Comment by love-linger** [comment]
我本地有30+仓库，分别在默认克隆路径的 `Github`, `Mine`, `Work` 子目录下，平均每次扫描耗时在100ms以内。所以必须加上等待，要不然体验极差

**Comment by love-linger** [comment]
又提交了个新的修改 - 即使当前目录下存在`.git`目录或文件，只要`git rev-parse --show-toplevel`无法返回正确的路径，也不再深入该目录的子目录扫描了。防止出现类似换系统后，仓库由于所有者发生变化，所有git命令无法正常执行时，扫描深度过大的情况，或是仓库本身损坏了的情况。

**Comment by Vixb1122** [comment]
之前用过一个叫 fork 的 gui，那个扫描就挺快的，貌似显示扫描进度不是刚需呢。

> 又提交了个新的修改 - 即使当前目录下存在`.git`目录或文件，只要`git rev-parse --show-toplevel`无法返回正确的路径，也不再深入该目录的子目录扫描了。防止出现类似换系统后，仓库由于所有者发生变化，所有git命令无法正常执行时，扫描深度过大的情况，或是仓库本身损坏了的情况。

**Comment by love-linger** [comment]
> 我刚又下载试了下，那软件扫描过快的话，会扫描完毕后延时1秒关闭扫描弹窗

是的，基本上都要做这样的处理，要不然体验很不好，会闪一下

**Comment by love-linger** [comment]
试了一下fork。Fork的判断逻辑好像不是使用`git rev-parse --show-toplevel`来判断是否是正确仓库，而是直接判断目录结构，是否符合git规范。比如，你建一个目录只要包含`.git/refs/`,`.git/objects/`,`.git/index`,`.git/HEAD`文件，它就会认为是仓库

**Comment by love-linger** [comment]
而`SourceGit`会对包含`.git`子目录的路径执行`git rev-parse --show-toplevel`检测，返回正确的仓库根目录时，才认为是可用仓库。这就是扫描比Fork慢的原因。

**Comment by love-linger** [comment]
这是个可以验证我上面关于fork检测仓库方式的最小测试。里面只有两个空目录，及两个空文件。但是Fork会认为是仓库。
[test.zip](https://github.com/user-attachments/files/17840564/test.zip)

**Comment by Vixb1122** [comment]
学到了，前面是我看错了，以为本地都是 git 仓库，我本地一些项目不是 git 仓库，会生成 build 临时文件夹 （目前本地没有前端项目，不知道有 node_modules 之类的话会不会更慢。）确实按照 8 层深度扫描会比较慢。
fork 这种方式确实会更快。

**Comment by love-linger** [comment]
哦，又测试了一下，好像 `.git/index` 文件都不需要……只要有`.git/refs/`,`.git/objects/`和`.git/HEAD`

> 学到了，前面是我看错了，以为本地都是 git 仓库，我本地一些项目不是 git 仓库，会生成 build 临时文件夹 （目前本地没有前端项目，不知道有 node_modules 之类的话会不会更慢。）确实按照 8 层深度扫描会比较慢。 fork 这种方式确实会更快。

你这个信息提醒了我。`node_modules`目录是否可以直接不扫描？

**Comment by Vixb1122** [comment]
> 哦，又测试了一下，好像 `.git/index` 文件都不需要……只要有`.git/refs/`,`.git/objects/`和`.git/HEAD`
> 
> > 学到了，前面是我看错了，以为本地都是 git 仓库，我本地一些项目不是 git 仓库，会生成 build 临时文件夹 （目前本地没有前端项目，不知道有 node_modules 之类的话会不会更慢。）确实按照 8 层深度扫描会比较慢。 fork 这种方式确实会更快。
> 
> 你这个信息提醒了我。`node_modules`目录是否可以直接不扫描？

对，感觉一些常规的 .gitignore 配置都能跳过扫描

**Comment by gadfly3173** [comment]
我本地有 5000+ node_modules (有些应该是模块中的)，115个在克隆目录下平级的git仓库。实际上这些node_modules远不如java项目的`target`、`WEB-INF`、tomcat的部署目录等耗费时间

```bash
$ find . -maxdepth 8 -name "node_modules" | wc -l
5002

$ find . -maxdepth 2 -name ".git" | wc -l
115

find . -maxdepth 8 -name "WEB-INF" | wc -l
155
```

**Comment by love-linger** [comment]
* SourceGit只扫描默认克隆目录下的子目录。文件不会去管。
* 只有某目录下存在`.git`目录或文件时，才会对该路径执行`git rev-parse --show-toplevel`指令。
* 如果已经判定为Git仓库，SourceGit不会再扫描其子目录。

所以大部情况下，扫描还是很快的。只有在默认克隆目录下存放了大量非GIT仓库，且层级足够深时才会明显变慢。
