### ISSUE TITLE
[bug] Local branch list does not refresh after deleting multiple branches

### ISSUE THREAD

**Issue by EreMaijala** [sourcegit-scm/sourcegit#729]
SourceGit 8.39 on macOS Sonoma 14.7.1 (23H222): If you select multiple local branches and delete them, they remain and stay selected in the Local Branches list. You can try to delete them again and receive error for each that the branch doesn't exist. A minor issue, but since SourceGit is so handy when doing cleanup, this is making it just a tiny bit more complicated. Everything seems to work fine if you delete only a single branch.

**Comment by love-linger** [comment]
I can NOT reproduce this issue on macOS Sequoia 15.1.1 (24B91).

https://github.com/user-attachments/assets/120874f7-4884-4e2e-96ce-619c0e53509a

According to the current implementation, after deleting multiple local branches, the `FileSystemWatcher` will trigger the event that the files under `.git/refs/heads/` have changed, and then `SourceGit` will refresh the branch tree.

**Comment by love-linger** [comment]
PS. If you encounter this problem again, you can use `F5` key to force refreshing the entire repository.

**Comment by EreMaijala** [comment]
This used to work for me too, so I thought it was a new issue. I'll see if it gets resolved after next round of OS updates. Thanks for the tip about F5!

**Comment by love-linger** [comment]
You can see all the keyboard shortcuts (or hotkeys) from the Application menu `Keyboard Shortcuts Reference`

**Comment by love-linger** [comment]
I've pushed a commit that manually mark the branch tree dirty after deleting multiple branches.
