### ISSUE TITLE
[UX] always use the "longer" progress bar in diff window when scrolling horizontal

### ISSUE THREAD

**Issue by ameaninglessname** [sourcegit-scm/sourcegit#732]
so that users don't have to jump between widgets when the lines are significantly different in length.

**Comment by ameaninglessname** [comment]
This behavior is presented in [Meld](https://meld.app)

**Comment by love-linger** [comment]
![image](https://github.com/user-attachments/assets/3f938bfb-c1bd-466a-8329-ab7944c9d445)

The `Extent` of `ScrollView` can NOT be changed out of `AvaloniaUI`.
