### ISSUE TITLE
[ENHANCEMENT] - Option to merge graph lanes

### ISSUE THREAD

**Issue by Shimoon** [sourcegit-scm/sourcegit#740]
# Problem
When dealing with large Git repositories that contains a lot of branches, it is very commun to get visual bottle necks when a lot of branches share the same parent commit and start to accumulate at one particular place in the graph.

# Proposal
An option to merge the graph lanes that share the same parent.
It have two benefices :
1. avoid lanes stacking
2. greatly reduce the horizontal graph size

Such option would make a new branch to only appear when its first commit is created instead of going on without any useful information to give to the user.
Like so, the graph complexity is diluted and informations appears only where they are relevant.

# Mockup
The only example of this feature I can think of is in GitExtensions :

![graph_lanes_parent_propale](https://github.com/user-attachments/assets/5197aa02-4fdc-42db-867e-91bf129339a5)

*On the left :*
- The graph behave just like the one in SourceGit and the lanes are stacked at one place, where branches share a common parent.
- This produce a lot of visually empty branches that goes up until their first commit happen. But like so, they simply pollute the space without much information to give.
- Moreover, branches that starts earlier in the graph are trying to avoid this stack and therefore add more complexity to this area by agraving this behavior.
    This is becoming hard to know at first glance which branch start on the previous commit or if it start at a lower level in the graph.

*On the right :*
- The setting is activated and produce a gradual split of branches along the original one. They only appear when their first commit is created.
- Notice how much the horizontal graph size is reduced, and so, without losing any information.

*SourceGit for reference :*

![graph_lanes_parent_stacked_sourcegit](https://github.com/user-attachments/assets/aacfc2c8-89f3-4248-a078-6bf56c6e1b91)

As always, thanks a lot for your hard work !!

**Comment by love-linger** [comment]
![image](https://github.com/user-attachments/assets/a6d6ae22-878e-4367-a081-454fea012209)

Currently, if there's no other commits between the commit and it parent, we use short link curve, just like the line pointed by RED arrow. Otherwise we use a standalone curve for it, see the line pointed by GREEN arrow.

This design is also used by `Fork`.

**Comment by Shimoon** [comment]
If I understand correctly, there is currently nothing that could potentially be used to create a branch from elsewhere than a commit ?
Is there any chance that this design could be improved to include this behavior ?
If this proposal cannot be implemented, could it be possible to address this issue through another solution ?

I think this is really important to improve the graph readability ! Right now, I have to filter branches out to see clearly but it prevent me to understand the repository organization as a whole which is kinda lame..

**Comment by love-linger** [comment]
Before:
![image](https://github.com/user-attachments/assets/0d9fc886-50b6-4c13-a1db-ac6b713d2e8f)

After enable merge lines:
![image](https://github.com/user-attachments/assets/8b315fe9-d6ae-4633-9785-c85e0691ac74)

I don't think it's any clearer with merge branch lines enabled...
