### ISSUE TITLE
Possible Trojan:Script/Wacatac.B!ml ? (according to MS Security at least)

### ISSUE THREAD

**Issue by Carighan** [sourcegit-scm/sourcegit#742]
I just downloaded the new 8.40 release, specifically `sourcegit_8.40.win-x64.zip`, and my laptop's MS Security (Enterprise variant, Windows 11 Pro, build 22631.4460) flagged it and removed it, citing [Trojan:Script/Wacatac.B!ml](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AScript%2FWacatac.B!ml&threatid=2147735503).

I then also tested it via VirusTotal, which [came back clean](https://www.virustotal.com/gui/url/83973deec9012e9ed1e72917aac7091acb720cb90ac64aefe8739c1c543b72ff?nocache=1).

After talking to IT, we think it's a false positive but agreed I'll open this ticket in case someone needs to / wants to make sure there has been no malicious code added in recent commits. I sadly lack the skills to check for that myself.

Thanks in advance,
Cari

**Comment by gadfly3173** [comment]
Windows Defender has false positives for some compressed packages. You can try to generate zip files from other workflows in CI or compile them locally.

**Comment by love-linger** [comment]
I have download the sourcegit_8.40.win-x64.zip from Github Release. And it has passed the Windows Defender check on Windows 11 Pro 24H2 26100.2314.

**Comment by aikawayataro** [comment]
https://github.com/sourcegit-scm/sourcegit/compare/v8.39...v8.40#files_bucket

Commit built on CI matches released tag, nothing JiaTan-ish at first glance :grin: Release artifacts also matches one from CI.
I suggest you report false positive to MS, and there's a thought that `!ml` in detection means "machine learning", so a false positive is very possible. I suspect that Microsoft is selectively enabling this "machine learning" detection, judging by the fact that it was only detected for certain people.

**Comment by gadfly3173** [comment]
> I suggest you report false positive to MS

I submitted it to https://www.microsoft.com/en-us/wdsi/submission/afe8c8ea-2e60-4156-bc4f-c556067e5a9c, but it showed `Malware detected` in `Protection`, but not in `Current detection`...

![image](https://github.com/user-attachments/assets/a399711b-5b39-47bd-a453-1d6575eb83d1)

**Comment by gadfly3173** [comment]
I got feedback from Microsoft said:

> Analyst comments:
>
> Our scanners show no positive detection, and we have no telemetry indicators for the file(s) submitted either. As such, this submission will be closed with no further action pending. If you require further assistance related to this case, you can respond to this email and provide us with additional information related to incorrect detection that will help us troubleshoot the case further.

It seems good now...

**Comment by love-linger** [comment]
I'll close this issue as completed.
