### ISSUE TITLE
Alert windows with error message

### ISSUE THREAD

**Issue by wl2776** [sourcegit-scm/sourcegit#746]
OS: Ubunu 24.04 with all recent updates

Sourcegit version: 8.40, installed from released .deb package

git version: 2.43.0

Almost any action causes pop-up of the alert window with the error message, saying about incorrect usage of `git rev-list` command.

![image](https://github.com/user-attachments/assets/318feef7-abd7-45d0-90b6-13edf83cb8b3)

**Comment by wl2776** [comment]
I suppose, these messages are caused by this line: https://github.com/sourcegit-scm/sourcegit/blob/ee8206794079958ec0b39d4776b5802c909b41d0/src/Commands/QueryCommitChildren.cs#L14

`git rev-list --help` does not show `-max` option.

**Comment by gadfly3173** [comment]
According to git documentations, `-<number>` option should in git 2.43
https://git-scm.com/docs/git-rev-list/2.43.0#Documentation/git-rev-list.txt--ltnumbergt

**Comment by wl2776** [comment]
Indeed, I've missed curly brackets around `max`. 

String interpolation should take place. 

Probably, it doesn't.

**Comment by wl2776** [comment]
I think, my installation is missing `Preference.Instance.MaxHistoryCommits` parameter.

I've tried to issue `git rev-list` command from a terminal.

If I omit a number after the first dash, then I get such output.

Compare: 

```
❯ git rev-list -10 --parents --branches --remotes --tags ^6d74533
2819df565474a3ac3dd1350da1dc7b443952bb76 9e4dcb06fa19c2f10b3bfcb001ccf705d85fb47e e53b9bd1a03ccc830ba88b2a12abe707110231b4
e53b9bd1a03ccc830ba88b2a12abe707110231b4 f9f193a456032019a6cfa06cce2de6b52a343525
f9f193a456032019a6cfa06cce2de6b52a343525 1d1a5a29d2820ff3bd8d052feb7f6f2b6587a410
1d1a5a29d2820ff3bd8d052feb7f6f2b6587a410 7b7146c0d3501b4c4076dfec8519c02dbba25931
7b7146c0d3501b4c4076dfec8519c02dbba25931 840fea5e80635e5ec1f3b318dd92b05139a95196
840fea5e80635e5ec1f3b318dd92b05139a95196 54de0ffcd0e7858ff8fc2c9baa70a1491f2abb19
54de0ffcd0e7858ff8fc2c9baa70a1491f2abb19 ccb526d2da6dcb1db9c9a5ef223b1b3e8486f42b
ccb526d2da6dcb1db9c9a5ef223b1b3e8486f42b 9e4dcb06fa19c2f10b3bfcb001ccf705d85fb47e
9e4dcb06fa19c2f10b3bfcb001ccf705d85fb47e 09f53f3c40ae26da0ad5f2437c0f18594c732d53
09f53f3c40ae26da0ad5f2437c0f18594c732d53 c159aad9268be1f6a315bacd62df2ef264954cbb 6d74533cf9b27f9ceeb8c3a2de5a83a2e9be8f34

```

Just `-` instead of `-10`:

```
❯ git rev-list - --parents --branches --remotes --tags ^6d74533
usage: git rev-list [<options>] <commit>... [--] [<path>...]

limiting output:
--max-count=<n>
--max-age=<epoch>
--min-age=<epoch>
--sparse
... (many more lines)
```

**Comment by love-linger** [comment]
This doesn't seem to be a problem with `QueryCommitChildren`, as this command is only executed when `Show children in commit details` is enabled to view commit details. 

There is another place in the project using `git rev-list` command - `QueryTrackStatus`, which is used to obtain differences between the branch and its tracking upstream branch.

**Comment by love-linger** [comment]
@wl2776 can you try `git rev-list --left-right LOCAL_BRANCH...REMOTE_BRANCH`

Remember replacing the `LOCAL_BRANCH` and `REMOTE_BRANCH` with yours

**Comment by wl2776** [comment]
> Try change the `History Commits` to another value, and see if this issue solved?
> Looking forward for your feedback.

Have tried to change this value to 5000, 100000, 25000 - same result.

I have also tried to manually edit `preferences.json`, and add `"HistoryCommits"` along with `"MaxHistoryCommits"`, my changes have no effect and get overwritten.

**Comment by wl2776** [comment]
And I observe these windows only in one repository, that is, unfortunately, private, and I cannot give access to it.

**Comment by wl2776** [comment]
> @wl2776 can you try `git rev-list --left-right LOCAL_BRANCH...REMOTE_BRANCH`
> Remember replacing the `LOCAL_BRANCH` and `REMOTE_BRANCH` with yours

I get empty output:

```
$ git rev-list --left-right master...origin/master
$
```

What is correct form of naming local and remote branches?

**Comment by love-linger** [comment]
> > @wl2776 can you try `git rev-list --left-right LOCAL_BRANCH...REMOTE_BRANCH`
> > Remember replacing the `LOCAL_BRANCH` and `REMOTE_BRANCH` with yours
> 
> I get empty output:
> 
> ```
> $ git rev-list --left-right master...origin/master
> $
> ```
> 
> What is correct form of naming local and remote branches?

If you go empty output, it means the local branch is update to its tracking remote. Otherwise, it will print the commit hashes with a prefix '<' (un-pushed commits) or '>' (remote newer changes)

**Comment by love-linger** [comment]
For example:

![image](https://github.com/user-attachments/assets/ffe059ee-32b8-4bf5-a792-76fada334584)

It means you have 4 commits in local branch `release` that has not pushed to the remote `origin/release`

**Comment by wl2776** [comment]
> If you go empty output, it means the local branch is update to its tracking remote. Otherwise, it will print the commit hashes with a prefix '<' (un-pushed commits) or '>' (remote newer changes)

This is not the case for this repo. All local and remote branches are in sync.

**Comment by love-linger** [comment]
If you can debug this project, try to add breakpoint to all lines that contains `App.RaiseException(...)` in `src/Commands/Command.cs`

**Comment by wl2776** [comment]
> If you can debug this project, try to add breakpoint to all lines that contains `App.RaiseException(...)` in `src/Commands/Command.cs`

I believe that I have enough skills to debug this project, but I'm not very familiar with C#. 
I mostly write in Python and C++.
How can I get started?

**Comment by love-linger** [comment]
On Ubuntu, you can use VSCode + .NET SDK + C# extension to debug this project.

.NET SDK installation : https://learn.microsoft.com/zh-cn/dotnet/core/install/linux-ubuntu-install?pivots=os-linux-ubuntu-2410&tabs=dotnet9

**Comment by gadfly3173** [comment]
> I believe that I have enough skills to debug this project, but I'm not very familiar with C#. I mostly write in Python and C++. 

If you are more familiar with PyCharm, etc., you can also use Jetbrains Rider, which is now free.

**Comment by wl2776** [comment]
Git receives the following command line

`rev-list -100000  --parents --exclude=feature/branch-name-mlflo[w] --decorate-refs-exclude=refs/heads/feature/branch-name-mlflo[w] --exclude=HEA[D] --branches --exclude=origin/feature/branch-name-mlflo[w] --decorate-refs-exclude=refs/remotes/origin/feature/branch-name-mlflo[w] --exclude=origin/HEA[D] --remotes --tags  ^2819df565474a3ac3dd1350da1dc7b443952bb76`

My git does not have `--decorate-refs-exclude` command line option.

And I doubt that `[w]` and `[D]` at ends of `mlflo[w]` and `HEA[D]` are valid patterns.

**Comment by wl2776** [comment]
[According to documentation](https://git-scm.com/search/results?search=decorate-refs-exclude&language=en), `--decorate-refs-exclude` is the option for `git log`, not `git rev-list`

**Comment by love-linger** [comment]
try to use `--branches --remotes` to replacing the `{filters}` in `Args` to see if this issue solved.

**Comment by wl2776** [comment]
This resolves the issue: 

```diff
diff --git a/src/Commands/QueryCommitChildren.cs b/src/Commands/QueryCommitChildren.cs
index 293de912..4006b01f 100644
--- a/src/Commands/QueryCommitChildren.cs
+++ b/src/Commands/QueryCommitChildren.cs
@@ -9,8 +9,8 @@ namespace SourceGit.Commands
WorkingDirectory = repo;
Context = repo;
_commit = commit;
-            if (string.IsNullOrEmpty(filters))
-                filters = "--branches --remotes --tags";
+            //if (string.IsNullOrEmpty(filters))
+            filters = "--branches --remotes --tags";
Args = $"rev-list -{max}  --parents {filters} ^{commit}";
}
```

**Comment by love-linger** [comment]
You can download the latest CI build from Github Action.
