### ISSUE TITLE
Where to ask for help?

### ISSUE THREAD

**Issue by ChrisTaylorDeveloper** [sourcegit-scm/sourcegit#747]
Where can I ask support / newbie questions?  Is there a support forum?  I don't want to open GitHub Issues unnecessarily.  Thank you.

**Comment by love-linger** [comment]
Currently, create an ISSUE is the only way...

**Comment by aikawayataro** [comment]
[GitHub Discussions](https://docs.github.com/en/discussions/quickstart) seems to work for this. It is possible to move issues to discussion and discuss them there, setup a FAQ topic and so on

**Comment by love-linger** [comment]
I've setup Github Discussions for this project
