### ISSUE TITLE
[Feature] Merge icons of local and tracked branches, like in SmartGit

### ISSUE THREAD

**Issue by wl2776** [sourcegit-scm/sourcegit#757]
Example.
I've cloned https://github.com/pelrun/hp-omen-linux-module and created local branches `rebase-6.2`, `rebase-6.1`, and `rebase-6.8`

Here is how this repo looks in Sourcegit

![image](https://github.com/user-attachments/assets/908ae6f4-48b5-41ee-aa35-25ca34b5b01f)

And here is how this repo looks in SmartGit

![image](https://github.com/user-attachments/assets/4827d3d5-ab69-456a-81cb-b354aa796d40)

Please, note `=` signs on gray background and puzzle-like curves for tags on branch `rebase-6.8`, where I've made one commit locally.

SmartGit's display looks much more understandable for me.

What do you think?

**Comment by wl2776** [comment]
To summarize, I suggest to implement following rules for drawing branch icons.

If local and tracked remote branches point at the same commit, draw icons close to each other with equality sign (`=`) between them.

If a local branch has commits, missing in remote, or remote branch has commits, missing locally, draw their icons on respective lines of git log, adding puzzle-like curves, showing divergence. Add number of differing commits (`+1`, `-1`, `+2`, `-2`...) near icons in log too.

**Comment by love-linger** [comment]
![image](https://github.com/user-attachments/assets/cd772edd-215d-41bc-8ed3-b0d487b4c46c)

The dot in blue means this commit is ahead (not pushed to remote) of its tracking upstream.
The dot in text foreground color means this commit is behind (not merged to local branch) of it tracking upstream.
The badge behind the branch name in left branch tree shows the summary of how many commits ahead and behind between the current local branch and its tracking remote

**Comment by love-linger** [comment]
the UI/UX design is very different between SourceGit and SmartGit, and currently there are no plans to add this feature.
