### ISSUE TITLE
Line ending warning appears forever

### ISSUE THREAD

**Issue by tlaloc911** [sourcegit-scm/sourcegit#761]
If you have active Enable Auto CRLF

![image](https://github.com/user-attachments/assets/2164a088-c877-45d1-85d5-43b31196f788)

and navigate over staged files that have CRLF line endings, the warning appears every time you select a file, and navigating becomes a little anoying because warnings fill the whole screen.

![image](https://github.com/user-attachments/assets/e68b0e87-4807-4eae-99c4-077531d88a20)

It would be great if warning appears just once for file or that specific situation appears in some other visual way, may be a ⚠️ icon together to the file name instead of a pop every time

**Comment by love-linger** [comment]
Done. You can download the latest CI build from Github Action.

**Comment by tlaloc911** [comment]
thank you so much!!

**Comment by goran-w** [comment]
Unfortunately, the implemented fix is flawed since it causes other problems (see issue #1278).

**Comment by goran-w** [comment]
Solved - this fix has been reverted, since the way to read git diff output from Exec() to ReadToEnd() has changed and there's no longer a need for overriding ´core.autocrlf´ to ignore warnings about line-endings. See fix by @love-linger for #1278.
