### ISSUE TITLE
Option to disable direct push (Ctrl pressed)

### ISSUE THREAD

**Issue by EreMaijala** [sourcegit-scm/sourcegit#766]
Would it be possible to add a setting to disable at least direct push when Ctrl is pressed? I'm pretty sure it had triggered twice for me without Ctrl being pressed on macOS, and it's not nice having to revert a commit that never should have been there in the first place.

**Comment by love-linger** [comment]
On macOS, clicking the push button with command key pressed will also trigger the directly push. I'll remove it later.

BTW, the AvaloniaUI does NOT allow users accessing the input key status out of key events, so `SourceGit` remember the unhandled modifier keys for this purpose. This is not the right way in my opinion, and may lead to undefined behaviors. But I do NOT find another way to do this.

**Comment by love-linger** [comment]
And after `8.40`, I have pushed a new commit that clears the `_unhandledModifiers` after it has been used for directly fetch/pull/push/stash. See

e224f59ea7 - enhance: clear unhandled key modifer before running command (#748)

**Comment by love-linger** [comment]
Please try the latest release. If this issue still exists, please create a new one.
