### ISSUE TITLE
Apparent memory leak when fetching from a large repo (v8.40)

### ISSUE THREAD

**Issue by jsiulian** [sourcegit-scm/sourcegit#768]
I am using SourceGit with a large repository and fetching from it increases the memory usage to around 12gb in my case and it never goes down again. I am able to replicate this every time as the behaviour is consistent.

**Comment by love-linger** [comment]
which platform do you use

**Comment by jsiulian** [comment]
I am on Windows 11 23h2

**Comment by love-linger** [comment]
While fetching remote changes, there's a progress bar and waiting icon those have infinite animation. This seems to be a bug of AvaloniaUI, see https://github.com/AvaloniaUI/Avalonia/issues/17192

**Comment by jsiulian** [comment]
This seems resolved with v8.41 - thank you!
