### ISSUE TITLE
[Feature] - Open with JetBrains

### ISSUE THREAD

**Issue by ennerperez** [sourcegit-scm/sourcegit#77]
Dynamically detect installed JetBrains IDEs from Toolbox app or using ENV vars
- Considere multiple installed instances per IDE.

![image](https://github.com/sourcegit-scm/sourcegit/assets/1206858/5be45bab-8b64-482d-b4f6-9a3c7acc0e59)

**Comment by love-linger** [comment]
I've never used JetBrains Rider before. Can you provide its command-line arguments?

**Comment by ennerperez** [comment]
macOS
![image](https://github.com/sourcegit-scm/sourcegit/assets/1206858/0df87456-f507-49d0-a29e-952650a2af85)

**NOTE**: Unable to draw the icon directly from install folder because is on SVG format.
Manual PNG upload is requiered for macOS (WIP)

**Comment by ennerperez** [comment]
Linux
![image](https://github.com/sourcegit-scm/sourcegit/assets/1206858/cb128036-316e-4922-be13-549c1e34ee76)

NOTE: Linux has PNG & SVG format in installation folder. Works as expected.

**Comment by ennerperez** [comment]
Windows
![image](https://github.com/sourcegit-scm/sourcegit/assets/1206858/c8e00488-51bd-4db5-bed2-7e5157b658f3)
