### ISSUE TITLE
Add Files search option

### ISSUE THREAD

**Issue by igor84** [sourcegit-scm/sourcegit#775]
As a long time Git Extensions user I love SourceGit. Might be the first real cross platform alternative I have found. Based on some initial testing I only detected two features I am missing for now:

1. I would like using Ctrl+f in Files tab of a selected commit to allow me to find a file by name. As far as I can see Git Extensions is using this command to list all the files: `git ls-tree -z -r --name-only <commit_hash>`.
2. In the changes tab I can search within a diff of selected file but I would like the search to automatically go through all the files in the diff.

**Comment by love-linger** [comment]
duplicate #730

**Comment by igor84** [comment]
I approve of your concerns in that ticket. I think Git Extensions goes around those problems by:

1. Not loading all the files unless user activates the file search using the Ctrl+F option
2. It just stores a list of all the files that it gets from the above `git ls-tree` command in memory in `List<string>`
3. In the UI it only shows a small popup with an input field and only after you type something into it it shows the first 20 matching results from that list as plain text paths (image attached)
4. As soon as that popup is dismissed it probably leaves that `List<string>` to the GC.

In Git Extension this is working flawlessly and with no visible increase in memory usage.

![image](https://github.com/user-attachments/assets/20e87a44-637a-44d5-a6a0-979696aae020)

**Comment by love-linger** [comment]
You can download the latest CI build from Github Action

**Comment by igor84** [comment]
Wau. Thanks for the quick reponse. I gave it a try on my ~90K files repo. When I open the repo SourceGit is taking ~90MB RAM, when I start typing in the Search Files box it jumps to ~180MB and after I finish it drops to ~150MB. The app is very responsive and does the search flawlessly so I think all this is ok.

As for UX, when I select a file from the drop down list the File List is filtered to only show the selected file while I expected it will still show the full tree with only the relevant folder expanded and the found file selected. I don't currently see anything really wrong with your solution, it is just different from what I am use to. Maybe it would be relevant in rare cases where for example I know all files related to some feature are in the same folder and I need some file A whose name I can't remember, but I do remember the name of file B that I know is in the same folder. I could then search for file B so that File List selects that file and then I could just see what other files are in the same folder.

**Comment by love-linger** [comment]
I would like to use the same behaviour with other search implementation, such as `Search Changes` and `Search Branches/Tags/Submodules`, for this feature.
