### ISSUE TITLE
[BUG] - SystemAccentColor doesn't seems to work anymore

### ISSUE THREAD

**Issue by Shimoon** [sourcegit-scm/sourcegit#776]
# Issue
Since the version `8.41`, the `SystemAccentColor` value doesn't seems to be taking into account for theme customization.

Tested with a custom theme + the **Nord** theme available on the [sourcegit-theme repository](https://github.com/sourcegit-scm/sourcegit-theme/blob/main/themes/Nord.json).

# Custom theme
```json
{
    "BasicColors": {
        "SystemAccentColor": "#40c19c"
    }
}

```

# Screenshot
![image](https://github.com/user-attachments/assets/4d623ced-f1d4-469c-b761-20f263edaced)

**Comment by love-linger** [comment]
Yes. You should change this from system settings - that's why it is called `SystemAccentColor`

**Comment by Shimoon** [comment]
Wasn't the goal of this value to actually override the system settings when set in a json file and loaded in the `Preference` **>** `Appearance` **>** `Theme Overrides` field ?
This is what I get when I rollback to the `8.40` version and using the same config as shown previously for theme overrides :
![image](https://github.com/user-attachments/assets/29859185-0de3-4f7c-933b-2ff771a83605)

**Comment by love-linger** [comment]
This setting is removed in `8.41` since there's no reason that users select a favorite color for system-wide applications, but want to use a different accent highlight color only for this app.

**Comment by Shimoon** [comment]
I don't think it's actually true, there is good reasons for that (I personally using this a lot). This subject was already aborded in [this issue](https://github.com/sourcegit-scm/sourcegit/issues/232) and ended up with the implementation of the `SystemAccentColor` key for theme customization which was a great addition I think.

**Comment by love-linger** [comment]
It was supported before. But I think it's better to keep the same accent color with the system settings - that's why it has been removed now.

**Comment by Shimoon** [comment]
I don't quite see the point of removing this kind of customization as is it purely optional (if you don't need it, just don't use it). So now, people how wants a better highlight of selected/active stuff in SourceGit with a specific color will needs to change the accent color system wide and therefore completely change the overall cross software experience ?

If I take my example (and I'm far from being the only one), I really like dark themes and I'm a very visual person. Sadly on Windows, the applications top bar have a super ugly white theme by default which is extremely distracting so I always change it for a dark grey color. But in SourceGit, all the highlights are also themed as dark grey which is really the opposite of an highlight.. I have to change the whole system color to clearly see what I have selected in SourceGit, while neglecting any other application I'm working with at the same time.

As I don't know the source code of this program, there is maybe some technical issues that I don't see that was making the maintaining of this feature very complex, I can completely understand.

But the previous system was actually perfect, it was the best of both worlds and was making the experience really grate !
I know it is not a super important feature but I do think that this is this kind of little things here and there that makes any software really great and complete !

**Comment by love-linger** [comment]
All right. You managed to convince me. I've revert the changes about `SystemAccentColor`. You can download the latest CI build from Github Action.

**Comment by Shimoon** [comment]
Awesome, thanks a lot for that !
