### ISSUE TITLE
Confusing date time when changing month

### ISSUE THREAD

**Issue by Shimoon** [sourcegit-scm/sourcegit#777]
# Context
I've noticed that SourceGit is showing the `Last month` label when in relative date mod as soon as the month changed even so the commits are only 2 days old.

# Screenshot
*Relative date :*
![image](https://github.com/user-attachments/assets/65961389-a1f1-4b9e-8265-a98774c4e138)

*Absolute date :*
![image](https://github.com/user-attachments/assets/70359185-629d-4e9e-8d1b-a7e87cc339b9)

*My current date :*
![image](https://github.com/user-attachments/assets/10ee8965-b3f1-4752-a26f-0e619610a973)

**Comment by love-linger** [comment]
> Oh so that is intended then, any chance to make it a bit more precise ?

Could you please illustrate how to handle this with a specific example?

**Comment by Shimoon** [comment]
If your question was about a user integration point of view, I was mostly talking about increasing the relative date precision (if it's possible of course) like the following :
![image](https://github.com/user-attachments/assets/6c5f2a28-46cc-497d-babe-bbd042ba0dd4)
*relative dates*

![image](https://github.com/user-attachments/assets/88d6e8b1-97a0-4fee-8e0c-2b4a355781c3)
*absolute dates*

So for example, if a commit was made at the previous month but is in fact (relatively) from 2 days ago, the label would display `2 days ago`.
I don't know if it's necessary to got down to the hours like shown in the joined pics though.

**Comment by love-linger** [comment]
I'll try to modify it later and push it to a new branch. Would you like to test it for me?

**Comment by Shimoon** [comment]
Of course !

**Comment by love-linger** [comment]
I decided to push the new implementation directly to the `develop` branch. You can download the latest CI build from Github Action.

**Comment by Shimoon** [comment]
Seems to work fine on my end
Thanks a lot for this addition!
