### ISSUE TITLE
[Feature] - Help & Support

### ISSUE THREAD

**Issue by ennerperez** [sourcegit-scm/sourcegit#78]
Missing features:
- [ ] About project link
- [ ] Changelog in app
- [ ] Version & Commit in app

**Comment by love-linger** [comment]
* User can found source code of this app from `About` page
![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/2da641f8-d647-4cdf-a877-7859126b8ff0)
* Change log shows when there's a new version available
![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/b9f0129f-094d-4915-86ca-da3c0246e6e0)
* I don't understand the `Version & Commit in app` means.
