### ISSUE TITLE
Cursor loop issue when hovering over SHA links in commit messages on macOS

### ISSUE THREAD

**Issue by ChiahongHong** [sourcegit-scm/sourcegit#782]
When a commit message contains a SHA link, the mouse cursor may get stuck in an infinite loop, switching between the hand cursor and the pointer cursor. This issue does **_not occur_** if the tooltip for the SHA link successfully appears. `PARENTS` and `CHILDREN` also do not have this issue.

This issue is inconsistent—it does not always occur. However, it seems to be specific to macOS, as I could not reproduce this behavior on Windows.

A video demonstrating the issue is attached:

https://github.com/user-attachments/assets/fe8e98f5-3a84-49c4-9313-7fea69777db8

**Comment by love-linger** [comment]
I can NOT reproduce this issue in the way the video shows, no matter how slowly or fast I moved my mouse

**Comment by ChiahongHong** [comment]
Are you using a mouse or a trackpad? I found that using a mouse alleviated the issue, but it occurs when using a trackpad.

I don’t have my MacBook with me right now, so I’ll try again after work to see if I can find a more specific and stable way to reproduce the issue.

**Comment by love-linger** [comment]
I'm using Macbook Pro with trackpad. I do not have a mouse for it.

**Comment by ChiahongHong** [comment]
After multiple investigations, I’ve identified the root cause, and I apologize for the earlier confusion—it’s unrelated to using a mouse or trackpad. The misunderstanding arose because I use an external monitor when connecting a mouse... : (

I suspect this is an issue with AvaloniaUI’s handling of DPI or something similar. This bug appears when the display is set to a specific scaling factor. For reference, my model is a MacBook Air M2. If your model has a different resolution, the issue might occur at a different scaling factor.

If you can reproduce the same behavior, it’s likely an upstream issue, and this issue can be closed!

![resolution](https://github.com/user-attachments/assets/51ea07ab-d5db-4be4-9770-111c95c49fb6)

https://github.com/user-attachments/assets/2f2116c5-a1c5-44fa-bc16-15b275381a66
