### ISSUE TITLE
比较大的git库中，操作响应延迟明显

### ISSUE THREAD

**Issue by owllyi** [sourcegit-scm/sourcegit#783]
在一个40G左右大小的git库中。无论是点击分支，还是分支上右键。或者在本地修改的文件上右键菜单。都会有明显延迟，大概1-3秒左右才会响应操作。
猜测是文件历史比较大造成的列表过长导致响应慢么？

比较大的库和服务器响应也比较慢，猜测是服务器的压力问题，cpu或者网络慢。但是本地操作也慢就特别不顺手，点什么都要等一会，和卡死了一样。

求优化方案哈~

**Comment by owllyi** [comment]
已经更新到最新的8.41版本，还是有同样的延迟问题。
由于库是内部的，不方便截图或者录像。想问下作者大大，还需要提供什么详细信息，我来补充下。

**Comment by owllyi** [comment]
修改了设置里的History Commits为5000，也没有好转。不知道这个选项是控制什么内容的。

**Comment by love-linger** [comment]
https://github.com/user-attachments/assets/11660a25-90a3-485c-b901-3a2964b9564c

与库大小没有关系。我UnrealEngine引擎的库 180K+ 文件, 同时显示20000提交没有任何压力

**Comment by gadfly3173** [comment]
点击分支时会导航到该分支最新的commit，并加载该commit信息，执行命令：
```bash
git show --no-show-signature --decorate=full --pretty=format:%H%n%P%n%D%n%aN±%aE%n%at%n%cN±%cE%n%ct%n%s -s {sha}
```
如果点击分支都会卡的话，可以检查一下是不是你的git执行过慢，比如git的执行文件在本地，仓库在WSL/网络上的磁盘中。

**Comment by owllyi** [comment]
我删除了Strawberry Perl，然后重装了最新版的Git For Windows，速度回复正常了。我猜测是Strawberry Perl造成的问题。
