### ISSUE TITLE
建议：文件试图新增打开当前版本文件

### ISSUE THREAD

**Issue by heartacker** [sourcegit-scm/sourcegit#789]
![image](https://github.com/user-attachments/assets/f42b3605-be5f-4f7b-8f99-b20331c68f7a)

1. 当前 `打开文件` 行为改为 **打开本地的文件**
2. 新增 `打开当前版本文件`

**Comment by love-linger** [comment]
我们在FILES视图中打开文件，更合理的应当是查看选中revision的文件，而非Worktree中的文件。如需打开Worktree中的文件，应当是选择 `Reveal in File Explorer`

**Comment by love-linger** [comment]
我仍建议对于查看本地文件使用`在文件浏览器中查看`选项
