### ISSUE TITLE
How to set the language for generating commit messages when using the AI-generated commit message feature?

### ISSUE THREAD

**Issue by Yakumo-Yukari** [sourcegit-scm/sourcegit#796]
By default, the generated commit messages are in English. Can the generated messages be set to other languages?

**Comment by love-linger** [comment]
https://kingname.info/2024/04/23/llama-chinese

**Comment by love-linger** [comment]
尝试在这两个提示词的最后都加上，那个"老奶奶"提示词

**Comment by love-linger** [comment]
![image](https://github.com/user-attachments/assets/b02198e8-fbd6-47b8-9b53-d9faa5f342e1)
