### ISSUE TITLE
[BUG] Can't display branch

### ISSUE THREAD

**Issue by JesseGuoX** [sourcegit-scm/sourcegit#80]
Hi all , I found some bugs in sourcegit. I create branch named 'jg' and 'jg_master' and it didnot appears in the tree.
In fact, any branch I create in this repo is not display.

### sourcegit
![image](https://github.com/sourcegit-scm/sourcegit/assets/2068290/d0227ef8-1bde-4e5f-963e-7490be487b00)

### sourcetree
![image](https://github.com/sourcegit-scm/sourcegit/assets/2068290/dced3da7-758d-4131-a2a7-8893ffc7bd42)

**Comment by love-linger** [comment]
It's because that you have filtered histories with branch `Master`.

![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/9b32aac0-76a8-4707-8ac3-1584c8f66c42)

**Comment by JesseGuoX** [comment]
Haha, my bad, did even notice this feature.
