### ISSUE TITLE
[Bug] `Stash N files...` stashes everything

### ISSUE THREAD

**Issue by SebastianSchumann** [sourcegit-scm/sourcegit#801]
If you mark a selection of files in “unstaged” files and right-click and select `Stash N files...`, all files are stashed.
If you perform the same operation in “staged” files, all staged files are stashed.

My expectation would be that only the selected files are stashed.

![Stash01](https://github.com/user-attachments/assets/050d36a2-96ee-4da4-8063-1b2f240a867e)

**Comment by love-linger** [comment]
It's a `git` limitation. You can test the `git stash push -m "message" -- <files>` command. It will stash both files in given `<files>` list and all the staged files.

**Comment by love-linger** [comment]
That's why there is a tip for this behaviour
![image](https://github.com/user-attachments/assets/6e48dd0e-8819-4b14-895f-0f06fd36a41a)

**Comment by love-linger** [comment]
After checking the `git` documents, I can not find a way to only stash selected unstaged changes. For example, the `Fork`, which is another well-known git GUI client, also prompt users this behaviour while stash unstaged changes
![image](https://github.com/user-attachments/assets/468fa765-c4a3-4f2e-a5cf-3917574b0a11)

**Comment by SebastianSchumann** [comment]
Yes `of selected files` - I didn't select any staged files.

**Comment by love-linger** [comment]
All the staged files will be included in the stash, even if you haven't specified them in the commandline.

**Comment by SebastianSchumann** [comment]
What about the following fully-automated workarround?:

*Stash N **unstaged** files*

- commit all staged files
- stage all unselected files
- commit
- stash
- reset mixed
- reset soft

**Comment by love-linger** [comment]
I'm very sorry. I do NOT want to introduce these two complex operations to this app.

* I do NOT know why the `git` keeps this behaviour, but I respect it. And I think it is not hard to apply the whole stash then discard some changes introduce by this stash.
* How to rollback if any of these steps fails or the app crashed before operation completed
* This will pollute the commit history. You can enable `--reflog` in the `Histories` view to see what happend.
