### ISSUE TITLE
clone名字不符合规范造成的问题

### ISSUE THREAD

**Issue by owllyi** [sourcegit-scm/sourcegit#802]
![image](https://github.com/user-attachments/assets/53f54b23-0324-477f-ae0b-e0e261ffe50e)

这种非标准的名字，有可能在内网中是有需求的，能否修改支持一下。

**Comment by love-linger** [comment]
在目前的版本中，你可以使用实际IP替换`gitserver`或是将设备`gitserver`改为`gitserver.local`等至少两个字段的名称。

**Comment by love-linger** [comment]
已提交修改。你可从Github Action中下载最新的包
