### ISSUE TITLE
Error pop-up spam can't be closed unless you close the whole program (request to add ability to close all error pop-ups)

### ISSUE THREAD

**Issue by Cirtoyt** [sourcegit-scm/sourcegit#803]
I got a wall of errors after a file in my repo was LF and was going to be converted to CRLF, and that's fine, I have no issue with the error itself. But from leaving my selection on that item I think a bunch of error pop-ups built up over time. With there being so many, no matter how many times I clicked on the "CLOSE" button the list would never disappear, plus it blocked my commit button. This is what it looked like this:
![image](https://github.com/user-attachments/assets/74e42365-f3c9-42ab-81b3-a54ddc079178)

I had to close and re-open the program to get rid of the wall of error pop-ups.

Could there be a little "x" icon on somewhere may in the top right that allows me to close all these errors? Or perhaps this error to not re-trigger so many times? Thanks!

**Comment by love-linger** [comment]
The client you are using is too old. This issue has been fixed in #761 and released in '8.41'.

![image](https://github.com/user-attachments/assets/9822327f-8ce0-4965-9e5b-8d3c95837fbb)
