### ISSUE TITLE
Linux下无法输入中文

### ISSUE THREAD

**Issue by crayxn** [sourcegit-scm/sourcegit#804]
- 使用 window11 wsl  Ubuntu22 
- 已安装  fcitx5
- 环境变量已配 export AVALONIA_IM_MODULE=fcitx

其他软件调起输入法没问题，就 sourcegit 无法调起输入法。拿 wireshark做例子
![image](https://github.com/user-attachments/assets/9bb79860-cb45-4863-9784-a603e60b543b)
![image](https://github.com/user-attachments/assets/38804740-441c-4ba0-8bb1-a9acafada30c)

**Comment by love-linger** [comment]
AvaloniaUI已经内置了fcitx的适配，尝试不要设置`AVALONIA_IM_MODULE`呢

**Comment by crayxn** [comment]
> AvaloniaUI已经内置了fcitx的装备，尝试不要设置`AVALONIA_IM_MODULE`呢

一样，也是不行

**Comment by love-linger** [comment]
![image](https://github.com/user-attachments/assets/36cae101-6378-42b1-8de3-e6aeece31cc6)

我发现刚开始无法输入中文，但当我清空输入再按 Ctrl+Space后，就可以激活fcitx5输入法了，很奇怪

**Comment by love-linger** [comment]
复现了几次，我这里确定是，刚打开SourceGit，在Welcome页Search输入框中输入文字，按Ctrl+Space无法激活fcitx输入法。然后点击右侧的清空按钮，再次按下Ctrl+Space就可以激活fcitx输入法了。一旦其激活，在程序关闭前都可以使用fcitx输入法。

**Comment by crayxn** [comment]
> 哦，改进了一下，WSL下只需要输入框失去一次焦点就可以按Ctrl+Space输入中文了。

好的 感谢您

**Comment by love-linger** [comment]
我想您误会我的意思了，我不是指的软件有新的修改，而是，我发现只要输入框失去一次焦点，我就可以按 Ctrl + Space 来激活fcitx输入法。我不清楚该方法是否对您有用。但这个方法在我的WSL环境中，是稳定复现的。

**Comment by crayxn** [comment]
> 我想您误会我的意思了，我不是指的软件有新的修改，而是，我发现只要输入框失去一次焦点，我就可以按 Ctrl + Space 来激活fcitx输入法。我不清楚该方法是否对您有用。但这个方法在我的WSL环境中，是稳定复现的。

 没误会，感谢您的回复。

**Comment by crayxn** [comment]
> 我想您误会我的意思了，我不是指的软件有新的修改，而是，我发现只要输入框失去一次焦点，我就可以按 Ctrl + Space 来激活fcitx输入法。我不清楚该方法是否对您有用。但这个方法在我的WSL环境中，是稳定复现的。

回来公司试了下，我的wsl环境按照您的方法依旧 无法拉起 fcitx

**Comment by love-linger** [comment]
尝试一下，手动使用 `fcitx5 --disable=wayland -d --verbose '*'=0` 重新启动fcitx5呢？

**Comment by crayxn** [comment]
> 尝试一下，手动使用 `fcitx5 --disable=wayland -d --verbose '*'=0` 重新启动fcitx5呢？

尝试很多遍了，确保 fcitx5已启动且gedit能正常使用，我才打开的 sourcegit

**Comment by crayxn** [comment]
> 尝试一下，手动使用 `fcitx5 --disable=wayland -d --verbose '*'=0` 重新启动fcitx5呢？

应该就是 我的环境问题，感谢您的回复

**Comment by love-linger** [comment]
我测试使用的是 AppImage 包，设置了 `XMODIFIERS=@im=fcitx`, `GTK_IM_MODULE=fcitx`, `QT_IM_MODULE=fcitx` 三个环境变量，(AVALONIA_IM_MODULE 确定不需要设置)，fcitx5 以上面的命令启动（gedit等都可以唤醒fcitx5）

其他没做任何特殊的设置，也未安装任何其他软件

这些信息希望对您有用

**Comment by love-linger** [comment]
哦，忘记说了

![image](https://github.com/user-attachments/assets/9cbdf52a-7f19-4005-9d9c-4ea8109b0cc3)
![image](https://github.com/user-attachments/assets/ed0f2918-fa82-4396-94fa-295dc8883c19)
