### ISSUE TITLE
[Bug] Branches with long name cannot be displayed (or scrolled)

### ISSUE THREAD

**Issue by albertodlc** [sourcegit-scm/sourcegit#807]
![image](https://github.com/user-attachments/assets/084ca419-950f-468a-95d2-40ab9e4e89ca)
![image](https://github.com/user-attachments/assets/18931a57-2773-4cd6-8b00-0de4020f4ab0)

The branch cannot be read correctly or scrolled to read the full branch name. Neither in the history or on the commit detail

**Comment by love-linger** [comment]
Done. You can download the latest CI build from Github Action.
![image](https://github.com/user-attachments/assets/3b3015f5-7d89-4663-a041-522de8697047)
