### ISSUE TITLE
[Feature] Support force push with shortcuts

### ISSUE THREAD

**Issue by p-fischer** [sourcegit-scm/sourcegit#808]
Hi, first of all: a big shout out to the awesome work you're doing with sourcegit. I'm amazed by the workload you manage to invest in this open source project and your responsiveness.

Being a long time Fork user I'm a happy user of SourceGit on Linux now.

One very common workflow for me is to rebase the branch I'm working on and force-push the changes.
On Fork there is a shortcut to open the push dialog, from where I can press `F` to toggle the force-push check mark and finally trigger the command by pressing `Enter`.

It would be great to have a similar workflow on SourceGit.

In SourceGit I'm only aware of the push shortcut, which directly triggers the push command with default options.

**Comment by love-linger** [comment]
I do NOT like to add such a hot-key because this action is dangerous
