### ISSUE TITLE
feature: auto-fetch 

### ISSUE THREAD

**Issue by briskt** [sourcegit-scm/sourcegit#814]
I'm migrating from Gitkraken for reasons other than the cost. One thing that's taking some brain retraining is the lack of [auto-fetch](https://help.gitkraken.com/gitkraken-desktop/preferences/#auto-fetch). I often forget to fetch before doing things like committing to a tracked branch. Usually it's not too difficult to fix, but sometimes it makes a mess I'd rather not have to deal with. Is this a feature worth considering for sourcegit? Regardless, I'm quite grateful for all the work that's gone into making sourcegit a useful tool to use, while being easy on the eyes.

**Comment by love-linger** [comment]
You can open `Repository Configure` and enable `Fetch remotes automatically` and change the fetch interval to do this job.
![image](https://github.com/user-attachments/assets/2e8b0676-4dc0-43cc-a86e-2b9ea4e1ddaa)

**Comment by briskt** [comment]
Ah, thank you! I somehow missed that whole config dialog!

**Comment by briskt** [comment]
One more comment: would it be possible and practical to make that a global setting?

**Comment by love-linger** [comment]
No plans to change this setting to global.

**Comment by ilianoKokoro** [comment]
@love-linger 
Would you consider changing your mind ? 
Is there a reason you want to keep it that way ? 
It would be really nice to set a global default, then be able to override it per repo. This way, it is not necessary to set it on each new repo.

**Comment by love-linger** [comment]
Generally, a user's repositories are divided into two types:

* Open source projects or team collaboration projects.
* Projects maintained by himself/herself.

For the second type, enabling the `Auto-Fetch` function is completely unnecessary and may interrupt the user's current operation. Furthermore, regarding enabling the `Auto-Fetch` function, I think it is a one-time task and will not be frequently changed for a single repository. Therefore, there is no need to move it to the global settings.

**Comment by ilianoKokoro** [comment]
@love-linger I see, I agree. Thinking about it, I am not really interested in a periodic auto fetch.
The feature I was actually really looking for Is just a gobal setting for autofetch when the Repo is opened. This is very useful on any repo, for example if I'm working on different devices and regardless of the 2 types of repo you mentioned.
