### ISSUE TITLE
Filter/Hide icon hidden behind scrollbar

### ISSUE THREAD

**Issue by adigie** [sourcegit-scm/sourcegit#815]
When repository contains a lot of tags and `Show Tags as Tree` is enabled, then it's not possible to click Filter/Hide icon as it's hidden behind the scroll bar:

![image](https://github.com/user-attachments/assets/fe83dc1b-b916-4634-b7f2-573e62647dbe)
![image](https://github.com/user-attachments/assets/8b47f3d4-3381-4a05-bcfb-ce29a018d1a4)

With `Show Tags as Tree` disabled icon is moved slightly to the left and can be clicked:

![image](https://github.com/user-attachments/assets/54d918bf-01d0-4146-b2ab-dc1364eb8716)

I would suggest to move it in both scenarios, so it doesn't overlap with the scroll bar.

**Comment by love-linger** [comment]
Fixed. You can download the latest CI build from Github Action.

**Comment by adigie** [comment]
Thanks!
