### ISSUE TITLE
[UX] Ability to check detail status of repositories in Submodules view

### ISSUE THREAD

**Issue by ameaninglessname** [sourcegit-scm/sourcegit#816]
![image](https://github.com/user-attachments/assets/270d2499-2998-40ac-b01e-93ce23a56837)

These yellow squares looks like some sort of indication, but I don't understand it.

I want to get these information about a submodule:

- does it synced with current remote?  ↑ ?  ↓? (does it contain changes not pushed)
- does it contain local changes
- ...

**Comment by love-linger** [comment]
It just shows the submodule is `dirty`.

For example, see `--ignore-submodule=dirty` option of `git status` command:
<img width="685" alt="image" src="https://github.com/user-attachments/assets/639dea9d-0269-4a7e-b55b-8a5d1c6f63a4" />

**Comment by ameaninglessname** [comment]
I want to reopen this issue as it didn't solve my problem: 

After made couple of changes to several submodules,
I want to commit changes for these submodules, one by one,

But here comes the problem:
I can't distinguish  from `SourceGit` which submodule contains changes that is not commited at a glance.

Any plan to improve this?

**Comment by ameaninglessname** [comment]
I tried `git status --ignore-submodule=dirty (or --ignore-submodule=none)`, they are going to the opposite side of my need.

**Comment by ameaninglessname** [comment]
@love-linger Could we reopen this issue?
