### ISSUE TITLE
正确设置 title，并在当使用系统默认窗体样式时，title 显示 工作区 和 文件路径

### ISSUE THREAD

**Issue by heartacker** [sourcegit-scm/sourcegit#818]
![image](https://github.com/user-attachments/assets/e4eeccbb-e042-4f6d-80f6-1c078f669e8a)

**Comment by heartacker** [comment]
参考  vscode。 哪怕不显示， 只要设置了title，这将有利于打开多个窗体的时候的区分不同的工作区。
- sourcegit 无法区别
![image](https://github.com/user-attachments/assets/ffeffbd3-c493-4517-9df8-9cadc0002798)

- vscode 可以区分
![image](https://github.com/user-attachments/assets/91cab22b-6e12-43d5-8afa-0a101571c4be)

**Comment by heartacker** [comment]
建议。 文件夹(当前分支(工作区修改状态)) -- 工作区 -- 绝对路径
如: Sourcegit(develop*) -- GIT-DEV  ~/GIT-REPO/sourcegit

**Comment by love-linger** [comment]
Done. You can download the latest CI build from Github Action.

**Comment by love-linger** [comment]
![image](https://github.com/user-attachments/assets/6ebfd8ce-29a7-4f7d-a489-c99f16a05ad3)

**Comment by heartacker** [comment]
非常妙，感谢
