### ISSUE TITLE
Ability to disable unwanted features of SourceGit?

### ISSUE THREAD

**Issue by F3llFr0mTh3Sky** [sourcegit-scm/sourcegit#819]
I don't know if this question already has been asked, nor if it is already doable, but I'd like a lot to have the ability to disable some features of this software before compilation. So splitting the project in submodules?
I particularly think about the auto updater and its pop up, which is totally useless when installing the app from a package manager like portage or other ones. I also think about other features of SourceGit like OpenAI.
I'd say everything else in SourceGit is pretty useful to me and it's a very good GUI for managing Git.

**Comment by love-linger** [comment]
* I fully agree with your point about the `Update Detection` feature. I mentioned this in the previous ISSUE. And this is why this app does not have a built-in auto-update feature, only prompts for new versions.
* Regarding `OpenAI`, this feature is originally optional. Integration in the project is no problem.

**Comment by love-linger** [comment]
#426

**Comment by love-linger** [comment]
I'll add a `dotnet` parameter `-p:DisableUpdateDetection=true` to disable `Update-Detection` feature.

**Comment by love-linger** [comment]
Done. You can now use `-p:DisableUpdateDetection=true` in `dotnet publish` command to disable the built-in update-detection feature.
