### ISSUE TITLE
Feature request: Responsive design for repositories tab

### ISSUE THREAD

**Issue by kethinov** [sourcegit-scm/sourcegit#821]
At present it is a fixed width, but if the repo name and path on file system are too long, the text gets cut off.

![Screenshot 2024-12-16 at 5 12 53 PM](https://github.com/user-attachments/assets/87e24e86-1775-4ebd-a51d-39ad443aaf63)

**Comment by love-linger** [comment]
Done. You can download the latest CI build from Github Action.

![image](https://github.com/user-attachments/assets/b3f81ca2-97b5-4861-a245-575043d311f2)
