### ISSUE TITLE
自定义操作，支持更多信息

### ISSUE THREAD

**Issue by heartacker** [sourcegit-scm/sourcegit#826]
![image](https://github.com/user-attachments/assets/21a26115-06e2-4d53-a598-0f57ec4c3a87)

希望添加 当前本地分支的名字等
## branch
- 当前本地分支 `{BRANCH_LOCAL}`  --------- 急需
- 当前选中commit 的 分支 `{BRANCH_SELECT}`
## remote
- {REMOTE_DEFAULT}
- {REMOTE_[0]} 第一个
- {REMOTE_[N]} 第N个. 超出返回最后一个

另外，模版下面的提示显示不全
![image](https://github.com/user-attachments/assets/66090e94-06af-447c-9fe4-125d783801f1)

**Comment by love-linger** [comment]
1. 当前分支、远程列表都可以在自定义脚本中获取的呀。比如：`git branch --show-current`
2. commit所属的分支？包含commit的refs可能会有多个，甚至可以仅仅是个tag，比如：
![image](https://github.com/user-attachments/assets/a14dc424-517b-4078-a816-1e1c0c6e3aa5)

**Comment by love-linger** [comment]
针对CommitTemplate中提示文字显示不全的问题，我已增加了该视图的高度。
