### ISSUE TITLE
Support custom terminal invocation or integrate Warp Terminal

### ISSUE THREAD

**Issue by blastmann** [sourcegit-scm/sourcegit#829]
While using SourceGit, I have noticed that currently it does not support custom terminal invocation. This somewhat limits the flexibility of users' workflow.

For example, in certain development environments, we may need to use specific terminal tools for command line operations to meet different needs and habits. At the same time, modern terminal tools like Warp Terminal have many excellent features, such as efficient command input and navigation, and a beautiful interface. If SourceGit could support custom terminal invocation or directly integrate Warp Terminal, it would greatly enhance users' development experience.

Hope you guys can consider this request and provide users with more terminal choices and a better development environment.

Thanks!

**Comment by love-linger** [comment]
I've add the `Warp` terminal support for macOS. You can download the latest CI build from Github Action.
