### ISSUE TITLE
Portable

### ISSUE THREAD

**Issue by alabotski** [sourcegit-scm/sourcegit#834]
Hello. Is it possible to store program settings not in the folder `c:\Users\Aliaksei\AppData\Roaming\SourceGit\`

But in the program folder itself? The meaning of the word “portable” is simply lost

**Comment by love-linger** [comment]
I've pushed a new commit to `develop` branch. You can run `dotnet publish -c Release -r win-x64 -p:EnablePortable=true -o $YOUR_PUBLISH_DIR .\src\SourceGit.csproj` to publish a portable version on Windows.

> [!NOTE]
> Remember replace the `$YOUR_PUBLISH_DIR` to the real path you want to store this app.

**Comment by heartacker** [comment]
我认为可以参考vscode，如果用户下载了可移动版本，只要文件夹里面新建一个data文件夹，那么软件数据就会放在data文件夹下面，否则就是其他默认

**Comment by love-linger** [comment]
> 我认为可以参考vscode，如果用户下载了可移动版本，只要文件夹里面新建一个data文件夹，那么软件数据就会放在data文件夹下面，否则就是其他默认

既然已经是[下载了可移动版本]，为什么还要用户再手动创建呢？

If the download package is already a `portable` version, why should users create the `data` folder manually?

另外，README文档已经修改说明。更正了Release页面中的均为`Pre-built binaries`，而非`Portable binaries`.

BTW. I've updated the `README` doc and made it clear that all binaries in `Release` page is `Pre-built Binaries`, not `Portable Binaries`

**Comment by love-linger** [comment]
![image](https://github.com/user-attachments/assets/0492cdf6-6623-4c67-b904-49be95dd6093)

**Comment by heartacker** [comment]
感谢。

其实每次你有更新，
我都下载win 压缩包（win-x64），和 linux 的deb 包，
（说明：我其实要的是压缩版，而不是这个 portable,因为我的配置还是要保存在各个电脑而不是程序文件夹下面)

win 自己解压，放在我的nas 文件
linux 的我也是一个一个的解压出来，复制 linux 的二进制到我的nas 文件夹，

因为我的nas 同步用，然后分别挂在windows 和linux 系统，我到时候那个系统用就打开对应的版本，
我在想
是否可以搞一个 linux 的非安装版本（非 portable 版本）
或者，直接搞一个windows + linux 的打包版本。

**Comment by love-linger** [comment]
Linux下可以直接使用AppImage，其数据文件仍然存放于系统用户目录中

**Comment by alabotski** [comment]
Seems it's not workig
2026.14

I have stored settings. On this path 
c:\Users\Aliaksei\AppData\Roaming\SourceGit\

**Comment by love-linger** [comment]
@alabotski You should create a `data` folder under the same folder of `SourceGit` executable. See README.md

https://github.com/sourcegit-scm/sourcegit/blob/7149a8d70c51cefc706328158bc89dcfd20e5024/README.md?plain=1#L81-L84
