### ISSUE TITLE
Nо available externaI editors found!

### ISSUE THREAD

**Issue by alabotski** [sourcegit-scm/sourcegit#835]
Tell me, where can I specify the path to the external editor? I couldn't find it in the settings!

![image](https://github.com/user-attachments/assets/f957e4c0-8fd4-4d9f-af6c-0099ba4239a5)

**Comment by love-linger** [comment]
You can open the app data storage dir from main menu, and then create a new file named `external_editors.json`. For example:
```json
{
    "tools": {
        "Visual Studio Code": "D:\\VSCode\\Code.exe"
    }
}
```
