### ISSUE TITLE
AI 集成，总是提示错误。

### ISSUE THREAD

**Issue by heartacker** [sourcegit-scm/sourcegit#837]
![image](https://github.com/user-attachments/assets/f8dfd0b9-0a92-4a0e-b994-7c420be6cdd7)

使用其他聊天工具， 我 api 链接配置完全相同的情况下，是可以的。

![image](https://github.com/user-attachments/assets/da618f36-cfa9-495f-8693-5b56584e6a67)

**Comment by love-linger** [comment]
sever url配置的是什么？

**Comment by heartacker** [comment]
https://api.xxx.xx/v1

https://api.xxx.xx 

xxx 是个人的代理，
实际测试都不行

**Comment by love-linger** [comment]
改成 https://api.xxx.xx/v1/chat/completions，SourceGit只使用到了OpenAI的 /chat/completions 功能

**Comment by love-linger** [comment]
feat-openai分支重写了，如果自己编译的话，那个分支配置才是base URL

**Comment by heartacker** [comment]
> 改成 [api.xxx.xx/v1/chat/completions，SourceGit只使用到了OpenAI的](https://api.xxx.xx/v1/chat/completions%EF%BC%8CSourceGit%E5%8F%AA%E4%BD%BF%E7%94%A8%E5%88%B0%E4%BA%86OpenAI%E7%9A%84) /chat/completions 功能

非常感谢，看起来是好了， 之前没有看到哪里说明要这样配置。或者是我没有注意到，我理所当然的以为 是 v1 就行。


另外， feat 新分支。最近会发布吗。谢谢

**Comment by love-linger** [comment]
> > 改成 [api.xxx.xx/v1/chat/completions，SourceGit只使用到了OpenAI的](https://api.xxx.xx/v1/chat/completions%EF%BC%8CSourceGit%E5%8F%AA%E4%BD%BF%E7%94%A8%E5%88%B0%E4%BA%86OpenAI%E7%9A%84) /chat/completions 功能
> 
> 非常感谢，看起来是好了， 之前没有看到哪里说明要这样配置。或者是我没有注意到，我理所当然的以为 是 v1 就行。

README中对于OpenAI的配置方式有具体的说明

> 另外， feat 新分支。最近会发布吗。谢谢

在等 https://github.com/openai/openai-dotnet/pull/21 这个PR被合并

**Comment by love-linger** [comment]
我严重怀疑openai官方对于dotnet的支持根本没上心，那个PR 6月7号创建，11月15号才 approval，到现在一个多月了，还在等那两个reviewer……

**Comment by heartacker** [comment]
合并已经发布
