### ISSUE TITLE
远程分支 的显示，非常占用node 的信息空间

### ISSUE THREAD

**Issue by heartacker** [sourcegit-scm/sourcegit#84]
![image](https://github.com/sourcegit-scm/sourcegit/assets/1876302/e08f9658-5895-4c3b-82cd-c71d180e5f2c)
 比如 同一个main 分支，有gerrit 和 origin， 就分开多个显示，很占用空间

**Comment by love-linger** [comment]
以上图中为例：因为`main`、`gerrit/main`、`origin/main`是三个不同的分支，它们之间是没有本质的联系的。一个远程分支可被多个本地分支tracking，同样一个本地分支可推送到不同的远程分支。本地分支的名称也不需要与其tracking的远程分支一致。它们出现在一行仅因为这三个分支的HEAD指向同一个commit。

这种情形不仅出现在上图所示的情况下，当分支名过长或是并行太多非合并分支时，也会出现commit subject无法显示的问题。这不可避免。

这种情况下，建议选中Commit，从详情页中查看

**Comment by heartacker** [comment]
发现 vscode 插件的这个方案也很不错， 同一个分支可以集中显示

![image](https://github.com/sourcegit-scm/sourcegit/assets/1876302/64a63ead-5b65-42c1-9e52-f34905cdd877)
