### ISSUE TITLE
WinMerge 比對異常

### ISSUE THREAD

**Issue by casper-rinnai** [sourcegit-scm/sourcegit#842]
我在 sourcegit 中用 winmerge 比對程式碼時，若只開一個比對，可以正常開啟。
若要開第二個比對時，就會出錯，
如圖
![image](https://github.com/user-attachments/assets/e5f3578b-f484-4927-ad6d-a27724f5ec2b)
但是用 fork 的話，是可以開二個比對的，
如下圖
![image](https://github.com/user-attachments/assets/b17f9f9d-5d7b-47eb-a124-17a786814e0d)
這是我的 winmerge 設定
![image](https://github.com/user-attachments/assets/cfa053a0-4b4b-4cfd-b1e4-e994377567e9)
這個是 fork 的設定
![image](https://github.com/user-attachments/assets/29d3147d-96b1-463e-b215-4c0f291ea77c)

感謝作者的開發

**Comment by love-linger** [comment]
Fixed. You can download the latest CI build from Github Action.
