### ISSUE TITLE
[Bug] - Unable to locate ssh-askpass (ksshaskpass)

### ISSUE THREAD

**Issue by ennerperez** [sourcegit-scm/sourcegit#85]
```
ssh_askpass: exec(/usr/lib/ssh/ssh-askpass): No such file or directory
git@gitlab.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```

My solution was creating a symbolic link

`sudo ln /usr/bin/ksshaskpass /usr/lib/ssh/ssh-askpass`

So, probably its a good idea to find for `ksshaskpass` if `ssh-askpass` was not found.

--

Manjaro Linux x64
Release:       23.1.4
KDE Plasma: 5.27.11

**Comment by love-linger** [comment]
This app does not call `ssh-askpass` directly. Instead, it will set `core.sshCommand` with the private key you have configured for some remote. For example, the command to pull changes from remote:

```csharp
var sshKey = new Config(repo).Get($"remote.{remote}.sshkey");
if (!string.IsNullOrEmpty(sshKey))
{
    Args = $"-c core.sshCommand=\"ssh -i '{sshKey}'\" ";
}
else
{
    Args = "-c credential.helper=manager ";
}
```

**Comment by love-linger** [comment]
It looks a little bit like another one from vscode: https://github.com/microsoft/vscode/issues/32097
