### ISSUE TITLE
8.45版本读取配置错误

### ISSUE THREAD

**Issue by matresnan** [sourcegit-scm/sourcegit#851]
我一直使用sourcegit的portable版本，当我从8.44版本升级到8.45（直接替换文件的方式），打开后之前的分组和仓库都不显示了

**Comment by love-linger** [comment]
之前并未提供真正的portable版本，有两种方式解决该问题

1. 下载不带`.portable`的版本
2. 从`C:\Users\YOUR_USER_NAME\AppData\Roaming\SourceGit`目录中，将`preference.json`文件及`avatars`目录复制到`SourceGit.exe`所在目录的`data`文件夹下

**Comment by love-linger** [comment]
新的`portable`版本，会将数据存放在程序所在目录的`data`子文件夹中

**Comment by gadfly3173** [comment]
scoop、choco这两个包管理器之前使用的都是portable版本，最好能加上自动复制旧配置文件/提示存在旧配置的功能吧？

**Comment by gadfly3173** [comment]
scoop、choco倒是正好没有使用portable版本，但是可以考虑给portable版本加上合并旧配置文件的功能？

**Comment by heartacker** [comment]
个人依旧建议： zip 版本和 portable 应该合为一个版本， 
可以借鉴vscode 的方式， 
vscode 分安装包和zip 版本。 安装版本和 zip 版本无异
只要用户在程序建立了 data 文件夹。那么数据保存在data 里面，否则将是默认。
这样可以减少用户的误解，减少版本的发布区分和下载的区分。

**Comment by love-linger** [comment]
这个后面我考虑一下，具体的解决方案

**Comment by love-linger** [comment]
提交了最新的Portable-Mode实现
