### ISSUE TITLE
Worktree repository display bug

### ISSUE THREAD

**Issue by gadfly3173** [sourcegit-scm/sourcegit#86]
After commit, reset, and other operations in the new repository created by `git worktree`, it will not be immediately displayed in the tab where the worktree repository is located, but will be displayed in the tab of the original repository. I need to reopen the worktree repository to display it.

Run command such as `git log` in worktree repository in console would has correct result.

**Comment by love-linger** [comment]
The `worktree` feature is not in the supported list for the current version.

**Comment by gadfly3173** [comment]
The reset command can trigger `Watcher.OnRepositoryChanged` on these path
```
FullPath: ${originRepo}/.git/worktrees/${worktreeRepo}/logs/HEAD
Name: logs/HEAD

FullPath: ${originRepo}/.git/worktrees/${worktreeRepo}/ORIG_HEAD
Name: ORIG_HEAD
```

FETCH button triggered this:
```
FullPath: ${originRepo}/.git/worktrees/${worktreeRepo}/FETCH_HEAD
Name: FETCH_HEAD
```

**Comment by gadfly3173** [comment]
`git rev-parse --is-inside-work-tree` can judge if current repo is a worktree repo.

**Comment by love-linger** [comment]
Could you please write a PR? I have not used the `worktree` feature.

**Comment by love-linger** [comment]
You can try commit 1fe050ed0bf4eb7ea6753e47eb7baca6d5d3f064.
