### ISSUE TITLE
软件卡死问题

### ISSUE THREAD

**Issue by owllyi** [sourcegit-scm/sourcegit#87]
非常棒的软件，能满足大部分需求。
不过在使用的时候遇到了两个体验问题：
1、好几次在操作界面之后卡死，整个界面任何位置都不能点击，没有相应。程序并不是未响应状态。感觉是弹出了一个隐藏的模式窗口遮挡住了操作。
2、在一次操作commit & push的时候，git程序高cpu和磁盘占用，大概过了10多分钟都没结束，我就强制杀掉进程了。

想问下这类问题，进一步该如何收集信息来帮助定位问题呢？

**Comment by love-linger** [comment]
非常感谢您能帮助改进本软件。

第一个问题，我想确认一下是否是点击了弹出面板的确认之后，比如：
![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/4d00a0c1-2edc-4eac-9019-39a31b2940aa)
如果界面处于这种状态，是会禁用大部分操作，直到这个面板执行的操作结束（或者出现错误）

第二个问题，这个软件本质上只是Git的图形化前端。负责将一些操作图形化，并展示当前仓库的状态。后台的Git程序CPU和磁盘占用长时间处于高位，可能是由于仓库长时间未清理，散列object太多。建议你可执行一下下面的操作，再尝试fetch，查看是否有所改善。
![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/c1de9d1d-9415-4490-aab5-a4d6b0ed16c7)

**Comment by love-linger** [comment]
需要注意的是执行清理操作，可能需要比较长的时间，取决于您仓库的状态。执行完成后 `.git/objects` 一般仅会保留两个目录，如下:

![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/3683df32-b721-4d6d-8b5e-c4ad3636919d)

**Comment by owllyi** [comment]
第一个问题，遇到过三次，明确有一次是点击出弹板，印象深刻。还有一次我是在左侧workspace区域操作菜单引起的。第三次记不清具体什么操作造成的了。

第二个问题，我同时开着fork和sourcegit，会不会造成了什么冲突呢？出现git高cpu问题之后，我杀掉sourcegit，继续用fork提交push，秒成功。所以我就不知道问题可能是哪里造成的了。

**Comment by owllyi** [comment]
右键操作我看也会弹出弹板，会不会在某些情况下弹板看着消失了，其实还在，阻挡了操作呢。

**Comment by love-linger** [comment]
1. 一般情况下多个git客户端不会造成冲突。如果需要写保护，git会创建lock文件，不会让后面的操作成功。
2. 面板不显示，之前使用旧版本的AvaloniaUI，以及在Linux X11上出现过，最近没有发现过了。有可能，下次如果卡住，你可以将鼠标移到面板应该弹出的区域，晃动一下鼠标，如果界面出现了，那就还是之前的AvaloniaUI的BUG。

**Comment by love-linger** [comment]
对了，能否提供一下你所使用的系统、系统版本、软件版本等信息呢？

**Comment by owllyi** [comment]
系统：Win10 22H2
软件：SourceGit 8.9

等再次遇到，我操作下鼠标试试看。当时尝试点击了各个位置，都没有效果。

**Comment by love-linger** [comment]
> 系统：Win10 22H2 软件：SourceGit 8.9
> 
> 等再次遇到，我操作下鼠标试试看。当时尝试点击了各个位置，都没有效果。

非常感谢！！！

**Comment by owllyi** [comment]
今天用了一整天，没有遇到卡死问题，先关闭吧，遇到问题我再提。
