### ISSUE TITLE
解决冲突时的体验问题

### ISSUE THREAD

**Issue by owllyi** [sourcegit-scm/sourcegit#88]
1、遇到冲突的时候，右键菜单显示的是yours和mines，建议在后面括号里标注上分别是哪个分支，以免选错。
2、合并解决完冲突，没有附加# Conflicts: xxx 这样的冲突信息，和其他git软件的行为不太一致，也容易忽略曾经发生过冲突。

**Comment by love-linger** [comment]
`Use Theirs`与`Use Mine`分别对应的是`git checkout --theirs -- <pathspec>`与`git checkout --ours -- <pathspec>`。右键菜单中括号中的内容都是针对前面可能引起歧义的描述，增加其对应的实际git指令（见 #41）。

同时，更早前（该项目之前在Gitee上发布），大家的建议是菜单项尽量保持与命令一致，方便熟悉git操作的人快速找到自己需要的命令所在的MenuItem。

其实对于git，正在操作的HEAD就是`--ours`，准备引入的INCOMMING CHANGES就是`--theirs`。这其中`rebase`操作会有点绕，直观上看与其他操作的`--ours`与`--theirs`正好相反。这是因为`rebase`可以等价的理解为两步：先从目标`base revision`上`checkout`一个分支，再一个个`cherry-pick`需要`rebase`的分支上的新提交。
