### ISSUE TITLE
[SUGGESTION] - Move to Nukebuild

### ISSUE THREAD

**Issue by ennerperez** [sourcegit-scm/sourcegit#91]
Use nukebuild to automate build process in a new way, avoid using specifics scripts per platforms with a minimal yaml; All CI/CD in C#. <3

https://nuke.build/
https://www.youtube.com/watch?v=E7CufNR84M4

Let me know your thoughts in this thread

**Comment by love-linger** [comment]
The Github Action do NOT using the scripts in `build` folder. It's using the `dotnet publish` command directly to test each commit pushed into `develop` branch.

The scripts defined in `build` folder is used to generate the final packages. Before I upload these packages and draft a new release, I need to run each package to confirm there are no obvious BUGs.

And, in my opinion, a script that can be run locally is more helpful to the user than a minimal CI/CD yaml configuration.

**Comment by ennerperez** [comment]
Some advantage of using nukebuild:

1. be able to debug the entire build process using c# code  step by step
2. ability to run locally and remotely
3. have an agnostic pipeline that works everywhere
4. You can automate and extend build tasks without knowing a lot yaml or sh/cmd
