### ISSUE TITLE
[SUGGESTION] - Separete UI from Core

### ISSUE THREAD

**Issue by ennerperez** [sourcegit-scm/sourcegit#94]
Create a new project to include all non-UI code, including models (but not ViewModels), commands and native code, in order to have an abstract layer of the application.

**Comment by love-linger** [comment]
NO!!! In fact, graphic user interface is the most important and main feature of the software!

And I have no plans to develop a open library that can be used by other software developers (of course, developers are free to strip what they need from the current library if they want). 

Besides, without the `Views/ViewModels/Converters` and other GUI related modules, I don't think there's anything worth a stand-alone project.

I don't want this project to get too complicated.
