### ISSUE TITLE
[FEATURE] -双击文件或目录自动Stage或者Unstage

### ISSUE THREAD

**Issue by owllyi** [sourcegit-scm/sourcegit#96]
1、测试了其他的git软件，都可以双击切换stage状态，现在还需要选中，然后菜单里点一个按钮，感觉有点不够顺畅。现在双击目录是折叠，感觉不如stage功能常用。
2、想问下当前支持git LFS么，菜单里没看到相关的选项。

**Comment by owllyi** [comment]
3、手动解决完冲突，应该检测并提示已经解决完冲突，可以stage了。
比如参考Fork：
![image](https://github.com/sourcegit-scm/sourcegit/assets/5955179/5b39f833-6b27-4990-a9dd-440c3dfb8329)

**Comment by owllyi** [comment]
刚才遇到了手动解决完冲突之后，点continue程序崩溃退出了。然后我又重新操作了一次，没有重现崩溃。

**Comment by love-linger** [comment]
第一个问题：工作区变更支持List/Grid/Tree三种显示方式，为统一三种方式的操作，目前是可以使用`空格（Space）`快捷键来或右键菜单快速stage/unstage选中的变更；

第二个问题，大部分LFS操作是支持的。目前.gitattribute文件添加LFS filter不支持GUI操作。LOCK/UNLOCK文件未支持。

第三个问题，这方面的确需要改进。目前建议使用`Open In Merge Tool`右键菜单解决冲突（在解决完冲突，并退出后，git会自动stage）。目前支持很多第三方merge工具。比如Windows平台下有：
![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/95f45e50-7964-4b7f-92eb-42a8a73e229d)

**Comment by love-linger** [comment]
如果发生crash，SourceGit会记录崩溃堆栈到以下目录中：

| OS | PATH |
| --- | --- |
| Windows | `C:\Users\USER_NAME\AppData\Roaming\SourceGit` |
| Linux | `/home/USER_NAME/.config/SourceGit` |
| macOS | `/Users/USER_NAME/.config/SourceGit` |

能否查看一下，是否有呢？

**Comment by love-linger** [comment]
![image](https://github.com/sourcegit-scm/sourcegit/assets/4075673/2e1f358e-113a-4871-8322-3af0be352372)

加入了对文件是否还有冲突的检测

**Comment by owllyi** [comment]
C:\Users\USER_NAME\AppData\Roaming\SourceGit
这里没有找到崩溃相关的记录

**Comment by love-linger** [comment]
> C:\Users\USER_NAME\AppData\Roaming\SourceGit 这里没有找到崩溃相关的记录

感谢，之后如果崩溃可以查看一下是否生成了堆栈
