### ISSUE TITLE
Executable filename changed on Linux

### ISSUE THREAD

**Issue by gadfly3173** [sourcegit-scm/sourcegit#97]
[sourcegit_8.10.linux-x64.tar.gz](https://github.com/sourcegit-scm/sourcegit/releases/download/v8.10/sourcegit_8.10.linux-x64.tar.gz)  from release use filename `sourcegit`, while [linux-x64](https://github.com/sourcegit-scm/sourcegit/actions/runs/8872692024/artifacts/1455262654) from Github Actions use `SourceGit`. Is this excepted behavior? The new filename is not compatible with `.desktop.template` provided under `v8.8`.

**Comment by love-linger** [comment]
I'll change the `.github/ci.yml` to use lowercase name (which is the common style for executable files on most Unix-like systems).

**Comment by love-linger** [comment]
https://github.com/sourcegit-scm/sourcegit/actions/runs/8874238258
